### PR TITLE
Modernize CMake build scripts

### PR DESCRIPTION
**Pull request by stotko**
- Split collecting source files into subdirectories: Only single layer (e.g. `add_subdirectory(core)`) with all further subdirectories handled inside that layer (e.g. `core/hashmap` in `core/CMakeLists.txt`)
- Use `target_sources(<target> PRIVATE ...)` to specify source files for `<target>`
- Sort source files by name and split them into groups based on their (sub)directory within the layer
- Remove `GLOB` statements and list all source files explicitly
- Avoid variables and set properties directly for better readability
- Consistent function naming convention `open3d_<function_name>(...)`
- Link against `Open3D::Open3D` instead of `${PROJECT_NAME}`

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3456)

### CODE REVIEW

**Comment by ssheorey** [comment]
Hey @stotko this is great. I'll complete the review later, but had a few additional suggestions in the mean time:
- Use `cmake-format` to consistently format the cmake files.
- Run `cmake-lint` to check them for problems.
- Use `CMAKE_MSVC_RUNTIME_LIBRARY` to sync `STATIC_WINDOWS_RUNTIME` of Open3D with 3rd party / external projects. See [here](https://github.com/intel-isl/Open3D/blob/9ad18dc6c3f25b293f085ed20c71db0fd204d5ae/3rdparty/civetweb/civetweb.cmake#L18) for an example. We can simplify some complex code such as [this](https://github.com/intel-isl/Open3D/blob/e77ec7e4eff25203f121315708f1329e35d5f1e2/3rdparty/zeromq/zeromq_build.cmake#L9).

Some TODO items for future:
- Sync security options (e.g.: PIC, stack protection, etc.) from Open3D to 3rd party libraries.
- Convert current `bash` script to build CUDA+CPU pybind library to a cmake script so that it works on Windows as well.

**Comment by stotko** [comment]
Thanks, these are all good points! I think we should address them in future PRs as this one here is just one step in a series of improvements.

>     * Use `cmake-format` to consistently format the cmake files.
> 
>     * Run `cmake-lint` to check them for problems.

I manually formatted a subset of files. Doing this systematically, e.g. with a CI job, would be much better. But this is out of the scope of this PR and would add even more noise here.

>     * Use `CMAKE_MSVC_RUNTIME_LIBRARY` to sync `STATIC_WINDOWS_RUNTIME` of Open3D with 3rd party / external projects. See [here](https://github.com/intel-isl/Open3D/blob/9ad18dc6c3f25b293f085ed20c71db0fd204d5ae/3rdparty/civetweb/civetweb.cmake#L18) for an example. We can simplify some complex code such as [this](https://github.com/intel-isl/Open3D/blob/e77ec7e4eff25203f121315708f1329e35d5f1e2/3rdparty/zeromq/zeromq_build.cmake#L9).

I have not touched the dependency system so far. This deserves some special attention and should be addressed in a separate PR.

>     * Sync security options (e.g.: PIC, stack protection, etc.) from Open3D to 3rd party libraries.

I already have some local work towards this goal which is build on top of this PR. Extending my existing work to 3rd party libraries should be quite straightforward.

>     * Convert current `bash` script to build CUDA+CPU pybind library to a cmake script so that it works on Windows as well.

Moving away from bash scripts in general (at least to a certain degree) would be beneficial to simplify the build steps, e.g. in the CI scripts.

**Review by yxlao — COMMENTED** [review]
> Reviewed 54 of 54 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3456)* status: all files reviewed, 3 unresolved discussions (waiting on @errissa, @prewettg, @ssheorey, and @stotko)

___
*[cpp/open3d/visualization/gui/CMakeLists.txt, line 110 at r1](https://reviewable.io/reviews/intel-isl/open3d/3456#-Mb0GgQW6CuKTGyOmFP4:-Mb0GgQW6CuKTGyOmFP5:b-80thne) ([raw file](https://github.com/intel-isl/open3d/blob/cb55e2d287e7538dae183a7cfc3608dad84f4e40/cpp/open3d/visualization/gui/CMakeLists.txt#L110)):*
> ```CMake
>         OUTPUT "${GUI_MAT_OUTPUT_FILE}"
>         COMMAND ${FILAMENT_MATC} ${GUI_MATC_ARGS} -o "${GUI_MAT_OUTPUT_FILE}" "${GUI_MAT_SOURCE_FILE}"
> 		MAIN_DEPENDENCY ${GUI_MAT_FILE} DEPENDS ${FILAMENT_TARGET}
> ```

nit: tab to space
___
*[cpp/open3d/visualization/webrtc_server/CMakeLists.txt, line 24 at r1](https://reviewable.io/reviews/intel-isl/open3d/3456#-Mb0GwuZCk2K41wEw4gu:-Mb0GwuZCk2K41wEw4gv:bmb8ubr) ([raw file](https://github.com/intel-isl/open3d/blob/cb55e2d287e7538dae183a7cfc3608dad84f4e40/cpp/open3d/visualization/webrtc_server/CMakeLists.txt#L24)):*
> ```CMake
> 
> 
> add_custom_target(copy_html_dir
> ```

(this was removed from master)
___
*[cpp/pybind/CMakeLists.txt, line 84 at r1](https://reviewable.io/reviews/intel-isl/open3d/3456#-Mb0JBsz5Udbe8yMw_cG:-Mb0JBsz5Udbe8yMw_cH:b-n3vzds) ([raw file](https://github.com/intel-isl/open3d/blob/cb55e2d287e7538dae183a7cfc3608dad84f4e40/cpp/pybind/CMakeLists.txt#L84)):*
> ```CMake
> # use the target_compile_definitions approach. Otherwise, use configure_file.
> if (BUILD_AZURE_KINECT)
>     target_compile_definitions(pybind PRIVATE BUILD_AZURE_KINECT)
> ```

Shall all these definitions be set in `open3d_set_global_properties` and we remove them here?
E.g. `BUILD_GUI`and `WITH_FAISS` is already set at`open3d_set_global_properties`.

**Review by stotko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3456)* status: 45 of 55 files reviewed, 2 unresolved discussions (waiting on @errissa, @prewettg, @ssheorey, and @yxlao)

___
*[cpp/open3d/visualization/gui/CMakeLists.txt, line 110 at r1](https://reviewable.io/reviews/intel-isl/open3d/3456#-Mb0GgQW6CuKTGyOmFP4:-Mb1RBrhAUplIMxay4d0:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/cb55e2d287e7538dae183a7cfc3608dad84f4e40/cpp/open3d/visualization/gui/CMakeLists.txt#L110)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: tab to space
</blockquote></details>

Done.
___
*[cpp/open3d/visualization/webrtc_server/CMakeLists.txt, line 24 at r1](https://reviewable.io/reviews/intel-isl/open3d/3456#-Mb0GwuZCk2K41wEw4gu:-Mb1RFdA9fjem2sGTbzx:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/cb55e2d287e7538dae183a7cfc3608dad84f4e40/cpp/open3d/visualization/webrtc_server/CMakeLists.txt#L24)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

(this was removed from master)
</blockquote></details>

Done.
___
*[cpp/pybind/CMakeLists.txt, line 84 at r1](https://reviewable.io/reviews/intel-isl/open3d/3456#-Mb0JBsz5Udbe8yMw_cG:-Mb1RRFI4ZNS1ULqewvQ:baf7qdz) ([raw file](https://github.com/intel-isl/open3d/blob/cb55e2d287e7538dae183a7cfc3608dad84f4e40/cpp/pybind/CMakeLists.txt#L84)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Shall all these definitions be set in `open3d_set_global_properties` and we remove them here?
E.g. `BUILD_GUI`and `WITH_FAISS` is already set at`open3d_set_global_properties`.
</blockquote></details>

Done. There is one intentional leftover in the `ml/tensorflow` module due to an incompatibility with `open3d_set_global_properties`. Perhaps, this could be resolved as well (along with other minor cleanups), but I would defer this to a separate PR to avoid blocking this one.

**Review by ssheorey — APPROVED** [review]
> Reviewed 40 of 54 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3456)* status: all files reviewed, 3 unresolved discussions (waiting on @errissa, @prewettg, @stotko, and @yxlao)

___
*[CMakeLists.txt, line 540 at r2](https://reviewable.io/reviews/intel-isl/open3d/3456#-Mb8cK5S2sPvYtPW7JsG:-Mb8cK5S2sPvYtPW7JsH:bc8jocr) ([raw file](https://github.com/intel-isl/open3d/blob/93d25995c1147a71005a0b1b9c5bf0da38ac791b/CMakeLists.txt#L540)):*
> ```CMake
>             target_compile_definitions(${target} PRIVATE BUILD_CACHED_CUDA_MANAGER)
>         endif()
>     endif()
> ```

Are the options below sorted? Not sure about the reason for the changes below.

**Review by stotko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3456)* status: all files reviewed, 3 unresolved discussions (waiting on @errissa, @prewettg, @ssheorey, and @yxlao)

___
*[CMakeLists.txt, line 540 at r2](https://reviewable.io/reviews/intel-isl/open3d/3456#-Mb8cK5S2sPvYtPW7JsG:-MbAQAWm-MJOqdDWtVyv:bf1ho74) ([raw file](https://github.com/intel-isl/open3d/blob/93d25995c1147a71005a0b1b9c5bf0da38ac791b/CMakeLists.txt#L540)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Are the options below sorted? Not sure about the reason for the changes below.
</blockquote></details>

Yes, I tried to group them similar to how the options are grouped. The order might still not be perfectly consistent, but at least they are now placed together.

**Review by yxlao — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3456)* status: all files reviewed, 4 unresolved discussions (waiting on @errissa, @prewettg, @ssheorey, @stotko, and @yxlao)

___
*[CMakeLists.txt, line 369 at r2](https://reviewable.io/reviews/intel-isl/open3d/3456#-MbG-DGC4CVeeS4SBw8o:-MbG-DGC4CVeeS4SBw8p:b-bc3uew) ([raw file](https://github.com/intel-isl/open3d/blob/93d25995c1147a71005a0b1b9c5bf0da38ac791b/CMakeLists.txt#L369)):*
> ```CMake
> string(REPLACE ";" "," CUDA_HARDENING_CFLAGS "${HARDENING_CFLAGS}")
> string(REPLACE ";" "," CUDA_HARDENING_LDFLAGS "${HARDENING_LDFLAGS}")
> add_compile_options(
> ```

Does it make sense to move the `add_compile_options` and `add_link_options` to `open3d_set_global_properties`?

**Pull request merged**
