### PR TITLE
Faster FixedRadiusSearch and HybridSearch

### PR DESCRIPTION
**Pull request by junha-l**
- Implement CUDA version of HybridSearch based on the FixedRadiusSearch
- Improve FixedRadiusSearch execution speed 
- Reduce memory consumption by removing the redundant Tensor copy

TODO:

- [x] Resolve CI error on ```RegistrationICPPointToPlane``` unit test

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2821)

### CODE REVIEW

**Comment by junha-l** [comment]
Benchmark result
image

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, 2 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2821)* status: 13 of 14 files reviewed, 5 unresolved discussions (waiting on @junha-l)

___
*[cpp/open3d/core/nns/FixedRadiusIndex.cpp, line 238 at r3](https://reviewable.io/reviews/intel-isl/open3d/2821#-MQRUQGo9hNDPhl6W3J1:-MQRUQGo9hNDPhl6W3J2:bde6cy4) ([raw file](https://github.com/intel-isl/open3d/blob/b058c81620b4644f2dd48a6172455509a9c6e997/cpp/open3d/core/nns/FixedRadiusIndex.cpp#L238)):*
> ```cpp
>     DISPATCH_FLOAT32_FLOAT64_DTYPE(dtype, [&]() {
>         NeighborSearchAllocator<scalar_t> output_allocator(device);
>         HybridSearchCUDA(
> ```

Add comments on why do we need to run `HybridSearchCUDA` twice?
___
*[cpp/open3d/core/nns/FixedRadiusSearch.cu, line 563 at r3](https://reviewable.io/reviews/intel-isl/open3d/2821#-MQRcaMU3kyrpKXsORKY:-MQRcaMV-lgsi9nCIWi5:b-b78ivz) ([raw file](https://github.com/intel-isl/open3d/blob/b058c81620b4644f2dd48a6172455509a9c6e997/cpp/open3d/core/nns/FixedRadiusSearch.cu#L563)):*
> ```Cuda
> 
>     if (grid.x) {
> #define FN_PARAMETERS                                                   \
> ```

why there's the need to use `#define` here?
___
*[cpp/open3d/core/nns/FixedRadiusSearch.cu, line 830 at r3](https://reviewable.io/reviews/intel-isl/open3d/2821#-MQRbkwVCXWtjmRexJ-x:-MQRbkwVCXWtjmRexJ-y:b-k5amrt) ([raw file](https://github.com/intel-isl/open3d/blob/b058c81620b4644f2dd48a6172455509a9c6e997/cpp/open3d/core/nns/FixedRadiusSearch.cu#L830)):*
> ```Cuda
>                       int32_t* indices,
>                       T* distances) {
>     // First, fixed radius search.
> ```

there is quite some duplicated code in this part with `FixedRadiusSearchCUDA`, is there a way to avoid duplication? 
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 248 at r3](https://reviewable.io/reviews/intel-isl/open3d/2821#-MQRTYN1-h4gUQMH6EhF:-MQRTYN1-h4gUQMH6EhG:b32f4qt) ([raw file](https://github.com/intel-isl/open3d/blob/b058c81620b4644f2dd48a6172455509a9c6e997/cpp/open3d/core/nns/NanoFlannIndex.cpp#L248)):*
> ```cpp
>     }
> 
>     radius = radius * radius;
> ```

maybe call this `r2` or `radius_squared` to be more clear?
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 252 at r3](https://reviewable.io/reviews/intel-isl/open3d/2821#-MQRTKu1AW7F8uHXv9-2:-MQRTKu1AW7F8uHXv9-3:b-nlg32f) ([raw file](https://github.com/intel-isl/open3d/blob/b058c81620b4644f2dd48a6172455509a9c6e997/cpp/open3d/core/nns/NanoFlannIndex.cpp#L252)):*
> ```cpp
>     Tensor indices;
>     Tensor distances;
>     std::tie(indices, distances) = SearchKnn(query_points, max_knn);
> ```

Does `SearchKnn` return `distance ^ 2`?

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2821)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @junha-l and @yxlao)

___
*[cpp/open3d/core/nns/FixedRadiusIndex.cpp, line 238 at r3](https://reviewable.io/reviews/intel-isl/open3d/2821#-MQRUQGo9hNDPhl6W3J1:-MQjzeXJAeCpRrXVOL7g:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/b058c81620b4644f2dd48a6172455509a9c6e997/cpp/open3d/core/nns/FixedRadiusIndex.cpp#L238)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Add comments on why do we need to run `HybridSearchCUDA` twice?
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/FixedRadiusSearch.cu, line 830 at r3](https://reviewable.io/reviews/intel-isl/open3d/2821#-MQRbkwVCXWtjmRexJ-x:-MQk-ASQ7vsRRNNak51Z:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/b058c81620b4644f2dd48a6172455509a9c6e997/cpp/open3d/core/nns/FixedRadiusSearch.cu#L830)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

there is quite some duplicated code in this part with `FixedRadiusSearchCUDA`, is there a way to avoid duplication? 
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 248 at r3](https://reviewable.io/reviews/intel-isl/open3d/2821#-MQRTYN1-h4gUQMH6EhF:-MQk-A9B55pNxQp2MZUz:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/b058c81620b4644f2dd48a6172455509a9c6e997/cpp/open3d/core/nns/NanoFlannIndex.cpp#L248)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

maybe call this `r2` or `radius_squared` to be more clear?
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 252 at r3](https://reviewable.io/reviews/intel-isl/open3d/2821#-MQRTKu1AW7F8uHXv9-2:-MQk-B3A99hxwSHjt3hC:b7lcb2r) ([raw file](https://github.com/intel-isl/open3d/blob/b058c81620b4644f2dd48a6172455509a9c6e997/cpp/open3d/core/nns/NanoFlannIndex.cpp#L252)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Does `SearchKnn` return `distance ^ 2`?
</blockquote></details>

Yes. It returns squared l2 distances.

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2821)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/nns/FixedRadiusSearch.cu, line 563 at r3](https://reviewable.io/reviews/intel-isl/open3d/2821#-MQRcaMU3kyrpKXsORKY:-MQk-kEGC9F7CgevKy4R:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/b058c81620b4644f2dd48a6172455509a9c6e997/cpp/open3d/core/nns/FixedRadiusSearch.cu#L563)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

why there's the need to use `#define` here?
</blockquote></details>

Done.

**Comment by junha-l** [comment]
Hi @yxlao 
I refactored GPU FixedRadiusSearch & HybridSearch and it seems to work fine. 

However, it fails on ```RegistrationICPPointToPlane``` unittest. 
```RegistrationICPPointToPoint``` passes and ```python/test/core/test_nn.py``` checks whether CPU HybridSearch and GPU HybridSearch output same results.
Do you have any idea?

**Comment by yxlao** [comment]
hi @junha-l , thanks for updating the PR. I ran the unit test in my local machine and it did failed on `RegistrationPermuteDevices` when CUDA is enabled. You may enable cuda compilation and try

```bash
make tests -j10 && ./bin/tests --gtest_filter="*RegistrationICPPointToPlane*"
```

The error i get is the same as CI:
```
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from Registration/RegistrationPermuteDevices
[ RUN      ] Registration/RegistrationPermuteDevices.RegistrationICPPointToPlane/0
[Open3D DEBUG] ICP Iteration #0: Fitness 1.0000, RMSE 0.7064
[Open3D DEBUG] ICP Iteration #1: Fitness 1.0000, RMSE 1.0768
[Open3D DEBUG] ICP Iteration #0: Fitness 1.0000, RMSE 0.7064
[Open3D DEBUG] Residual : 1.78e-01 (# of elements : 14)
[Open3D DEBUG] ICP Iteration #1: Fitness 1.0000, RMSE 1.0767
[Open3D DEBUG] Residual : 1.54e-01 (# of elements : 14)
[       OK ] Registration/RegistrationPermuteDevices.RegistrationICPPointToPlane/0 (296 ms)
[ RUN      ] Registration/RegistrationPermuteDevices.RegistrationICPPointToPlane/1
[Open3D DEBUG] ICP Iteration #0: Fitness 1.0000, RMSE 1.5253
[Open3D DEBUG] ICP Iteration #1: Fitness 0.7857, RMSE 1.4549
[Open3D DEBUG] ICP Iteration #0: Fitness 1.0000, RMSE 0.7064
[Open3D DEBUG] Residual : 1.78e-01 (# of elements : 14)
[Open3D DEBUG] ICP Iteration #1: Fitness 1.0000, RMSE 1.0767
[Open3D DEBUG] Residual : 1.54e-01 (# of elements : 14)
/home/yixing/repo/Open3D/cpp/tests/t/pipelines/registration/Registration.cpp:280: Failure
The difference between reg_p2plane_t.fitness_ and reg_p2plane_l.fitness_ is 0.5714285714285714, which exceeds 0.0005, where
reg_p2plane_t.fitness_ evaluates to 1,
reg_p2plane_l.fitness_ evaluates to 0.42857142857142855, and
0.0005 evaluates to 0.00050000000000000001.
/home/yixing/repo/Open3D/cpp/tests/t/pipelines/registration/Registration.cpp:281: Failure
The difference between reg_p2plane_t.inlier_rmse_ and reg_p2plane_l.inlier_rmse_ is 0.43163930948578066, which exceeds 0.0005, where
reg_p2plane_t.inlier_rmse_ evaluates to 1.4809588366315065,
reg_p2plane_l.inlier_rmse_ evaluates to 1.0493195271457258, and
0.0005 evaluates to 0.00050000000000000001.
[  FAILED  ] Registration/RegistrationPermuteDevices.RegistrationICPPointToPlane/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00> (535 ms)
[----------] 2 tests from Registration/RegistrationPermuteDevices (831 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (831 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Registration/RegistrationPermuteDevices.RegistrationICPPointToPlane/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
```

**Comment by junha-l** [comment]
@yxlao  Problem resolved

**Comment by reyanshsolis** [comment]
Hi @junha-l, I would like to point out a possible issue for CUDA going out of memory. I tried with several point clouds, on my GTX 1050Ti GPU [4GB]. I am still trying to confirm the source of the issue, but it would be very helpful, if you may once look into the memory usage on CUDA, regarding this issue. Thanks.

 ```In function void open3d::core::__OPEN3D_CUDA_CHECK(cudaError_t, const char*, int):
/.../Open3D/cpp/open3d/core/CUDAUtils.h:75 [Open3D Error] /.../Open3D/cpp/open3d/core/MemoryManagerCUDACached.cu:145 CUDA runtime error: out of memory```

**Comment by reyanshsolis** [comment]
> Hi @junha-l, I would like to point out a possible issue for CUDA going out of memory. I tried with several point clouds, on my GTX 1050Ti GPU [4GB]. I am still trying to confirm the source of the issue, but it would be very helpful, if you may once look into the memory usage on CUDA, regarding this issue. Thanks.
> 
> ```
> /.../Open3D/cpp/open3d/core/CUDAUtils.h:75 [Open3D Error] /.../Open3D/cpp/open3d/core/MemoryManagerCUDACached.cu:145 CUDA runtime error: out of memory``` 
> ```

Other than this, I have also faced the following errors:
``` terminate called after throwing an instance of 'std::runtime_error'
  what():  In function void open3d::core::__OPEN3D_CUDA_CHECK(cudaError_t, const char*, int):
/home/rey/workspace/ISL/master/Open3D/cpp/open3d/core/CUDAUtils.h:75 [Open3D Error] /home/rey/workspace/ISL/master/Open3D/cpp/open3d/core/MemoryManagerCUDACached.cu:145 CUDA runtime error: all CUDA-capable devices are busy or unavailable
Aborted (core dumped)```

```terminate called after throwing an instance of 'std::runtime_error'
  what():  In function void open3d::core::__OPEN3D_CUDA_CHECK(cudaError_t, const char*, int):
/home/rey/workspace/ISL/master/Open3D/cpp/open3d/core/CUDAUtils.h:75 [Open3D Error] /home/rey/workspace/ISL/master/Open3D/cpp/open3d/core/CUDAState.cuh:86 CUDA runtime error: unknown error
Aborted (core dumped)```

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 10 of 17 files at r4, 1 of 4 files at r5, 4 of 4 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2821)* status: 17 of 18 files reviewed, 2 unresolved discussions (waiting on @junha-l and @yxlao)

___
*[cpp/open3d/core/nns/FixedRadiusIndex.cpp, line 86 at r8](https://reviewable.io/reviews/intel-isl/open3d/2821#-MTrqF8i9OL8uEQR555w:-MTrqF8j78NM9SyuMqmu:b-6blrys) ([raw file](https://github.com/intel-isl/open3d/blob/46f4e85f5d252f61a0fec8b8a623eae9143bd72a/cpp/open3d/core/nns/FixedRadiusIndex.cpp#L86)):*
> ```cpp
>                 static_cast<scalar_t *>(dataset_points_.GetDataPtr()),
>                 static_cast<scalar_t>(radius), points_row_splits_.size(),
>                 points_row_splits_.data(), hash_table_splits_.data(),
> ```

Seems like we are using many different data types:
```cpp
points_row_splits_      : int64_t
queries_row_splits      : int64_t
hash_table_cell_splits_ : int32_t (casted to `uint32_t`)
hash_table_index_       : int32_t (casted to `uint32_t`)
```

Especially, casting `int32_t*` to `uint32_t*` doesn't seem appropriate. Could we unify the datatypes here? Potentially `int64_t` can be the option.

Same for the rest of this PR.
___
*[cpp/open3d/core/nns/FixedRadiusIndex.cpp, line 200 at r8](https://reviewable.io/reviews/intel-isl/open3d/2821#-MTrs75g4e5frfBAC8B0:-MTrs75g4e5frfBAC8B1:b7pqwgq) ([raw file](https://github.com/intel-isl/open3d/blob/46f4e85f5d252f61a0fec8b8a623eae9143bd72a/cpp/open3d/core/nns/FixedRadiusIndex.cpp#L200)):*
> ```cpp
>                       static_cast<const int64_t *>(
>                               neighbors_row_splits.GetDataPtr()),
>                       static_cast<int64_t *>(indices_unsorted.GetDataPtr()),
> ```

we can all use `GetDataPtr<xxx>()` here

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2821)* status: 13 of 18 files reviewed, 2 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/nns/FixedRadiusIndex.cpp, line 86 at r8](https://reviewable.io/reviews/intel-isl/open3d/2821#-MTrqF8i9OL8uEQR555w:-MTy4DpN6UwpkfO32RK1:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c10de3968c52c7cb6fe9ead2f8fe7e955e6a4000/cpp/open3d/core/nns/FixedRadiusIndex.cpp#L86)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Seems like we are using many different data types:
```cpp
points_row_splits_      : int64_t
queries_row_splits      : int64_t
hash_table_cell_splits_ : int32_t (casted to `uint32_t`)
hash_table_index_       : int32_t (casted to `uint32_t`)
```

Especially, casting `int32_t*` to `uint32_t*` doesn't seem appropriate. Could we unify the datatypes here? Potentially `int64_t` can be the option.

Same for the rest of this PR.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/FixedRadiusIndex.cpp, line 200 at r8](https://reviewable.io/reviews/intel-isl/open3d/2821#-MTrs75g4e5frfBAC8B0:-MTy4Evx1A00PVS1ajga:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c10de3968c52c7cb6fe9ead2f8fe7e955e6a4000/cpp/open3d/core/nns/FixedRadiusIndex.cpp#L200)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we can all use `GetDataPtr<xxx>()` here
</blockquote></details>

Done.

**Comment by yxlao** [comment]
LGTM, let's address the memory issue in a separate PR. @junha-l please see https://github.com/intel-isl/Open3D/pull/3064.

**Review by yxlao — APPROVED** [review]

**Pull request merged**
