### PR TITLE
ParallelFor takes device as argument

### PR DESCRIPTION
**Pull request by yxlao**
- `ParallelFor` now takes device as argument: `ParallelFor(device, n, func);`. If `func` is CUDA compatible, the same source code can be compiled for CPU and CUDA, respectively.
- Remove grain-size control in `ParallelFor` since it hurts performance even for small ops. For bigger ops, it is more likely to hurt performance.
  - Benchmark code: https://github.com/intel-isl/Open3D/blob/c2d6a41a0a5101d692deaccc23c40acfb1299fbc/cpp/benchmarks/core/ParallelFor.cpp#L40-L64
  - Result:
    ```
    ----------------------------------------------------------
    Benchmark                Time             CPU   Iterations
    ----------------------------------------------------------
    SimpleOpGrained      0.699 ms        0.699 ms          980
    SimpleOp             0.077 ms        0.077 ms         8059
    ```

This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3749)

### CODE REVIEW

**Review by stotko — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3749)* status: all files reviewed, 4 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[cpp/open3d/core/ParallelFor.h, line 50 at r1](https://reviewable.io/reviews/intel-isl/open3d/3749#-Mf84pxy1sfch0njMbvJ:-Mf84pxzAu04f2Kstabi:bua8qlo) ([raw file](https://github.com/intel-isl/open3d/blob/78ca1a12837bafeb60342e4fb2f95e4c7d721118/cpp/open3d/core/ParallelFor.h#L50)):*
> ```objc
> 
> static constexpr int64_t OPEN3D_PARFOR_BLOCK = 128;
> static constexpr int64_t OPEN3D_PARFOR_THREAD = 4;
> ```

Could you also benchmark the effect of this constant for light and heavy functions `func_t`? Note that device synchronization is required to get correct result.
___
*[cpp/open3d/core/ParallelFor.h, line 58 at r1](https://reviewable.io/reviews/intel-isl/open3d/3749#-Mf85PpECDKyX5V4Bgjp:-Mf85PpECDKyX5V4Bgjq:brcrjvz) ([raw file](https://github.com/intel-isl/open3d/blob/78ca1a12837bafeb60342e4fb2f95e4c7d721118/cpp/open3d/core/ParallelFor.h#L58)):*
> ```objc
>     int64_t idx = blockIdx.x * items_per_block + threadIdx.x;
> #pragma unroll
>     for (int64_t i = 0; i < thread_size; i++) {
> ```

nit: `++i` even though the loop will be unrolled
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 29 at r1](https://reviewable.io/reviews/intel-isl/open3d/3749#-Mf85rCI3Ap6hPywtnGq:-Mf85rCI3Ap6hPywtnGr:b2j9ip8) ([raw file](https://github.com/intel-isl/open3d/blob/78ca1a12837bafeb60342e4fb2f95e4c7d721118/cpp/open3d/core/kernel/CPULauncher.h#L29)):*
> ```objc
> #pragma once
> 
> #include "open3d/core/ParallelFor.h"
> ```

We can now remove this file entirely, right?
___
*[cpp/open3d/core/kernel/CUDALauncher.cuh, line 29 at r1](https://reviewable.io/reviews/intel-isl/open3d/3749#-Mf85vKX8q3OBlDEx5wx:-Mf85vKX8q3OBlDEx5wy:b-q64pkt) ([raw file](https://github.com/intel-isl/open3d/blob/78ca1a12837bafeb60342e4fb2f95e4c7d721118/cpp/open3d/core/kernel/CUDALauncher.cuh#L29)):*
> ```Cuda
> #pragma once
> 
> #include "open3d/core/ParallelFor.h"
> ```

See above.

**Comment by yxlao** [comment]
CUDA block size and thread size (workload per thread) benchmark:

benchmark_summary copy

- From the bottom right figure, our current default (red bounding box) seems to be a reasonable choice for this set of benchmarks.
- stdgpu/hashmap is not benchmarked since it does not use `ParallelFor` so the performance is not affected.
- Source code and raw results can be found in: https://github.com/intel-isl/Open3D/tree/yixing/parallel-for-benchmark.

**Comment by yxlao** [comment]
Update: results with synchronization (https://github.com/intel-isl/Open3D/pull/3795). The conclusion is similar. 
benchmark_full_synchronized

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3749)* status: 3 of 36 files reviewed, 3 unresolved discussions (waiting on @ssheorey and @stotko)

___
*[cpp/open3d/core/ParallelFor.h, line 50 at r1](https://reviewable.io/reviews/intel-isl/open3d/3749#-Mf84pxy1sfch0njMbvJ:-MfQI1GG83mBuf18W7w5:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/78ca1a12837bafeb60342e4fb2f95e4c7d721118/cpp/open3d/core/ParallelFor.h#L50)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Could you also benchmark the effect of this constant for light and heavy functions `func_t`? Note that device synchronization is required to get correct result.
</blockquote></details>

Done.
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 29 at r1](https://reviewable.io/reviews/intel-isl/open3d/3749#-Mf85rCI3Ap6hPywtnGq:-MfQI-QDA-TFsxb_JIfA:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/78ca1a12837bafeb60342e4fb2f95e4c7d721118/cpp/open3d/core/kernel/CPULauncher.h#L29)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

We can now remove this file entirely, right?
</blockquote></details>

Done.
___
*[cpp/open3d/core/kernel/CUDALauncher.cuh, line 29 at r1](https://reviewable.io/reviews/intel-isl/open3d/3749#-Mf85vKX8q3OBlDEx5wx:-MfQI-hoCpxXhj_YVfin:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/78ca1a12837bafeb60342e4fb2f95e4c7d721118/cpp/open3d/core/kernel/CUDALauncher.cuh#L29)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.

**Review by stotko — APPROVED** [review]
> Reviewed 29 of 29 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3749)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ssheorey)

**Pull request merged**
