### PR TITLE
Add point cloud plane segmentation

### PR DESCRIPTION
**Pull request by kongsgard**
Implementation of plane segmentation for `PointCloud` using the RANSAC algorithm.
It will find the plane with the greatest number of points in the cloud. Therefore, if the cloud has several planes, the model can be rerun multiple times until all planes are found by removing the inliers each time.

Adresses issue #591.

Example segmentation for `fragment.pcd` with 50 iterations is given below:
plane_segmentation

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1287)

### CODE REVIEW

**Comment by prass-anyvision** [comment]
Could I help, this would be really useful for me? Is the code already usable from the branch?

**Comment by griegler** [comment]
What I can see we are waiting for @yxlao to approve the changes.

**Comment by prass-anyvision** [comment]
Is there a way to draw the plane from the plane equation? I currently have the following snippet :- 
```
def flatten_scene_to_plane(self, plane_equation, point_cloud, downsize_step=1):
    plane_points = []
    for point_3d in tqdm(point_cloud[::downsize_step]):
        x_3d, y_3d, z_3d = point_3d
        x_3d_inferred, y_3d_inferred, z_3d_inferred = point_3d
        if plane_equation.c != 0:
            z_3d_inferred = (plane_equation.d - plane_equation.a * x_3d - plane_equation.b * y_3d) / plane_equation.c
        elif plane_equation.b != 0:
            y_3d_inferred = (plane_equation.d - plane_equation.a * x_3d - plane_equation.c * z_3d) / plane_equation.b
        else:
            x_3d_inferred = (
                                        plane_equation.d - plane_equation.b * y_3d - plane_equation.c * z_3d) / plane_equation.a
        plane_points.append(np.array([x_3d_inferred, y_3d_inferred, z_3d_inferred]))
    return plane_points
```

and this gives very bad estimations(visually) for the ground plane I am trying to estimate on a custom cloud, with the return plane equation.

**Comment by kongsgard** [comment]
Fixed the Python style formatting.
Let me know if there is anything else that should be done before this PR can be merged.

@prass-anyvision You could add a triangular mesh with 3-4 vertices acquired from the plane equation (select x, y arbitrary and solve for z) to draw a plane. 
Could you share the point cloud you've used in your example? It might be necessary to increase the number of iterations, depending on the number of points in the point cloud.

**Comment by gamahirawan** [comment]
Hi, I interested to this tools and tried it directly. However I got error notification at line 16 

> open3d.open3d.geometry.PointCloud' object has no attribute 'segment_plane' I am not sure is it problem in the code or I didn't run the code properly? Thanks

**Comment by prass-anyvision** [comment]
> Hi, I interested to this tools and tried it directly. However I got error notification at line 16
> 
> > open3d.open3d.geometry.PointCloud' object has no attribute 'segment_plane' I am not sure is it problem in the code or I didn't run the code properly? Thanks

It has not yet been merged in....

**Comment by xiongzubiao** [comment]
Bump. This feature is really useful.

**Pull request merged**
