### PR TITLE
Nacho/robust kernel colorized icp

### PR DESCRIPTION
**Pull request by nachovizzo**
This PR extends PR#2425.

 - I've implemented the robust kernel functionality in the `ColoredICP` pipeline.
 - To do so, I had to expose the `TransformationEstimationForColoredICP`. I'm not sure if this was not part of the API for some reason.
 - The new changes are also compatible with existing code(through default parameters)
 - The `lambda_geomtric` parameters is now expose through the `TransformationEstimationForColoredICP` class.
 - The `registration_colored_icp` function has now the exact same API that `registration_icp`. With the difference that other `TransformationEstimation` objects are not accepted. These 2 functions could be merge in the future.

There are still some `weight = 1.0;` That I did not want to inject an explicit robust kernel there. For now, this completes the other PR in terms of the registration pipelines. More to come!

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2497)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/pipelines/registration/ColoredICP.h  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6353222&bid=20628360)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/pipelines/registration/ColoredICP.h  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6353222&bid=20628360)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/pipelines/registration/ColoredICP.h  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6353222&bid=20628360)

**Comment by nachovizzo** [comment]
@theNded this PR is ready to review. It doesn't add any new functionality, just some changes to the API.
I have also a full implementation of `GeneralizedICP` that depends on this PR, whenever this gets merged I'll open the `gicp` PR.

**Comment by theNded** [comment]
> @theNded this PR is ready to review. It doesn't add any new functionality, just some changes to the API.
> I have also a full implementation of `GeneralizedICP` that depends on this PR, whenever this gets merged I'll open the `gicp` PR.

That is awesome! G-ICP is one key feature we are missing, thanks for your great contribution!

**Review by theNded — APPROVED** [review]
> Reviewed 13 of 14 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2497)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
