### PR TITLE
Key callback action event to handle PRESS, RELEASE, REPEAT

### PR DESCRIPTION
**Pull request by sammo2828**
Background: In some applications, it's necessary to press and hold a key. The existing `register_key_callback()` allows callback for keyboard button events, which include keyboard PRESS and REPEAT. Most operating systems have a keyboard repeat delay, which means there will be a pause between the PRESS event and the REPEAT events, causing jerky behaviour when pressing and holding a key.

This pull request exposes some lower level GLFW functionality to allow callbacks that can see PRESS, REPEAT and RELEASE *action* events.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1313)

### CODE REVIEW

**Comment by sammo2828** [comment]
Here's an example of pressing spacebar to smoothly rotate a cube:

```python
import open3d as o3d

mesh_box = o3d.geometry.TriangleMesh.create_box(width=1.0, height=1.0, depth=1.0)

vis = o3d.visualization.VisualizerWithKeyCallback()

rotating = False

def rotate_view(vis):
    ctr = vis.get_view_control()
    ctr.rotate(10.0, 0.0)

def key_action_callback(vis, action, mods):
    global rotating
    if action == 1:  # key down
        rotating = True
    elif action == 0:  # key up
        rotating = False

vis.register_key_action_callback(32, key_action_callback)  # space

vis.create_window()
vis.add_geometry(mesh_box)

while True:
    if not vis.poll_events():
        break
    if rotating:
        rotate_view(vis)
    vis.update_renderer()

vis.destroy_window()
```

**Comment by sammo2828** [comment]
Thanks for the review and pointing out those particular changes. Turns out I accidentally pushed the wrong branch and it included some unrelated changes. I don't think I can change the branch in an existing PR, so I've pushed changes to remove. Sorry for the confusion.
Please take another look at the changes.

**Comment by sammo2828** [comment]
Added example to the branch as requested.

**Comment by griegler** [comment]
@yxlao can you have an additional look at this please.

**Comment by sammo2828** [comment]
Oops. Sorry about the tabs. Still fine tuning my o3d environment ;)
Fixed.

**Comment by yxlao** [comment]
There's still a style erorr: https://travis-ci.org/intel-isl/Open3D/jobs/620033350#L1132.

Please install `yapf` and run `make apply-style` in the `build` directory. See [this doc](http://www.open3d.org/docs/release/contribute.html#checking-and-applying-format).

**Comment by sammo2828** [comment]
Looks like it's passed ci now

**Comment by sammo2828** [comment]
@yxlao can we merge this yet? Let me know if you need anything else from me.

**Comment by sammo2828** [comment]
This is getting out of date. Is there a reason why it wasn't merged earlier?

If there is still interest, I'll update the branch with master so it can be merged.

Otherwise, let's close this PR.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/Python/Advanced/customized_visualization_key_action.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=4795741&bid=15963032)

**Pull request merged**
