### PR TITLE
Add shader and supporting code for variable line width line sets

### PR DESCRIPTION
**Pull request by errissa**
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2678)

### CODE REVIEW

**Review by prewettg — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2678)* status: all files reviewed, 3 unresolved discussions (waiting on @errissa)

___
*[cpp/open3d/visualization/gui/Materials/unlitLine.mat, line 32 at r1](https://reviewable.io/reviews/intel-isl/open3d/2678#-MNPWoxi0A3HwurUYxgf:-MNPWoxi0A3HwurUYxgg:b-6fs2h2) ([raw file](https://github.com/intel-isl/open3d/blob/5daaeb6c2d1104ad56db8c3613a1d6082d49ab07/cpp/open3d/visualization/gui/Materials/unlitLine.mat#L32)):*
> ```
>         // now compute offset
>         vec2 dir = normalize(screen_next - screen_pos);
>         vec2 normal = vec2(-dir.y, dir.x);
> ```

When rotating lines sometimes they disappear. It's hard for me to tell if the problem is something in the shader, or if Filament is culling the line (maybe the far clipping plane is a little too close?)
___
*[cpp/open3d/visualization/gui/Materials/unlitLine.mat, line 35 at r1](https://reviewable.io/reviews/intel-isl/open3d/2678#-MNPTGzm02RkgTaljdHd:-MNPTGzn0cQ2HLnJQycf:bmoj18x) ([raw file](https://github.com/intel-isl/open3d/blob/5daaeb6c2d1104ad56db8c3613a1d6082d49ab07/cpp/open3d/visualization/gui/Materials/unlitLine.mat#L35)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         // material.worldPosition.xy = screen_pos + normal*next.w;
>         material.worldPosition = getWorldFromClipMatrix() * (projected_pos + offset);
> //        material.worldPosition.xyz -= getWorldOffset();
>         //        gl_Position = projected_pos + offset;
> ```
</details>

Could we clean up the commented code? I assume it was experimental?
___
*[cpp/open3d/visualization/visualizer/GuiVisualizer.h, line 73 at r1](https://reviewable.io/reviews/intel-isl/open3d/2678#-MNPWKSx1knw7111WDFD:-MNPWKSx1knw7111WDFE:bx1qep0) ([raw file](https://github.com/intel-isl/open3d/blob/5daaeb6c2d1104ad56db8c3613a1d6082d49ab07/cpp/open3d/visualization/visualizer/GuiVisualizer.h#L73)):*
> ```objc
>     void Layout(const gui::Theme& theme) override;
> 
>     void CauseCrash();
> ```

Good for testing, but maybe not for master. Also, doesn't do what was advertised: there is no crash...

**Review by errissa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2678)* status: all files reviewed, 3 unresolved discussions (waiting on @prewettg)

___
*[cpp/open3d/visualization/gui/Materials/unlitLine.mat, line 32 at r1](https://reviewable.io/reviews/intel-isl/open3d/2678#-MNPWoxi0A3HwurUYxgf:-MNTvogp4OapPQzxI0_q:b2j29y6) ([raw file](https://github.com/intel-isl/open3d/blob/5daaeb6c2d1104ad56db8c3613a1d6082d49ab07/cpp/open3d/visualization/gui/Materials/unlitLine.mat#L32)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

When rotating lines sometimes they disappear. It's hard for me to tell if the problem is something in the shader, or if Filament is culling the line (maybe the far clipping plane is a little too close?)
</blockquote></details>

I investigated this by switching to old code path and the lines in the test disappear with the old path. I believe this is a clipping plane issue, not an issue with the wide lines. Of course, it's much more obvious when a fat line disappears than a skinny single pixel line.
___
*[cpp/open3d/visualization/gui/Materials/unlitLine.mat, line 35 at r1](https://reviewable.io/reviews/intel-isl/open3d/2678#-MNPTGzm02RkgTaljdHd:-MNTwPVx2OsWUw0ozW_Y:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/5daaeb6c2d1104ad56db8c3613a1d6082d49ab07/cpp/open3d/visualization/gui/Materials/unlitLine.mat#L35)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

> ```
>         // material.worldPosition.xy = screen_pos + normal*next.w;
>         material.worldPosition = getWorldFromClipMatrix() * (projected_pos + offset);
> //        material.worldPosition.xyz -= getWorldOffset();
>         //        gl_Position = projected_pos + offset;
> ```
Could we clean up the commented code? I assume it was experimental?
</blockquote></details>

Done.
___
*[cpp/open3d/visualization/visualizer/GuiVisualizer.h, line 73 at r1](https://reviewable.io/reviews/intel-isl/open3d/2678#-MNPWKSx1knw7111WDFD:-MNTwVbSB9NZrPuL34eR:b40k3a5) ([raw file](https://github.com/intel-isl/open3d/blob/5daaeb6c2d1104ad56db8c3613a1d6082d49ab07/cpp/open3d/visualization/visualizer/GuiVisualizer.h#L73)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

Good for testing, but maybe not for master. Also, doesn't do what was advertised: there is no crash...
</blockquote></details>

I meant to note this was here just for testing. It is removed now.

**Review by errissa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2678)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @prewettg)

___
*[cpp/open3d/visualization/gui/Materials/unlitLine.mat, line 32 at r1](https://reviewable.io/reviews/intel-isl/open3d/2678#-MNPWoxi0A3HwurUYxgf:-MNTyAQq-7dcm2SGMVzi:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/5daaeb6c2d1104ad56db8c3613a1d6082d49ab07/cpp/open3d/visualization/gui/Materials/unlitLine.mat#L32)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

I investigated this by switching to old code path and the lines in the test disappear with the old path. I believe this is a clipping plane issue, not an issue with the wide lines. Of course, it's much more obvious when a fat line disappears than a skinny single pixel line.
</blockquote></details>

Done.
___
*[cpp/open3d/visualization/visualizer/GuiVisualizer.h, line 73 at r1](https://reviewable.io/reviews/intel-isl/open3d/2678#-MNPWKSx1knw7111WDFD:-MNTyC3T35zp6bIC63Tw:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/5daaeb6c2d1104ad56db8c3613a1d6082d49ab07/cpp/open3d/visualization/visualizer/GuiVisualizer.h#L73)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

I meant to note this was here just for testing. It is removed now.
</blockquote></details>

Done.

**Review by prewettg — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2678)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
