### PR TITLE
Update VoxelGrid::CarveSilhouette and VoxelGrid::CarveDepthMap to sup…

### PR DESCRIPTION
**Pull request by jkerfs**
…port only carving voxels that project to image (#1441)

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1457)

### CODE REVIEW

**Comment by jkerfs** [comment]
Let me know what everyone thinks of the argument "keep_voxels_outside_image" (could obviously use the opposite - "remove_voxels_outside_image").

Also what do we think about using a default value for this argument so that the API remains consistent?  I didn't find any examples of methods with default values in this project, but pybind11 supports it.

**Comment by griegler** [comment]
Also please run `make apply-style` to pass CI.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=4872180&bid=16151701)

**Comment by griegler** [comment]
@yxlao can you restart travis. It seems there was a timeout. Otherwise, looks good to me.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=4872180&bid=16151701)

**Comment by jkerfs** [comment]
@griegler  how should I resolve this codacy error where it complains about assigning a boolean to a pointer?

**Pull request merged**
