### PR TITLE
Use GitHub actions again for macOS CI

### PR DESCRIPTION
**Pull request by yxlao**
- Enable GitHub actions for macOS CI, disable Travis.
- Skip `brew update` for macOS on CI.
- Use `ccache` for Ubuntu and macOS builds
  - Prints `ccache` status before and each run. It shows that `cache` is indeed activated. e.g. https://github.com/intel-isl/Open3D/runs/843543441#step:6:24 and https://github.com/intel-isl/Open3D/runs/843543441#step:6:6213

This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2045)

### CODE REVIEW

**Comment by benjaminum** [comment]
@yxlao macos on travis is very slow. Would it make sense to switch to the github macos runner?

**Comment by yxlao** [comment]
@benjaminum I also prefer the GitHub macOS actions, however, we have had stability issues with randomly failing tests. That's why we only used GitHub macOS actions for a while and switched back to Travis.

Currently, Travis is breaking on master; additionally, it sometimes hits the 50 min total time limit and the test will fail. So sure, we can give Github actions another try.

**Comment by benjaminum** [comment]
> @benjaminum I also prefer the GitHub macOS actions, however, we have had stability issues with randomly failing tests. That's why we only used GitHub macOS actions for a while and switched back to Travis.
> 
> Currently, Travis is breaking on master; additionally, it sometimes hits the 50 min total time limit and the test will fail. So sure, we can give Github actions another try.

I did not know about the stability issues but it is a good idea to try github again because we will likely run into the travis timelimit more often.

**Comment by yxlao** [comment]
@barnjamin ready for review now

**Pull request merged**
