### PR TITLE
ISS(Intrinsic Shape Signature) Keypoint Detection Module

### PR DESCRIPTION
**Pull request by nachovizzo**
# Intrinsic Shape Signature Keypoint Detection Module

I'm opening the PR to start reviewing details in the code, this is my first PR targeting `Open3D` so I guess I might miss some stuff in between. This PR implements the detector described in this [paper](https://www.researchgate.net/publication/224135303_Intrinsic_shape_signatures_A_shape_descriptor_for_3D_object_recognition)

## Why

**ISS** Is a popular 3D shape descriptor, it's fast to compute and it shows good results(please check notebook) on `smooth` 3D shapes. I also plan to implement some other keypoints modules for Open3D.

This can augment the Open3D usability for classical object detection, 3D shape retrieval, and registration tasks.

## ToDo Before merge
 - [x] Add unit tests (wip)
 - [x] Create docs from python notebook. (Does this happen automatically?)
 - [x] Update `CHANGELOG..md`

## Related issues
 - #1236 
 - #1944 
 - #1952

## Some results
**Armadillo:**
image

**Standford Bunny:**
image

## Notes
 - I'm sorry I'm not more verbose on the PR description, but I think it's time to review the code so we can discuss the details.
 - I'm open to any suggestion, so I appreciate if you can be as brutal as possible with the code.
 - If you have any suggestion for contributing to the Open3D library, besides the guide in the docs, I will be happy to know it, since I also plan to open a few more PRs in the following weeks

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1966)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/Python/Advanced/iss_keypoint_detector.py  1
         

Clones added
============
- examples/Python/Advanced/iss_keypoint_detector.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5707760&bid=18680807)

**Comment by nachovizzo** [comment]
@yxlao I wrote this code before 816ec6c93a8. Now is not working(maybe due to an error in the merge). Is there anything I should take into account besides moving the pybind modules into the new directory?
Thanks!

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/Python/Advanced/iss_keypoint_detector.py  1
         

Clones added
============
- examples/Python/Advanced/iss_keypoint_detector.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5707760&bid=18680807)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/Python/Advanced/iss_keypoint_detector.py  1
         

Clones added
============
- examples/Python/Advanced/iss_keypoint_detector.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5707760&bid=18680807)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/Python/Advanced/iss_keypoint_detector.py  1
         

Clones added
============
- examples/Python/Advanced/iss_keypoint_detector.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5707760&bid=18680807)

**Comment by nachovizzo** [comment]
The build is failing to create the docs for the provided notebook. I have literally no idea of what to do to make it work. This is the error
```sh
[Processing notebook iss_keypoint_detector.ipynb]
has_code: True, has_output: False, execute: True
Traceback (most recent call last):
  File "make_docs.py", line 468, in <module>
    jdb.run()
  File "make_docs.py", line 387, in run
    ep.preprocess(nb, {"metadata": {"path": nb_path.parent}})
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 403, in preprocess
    with self.setup_preprocessor(nb, resources, km=km):
  File "/opt/python/3.6.10/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 345, in setup_preprocessor
    self.km, self.kc = self.start_new_kernel(**kwargs)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 291, in start_new_kernel
    km.start_kernel(extra_arguments=self.extra_arguments, **kwargs)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/jupyter_client/manager.py", line 301, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/jupyter_client/manager.py", line 254, in pre_start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/jupyter_client/manager.py", line 178, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/jupyter_client/manager.py", line 84, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 235, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named e4a35403-8988-4173-8f29-e202a2bccd27
The command "./util/scripts/make-documentation.sh" exited with 1.
```

**Comment by nachovizzo** [comment]
___
*[src/Open3D/Keypoints/ISSDetector.h, line 33 at r3](https://reviewable.io/reviews/intel-isl/open3d/1966#-MA5UO1wBJwimyP_PLTL:-MA7XqtvANW9sKier8iJ:b-laz6ri) ([raw file](https://github.com/intel-isl/open3d/blob/70c147178a239fd9dc597f8791d8e26c3c05dc2a/src/Open3D/Keypoints/ISSDetector.h#L33)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

can we move this to a member function of `PointCloud`?
</blockquote></details>

So, I thought about this for some time. I don't mind at all, but I see 2 drawbacks
1) The `PointCloud` might get bigger for no reason(especially if at some point we add more keypoints)
2) The method by itself builds a `KDTree`, that could be passed by reference across the functions, but the problem is that if you will build a new `KDTree` everytime you call the function. Although I think this would only impact the performance of the experiments.

If you think it still seems reasonable, I already have the implementation ready,  it's a matter of design. you let me know and I will change it right away.
If you ask me, I'd actually also prefer to have just a member function of the `PointCloud` class, because, for a given pointcloud, I just want to get the keypoints, without doing any additional step, this also looks more aligned with the style of other functionality in the library(like the `poisson` reconstruction, etc) I got confused somehow by #1952

**Comment by nachovizzo** [comment]
___
*[src/Open3D/Keypoints/ISSDetector.h, line 33 at r3](https://reviewable.io/reviews/intel-isl/open3d/1966#-MA5UO1wBJwimyP_PLTL:-MA90rUw1Qz69ruv1UnC:b-rtrx2i) ([raw file](https://github.com/intel-isl/open3d/blob/70c147178a239fd9dc597f8791d8e26c3c05dc2a/src/Open3D/Keypoints/ISSDetector.h#L33)):*
<details><summary><i>Previously, nachovizzo (Ignacio Vizzo) wrote…</i></summary><blockquote>

So, I thought about this for some time. I don't mind at all, but I see 2 drawbacks
1) The `PointCloud` might get bigger for no reason(especially if at some point we add more keypoints)
2) The method by itself builds a `KDTree`, that could be passed by reference across the functions, but the problem is that if you will build a new `KDTree` everytime you call the function. Although I think this would only impact the performance of the experiments.

If you think it still seems reasonable, I already have the implementation ready,  it's a matter of design. you let me know and I will change it right away.
If you ask me, I'd actually also prefer to have just a member function of the `PointCloud` class, because, for a given pointcloud, I just want to get the keypoints, without doing any additional step, this also looks more aligned with the style of other functionality in the library(like the `poisson` reconstruction, etc) I got confused somehow by #1952

</blockquote></details>

I have convinced myself that's much better to just add 1 unique function to the `PointCloud` class than add a completely new class/sub-library, so I went ahead and fixed this in 
722e62b

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/Python/Advanced/iss_keypoint_detector.py  1
         

Clones added
============
- examples/Python/Advanced/iss_keypoint_detector.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5707760&bid=18680807)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/Python/Advanced/iss_keypoint_detector.py  1
         

Clones added
============
- examples/Python/Advanced/iss_keypoint_detector.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5707760&bid=18680807)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/Python/Advanced/iss_keypoint_detector.py  1
         

Clones added
============
- examples/Python/Advanced/iss_keypoint_detector.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5707760&bid=18680807)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/Python/Advanced/iss_keypoint_detector.py  1
         

Clones added
============
- examples/Python/Advanced/iss_keypoint_detector.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5707760&bid=18680807)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/python/Advanced/iss_keypoint_detector.py  1
         

Clones added
============
- examples/python/Advanced/iss_keypoint_detector.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5707760&bid=18680807)

**Comment by nachovizzo** [comment]
@germanros1987 @yxlao Should I do something with this PR?

**Comment by germanros1987** [comment]
@griegler @yxlao the system says that both of you have requested changes, but it seems that @nachovizzo has addressed your requests. What is your opinion?

**Comment by yxlao** [comment]
Can you merge master to this branch, looks like some of the CI tests didn't past.

**Comment by nachovizzo** [comment]
@yxlao sure, I think the docs tests are failing, I'm not sure what should I do with the example-notebook to fix this

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5707760&bid=18680807)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5707760&bid=18680807)

**Comment by nachovizzo** [comment]
I will fix the following issues in the near future if possible and not within this PR:
1. Merge common functionality of eigendecomposition from the `ISS` module and the `EstimateNormals()` functions.
1. Create a propper `Keypoint` abstract class where we can derive new types of Keypoints.

I'm currently working on fixing the notebook example and that should solve all the issues mentioned during the review(if we can post-pone the 2 mentioned above)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5707760&bid=18680807)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5707760&bid=18680807)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5707760&bid=18680807)

**Comment by yxlao** [comment]
thanks @nachovizzo

**Pull request merged**
