### PR TITLE
Merged Open3D-3rdparty repository into main repository

### PR DESCRIPTION
**Pull request by griegler**
1) It seems to be much cleaner to have the code in one place.
2) It greatly simplifies PRs that involve changes in the 3rdparty folder (like adding an additional module).

No files have been changed. The only relevant diff is in `.gitmodules`, the other files have just moved from the `Open3D-3rdparty` repository.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/967)

### CODE REVIEW

**Comment by syncle** [comment]
Thanks for your effort @griegler! This PR is opposite to previous PR #725. I was not able to fully understand the two reasons you mentioned. Could you give some more example why this PR is necessary?

**Comment by qianyizh** [comment]
hahaha, finally one more vote for my original design...

@griegler to give you some context. My original design was exactly the same as you are doing in this PR. However, Dan strongly argued against it in this thread #238 . As a result of compromise, we end up with a solution in #725 . Hence the current structure.

There are indeed pros and cons of each structure. We can discuss in our meetings.

**Comment by griegler** [comment]
@syncle @qianyizh I have seen (after the initial PR) the discussion and understand the reasoning to move the 3rdparty source out of the main repository, but I think the current setting is not satisfactory at all. It is actually the very same as having all the source in the main repository, but with the major disadvantage that when we have a PR that involves 3rdparty code (see convex hull PR, or the triangle triangle intersection) that with have to merge two PRs independently that actually belong together. 

Therefore, I think that the larger 3rdparty projects should be separate submodules (as I tried in the current form of this PR). Then, (most of) the 3rdparty source is hosted independently as needed, while at the same time it is easy to contribute PRs that involve 3rdparty code. 

I am happy to discuss this further in our meeting. Anyway, the current PR is failing the integration tests.

**Comment by yxlao** [comment]
hi @griegler, I pushed your changes to a backup branch https://github.com/griegler/Open3D/tree/submodules-backup. In this PR, I reverted several changes such that only header-only library like Pybind11 and Eigen are submodules. Let's get this merged this first to unblock other PRs. 

Later, it should be possible to convert other 3rd party libraries using custom `ExternalProject_Add` function. We can convert them one-by-one.

**Pull request merged**
