### PR TITLE
Tensor Cumulative Sum CPU

### PR DESCRIPTION
**Pull request by junha-l**
Implement cumulative sum function in Tensor.

TODO: 
- [x] benchmark for Tensor::CumSum

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2364)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/Tensor.cpp  12
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6215738&bid=20266046)

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2364)* status: all files reviewed, 5 unresolved discussions (waiting on @junha-l)

___
*[cpp/open3d/core/Tensor.h, line 825 at r1](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHuCD5v54eoNdZ_ozML:-MHuCD5v54eoNdZ_ozMM:buxgou7) ([raw file](https://github.com/intel-isl/open3d/blob/f25c2cd582fb3e04475f6a4c4cb9124b70103412/cpp/open3d/core/Tensor.h#L825)):*
> ```objc
>     /// \param dims A list of dimensions to be reduced. Should be length 1.
>     Tensor CumSum(const SizeVector& dims) const;
> ```

pytorch and numpy only support single `dim`, let's be consistent with https://pytorch.org/docs/stable/generated/torch.cumsum.html
___
*[cpp/open3d/core/Tensor.cpp, line 1083 at r1](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHuCVL0ATr_blEGRjQE:-MHuCVL0ATr_blEGRjQF:bell9pa) ([raw file](https://github.com/intel-isl/open3d/blob/f25c2cd582fb3e04475f6a4c4cb9124b70103412/cpp/open3d/core/Tensor.cpp#L1083)):*
> ```cpp
> 
> Tensor Tensor::CumSum(const SizeVector& dims) const {
>     return kernel::CumSum(*this, dims);
> ```

Let's keep the convention to allocate the new tensor here and call the kernel function with the allocated tensor, i.e.
```cpp
Tensor result = core::Tensor::empty(xxx, xxx);
kernel::CumSum(*this, result, dim);
```

Check `WrapDim`, it is possible that the dimension can be wrapped around, e.g. `dim = -1`.
___
*[cpp/open3d/core/kernel/CumSumCPU.cpp, line 48 at r1](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHuGKDDAqw9O6IVzNuw:-MHuGKDDAqw9O6IVzNux:b-hlls12) ([raw file](https://github.com/intel-isl/open3d/blob/f25c2cd582fb3e04475f6a4c4cb9124b70103412/cpp/open3d/core/kernel/CumSumCPU.cpp#L48)):*
> ```cpp
> 
>     // Destination Tensor.
>     Tensor dst(src.GetShape(), src.GetDtype(), src.GetDevice());
> ```

This algorithm is not optimal. We shouldn't need transpose. 

```python
# Assume `dim` is the selected axis
dst <- np.zeros_like(src)
for i in range(src.shape[dim]):
    if i == 0:
        dst's 0-th slice on dim <- src's 0-th slice on dim
    else:
        dst's i-th slice on dim <- src's i-th slice on dim + dst's (i-1)-th slice on dim
```

Recommendations:
- Use `Tensor::Slice()` function for slicing at a specific axis
- For the assignment, if the shapes are different but num-elements are the same, use `Tensor::Reshape()` to reshape and then assign
- Use TBB's `parallel_scan` for parallization
___
*[cpp/tests/core/Tensor.cpp, line 2207 at r1](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHuIQla9lSRIaJwLMPU:-MHuIQla9lSRIaJwLMPV:b-nn7g79) ([raw file](https://github.com/intel-isl/open3d/blob/f25c2cd582fb3e04475f6a4c4cb9124b70103412/cpp/tests/core/Tensor.cpp#L2207)):*
> ```cpp
> }
> 
> TEST_P(TensorPermuteDevices, CumSum) {
> ```

Test cases (some can throw exception):
- input shape: `{}`; dim = 0, 1
- input shape: `{0}`; dim = 0, 1
- input shape: `{2}`; dim = 0, 1
- input shape: `{2, 3}`; dim = 0, 1, 2
- input shape: `{0, 3}`; dim = 0, 1
- input shape: `{3, 0}`; dim = 0, 1
___
*[cpp/tests/core/Tensor.cpp, line 2208 at r1](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHuJ29H0A9Q1Jw9t8b4:-MHuJ29H0A9Q1Jw9t8b5:b-qvuazw) ([raw file](https://github.com/intel-isl/open3d/blob/f25c2cd582fb3e04475f6a4c4cb9124b70103412/cpp/tests/core/Tensor.cpp#L2208)):*
> ```cpp
> 
> TEST_P(TensorPermuteDevices, CumSum) {
>     core::Device device = GetParam();
> ```

you could just hard-code CPU device for now, and add a `// TODO` for CUDA

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2364)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @junha-l and @yxlao)

___
*[cpp/open3d/core/Tensor.h, line 825 at r1](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHuCD5v54eoNdZ_ozML:-MHvOWQT650yqUhc-Fqx:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f25c2cd582fb3e04475f6a4c4cb9124b70103412/cpp/open3d/core/Tensor.h#L825)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

pytorch and numpy only support single `dim`, let's be consistent with https://pytorch.org/docs/stable/generated/torch.cumsum.html
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.cpp, line 1083 at r1](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHuCVL0ATr_blEGRjQE:-MHvOZQSD06QS4GXPnX2:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f25c2cd582fb3e04475f6a4c4cb9124b70103412/cpp/open3d/core/Tensor.cpp#L1083)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Let's keep the convention to allocate the new tensor here and call the kernel function with the allocated tensor, i.e.
```cpp
Tensor result = core::Tensor::empty(xxx, xxx);
kernel::CumSum(*this, result, dim);
```

Check `WrapDim`, it is possible that the dimension can be wrapped around, e.g. `dim = -1`.
</blockquote></details>

Done.
___
*[cpp/tests/core/Tensor.cpp, line 2207 at r1](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHuIQla9lSRIaJwLMPU:-MHvObrd5_S7gDWjqmWa:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f25c2cd582fb3e04475f6a4c4cb9124b70103412/cpp/tests/core/Tensor.cpp#L2207)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Test cases (some can throw exception):
- input shape: `{}`; dim = 0, 1
- input shape: `{0}`; dim = 0, 1
- input shape: `{2}`; dim = 0, 1
- input shape: `{2, 3}`; dim = 0, 1, 2
- input shape: `{0, 3}`; dim = 0, 1
- input shape: `{3, 0}`; dim = 0, 1


</blockquote></details>

Done.
___
*[cpp/tests/core/Tensor.cpp, line 2208 at r1](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHuJ29H0A9Q1Jw9t8b4:-MHvOcXz3nOzfZUzgJT5:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f25c2cd582fb3e04475f6a4c4cb9124b70103412/cpp/tests/core/Tensor.cpp#L2208)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

you could just hard-code CPU device for now, and add a `// TODO` for CUDA
</blockquote></details>

Done.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/Tensor.cpp  16
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6215738&bid=20266046)

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2364)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/kernel/CumSumCPU.cpp, line 48 at r1](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHuGKDDAqw9O6IVzNuw:-MHvOgnw8Jt-yFRjfdqf:b-98gsac) ([raw file](https://github.com/intel-isl/open3d/blob/f25c2cd582fb3e04475f6a4c4cb9124b70103412/cpp/open3d/core/kernel/CumSumCPU.cpp#L48)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

This algorithm is not optimal. We shouldn't need transpose. 

```python
# Assume `dim` is the selected axis
dst <- np.zeros_like(src)
for i in range(src.shape[dim]):
    if i == 0:
        dst's 0-th slice on dim <- src's 0-th slice on dim
    else:
        dst's i-th slice on dim <- src's i-th slice on dim + dst's (i-1)-th slice on dim
```

Recommendations:
- Use `Tensor::Slice()` function for slicing at a specific axis
- For the assignment, if the shapes are different but num-elements are the same, use `Tensor::Reshape()` to reshape and then assign
- Use TBB's `parallel_scan` for parallization




</blockquote></details>

I replaced the ```Transpose``` to ```Slice```. 

I have a question about the parallelization 
This function uses ```Tensor::Add_(...)``` to calculate the cumulative sum and ```Tensor::Add_``` is parallelized in element-wise manner (using OpenMP). 
Is it okay to use overlapped parallelization? 
I mean, is there no problem to run OpenMP parallelized function inside the tbb's parallel_scan?

**Review by yxlao — CHANGES_REQUESTED** [review]
the PR size seems reasonable, shall we also add pybind and tests in this PR?

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2364#-:-MHvfehv0KuXfAadrILU:b-bczypw)* status: all files reviewed, 5 unresolved discussions (waiting on @junha-l and @yxlao)

___
*[cpp/open3d/core/Tensor.h, line 823 at r2](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHveEPj9TfDKijTk9sX:-MHveEPj9TfDKijTk9sY:b-xk6nbt) ([raw file](https://github.com/intel-isl/open3d/blob/9179dce5bc3f1e15f6337be5765893e103fccdc2/cpp/open3d/core/Tensor.h#L823)):*
> ```objc
> 
>     /// Returns the cumulative sum of the tensor along the given \p dims.
>     /// \param dim dimension to do the operation over.
> ```

dimension -> The dimension
___
*[cpp/open3d/core/kernel/CumSumCPU.cpp, line 48 at r1](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHuGKDDAqw9O6IVzNuw:-MHvbvOI5VhR9Xk6OdDy:b-vtm74n) ([raw file](https://github.com/intel-isl/open3d/blob/f25c2cd582fb3e04475f6a4c4cb9124b70103412/cpp/open3d/core/kernel/CumSumCPU.cpp#L48)):*
<details><summary><i>Previously, junha-l (Junha Lee) wrote…</i></summary><blockquote>

I replaced the ```Transpose``` to ```Slice```. 

I have a question about the parallelization 
This function uses ```Tensor::Add_(...)``` to calculate the cumulative sum and ```Tensor::Add_``` is parallelized in element-wise manner (using OpenMP). 
Is it okay to use overlapped parallelization? 
I mean, is there no problem to run OpenMP parallelized function inside the tbb's parallel_scan?
</blockquote></details>

Probably it depends on the input shape. E.g. if the input tensor has shape `{N,}` where `N` is pretty large, each `add` only applies to single elements and parallel_scan might help. We can add some benchmarks in `cpp/benchmarks/core` and see if it helps.
___
*[cpp/open3d/core/kernel/CumSumCPU.cpp, line 36 at r2](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHvef3u0mg_IIIS9SX3:-MHvef3u0mg_IIIS9SX4:b-f00z5o) ([raw file](https://github.com/intel-isl/open3d/blob/9179dce5bc3f1e15f6337be5765893e103fccdc2/cpp/open3d/core/kernel/CumSumCPU.cpp#L36)):*
> ```cpp
> Tensor CumSumCPU(const Tensor& src, Tensor& dst, int64_t dim) {
>     // Destination Tensor.
>     dst.CopyFrom(src);
> ```

copy the first slice instead of copy the whole tensor

**Review by yxlao — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2364)* status: all files reviewed, 6 unresolved discussions (waiting on @junha-l and @yxlao)

___
*[cpp/open3d/core/Tensor.cpp, line 1084 at r2](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHvhDC02CRXQ_uMXWsQ:-MHvhDC1A2d4iGOeLbgo:beh3cja) ([raw file](https://github.com/intel-isl/open3d/blob/9179dce5bc3f1e15f6337be5765893e103fccdc2/cpp/open3d/core/Tensor.cpp#L1084)):*
> ```cpp
> Tensor Tensor::CumSum(int64_t dim) const {
>     Tensor dst(GetShape(), dtype_, GetDevice());
>     return kernel::CumSum(*this, dst, dim);
> ```

`kernel::CumSum` shall return `void`; we return `dst` here.

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2364)* status: 3 of 9 files reviewed, 6 unresolved discussions (waiting on @junha-l and @yxlao)

___
*[cpp/open3d/core/Tensor.h, line 823 at r2](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHveEPj9TfDKijTk9sX:-MHvpkst-WOI-w0RCX0z:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/9179dce5bc3f1e15f6337be5765893e103fccdc2/cpp/open3d/core/Tensor.h#L823)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

dimension -> The dimension
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.cpp, line 1084 at r2](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHvhDC02CRXQ_uMXWsQ:-MHvpmIB95h-DnOoMPR7:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/9179dce5bc3f1e15f6337be5765893e103fccdc2/cpp/open3d/core/Tensor.cpp#L1084)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`kernel::CumSum` shall return `void`; we return `dst` here.
</blockquote></details>

Done.
___
*[cpp/open3d/core/kernel/CumSumCPU.cpp, line 36 at r2](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHvef3u0mg_IIIS9SX3:-MHvpq0o4dHLpIUkIF5U:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/9179dce5bc3f1e15f6337be5765893e103fccdc2/cpp/open3d/core/kernel/CumSumCPU.cpp#L36)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

copy the first slice instead of copy the whole tensor
</blockquote></details>

Done.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/Tensor.cpp  16
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6215738&bid=20266046)

**Review by junha-l — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, 1 of 7 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2364)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @junha-l and @yxlao)

___
*[cpp/open3d/core/kernel/CumSumCPU.cpp, line 48 at r1](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHuGKDDAqw9O6IVzNuw:-MHw1WE11xhoF9Jgp9de:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f25c2cd582fb3e04475f6a4c4cb9124b70103412/cpp/open3d/core/kernel/CumSumCPU.cpp#L48)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Probably it depends on the input shape. E.g. if the input tensor has shape `{N,}` where `N` is pretty large, each `add` only applies to single elements and parallel_scan might help. We can add some benchmarks in `cpp/benchmarks/core` and see if it helps.
</blockquote></details>

Done.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/Tensor.cpp  16
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6215738&bid=20266046)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/benchmarks/core/CumSum.cpp  1
- cpp/tests/core/Tensor.cpp  16
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6215738&bid=20266046)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/benchmarks/core/CumSum.cpp  1
- cpp/tests/core/Tensor.cpp  16
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6215738&bid=20266046)

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r3, 1 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2364)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @junha-l and @yxlao)

___
*[cpp/benchmarks/core/CumSum.cpp, line 47 at r5](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHxon3w34ABBnqSX9Bq:-MHxon3w34ABBnqSX9Br:bsoq38s) ([raw file](https://github.com/intel-isl/open3d/blob/aadc6c51de60a4c4829f4fb9a0b3da9739e07e42/cpp/benchmarks/core/CumSum.cpp#L47)):*
> ```cpp
> }
> 
> BENCHMARK_CAPTURE(CumSum, CPU, Device("CPU:0"))->Unit(benchmark::kMillisecond);
> ```

What kind of benchmark result did you get when `large_dim` is large or small?
___
*[cpp/open3d/core/kernel/CumSumCPU.cpp, line 53 at r5](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHxl-wV3EUxjwNtgvvE:-MHxl-wW1iDVBmz2lZd2:b-l1wmz2) ([raw file](https://github.com/intel-isl/open3d/blob/aadc6c51de60a4c4829f4fb9a0b3da9739e07e42/cpp/open3d/core/kernel/CumSumCPU.cpp#L53)):*
> ```cpp
>     template <class Tag>
>     void operator()(const tbb::blocked_range<size_t>& r, Tag) {
>         Tensor temp = sum;
> ```

Not sure if this would be problematic, since `Tensor temp = sum;` does not copy the Tensor. Potentially you'll need `Tensor::Copy()`. Need to check TBB's requirements.

Also seems the lambda expression form https://www.threadingbuildingblocks.org/docs/help/reference/algorithms/parallel_scan_func.html looks simpler, can we switch to that?

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2364)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @junha-l and @yxlao)

___
*[cpp/open3d/core/kernel/CumSumCPU.cpp, line 53 at r5](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHxl-wV3EUxjwNtgvvE:-MHyoSkQ-K0JHW091ald:b-nn9vvx) ([raw file](https://github.com/intel-isl/open3d/blob/aadc6c51de60a4c4829f4fb9a0b3da9739e07e42/cpp/open3d/core/kernel/CumSumCPU.cpp#L53)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Not sure if this would be problematic, since `Tensor temp = sum;` does not copy the Tensor. Potentially you'll need `Tensor::Copy()`. Need to check TBB's requirements.

Also seems the lambda expression form https://www.threadingbuildingblocks.org/docs/help/reference/algorithms/parallel_scan_func.html looks simpler, can we switch to that?
</blockquote></details>

Well, it passes unit test without ```Tensor::Copy()```, but I'll check the TBB's requirement again.

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2364)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @junha-l and @yxlao)

___
*[cpp/open3d/core/kernel/CumSumCPU.cpp, line 63 at r5](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHyt9Aj9YYvrOtLtyi4:-MHyt9Aj9YYvrOtLtyi5:b-ly7jnl) ([raw file](https://github.com/intel-isl/open3d/blob/aadc6c51de60a4c4829f4fb9a0b3da9739e07e42/cpp/open3d/core/kernel/CumSumCPU.cpp#L63)):*
> ```cpp
>     }
>     ScanSumBody(ScanSumBody& b, tbb::split) : out(b.out), in(b.in), dim(b.dim) {
>         sum = Tensor::Zeros(
> ```

I think it's okay not to use ```Tensor::Copy()``` in ```operator[]``` function, since it creates a new ```ScanSumBody``` instance with this constructor when parallel_scan splits into multiple threads.

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2364)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @junha-l and @yxlao)

___
*[cpp/benchmarks/core/CumSum.cpp, line 47 at r5](https://reviewable.io/reviews/intel-isl/open3d/2364#-MHxon3w34ABBnqSX9Bq:-MHyyTgq4oIoCKxZYcQt:b-b1pb2b) ([raw file](https://github.com/intel-isl/open3d/blob/aadc6c51de60a4c4829f4fb9a0b3da9739e07e42/cpp/benchmarks/core/CumSum.cpp#L47)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

What kind of benchmark result did you get when `large_dim` is large or small?
</blockquote></details>

It is really slow when ```large_dim``` is ```(1ULL << 27) + 10``` and cumsum operates on that dimension. 
And it seems that it gets slower when we use ```tbb::parallel_scan```.

~~I'll share the exact numbers after the benchmark is done.~~
It takes 584s without ```tbb::parallel_scan``` 
and takes 3530s with ```tbb::parallel_scan```

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/benchmarks/core/CumSum.cpp  1
- cpp/tests/core/Tensor.cpp  16
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6215738&bid=20266046)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/Tensor.cpp  16
- cpp/benchmarks/core/CumSum.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6215738&bid=20266046)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/Tensor.cpp  16
- python/test/core/test_core.py  4
- cpp/benchmarks/core/CumSum.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6215738&bid=20266046)

**Comment by yxlao** [comment]
Let's first revert back to the version without TBB. Still, it is way too slow. We need to figure out a different method.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- python/test/core/test_core.py  4
- cpp/benchmarks/core/CumSum.cpp  1
- cpp/tests/core/Tensor.cpp  16
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6215738&bid=20266046)

**Pull request closed without merging**
