### PR TITLE
Port header-only submodules to URL downloading

### PR DESCRIPTION
**Pull request by stotko**
This PR ports all header-only library that are currently included as `git submodules` to the `ExternalProject_Add` URL downloading approach:
- `Eigen`: Also upgrade from dev version to `3.4 RC1`
- `tinyobjloader`: Also upgrade from `2.0.0 RC1` to `2.0.0 RC8`
- Other ported libraries are kept at their particular version. Upgrading them should be evaluated in a different PR.

The remaining `git submodules` will be ported in a future PR to keep this one simpler.

Issue: #3134
Issue: #3640

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3643)

### CODE REVIEW

**Comment by Dudulle** [comment]
Eigen 3.4-rc1 fixes the nvcc warnings suppressed in `cpp/CMakeLists.txt`
The following lines are not necessary anymore after updating:
https://github.com/intel-isl/Open3D/blob/31a162d84fa3f5e3b95daae94b58d4a6410dd0ba/cpp/CMakeLists.txt#L25-L32
https://github.com/intel-isl/Open3D/blob/31a162d84fa3f5e3b95daae94b58d4a6410dd0ba/cpp/CMakeLists.txt#L41-L45

**Review by yxlao — APPROVED** [review]
> Reviewed 28 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3643)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ssheorey)

**Comment by stotko** [comment]
Awesome, thanks @Dudulle for figuring this out!

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3643)* status: 28 of 29 files reviewed, all discussions resolved (waiting on @stotko)

**Review by ssheorey — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3643)* status: 28 of 29 files reviewed, 1 unresolved discussion (waiting on @stotko)

___
*[cpp/CMakeLists.txt, line 29 at r2](https://reviewable.io/reviews/intel-isl/open3d/3643#-Md3cKnh2eNWujbQtmK5:-Md3cKnh2eNWujbQtmK6:bwdrqgn) ([raw file](https://github.com/intel-isl/open3d/blob/d6d2d0b3df09d5ff7a131d1790618e0ef2793334/cpp/CMakeLists.txt#L29)):*
> ```
> nodiscard
> ```
This still causes an error on Github CI:
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include\cub\host/mutex.cuh(91): error : ignoring return value from routine declared with "nodiscard" attribute [C:\Open3D\build\cpp\open3d\core\core.vcxproj]`

**Comment by Dudulle** [comment]
___
*[cpp/CMakeLists.txt, line 29 at r2](https://reviewable.io/reviews/intel-isl/open3d/3643#-Md3cKnh2eNWujbQtmK5:-Md3oP48-hgGKjZgu4aA:bdojedf) ([raw file](https://github.com/intel-isl/open3d/blob/d6d2d0b3df09d5ff7a131d1790618e0ef2793334/cpp/CMakeLists.txt#L29)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> nodiscard
> ```
This still causes an error on Github CI:
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include\cub\host/mutex.cuh(91): error : ignoring return value from routine declared with "nodiscard" attribute [C:\Open3D\build\cpp\open3d\core\core.vcxproj]`
</blockquote></details>

Right, sorry about that. Warning 2809 still needs to be suppressed.
This is fixed in CUDA 11.1 or 11.2 though.

**Review by stotko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3643)* status: 28 of 29 files reviewed, 1 unresolved discussion (waiting on @ssheorey)

___
*[cpp/CMakeLists.txt, line 29 at r2](https://reviewable.io/reviews/intel-isl/open3d/3643#-Md3cKnh2eNWujbQtmK5:-MdH5mFgBtcBh9E2Jlqr:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d6d2d0b3df09d5ff7a131d1790618e0ef2793334/cpp/CMakeLists.txt#L29)):*
<details><summary><i>Previously, Dudulle (Cyril Kaiser) wrote…</i></summary><blockquote>

Right, sorry about that. Warning 2809 still needs to be suppressed.
This is fixed in CUDA 11.1 or 11.2 though.
</blockquote></details>

Done.

**Review by yxlao — APPROVED** [review]

**Pull request merged**
