### PR TITLE
resolves pts format of docs (#1771)

### LINKED ISSUE #1771: pts format: Explanation of i in the documentation missing
I'm working with Open3D with data from different devices. One of them does not provide the point cloud as a file, so I am creating the file by myself with a little Python script.

However, I am confused by the supported formats: 
The **pts format** contains lines of `[x, y, z, i, r, g, b]`.  xyz and rgb are intuitive and explained, but **what exactly is the i for?** And in what format is it expected? 
I looked through the [documentation](http://www.open3d.org/docs/release/tutorial/Basic/file_io.html) of both Python and C++ and searched on the internet for the pts format, but found no easy explanation.

### PR DESCRIPTION
**Pull request by jbjeong**
* resolves #1771 
* add an explanation of intensity value 'i'

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1816)

### CODE REVIEW

**Comment by jbjeong** [comment]
According to that [http://www.danielgm.net/cc/forum/viewtopic.php?t=1307](http://www.danielgm.net/cc/forum/viewtopic.php?t=1307), the range of intensity value `i` is pseudo-standards and 'intensity' field highly depends on the scanner manufacturer.

I found this documentation: [pts](http://paulbourke.net/dataformats/pts/) and it says the range is 0 ~ 255.

By the way, current Open3D implementation ignores the `intensity` 
https://github.com/intel-isl/Open3D/blob/47f77f6f89545054513edafd932cf66787b49c5a/src/Open3D/IO/FileFormat/FilePTS.cpp#L77

**Comment by germanros1987** [comment]
@jbjeong sorry for the delay in merging this. Could you please resolve the conflicts?

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/Open3D/Visualization/Shader/Shader.h  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5503400&bid=18038407)

**Comment by jbjeong** [comment]
Okay.

**Comment by yxlao** [comment]
Closing this for now as it seems that the intensity value does not have a clear specification, and it could be sensor dependent. 
The current implementation does not load intensity in the PTS file. We'll be adding support to loading pts file with intensity values for the tensor-based point cloud.

**Comment by yxlao** [comment]
Added asana task https://app.asana.com/0/1111336323009173/1199555181435487 @ShubhamAgarwal12

**Pull request closed without merging**
