### PR TITLE
Tensor nested initializer list with recursion

### PR DESCRIPTION
**Pull request by ShubhamAgarwal12**
Implementation of nested initializer list. 
Changes Tensor Init to utilize the same.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3055)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3055)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @ShubhamAgarwal12)

___
*[cpp/open3d/core/NestedInitializeList.h, line 1 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr2TfB9gYyPG8k-t1O:-MTr2TfB9gYyPG8k-t1P:bujioet) ([raw file](https://github.com/intel-isl/open3d/blob/89bfc1490130f926af9917ad1b271859cbe0bb8b/cpp/open3d/core/NestedInitializeList.h#L1)):*
> ```objc
> #include <open3d/core/Scalar.h>
> ```

Remove `Scalar.h`? 
Call this `TensorInit.h`
___
*[cpp/open3d/core/NestedInitializeList.h, line 3 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr2bsZ71Vinm1Vzo0I:-MTr2bsZ71Vinm1Vzo0J:bbl1pea) ([raw file](https://github.com/intel-isl/open3d/blob/89bfc1490130f926af9917ad1b271859cbe0bb8b/cpp/open3d/core/NestedInitializeList.h#L3)):*
> ```objc
> #include <open3d/core/Scalar.h>
> 
> #include <cassert>
> ```

Check and remove unnecessary headers. 

E.g. is `cassert` used? what about others?
___
*[cpp/open3d/core/NestedInitializeList.h, line 12 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr2mJWCeHBU7zB5uZW:-MTr2mJWCeHBU7zB5uZX:b-ey9pxx) ([raw file](https://github.com/intel-isl/open3d/blob/89bfc1490130f926af9917ad1b271859cbe0bb8b/cpp/open3d/core/NestedInitializeList.h#L12)):*
> ```objc
> namespace core {
> 
> /***************************
> ```

remove comments
___
*[cpp/open3d/core/NestedInitializeList.h, line 17 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr2rPh0NQOgHsQmwA7:-MTr2rPh0NQOgHsQmwA8:bcxynk3) ([raw file](https://github.com/intel-isl/open3d/blob/89bfc1490130f926af9917ad1b271859cbe0bb8b/cpp/open3d/core/NestedInitializeList.h#L17)):*
> ```objc
> 
> template <class T, std::size_t I>
> struct nested_initializer_list {
> ```

name class/struct with `CamelCase`, i.e. `NestedInitializerList`, same for the rest
___
*[cpp/open3d/core/NestedInitializeList.h, line 28 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr382SAkC4tv9FnBhk:-MTr382SAkC4tv9FnBhl:b-x4sv1j) ([raw file](https://github.com/intel-isl/open3d/blob/89bfc1490130f926af9917ad1b271859cbe0bb8b/cpp/open3d/core/NestedInitializeList.h#L28)):*
> ```objc
> 
> template <class T, std::size_t I>
> using nested_initializer_list_t = typename nested_initializer_list<T, I>::type;
> ```

name the type with `CamelCase`, same for the rest
___
*[cpp/open3d/core/NestedInitializeList.h, line 31 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr39p6-lc87niFAazE:-MTr39p6-lc87niFAazF:b-r6uneh) ([raw file](https://github.com/intel-isl/open3d/blob/89bfc1490130f926af9917ad1b271859cbe0bb8b/cpp/open3d/core/NestedInitializeList.h#L31)):*
> ```objc
> 
> template <class T, class S>
> void nested_copy(T&& iter, const S& s) {
> ```

name a function with `CamelCase`, same for the rest
___
*[cpp/open3d/core/Tensor.h, line 237 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr3Mof839e2Nl3aR3p:-MTr3Mof839e2Nl3aR3q:b-fgp956) ([raw file](https://github.com/intel-isl/open3d/blob/89bfc1490130f926af9917ad1b271859cbe0bb8b/cpp/open3d/core/Tensor.h#L237)):*
> ```objc
>     /// Create a n-D tensor with initializer list.
>     template <typename T, std::size_t I>
>     static Tensor InitN(const nested_initializer_list_t<T, I> nested_list,
> ```

this should be private
___
*[cpp/open3d/core/Tensor.h, line 268 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr3dBzB6SnDZotDh09:-MTr3dBzB6SnDZotDh0A:b-lzvlni) ([raw file](https://github.com/intel-isl/open3d/blob/89bfc1490130f926af9917ad1b271859cbe0bb8b/cpp/open3d/core/Tensor.h#L268)):*
> ```objc
>     template <typename T>
>     static Tensor Init(
>             const std::initializer_list<std::initializer_list<T>> in_list,
> ```

Instead of `std::initializer_list<std::initializer_list<T>>`, use `NestedInitializerList<T, 2>`. Same for the 0d, 1d, 2d, 3d case.
___
*[cpp/tests/core/Tensor.cpp, line 2797 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr4OEy76h9zu34jyk6:-MTr4OEy76h9zu34jyk7:byp330p) ([raw file](https://github.com/intel-isl/open3d/blob/89bfc1490130f926af9917ad1b271859cbe0bb8b/cpp/tests/core/Tensor.cpp#L2797)):*
> ```cpp
> 
> }  // namespace tests
> }  // namespace open3d
> ```

add an empty line at the end

**Review by ShubhamAgarwal12 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3055)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/Tensor.h, line 237 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr3Mof839e2Nl3aR3p:-MTsaiObCcPiOVpySDD6:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/216b36b64115277156bb24e5aa9bba5be0915d5a/cpp/open3d/core/Tensor.h#L237)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

this should be private
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.h, line 268 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr3dBzB6SnDZotDh09:-MTsal108mqT8_pHk62Z:b-uofpqk) ([raw file](https://github.com/intel-isl/open3d/blob/216b36b64115277156bb24e5aa9bba5be0915d5a/cpp/open3d/core/Tensor.h#L268)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Instead of `std::initializer_list<std::initializer_list<T>>`, use `NestedInitializerList<T, 2>`. Same for the 0d, 1d, 2d, 3d case.
</blockquote></details>

Using the "NestedInitializerList<T, 2>" leads to ambiguity for 0-dimensional inputs similar to the one we faced without template. To avoid this, I used the explicit nested std::initializer_list<T> wrappers.
___
*[cpp/tests/core/Tensor.cpp, line 2797 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr4OEy76h9zu34jyk6:-MTsbnNW1Yny7lc5hRCJ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/216b36b64115277156bb24e5aa9bba5be0915d5a/cpp/tests/core/Tensor.cpp#L2797)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add an empty line at the end
</blockquote></details>

Done.
___
*[cpp/open3d/core/NestedInitializeList.h, line 1 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr2TfB9gYyPG8k-t1O:-MTsbffp5-cv4a0E1AOe:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/216b36b64115277156bb24e5aa9bba5be0915d5a/cpp/open3d/core/NestedInitializeList.h#L1)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Remove `Scalar.h`? 
Call this `TensorInit.h`
</blockquote></details>

Done.
___
*[cpp/open3d/core/NestedInitializeList.h, line 3 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr2bsZ71Vinm1Vzo0I:-MTsbg6b-xKQ8l94oo8u:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/216b36b64115277156bb24e5aa9bba5be0915d5a/cpp/open3d/core/NestedInitializeList.h#L3)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Check and remove unnecessary headers. 

E.g. is `cassert` used? what about others?
</blockquote></details>

Done.
___
*[cpp/open3d/core/NestedInitializeList.h, line 12 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr2mJWCeHBU7zB5uZW:-MTsbhHAEQbd2DxNF4xj:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/216b36b64115277156bb24e5aa9bba5be0915d5a/cpp/open3d/core/NestedInitializeList.h#L12)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove comments
</blockquote></details>

Done.
___
*[cpp/open3d/core/NestedInitializeList.h, line 17 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr2rPh0NQOgHsQmwA7:-MTsbiBv72QdEMwxi3yN:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/216b36b64115277156bb24e5aa9bba5be0915d5a/cpp/open3d/core/NestedInitializeList.h#L17)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

name class/struct with `CamelCase`, i.e. `NestedInitializerList`, same for the rest
</blockquote></details>

Done.
___
*[cpp/open3d/core/NestedInitializeList.h, line 28 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr382SAkC4tv9FnBhk:-MTsbitj1CH-Ru_L4ZuY:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/216b36b64115277156bb24e5aa9bba5be0915d5a/cpp/open3d/core/NestedInitializeList.h#L28)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

name the type with `CamelCase`, same for the rest
</blockquote></details>

Done.
___
*[cpp/open3d/core/NestedInitializeList.h, line 31 at r1](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTr39p6-lc87niFAazE:-MTsbjqG5DK2ngPRv52f:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/216b36b64115277156bb24e5aa9bba5be0915d5a/cpp/open3d/core/NestedInitializeList.h#L31)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

name a function with `CamelCase`, same for the rest
</blockquote></details>

Done.

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3055)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @ShubhamAgarwal12 and @yxlao)

___
*[cpp/open3d/core/Tensor.h, line 1114 at r3](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTyUVHwCQ_qgfDplR0x:-MTyUVHx8VB7gMx939Gz:b-j4mx2) ([raw file](https://github.com/intel-isl/open3d/blob/ec1d9afb89c843271a0d6cbb7187cd4bceac1d9f/cpp/open3d/core/Tensor.h#L1114)):*
> ```objc
>     std::string ScalarPtrToString(const void* ptr) const;
> 
> private:
> ```

it can be `protected`, since other "hidden" functions are `protected` here
___
*[cpp/open3d/core/Tensor.h, line 1116 at r3](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTyWh9P7n7-MZSxpJ6L:-MTyWh9P7n7-MZSxpJ6M:btbm2wh) ([raw file](https://github.com/intel-isl/open3d/blob/ec1d9afb89c843271a0d6cbb7187cd4bceac1d9f/cpp/open3d/core/Tensor.h#L1116)):*
> ```objc
> private:
>     /// Create a n-D tensor with initializer list.
>     template <typename T, std::size_t I>
> ```

`size_t` (remove `std::`)
___
*[cpp/open3d/core/TensorInit.h, line 1 at r3](https://reviewable.io/reviews/intel-isl/open3d/3055#-MU1IOa-1Ax7d8vv2MQP:-MU1IOa-1Ax7d8vv2MQQ:bme3lgq) ([raw file](https://github.com/intel-isl/open3d/blob/ec1d9afb89c843271a0d6cbb7187cd4bceac1d9f/cpp/open3d/core/TensorInit.h#L1)):*
> ```objc
> // ----------------------------------------------------------------------------
> ```

The OpenBLAS x86 CI is failing to compile. Could you check to see what was the issue? 
___
*[cpp/open3d/core/TensorInit.h, line 27 at r3](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTyToyF-02cSjLXQGzn:-MTyToyF-02cSjLXQGzo:b6nuatc) ([raw file](https://github.com/intel-isl/open3d/blob/ec1d9afb89c843271a0d6cbb7187cd4bceac1d9f/cpp/open3d/core/TensorInit.h#L27)):*
> ```objc
> // ----------------------------------------------------------------------------
> 
> #pragma once
> ```

The `#pragma once` was missing, so I added it here.

Besides, could you add the necessary headers for `TensorInit.h`? That is, directly compile `TensorInit.h` with a dummy `main` function and add the missing headers. This will make sure that later if `TensorInit.h` is included by some other files but not `Tensor.h`, the headers are there.
___
*[cpp/open3d/core/TensorInit.h, line 32 at r3](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTySM8A2e17WuYdc3yh:-MTySM8A2e17WuYdc3yi:bw4j7w9) ([raw file](https://github.com/intel-isl/open3d/blob/ec1d9afb89c843271a0d6cbb7187cd4bceac1d9f/cpp/open3d/core/TensorInit.h#L32)):*
> ```objc
> namespace core {
> 
> template <class T, std::size_t I>
> ```

`std::size_t` can be `size_t`
___
*[cpp/open3d/core/TensorInit.h, line 107 at r3](https://reviewable.io/reviews/intel-isl/open3d/3055#-MTySWD_Chgq8nck5zpa:-MTySWD_Chgq8nck5zpb:b-qlh9if) ([raw file](https://github.com/intel-isl/open3d/blob/ec1d9afb89c843271a0d6cbb7187cd4bceac1d9f/cpp/open3d/core/TensorInit.h#L107)):*
> ```objc
> 
> template <class R, class T>
> constexpr R Shape(T t) {
> ```

One drawback of this approach is that we expose these helper functions to the public header, e.g. people will be confused to see `open3d::core::Shape`.

Could you think of a way to hide these helper functions/classes? One example is to use a new namespace, e.g., `open3d::core::tensor_init::Shape`.

**Comment by yxlao** [comment]
@ShubhamAgarwal12 you may follow https://github.com/intel-isl/Open3D/blob/63ffaf34f1a1ce4817785c3f1061cacbd74b34bc/.github/workflows/arm64.yml#L18 to install dependencies for openblas and compile with openblas locally, in order to debug the ci issue.

**Pull request merged**
