### PR TITLE
Tensor Multi Scale ICP [min. required changes]

### PR DESCRIPTION
**Pull request by reyanshsolis**
Changes:

- Added `Multi-Scale ICP` in `Tensor Registration` [+ added pybinds].
- Changed the `Transform` function to return directly if the transformation tensor is `identity.
- `Removed 1NNSearch`, as HybridSearch is now optimized. Clears up the interface.

- Refactored ICP pipeline to follow:
```(N, 6) Float32 system -> reduce -> (6, 6) Float32 system -> convert -> (6, 6) Float64 system on CPU -> solve -> (6, 1) Float64 pose on CPU -> (4, 4) Float64 matrix on CPU```

[Unit Test not added, will add that with #3253]. Results verified using example testing.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3285)

### CODE REVIEW

**Review by theNded — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3285)* status: all files reviewed, 3 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 294 at r2](https://reviewable.io/reviews/intel-isl/open3d/3285#-MYKtkvU1Ga8lAxejTo9:-MYKtkvU1Ga8lAxejToA:b-mwaj7u) ([raw file](https://github.com/intel-isl/open3d/blob/7c419cc36f4c0438b6dc277934a64de184f5977b/cpp/open3d/core/nns/NanoFlannIndex.cpp#L294)):*
> ```cpp
>                         while (neighbour_idx < max_knn) {
>                             indices_ptr[result_idx + neighbour_idx] = -1;
>                             distances_ptr[result_idx + neighbour_idx] = 0;
> ```

-1 makes more sense to me, if it doesn't do harm to performance.
___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 179 at r2](https://reviewable.io/reviews/intel-isl/open3d/3285#-MYKt7ci86kBGVkJoNf6:-MYKt7ci86kBGVkJoNf7:b-nxiqco) ([raw file](https://github.com/intel-isl/open3d/blob/7c419cc36f4c0438b6dc277934a64de184f5977b/cpp/open3d/t/pipelines/registration/Registration.h#L179)):*
> ```objc
>         const std::vector<double> &max_correspondence_distances,
>         const core::Tensor &init = core::Tensor::Eye(4,
>                                                      core::Dtype::Float32,
> ```

The 4x4 transformation matrix should always use Float64 and should always be on CPU. 
If I haven't been clear enough, please refer to this:
(N, 6) Float32 system -> reduce -> (6, 6) Float32 system -> convert -> (6, 6) Float64 system on CPU -> solve -> (6, 1) Float64 pose on CPU -> (4, 4) Float64 matrix on CPU
___
*[cpp/pybind/t/pipelines/registration/registration.cpp, line 244 at r2](https://reviewable.io/reviews/intel-isl/open3d/3285#-MYKtg5l-v_NsoCcl7UG:-MYKtg5m44z0_svnqCft:b-kmzxkb) ([raw file](https://github.com/intel-isl/open3d/blob/7c419cc36f4c0438b6dc277934a64de184f5977b/cpp/pybind/t/pipelines/registration/registration.cpp#L244)):*
> ```cpp
>     m.def("registration_icp", &RegistrationICP, "Function for ICP registration",
>           "source"_a, "target"_a, "max_correspondence_distance"_a,
>           "init"_a = core::Tensor::Eye(4, core::Dtype::Float32,
> ```

Float64

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3285)* status: all files reviewed, 3 unresolved discussions (waiting on @reyanshsolis and @theNded)

___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 294 at r2](https://reviewable.io/reviews/intel-isl/open3d/3285#-MYKtkvU1Ga8lAxejTo9:-MYKxUco1JT0gUSdj866:b-n113e8) ([raw file](https://github.com/intel-isl/open3d/blob/7c419cc36f4c0438b6dc277934a64de184f5977b/cpp/open3d/core/nns/NanoFlannIndex.cpp#L294)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

-1 makes more sense to me, if it doesn't do harm to performance.
</blockquote></details>

When we keep it -1, then we first need to search for -1 indices and fetch them before using reduction. 
Keeping it 0 allows reducing directly, and we still have indices as -1 for no correspondence case.

In PCL implementation, I remember using distance > 0.001 conditions on the search result, to check the valid indices and distance, so ig there also it was 0. 
___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 179 at r2](https://reviewable.io/reviews/intel-isl/open3d/3285#-MYKt7ci86kBGVkJoNf6:-MYKyBkSAXsIyVolw_Wk:b-j6yr3x) ([raw file](https://github.com/intel-isl/open3d/blob/7c419cc36f4c0438b6dc277934a64de184f5977b/cpp/open3d/t/pipelines/registration/Registration.h#L179)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

The 4x4 transformation matrix should always use Float64 and should always be on CPU. 
If I haven't been clear enough, please refer to this:
(N, 6) Float32 system -> reduce -> (6, 6) Float32 system -> convert -> (6, 6) Float64 system on CPU -> solve -> (6, 1) Float64 pose on CPU -> (4, 4) Float64 matrix on CPU
</blockquote></details>

Since we are only supporting Float32 type point cloud, the user will need to convert the transformation matrix every time before using it to transform the point cloud. Would you suggest to
- just change the transformation to Float64 
- or, change the default support from Float32 pointcloud to Float64 pointcloud and change transformation to Float64, 
- or add support for both the pointcloud in this release and keep Transformation same as pointcloud dtype and Float64 by default ?

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3285)* status: 6 of 17 files reviewed, 3 unresolved discussions (waiting on @reyanshsolis and @theNded)

___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 179 at r2](https://reviewable.io/reviews/intel-isl/open3d/3285#-MYKt7ci86kBGVkJoNf6:-MYLN7kk5sWrgPvKTRtJ:bs7wumx) ([raw file](https://github.com/intel-isl/open3d/blob/7c419cc36f4c0438b6dc277934a64de184f5977b/cpp/open3d/t/pipelines/registration/Registration.h#L179)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Since we are only supporting Float32 type point cloud, the user will need to convert the transformation matrix every time before using it to transform the point cloud. Would you suggest to
- just change the transformation to Float64 
- or, change the default support from Float32 pointcloud to Float64 pointcloud and change transformation to Float64, 
- or add support for both the pointcloud in this release and keep Transformation same as pointcloud dtype and Float64 by default ?
</blockquote></details>

Done.

**Review by theNded — APPROVED** [review]
> Reviewed 12 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3285)* status: 18 of 19 files reviewed, 3 unresolved discussions (waiting on @reyanshsolis and @theNded)

___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 108 at r3](https://reviewable.io/reviews/intel-isl/open3d/3285#-MYk2zMfCTW2YOhzBkEb:-MYk2zMfCTW2YOhzBkEc:b-l524up) ([raw file](https://github.com/intel-isl/open3d/blob/fa4a180aa896d495ef3a99e097a76b59bc9904e8/cpp/open3d/t/pipelines/registration/Registration.cpp#L108)):*
> ```cpp
>                                         const core::Tensor &transformation) {
>     core::Device device = source.GetDevice();
>     core::Dtype dtype = core::Dtype::Float32;
> ```

Are we sticking to Float32 for evaluation?
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 254 at r3](https://reviewable.io/reviews/intel-isl/open3d/3285#-MYk357E1CdM2-kxeMR1:-MYk357E1CdM2-kxeMR2:b-80uh6n) ([raw file](https://github.com/intel-isl/open3d/blob/fa4a180aa896d495ef3a99e097a76b59bc9904e8/cpp/open3d/t/pipelines/registration/Registration.cpp#L254)):*
> ```cpp
>                                                    target_down_pyramid[i],
>                                                    result.correspondence_set_)
>                             .To(device, dtype);
> ```

Are we sticking to device version matmul?

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3285)* status: 14 of 19 files reviewed, 3 unresolved discussions (waiting on @theNded)

___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 108 at r3](https://reviewable.io/reviews/intel-isl/open3d/3285#-MYk2zMfCTW2YOhzBkEb:-MYkwmbE-eCqxyiNFpb_:b-74mkit) ([raw file](https://github.com/intel-isl/open3d/blob/fa4a180aa896d495ef3a99e097a76b59bc9904e8/cpp/open3d/t/pipelines/registration/Registration.cpp#L108)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Are we sticking to Float32 for evaluation?
</blockquote></details>

Float32 is for the point cloud. 
Transformation is expected to be of `Float64` on `CPU`, in ` source_transformed.Transform(transformation.To(device, dtype));` the device and dtype are matched with the pointcloud. 
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 254 at r3](https://reviewable.io/reviews/intel-isl/open3d/3285#-MYk357E1CdM2-kxeMR1:-MYkxtUf2ztWTDISsOa7:b-4l2svp) ([raw file](https://github.com/intel-isl/open3d/blob/fa4a180aa896d495ef3a99e097a76b59bc9904e8/cpp/open3d/t/pipelines/registration/Registration.cpp#L254)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Are we sticking to device version matmul?
</blockquote></details>

  Changed. Done.
___
*[cpp/pybind/t/pipelines/registration/registration.cpp, line 244 at r2](https://reviewable.io/reviews/intel-isl/open3d/3285#-MYKtg5l-v_NsoCcl7UG:-MYkxeNCEV-7RtK-ak4P:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/7c419cc36f4c0438b6dc277934a64de184f5977b/cpp/pybind/t/pipelines/registration/registration.cpp#L244)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Float64
</blockquote></details>

Done.

**Pull request merged**
