### PR TITLE
ARM CI

### PR DESCRIPTION
**Pull request by yxlao**
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2414)

### CODE REVIEW

**Review by theNded — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2414)* status: all files reviewed, 1 unresolved discussion (waiting on @yxlao)

___
*[.github/workflows/macos.yml, line 1 at r1](https://reviewable.io/reviews/intel-isl/open3d/2414#-MIj98ifCak_9NYnGiNw:-MIj98ifCak_9NYnGiNx:b-se3q30) ([raw file](https://github.com/intel-isl/open3d/blob/e61dd3ef3127ab2f808dd89a5cd8362437c2fabc/.github/workflows/macos.yml#L1)):*
> ```YAML
> name: MacOS CI
> ```

The official name should be macOS right?

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2414)* status: all files reviewed, 1 unresolved discussion (waiting on @theNded)

___
*[.github/workflows/macos.yml, line 1 at r1](https://reviewable.io/reviews/intel-isl/open3d/2414#-MIj98ifCak_9NYnGiNw:-MIjxAdr9xlMnPtosQn2:bmit0e) ([raw file](https://github.com/intel-isl/open3d/blob/e61dd3ef3127ab2f808dd89a5cd8362437c2fabc/.github/workflows/macos.yml#L1)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

The official name should be macOS right?
</blockquote></details>

Yes, it is macOS officialy. But it doesn't look nice in our list of CIs, since other names are upper case.

I've changed it back to macOS.

**Review by theNded — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2414)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by yxlao** [comment]
thanks @theNded , merging

**Pull request merged**
