### PR TITLE
Fix macOS GL function call segmentaiton fault when BUILD_GUI=ON

### LINKED ISSUE #2552: open3d.visualization.VisualizerWithVertexSelection produces Segmentation fault on Mac OS with v0.11.1
**Describe the bug**
I'm trying to use the open3d.visualization.VisualizerWithVertexSelection class to create an interactive visualization, however it always crashes with segmentation fault (Error message: `Segmentation fault: 11`).

**To Reproduce**

I wrote a simple script to test the behavior of VisualizerWithVertexSelection:
```
import open3d as o3d

pcd = o3d.io.read_point_cloud('test.pcd')
vis = o3d.visualization.VisualizerWithVertexSelection()

vis.create_window()
vis.add_geometry(pcd)
vis.run()
```
and ran it using Open3D v0.11.1, which produces a segmentation fault without opening any window. I switched my Open3D version to v0.11.0, and I was able to run the script without any trouble, so hopefully this can help identify the issue. Works just fine with both versions on Ubuntu.

**Expected behavior**
Expected to have a functional VisualizerWithVertexSelection window appear.

**Environment (please complete the following information):**

- Operating system: MacOS 10.15.6
- Python version: Python 3.7.1
- Open3D version: 0.11.1
- Is this remote workstation?: no
- How did you install Open3D?: pip

### LINKED ISSUE #2598: Segmentation fault: 11 on MacOS Mojave 10.14.6
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**

Segmentation fault: 11 on MacOS Mojave 10.14.6.

**To Reproduce**

1. cd Open3D/python/examples/python

Saved this
`import open3d as o3d

print("Load a ply point cloud, print it, and render it")
pcd = o3d.io.read_point_cloud("../test_data/fragment.ply")
print(pcd)

o3d.visualization.draw_geometries([pcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])`
under name visu-poclo.py.

2. python visu-poclo.py

3. See error
`Load a ply point cloud, print it, and render it
PointCloud with 196133 points.
Segmentation fault: 11`

**Expected behavior**
Point cloud rendering window.

**Screenshots**

**Environment (please complete the following information):**

- Operating system: MacOS Mojave 10.14.6.
- Python version: 3.8.3
- Open3D version: open3d-0.11.2
- Is this remote workstation?:  no
- How did you install Open3D?: 
conda install -c open3d-admin open3d
conda install -c conda-forge addict
conda install -c conda-forge plyfile

- Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)

**Additional context**

Tried on two Macs.
C++ programs, like Open3D.app work fine.

### PR DESCRIPTION
**Pull request by yxlao**
Question: do we have a better way to trigger `bluegl::bind()` using Filament's public API? In this way, we can avoid having to include `bluegl`'s header.

Fixes #2598
Fixes #2552

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2807)

### CODE REVIEW

**Review by errissa — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2807)* status: all files reviewed, 2 unresolved discussions (waiting on @prewettg and @yxlao)

___
*[cpp/open3d/visualization/visualizer/Visualizer.cpp, line 32 at r2](https://reviewable.io/reviews/intel-isl/open3d/2807#-MP9wM6T2z-8HHbMLwKE:-MP9wM6U3-R7PiZEaiCo:b-v2a6ky) ([raw file](https://github.com/intel-isl/open3d/blob/4a22c1594a34788e2f8c8fee667e00ff46c9474b/cpp/open3d/visualization/visualizer/Visualizer.cpp#L32)):*
> ```cpp
> 
> #if defined(__APPLE__) && defined(BUILD_GUI)
> #include <bluegl/BlueGL.h>
> ```

Instead of cloning filament source how about declaring `bluegl::bind` and `bluegl::unbind` here as `extern`?
___
*[cpp/open3d/visualization/visualizer/VisualizerRender.cpp, line 38 at r2](https://reviewable.io/reviews/intel-isl/open3d/2807#-MP9webM8raDA0lBsDJI:-MP9webM8raDA0lBsDJJ:bu6xv6u) ([raw file](https://github.com/intel-isl/open3d/blob/4a22c1594a34788e2f8c8fee667e00ff46c9474b/cpp/open3d/visualization/visualizer/VisualizerRender.cpp#L38)):*
> ```cpp
> 
> #if defined(__APPLE__) && defined(BUILD_GUI)
> #include <bluegl/BlueGL.h>
> ```

See previous comment.

**Review by yxlao — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2807)* status: all files reviewed, 2 unresolved discussions (waiting on @errissa and @prewettg)

___
*[cpp/open3d/visualization/visualizer/Visualizer.cpp, line 32 at r2](https://reviewable.io/reviews/intel-isl/open3d/2807#-MP9wM6T2z-8HHbMLwKE:-MPAJZ3108oJtF9hNcgE:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/4a22c1594a34788e2f8c8fee667e00ff46c9474b/cpp/open3d/visualization/visualizer/Visualizer.cpp#L32)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

Instead of cloning filament source how about declaring `bluegl::bind` and `bluegl::unbind` here as `extern`?
</blockquote></details>

Done.
___
*[cpp/open3d/visualization/visualizer/VisualizerRender.cpp, line 38 at r2](https://reviewable.io/reviews/intel-isl/open3d/2807#-MP9webM8raDA0lBsDJI:-MPAJZbe8ZB5kmzat4VD:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/4a22c1594a34788e2f8c8fee667e00ff46c9474b/cpp/open3d/visualization/visualizer/VisualizerRender.cpp#L38)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

See previous comment.
</blockquote></details>

Done.

**Review by yxlao — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2807)* status: all files reviewed, 2 unresolved discussions (waiting on @errissa and @prewettg)

___
*[cpp/open3d/visualization/visualizer/Visualizer.cpp, line 32 at r2](https://reviewable.io/reviews/intel-isl/open3d/2807#-MP9wM6T2z-8HHbMLwKE:-MPAL00o06DZPQQzj2bq:b-myhatu) ([raw file](https://github.com/intel-isl/open3d/blob/4a22c1594a34788e2f8c8fee667e00ff46c9474b/cpp/open3d/visualization/visualizer/Visualizer.cpp#L32)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

From https://stackoverflow.com/a/2604280/1255535, looks like we could drop the `extern` keyword for functions.

**Review by errissa — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2807)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @prewettg)

**Pull request merged**
