### PR TITLE
initial support for tensor-based mesh

### PR DESCRIPTION
**Pull request by yxlao**
In this PR:
- Similar design to `tgeometry::PointCloud`, but now `TriangleMesh` has a point dict and a triangle dict
- Used the name "point" instead of "vertex" to be consistent with the point cloud class
- Container only PR with getter/setter/has-test/push-back, other member functions are marked as unimplemented

One thing to discuss is the convenience functions for getter and setters:
- They are good for "type-safe" programming, buy avoiding string-based attributes in C++ code
- However, they also introduce a new learning curve for the user

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2167)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/tgeometry/PointCloud.h  4
- cpp/open3d/tgeometry/TriangleMesh.h  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6008750&bid=19697175)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/tgeometry/TriangleMesh.h  4
- cpp/open3d/tgeometry/PointCloud.h  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6008750&bid=19697175)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/tgeometry/TriangleMesh.h  4
- cpp/open3d/tgeometry/PointCloud.h  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6008750&bid=19697175)

**Comment by yxlao** [comment]
@griegler all comments addressed, ready to be reviewed again.

**Review by griegler — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2167)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @benjaminum, @griegler, @theNded, and @yxlao)

___
*[cpp/open3d/tgeometry/TriangleMesh.h, line 166 at r1](https://reviewable.io/reviews/intel-isl/open3d/2167#-MEgsVc6C0Ms-5R3D-gO:-MFa8Jyn9-VxVdYFJrAK:b-4edyp8) ([raw file](https://github.com/intel-isl/open3d/blob/72a66facf066413a99d75452bb064e85585362f5/cpp/open3d/tgeometry/TriangleMesh.h#L166)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

if both vertex color and triangle color are specified, we also need to decide how to render it
also we don't have triangle colors in the original triangle mesh
let's discuss this in the Wed meeting
</blockquote></details>

Yes, we would need an ordering in the visualization, but I can remember some issues asking for this and right now it is only possible with duplication of vertices.

**Pull request merged**
