### PR TITLE
Optimize TSDF-related operations

### PR DESCRIPTION
**Pull request by theNded**
- Upgrade hashmap interface to support `clear` for in-place hashmap update
- Implement `Inverse` specifically for 4x4 transformation matrices
- Rewrite raycasting and support min/max range for adaptive raycasting
- Support predefined number of points for surface extraction
- Redefine protocols for intrinsic/extrinsic processing: type/device check in the kernel caller, assert in the macro/indexer
- Add experimental voxelhashing's Model and Frame interfaces and CLI voxel hashing

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3314)

### CODE REVIEW

**Review by yxlao — APPROVED** [review]
LGTM after minor changes

> Reviewed 28 of 37 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3314#-:-MYrG8KY8h2qMSRHEHzy:b-ose09f)* status: all files reviewed, 12 unresolved discussions (waiting on @reyanshsolis, @ssheorey, and @theNded)

___
*[cpp/open3d/t/geometry/TSDFVoxelGrid.h, line 90 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYqkJDQ2xpbOBtKgVr4:-MYqkJDQ2xpbOBtKgVr5:bhhyn15) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/geometry/TSDFVoxelGrid.h#L90)):*
> ```objc
> 
>     enum SurfaceMaskCode {
>         VertexMap = 1,
> ```

I would recommend starting from `0`, and use `<<`, similar to:

https://github.com/intel-isl/Open3D/blob/3ea00489d13ac7ef826d09e320972d4649782013/cpp/open3d/visualization/gui/Events.h#L35-L42
___
*[cpp/open3d/t/geometry/Utility.h, line 36 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYqvnIgD2ymFoaTKo2f:-MYqvnIgD2ymFoaTKo2g:bcdff6) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/geometry/Utility.h#L36)):*
> ```objc
> 
> /// TODO(wei): find a proper place for such functionalities
> inline core::Tensor InverseTransformation(const core::Tensor& T) {
> ```

could we change it to lower case `t`?
___
*[cpp/open3d/t/geometry/Utility.h, line 45 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYqvaE_8P7-AkOkwoqp:-MYqvaE_8P7-AkOkwoqq:bkat5u0) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/geometry/Utility.h#L45)):*
> ```objc
> 
>     core::Tensor Tinv({4, 4}, core::Dtype::Float64, core::Device("CPU:0"));
>     const double* T_ptr = static_cast<const double*>(T.GetDataPtr());
> ```

`T.GetDataPtr<double>()` works for both const and non-const
___
*[cpp/open3d/t/geometry/kernel/GeometryIndexer.h, line 64 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYqxJ3m8SbeJKj9MjG7:-MYqvkiR0fpFKiaaJDg9:blnnq4o) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/geometry/kernel/GeometryIndexer.h#L64)):*
> ```objc
> 
>         const double* intrinsic_ptr =
>                 static_cast<const double*>(intrinsics.GetDataPtr());
> ```

same, `GetDataPtr<T>()`
___
*[cpp/open3d/t/geometry/kernel/TSDFVoxelGrid.cpp, line 128 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYr6KzP48pDvtvmX_ep:-MYr6KzP48pDvtvmX_eq:br52qru) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/geometry/kernel/TSDFVoxelGrid.cpp#L128)):*
> ```cpp
>                    float depth_min,
>                    float depth_max) {
>     static const core::Device host("CPU:0");
> ```

This seems to be used in quite a few places. Guess we can make a static member `core::Device::host`, this is similar to how we set up the `core::Dtype::xxx`. I'll do it in a separate PR.
___
*[cpp/open3d/t/pipelines/voxelhashing/Frame.h, line 61 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYr801F2zaXEYL0qPaV:-MYr801F2zaXEYL0qPaW:b-dn4x3o) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/pipelines/voxelhashing/Frame.h#L61)):*
> ```objc
> 
>     void SetData(const std::string& name, const core::Tensor& data) {
>         if (data_.count(name) != 0) {
> ```

this can potentially be done by
`data_[name] = data`;
___
*[cpp/open3d/t/pipelines/voxelhashing/Model.h, line 51 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYr8KGr0rNafL7dq72L:-MYr8KGr0rNafL7dq72M:b9aa99d) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/pipelines/voxelhashing/Model.h#L51)):*
> ```objc
>                                                          core::Dtype::Float64,
>                                                          core::Device("CPU:0")),
>           const core::Device& device = core::Device("CUDA:0"));
> ```

do we set CUDA:0 as the default on purpose?
___
*[cpp/open3d/t/pipelines/voxelhashing/Option.h, line 41 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYrEJDO-sNCOedJHBe_:-MYrEJDP8BhHxLo5zcsm:b-tal4yo) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/pipelines/voxelhashing/Option.h#L41)):*
> ```objc
> namespace voxelhashing {
> 
> class Option {
> ```

Shall we use `struct` instead?
___
*[cpp/tests/t/geometry/TSDFVoxelGrid.cpp, line 73 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYrFNF48nl9WdpLU0-A:-MYrFNF48nl9WdpLU0-B:b-hkv8gm) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/tests/t/geometry/TSDFVoxelGrid.cpp#L73)):*
> ```cpp
>         auto focal_length = intrinsic.GetFocalLength();
>         auto principal_point = intrinsic.GetPrincipalPoint();
>         core::Tensor intrinsic_t = core::Tensor(
> ```

we can do:
```cpp
 core::Tensor intrinsic_t = core::Tensor::Init<double>(
    {{a, b, c},
     {d, e, f},
     {g, h, i}}
);
```
___
*[cpp/tests/t/geometry/TSDFVoxelGrid.cpp, line 145 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYrFfam9lLUq0lRvCjv:-MYrFfam9lLUq0lRvCjw:b-csg7r3) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/tests/t/geometry/TSDFVoxelGrid.cpp#L145)):*
> ```cpp
>         auto focal_length = intrinsic.GetFocalLength();
>         auto principal_point = intrinsic.GetPrincipalPoint();
>         core::Tensor intrinsic_t = core::Tensor(
> ```

same, we can use `Tensor::Init<double>()`
___
*[examples/cpp/TIntegrateRGBD.cpp, line 98 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYrFoRj-nn0Tf-YDPwr:-MYrFoRj-nn0Tf-YDPws:bik4akr) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/examples/cpp/TIntegrateRGBD.cpp#L98)):*
> ```cpp
>     auto focal_length = intrinsic.GetFocalLength();
>     auto principal_point = intrinsic.GetPrincipalPoint();
>     Tensor intrinsic_t = Tensor(
> ```

`Tensor::Init<double>`
___
*[examples/cpp/VoxelHashing.cpp, line 121 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYrFr4pC2Q0HYfagVUM:-MYrFr4pC2Q0HYfagVUN:bik4akr) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/examples/cpp/VoxelHashing.cpp#L121)):*
> ```cpp
>     auto principal_point = intrinsic.GetPrincipalPoint();
>     Tensor intrinsic_t = Tensor(
>             std::vector<double>({focal_length.first, 0, principal_point.first,
> ```

`Tensor::Init<double>`

**Review by reyanshsolis — CHANGES_REQUESTED** [review]
> Reviewed 19 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3314)* status: all files reviewed, 13 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[cpp/open3d/t/geometry/TSDFVoxelGrid.cpp, line 135 at r1](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYhmfqJB7ObTZaJHVtp:-MYhmfqJB7ObTZaJHVtq:b-c1cljm) ([raw file](https://github.com/intel-isl/open3d/blob/b90ddd0ca138bd390c0b000a799bc221623fea1f/cpp/open3d/t/geometry/TSDFVoxelGrid.cpp#L135)):*
> ```cpp
>     // estimate surfaces.
>     // TODO(wei): merge CreateFromDepth and Touch in one kernel.
>     utility::Timer timer;
> ```

May we remove timers, its header file, and LogInfo from this file and the rest of this PR?

**Review by reyanshsolis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3314)* status: all files reviewed, 14 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[cpp/open3d/t/geometry/kernel/TSDFVoxelGridImpl.h, line 486 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYv2xpMEdFyfM7muGjq:-MYv2xpMEdFyfM7muGjr:b-rqoxgt) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/geometry/kernel/TSDFVoxelGridImpl.h#L486)):*
> ```objc
> #endif
> 
>     utility::LogInfo("{} vertices extracted", total_count);
> ```

Can we use `LogDebug` instead of `LogInfo` inside the kernel?
___
*[cpp/open3d/t/geometry/kernel/TSDFVoxelGridImpl.h, line 1125 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYv07u-7VDfcbRgp4Io:-MYv07u-7VDfcbRgp4Ip:btl9589) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/geometry/kernel/TSDFVoxelGridImpl.h#L1125)):*
> ```objc
> #pragma omp critical
>                 {
>                     range_ptr[0] = min(z_min, range_ptr[0]);
> ```

In the future, we may define `atomicMinf` and `atomicMaxf` for CUDA as well, if we don't have that now.

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3314)* status: all files reviewed, 14 unresolved discussions (waiting on @reyanshsolis, @ssheorey, and @yxlao)

___
*[cpp/open3d/t/geometry/TSDFVoxelGrid.h, line 90 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYqkJDQ2xpbOBtKgVr4:-MZ9PYbf2YZI2rSQiJzw:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/geometry/TSDFVoxelGrid.h#L90)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

I would recommend starting from `0`, and use `<<`, similar to:

https://github.com/intel-isl/Open3D/blob/3ea00489d13ac7ef826d09e320972d4649782013/cpp/open3d/visualization/gui/Events.h#L35-L42


</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TSDFVoxelGrid.cpp, line 135 at r1](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYhmfqJB7ObTZaJHVtp:-MZ9Q2oiCbsyZCxtelNY:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/b90ddd0ca138bd390c0b000a799bc221623fea1f/cpp/open3d/t/geometry/TSDFVoxelGrid.cpp#L135)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

May we remove timers, its header file, and LogInfo from this file and the rest of this PR? 
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Utility.h, line 36 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYqvnIgD2ymFoaTKo2f:-MZ9Q7k-15LtF15a3kn1:b-cd4j23) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/geometry/Utility.h#L36)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

could we change it to lower case `t`?
</blockquote></details>

Not really, as T is generally reserved for 4x4 matrices.
In the future I plan to wrap it up with a Transformation class.
___
*[cpp/open3d/t/geometry/Utility.h, line 45 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYqvaE_8P7-AkOkwoqp:-MZ9QRj80no7DK6VUett:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/geometry/Utility.h#L45)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`T.GetDataPtr<double>()` works for both const and non-const
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/kernel/GeometryIndexer.h, line 64 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYqxJ3m8SbeJKj9MjG7:-MZ9R4Kj3BfjeikAgxED:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/geometry/kernel/GeometryIndexer.h#L64)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

same, `GetDataPtr<T>()`
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/kernel/TSDFVoxelGrid.cpp, line 128 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYr6KzP48pDvtvmX_ep:-MZ9RJMGBRMBn9JLCiVj:b8kq0cc) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/geometry/kernel/TSDFVoxelGrid.cpp#L128)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

This seems to be used in quite a few places. Guess we can make a static member `core::Device::host`, this is similar to how we set up the `core::Dtype::xxx`. I'll do it in a separate PR.
</blockquote></details>

Let's do it in another PR
___
*[cpp/open3d/t/geometry/kernel/TSDFVoxelGridImpl.h, line 486 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYv2xpMEdFyfM7muGjq:-MZ9RQB08m6xdzo-MUWO:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/geometry/kernel/TSDFVoxelGridImpl.h#L486)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Can we use `LogDebug` instead of `LogInfo` inside the kernel?
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/kernel/TSDFVoxelGridImpl.h, line 1125 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYv07u-7VDfcbRgp4Io:-MZ9Rl1D5E6aCDYIVT41:bqfxx92) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/geometry/kernel/TSDFVoxelGridImpl.h#L1125)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

In the future, we may define `atomicMinf` and `atomicMaxf` for CUDA as well, if we don't have that now. 
</blockquote></details>

TODO in the future.
___
*[cpp/open3d/t/pipelines/voxelhashing/Frame.h, line 61 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYr801F2zaXEYL0qPaV:-MZ9RzEg--H9a1D2Avji:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/pipelines/voxelhashing/Frame.h#L61)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

this can potentially be done by
`data_[name] = data`;
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/voxelhashing/Model.h, line 51 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYr8KGr0rNafL7dq72L:-MZ9S-OV-ajOXzkYO0MW:begf3i) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/pipelines/voxelhashing/Model.h#L51)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

do we set CUDA:0 as the default on purpose?
</blockquote></details>

Yes, voxel hashing's speed is generally only acceptable on CUDA
___
*[cpp/open3d/t/pipelines/voxelhashing/Option.h, line 41 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYrEJDO-sNCOedJHBe_:-MZ9S9OC0oIM9zElauW1:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/open3d/t/pipelines/voxelhashing/Option.h#L41)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Shall we use `struct` instead?
</blockquote></details>

Done.
___
*[cpp/tests/t/geometry/TSDFVoxelGrid.cpp, line 73 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYrFNF48nl9WdpLU0-A:-MZ9V5kl0o_LHjyReZfw:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/tests/t/geometry/TSDFVoxelGrid.cpp#L73)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we can do:
```cpp
 core::Tensor intrinsic_t = core::Tensor::Init<double>(
    {{a, b, c},
     {d, e, f},
     {g, h, i}}
);
```
</blockquote></details>

Done.
___
*[cpp/tests/t/geometry/TSDFVoxelGrid.cpp, line 145 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYrFfam9lLUq0lRvCjv:-MZ9V5y94IVHfnMfIYN-:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/cpp/tests/t/geometry/TSDFVoxelGrid.cpp#L145)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

same, we can use `Tensor::Init<double>()`
</blockquote></details>

Done.
___
*[examples/cpp/TIntegrateRGBD.cpp, line 98 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYrFoRj-nn0Tf-YDPwr:-MZ9VXF-0LcDXVJ1ccXR:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/examples/cpp/TIntegrateRGBD.cpp#L98)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`Tensor::Init<double>`
</blockquote></details>

Done.
___
*[examples/cpp/VoxelHashing.cpp, line 121 at r2](https://reviewable.io/reviews/intel-isl/open3d/3314#-MYrFr4pC2Q0HYfagVUM:-MZ9VXmd9Pqjuf1671Iz:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/dfd7152abe1d1f91f30216632aaf30d06a0e4f74/examples/cpp/VoxelHashing.cpp#L121)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`Tensor::Init<double>`
</blockquote></details>

Done.

**Review by reyanshsolis — APPROVED** [review]
> Reviewed 4 of 37 files at r1, 5 of 11 files at r2, 33 of 33 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3314)* status: all files reviewed, 14 unresolved discussions (waiting on @reyanshsolis, @ssheorey, and @yxlao)

**Pull request merged**
