### PR TITLE
Faiss Build Test

### PR DESCRIPTION
**Pull request by junha-l**
This PR is a minimal update to test Faiss build integration.

Done
- Fetch recent commit of Faiss.
- Patch Faiss CMake scripts to allow selection of BLAS libraries
- Minimal code to check integration is successful 

TODO
- [x] Resolve link error with MKL
- [x] Resolve OpenMP error on MacOS

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2382)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2382)* status: 0 of 13 files reviewed, 1 unresolved discussion

___
*[3rdparty/find_dependencies.cmake, line 1023 at r1](https://reviewable.io/reviews/intel-isl/open3d/2382#-MIK336w6m9JwfRlghNq:-MIK336x9NhuFPm-Y_Nm:b-5izpuz) ([raw file](https://github.com/intel-isl/open3d/blob/9ab28dcafdf761fd50d52aaee17901c1e112d93c/3rdparty/find_dependencies.cmake#L1023)):*
> ```CMake
>     )
>     add_dependencies(3rdparty_faiss ext_faiss)
>     target_link_libraries(3rdparty_faiss INTERFACE ${BLAS_LIBRARIES})
> ```

@yxlao I tried to link MKL by replacing this code to 
```
target_link_libraries(3rdparty_faiss INTERFACE 3rdparty_mkl)
```
but it fails to link some functions. 

Apparently, it fails to link some LAPACK functions (e.g. sgeqrf_, )

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by yxlao** [comment]
That depends on whether Faiss can works properly with MKL. We need to make sure that Faiss works properly with MKL. I would suggest creating a fork of Faiss (without Open3D) and make try to make it work with MKL, and without OpenBLAS and LAPACK installed in the system.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by junha-l** [comment]
@yxlao 
The mkl issue is resolved, but there is a build error about the OpenMP on OSX.
Do you have any idea about this problem?

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by junha-l** [comment]
Hi @yxlao 

I have some questions about the usage of OpenMP in Open3D

0. It seems that we need libomp binary to compile OpenMP related codes with clang. 
Is that true?

1. Open3D does not ship with libomp binary in pip & conda package on MacOS. 
So the users who use Open3D on MacOS machines can not enjoy the parallelization with OpenMP?
What if a user who uses MacOS machine and he/she installs libomp binary by themselves? 
Is the OpenMP parallelization just enabled?

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by yxlao** [comment]
> It seems that we need libomp binary to compile & execute OpenMP related codes with clang.
Is that true?

If you're referring to macOS libraries, yes. 

> Open3D does not ship with libomp binary in pip & conda package on MacOS.
So the users who use Open3D on MacOS machines can not enjoy the parallelization with OpenMP?

Right. This is true for macOS.

> What if a user who uses MacOS machine and he/she installs libomp binary by themselves?
Is the OpenMP parallelization just enabled?

Currently, even if the user installs libomp by themselves, the pre-compiled Open3D python packages still do not OpenMP on macOS. To use openmp in macOS, one must compile Open3D from source and possibly CMake changes are required.

**Comment by junha-l** [comment]
@yxlao 
I found that there are the same errors with Ubuntu GPU CI on my local ubuntu machine 

```
'thrust::system::system_error'
  what():  CUDA free failed: cudaErrorIllegalAddress: an illegal memory access was encountered
```
error occurs on 
```test_non_zero``` and ```test_boolean_advanced_indexing``` tests in test_core.py script

**Comment by junha-l** [comment]
@yxlao
I found that there are the same errors with Ubuntu GPU CI on my local ubuntu machine

```
thrust::system::system_error'
  what():  CUDA free failed: cudaErrorIllegalAddress: an illegal memory access was encountered
```

errors occur on
```test_non_zero``` and ```test_boolean_advanced_indexing``` tests in test_core.py script


Only python tests get failed. CPP unit tests have no problem.

I didn't change anything from the original build pipeline except the scope of the BLAS, MKL targets (private -> public) so I don't know why these tests get failed.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by junha-l** [comment]
It turns out that the errors on Ubuntu GPU CI come from the incorrect CMake option passes to the faiss. 
Specifically, we need to pass ```-DCUDAToolkit_ROOT``` and ```-DCMAKE_CUDA_FLAGS```.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by junha-l** [comment]
@yxlao 
After I insert a line ```pip install cmake==3.18.2 -U``` right after the virtualenv activation, I got this error

```
2020-10-14T06:00:40.5031830Z qemu: uncaught target signal 11 (Segmentation fault) - core dumped
2020-10-14T06:00:40.9349151Z ##[error]The process '/home/runner/work/_actions/uraimo/run-on-arch-action/v2.0.2/src/run-on-arch.sh' failed with exit code 245
```

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by junha-l** [comment]
> @yxlao
> After I insert a line `pip install cmake==3.18.2 -U` right after the virtualenv activation, I got this error
> 
> ```
> 2020-10-14T06:00:40.5031830Z qemu: uncaught target signal 11 (Segmentation fault) - core dumped
> 2020-10-14T06:00:40.9349151Z ##[error]The process '/home/runner/work/_actions/uraimo/run-on-arch-action/v2.0.2/src/run-on-arch.sh' failed with exit code 245
> ```

I couldn't resolve the above error with pip installed cmake
So I tried to compile cmake from source.
It seems to work, but it takes huge amout of time.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by junha-l** [comment]
@yxlao 
I figured out the solution for the compiler error in OpenBLAS / arm64 CI and tested it in my local docker environment.

But it fails on the CI because of the timeout. It takes too much time to compile cmake from source.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6247791&bid=20347075)

**Comment by yxlao** [comment]
We'll need to use private targets, otherwise, the static 3rd-party library will be installed in the Open3D install directory even when we are building shared library `libOpen3D.so`, which is inconsistent with our python wheel release workflow (where it requires a single libopen3d shared library).

image

I am working on a potential fix for this.

**Review by yxlao — APPROVED** [review]

**Pull request merged**
