### PR TITLE
New ClearGeometries for Visualizer

### PR DESCRIPTION
**Pull request by sammo2828**
I find myself using `remove_geometry` and `add_geometry` all the time, needing to keep track of everything I've previously added. As a convenience, `clear_geometries` will remove all currently added geometries.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1338)

### CODE REVIEW

**Comment by sammo2828** [comment]
Done, except this:

> Add a period . at the end of this sentence.

There are no periods . at the end of other comment titles, e.g.

https://github.com/intel-isl/Open3D/blob/c503881e6bf48a504eff3b8eb03fdf78ef37425a/src/Open3D/Visualization/Visualizer/Visualizer.h#L125-L130

Trying to keep things consistent.

**Comment by sammo2828** [comment]
Nice. I'll add the period.

**Comment by sammo2828** [comment]
Looks like it's been merged. Thanks.

**Comment by yxlao** [comment]
It's not merged yet. I just merged `master` into this branch to fix a conflict. After CI passes, we'll merge this to `master`.

**Pull request merged**
