### PR TITLE
rpc visualization interface

### PR DESCRIPTION
**Pull request by benjaminum**
This PR adds functionality for sending data to an external visualizer app. It includes
- C++ and python functions for sending data
- base class for receiving data
- unit tests

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2090)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  8
         

Clones added
============
- cpp/tests/utility/RemoteFunctions.cpp  5
- cpp/open3d/utility/RemoteFunctions.cpp  2
- cpp/open3d/utility/ReceiverBase.h  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  8
         

Clones added
============
- cpp/open3d/utility/RemoteFunctions.cpp  2
- cpp/open3d/utility/ReceiverBase.h  5
- cpp/tests/utility/RemoteFunctions.cpp  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  8
         

Clones added
============
- cpp/tests/utility/RemoteFunctions.cpp  5
- cpp/open3d/utility/ReceiverBase.h  5
- cpp/open3d/utility/RemoteFunctions.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  8
         

Clones added
============
- cpp/open3d/utility/ReceiverBase.h  5
- cpp/open3d/utility/RemoteFunctions.cpp  2
- cpp/tests/utility/RemoteFunctions.cpp  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  8
         

Clones added
============
- cpp/open3d/utility/RemoteFunctions.cpp  2
- cpp/tests/utility/RemoteFunctions.cpp  5
- cpp/open3d/utility/ReceiverBase.h  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  8
         

Clones added
============
- cpp/open3d/utility/RemoteFunctions.cpp  2
- cpp/tests/utility/RemoteFunctions.cpp  5
- cpp/open3d/utility/ReceiverBase.h  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  8
         

Clones added
============
- cpp/tests/utility/RemoteFunctions.cpp  5
- cpp/open3d/utility/RemoteFunctions.cpp  2
- cpp/open3d/utility/ReceiverBase.h  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  8
         

Clones added
============
- cpp/tests/utility/RemoteFunctions.cpp  5
- cpp/open3d/utility/RemoteFunctions.cpp  2
- cpp/open3d/utility/ReceiverBase.h  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  8
         

Clones added
============
- cpp/open3d/utility/ReceiverBase.h  5
- cpp/open3d/utility/RemoteFunctions.cpp  2
- cpp/tests/utility/RemoteFunctions.cpp  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  8
         

Clones added
============
- cpp/tests/utility/RemoteFunctions.cpp  5
- cpp/open3d/utility/RemoteFunctions.cpp  2
- cpp/open3d/utility/ReceiverBase.h  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  8
         

Clones added
============
- cpp/open3d/utility/ReceiverBase.h  5
- cpp/open3d/utility/RemoteFunctions.cpp  2
- cpp/tests/utility/RemoteFunctions.cpp  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  10
- python/test/test_remote_functions.py  6
         

Clones added
============
- cpp/tests/utility/RemoteFunctions.cpp  6
- cpp/pybind/utility/receiver.cpp  1
- cpp/open3d/utility/RemoteFunctions.cpp  21
- cpp/open3d/utility/RemoteFunctions.h  3
- cpp/open3d/utility/ReceiverBase.h  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  10
- python/test/test_remote_functions.py  6
         

Clones added
============
- cpp/open3d/utility/ReceiverBase.h  5
- cpp/open3d/utility/RemoteFunctions.h  3
- cpp/pybind/utility/receiver.cpp  1
- cpp/open3d/utility/RemoteFunctions.cpp  21
- cpp/tests/utility/RemoteFunctions.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  10
- python/test/test_remote_functions.py  6
         

Clones added
============
- cpp/pybind/utility/receiver.cpp  1
- cpp/open3d/utility/RemoteFunctions.cpp  21
- cpp/tests/utility/RemoteFunctions.cpp  6
- cpp/open3d/utility/RemoteFunctions.h  3
- cpp/open3d/utility/ReceiverBase.h  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 10
- Added 11
           

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  10
- python/test/test_remote_functions.py  6
         

Clones added
============
- cpp/open3d/utility/RemoteFunctions.cpp  21
- cpp/open3d/utility/ReceiverBase.h  5
- cpp/pybind/utility/receiver.cpp  1
- cpp/open3d/utility/RemoteFunctions.h  3
- cpp/tests/utility/RemoteFunctions.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_remote_functions.py  6
- python/open3d/visualization/_external_visualizer.py  10
         

Clones added
============
- cpp/tests/utility/RemoteFunctions.cpp  6
- cpp/open3d/utility/ReceiverBase.h  5
- cpp/open3d/utility/RemoteFunctions.h  3
- cpp/pybind/utility/receiver.cpp  1
- cpp/open3d/utility/RemoteFunctions.cpp  21
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_remote_functions.py  6
- python/open3d/visualization/_external_visualizer.py  10
         

Clones added
============
- cpp/open3d/utility/ReceiverBase.h  5
- cpp/open3d/utility/RemoteFunctions.cpp  21
- cpp/open3d/utility/RemoteFunctions.h  3
- cpp/tests/utility/RemoteFunctions.cpp  6
- cpp/pybind/utility/receiver.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  10
- python/test/test_remote_functions.py  6
         

Clones added
============
- cpp/pybind/utility/receiver.cpp  1
- cpp/tests/utility/RemoteFunctions.cpp  6
- cpp/open3d/utility/ReceiverBase.h  5
- cpp/open3d/utility/RemoteFunctions.h  3
- cpp/open3d/utility/RemoteFunctions.cpp  21
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  9
- python/test/test_remote_functions.py  6
         

Clones added
============
- cpp/open3d/utility/RemoteFunctions.cpp  21
- cpp/tests/utility/RemoteFunctions.cpp  5
- cpp/open3d/utility/ReceiverBase.h  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_remote_functions.py  6
- python/open3d/visualization/_external_visualizer.py  9
         

Clones added
============
- cpp/open3d/utility/RemoteFunctions.cpp  21
- cpp/tests/utility/RemoteFunctions.cpp  5
- cpp/open3d/utility/ReceiverBase.h  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  9
- python/test/test_remote_functions.py  6
         

Clones added
============
- cpp/open3d/utility/ReceiverBase.h  5
- cpp/tests/utility/RemoteFunctions.cpp  5
- cpp/open3d/utility/RemoteFunctions.cpp  21
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_remote_functions.py  6
- python/open3d/visualization/_external_visualizer.py  9
         

Clones added
============
- cpp/tests/utility/RemoteFunctions.cpp  5
- cpp/open3d/utility/RemoteFunctions.cpp  21
- cpp/open3d/utility/ReceiverBase.h  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_remote_functions.py  6
- python/open3d/visualization/_external_visualizer.py  9
         

Clones added
============
- cpp/open3d/utility/ReceiverBase.h  5
- cpp/tests/utility/RemoteFunctions.cpp  5
- cpp/open3d/utility/RemoteFunctions.cpp  21
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_remote_functions.py  6
- python/open3d/visualization/_external_visualizer.py  9
         

Clones added
============
- cpp/open3d/utility/RemoteFunctions.cpp  21
- cpp/open3d/utility/ReceiverBase.h  5
- cpp/tests/utility/RemoteFunctions.cpp  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  9
- python/test/test_remote_functions.py  6
         

Clones added
============
- cpp/tests/io/rpc/RemoteFunctions.cpp  5
- cpp/open3d/io/rpc/ReceiverBase.h  5
- cpp/open3d/io/rpc/RemoteFunctions.cpp  21
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_remote_functions.py  6
- python/open3d/visualization/_external_visualizer.py  9
         

Clones added
============
- cpp/tests/io/rpc/RemoteFunctions.cpp  5
- cpp/open3d/io/rpc/ReceiverBase.h  5
- cpp/open3d/io/rpc/RemoteFunctions.cpp  21
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/test/test_remote_functions.py  6
- python/open3d/visualization/_external_visualizer.py  9
         

Clones added
============
- cpp/open3d/io/rpc/BufferConnection.cpp  1
- cpp/open3d/io/rpc/RemoteFunctions.cpp  21
- cpp/open3d/io/rpc/DummyReceiver.cpp  1
- cpp/open3d/io/rpc/ReceiverBase.cpp  5
- cpp/tests/io/rpc/RemoteFunctions.cpp  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  9
- python/test/test_remote_functions.py  6
         

Clones added
============
- cpp/open3d/io/rpc/RemoteFunctions.cpp  21
- cpp/open3d/io/rpc/ReceiverBase.cpp  5
- cpp/tests/io/rpc/RemoteFunctions.cpp  5
- cpp/open3d/io/rpc/DummyReceiver.cpp  1
- cpp/open3d/io/rpc/BufferConnection.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_remote_functions.py  6
- python/open3d/visualization/_external_visualizer.py  9
         

Clones added
============
- cpp/tests/io/rpc/RemoteFunctions.cpp  5
- cpp/open3d/io/rpc/RemoteFunctions.cpp  21
- cpp/open3d/io/rpc/BufferConnection.cpp  1
- cpp/open3d/io/rpc/ReceiverBase.cpp  5
- cpp/open3d/io/rpc/DummyReceiver.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  9
- python/test/test_remote_functions.py  6
         

Clones added
============
- cpp/open3d/io/rpc/DummyReceiver.cpp  1
- cpp/open3d/io/rpc/BufferConnection.cpp  1
- cpp/tests/io/rpc/RemoteFunctions.cpp  5
- cpp/open3d/io/rpc/RemoteFunctions.cpp  21
- cpp/open3d/io/rpc/ReceiverBase.cpp  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_remote_functions.py  6
- python/open3d/visualization/_external_visualizer.py  9
         

Clones added
============
- cpp/open3d/io/rpc/DummyReceiver.cpp  1
- cpp/tests/io/rpc/RemoteFunctions.cpp  5
- cpp/open3d/io/rpc/RemoteFunctions.cpp  21
- cpp/open3d/io/rpc/ReceiverBase.cpp  5
- cpp/open3d/io/rpc/BufferConnection.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Comment by yxlao** [comment]
@benjaminum also merge master, since the code formatter has been updated

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/visualization/_external_visualizer.py  9
- python/test/test_remote_functions.py  6
         

Clones added
============
- cpp/open3d/io/rpc/RemoteFunctions.cpp  21
- cpp/tests/io/rpc/RemoteFunctions.cpp  5
- cpp/open3d/io/rpc/BufferConnection.cpp  1
- cpp/open3d/io/rpc/ReceiverBase.cpp  5
- cpp/open3d/io/rpc/DummyReceiver.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5881999&bid=19251993)

**Pull request merged**
