### PR TITLE
Add shader and material build functions

### PR DESCRIPTION
**Pull request by stotko**
Shader encoding and material compilation are both build steps that follow similar rules as CMake's native C++/CUDA/etc. language compilation model. Move the build generation code into dedicated functions and make it more robust.

#### Shader (similar to static library concept)
- Split old encoder executable into encoder (compiler) and linker executables which are both much simpler
- Add file existence check at CMake configuration time (implicitly when computing absolute paths)
- Make generated header smaller (and more readable) due to above separation with a reduction from ~780 to ~500 lines
- Move `source_group` into existing macro
- Add better compile/link message and use `VERBATIM` to make build commands robust across platforms

#### Material (similar to object library concept)
- Add file existence check at CMake configuration time (implicitly when computing absolute paths)
- Hide internal platform-specific flag generation
- Add `source_group` for materials
- Add better compile message and use `VERBATIM` to make build commands robust across platforms

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3547)

### CODE REVIEW

**Review by errissa — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3547)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @ssheorey, @stotko, and @yxlao)

___
*[cmake/add_compiled_materials.cmake, line 37 at r1](https://reviewable.io/reviews/intel-isl/open3d/3547#-MbdWWU2CFmlrbVT6gF4:-MbdWWU3B5yMTQvzsJED:be47sxh) ([raw file](https://github.com/intel-isl/open3d/blob/4f76de7d52a9fcc763d685d7d3c6ada9894c056a/cmake/add_compiled_materials.cmake#L37)):*
> ```CMake
>     if (IOS OR ANDROID)
>         set(FILAMENT_MATC_ARGS "--platform=mobile")
>     elseif (NOT WIN32)
> ```

why not WIN32? WIN32 is a desktop platform
___
*[cmake/add_encoded_shader.cmake, line 1 at r1](https://reviewable.io/reviews/intel-isl/open3d/3547#-MbdWozRCmewID-FLlON:-MbdWozRCmewID-FLlOO:b-s7281z) ([raw file](https://github.com/intel-isl/open3d/blob/4f76de7d52a9fcc763d685d7d3c6ada9894c056a/cmake/add_encoded_shader.cmake#L1)):*
> ```CMake
> # open3d_add_encoded_shader(<target>
> ```

Since we are planning to eliminate the old visualizer (and therefore the GLSL shaders) I don't think it's worth having a new executable program plus new cmake for the old GLSL files.

**Review by yxlao — APPROVED** [review]
> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3547)* status: all files reviewed, 3 unresolved discussions (waiting on @ssheorey and @stotko)

___
*[cmake/add_encoded_shader.cmake, line 56 at r1](https://reviewable.io/reviews/intel-isl/open3d/3547#-Mbd_IYa-Gj8AJ0FUmTt:-Mbd_IYa-Gj8AJ0FUmTu:bt9azs9) ([raw file](https://github.com/intel-isl/open3d/blob/4f76de7d52a9fcc763d685d7d3c6ada9894c056a/cmake/add_encoded_shader.cmake#L56)):*
> ```CMake
> 
>     add_custom_command(
>             OUTPUT ${OUTPUT_FULL_PATH}
> ```

nit: reduce indentation

**Review by stotko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3547)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @errissa, @ssheorey, and @yxlao)

___
*[cmake/add_compiled_materials.cmake, line 37 at r1](https://reviewable.io/reviews/intel-isl/open3d/3547#-MbdWWU2CFmlrbVT6gF4:-MbeOM234ZxJiP1ArE4a:b-u1jpy7) ([raw file](https://github.com/intel-isl/open3d/blob/4f76de7d52a9fcc763d685d7d3c6ada9894c056a/cmake/add_compiled_materials.cmake#L37)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

why not WIN32? WIN32 is a desktop platform
</blockquote></details>

I just moved that code and have not done any changes to it. But yes, it looks a bit strange. Fixed.
___
*[cmake/add_encoded_shader.cmake, line 1 at r1](https://reviewable.io/reviews/intel-isl/open3d/3547#-MbdWozRCmewID-FLlON:-MbeOnN35xL35Xfe0qYa:bgspo01) ([raw file](https://github.com/intel-isl/open3d/blob/4f76de7d52a9fcc763d685d7d3c6ada9894c056a/cmake/add_encoded_shader.cmake#L1)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

Since we are planning to eliminate the old visualizer (and therefore the GLSL shaders) I don't think it's worth having a new executable program plus new cmake for the old GLSL files. 
</blockquote></details>

I was not aware that the GLSL shaders will also be removed. I would argue merging these changes now still provides a benefit until the old visualizer really gets removed. As far as I understand it now, we are deprecating it first, so it will be still around in the near future?! (please correct me if I am wrong)
___
*[cmake/add_encoded_shader.cmake, line 56 at r1](https://reviewable.io/reviews/intel-isl/open3d/3547#-Mbd_IYa-Gj8AJ0FUmTt:-MbeOmZ_8du7aWXLRctG:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/4f76de7d52a9fcc763d685d7d3c6ada9894c056a/cmake/add_encoded_shader.cmake#L56)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: reduce indentation
</blockquote></details>

Done.

**Review by errissa — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3547)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ssheorey)

**Pull request merged**
