### PR TITLE
tensor transform pointcloud

### PR DESCRIPTION
**Pull request by reyanshsolis**
* [Added] t::geometry::PointCloud Transform, Translate and Rotate functions, with UnitTests.

Files Modified:
* cpp/open3d/t/geometry/PointCloud.cpp
* cpp/tests/t/geometry/PointCloud.cpp
* python/tests/t/geometry/test_pointcloud.py

This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2704)

### CODE REVIEW

**Review by yxlao — APPROVED** [review]
LGTM after some cosmetic changes.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2704#-:-MO0hNsSCA3pUUO3eFGV:byihfa3)* status: all files reviewed, 12 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 76 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0ZMaC06hlg5tEVd85:-MO0ZMaC06hlg5tEVd86:b2gfhc0) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L76)):*
> ```cpp
> PointCloud &PointCloud::Transform(const core::Tensor &transformation) {
>     transformation.AssertShape({4, 4});
>     // Use reserve() keyword.
> ```

remove this line?
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 77 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0ZSRF0KFQfpuN7F8w:-MO0ZSRF0KFQfpuN7F8x:b-bwiyju) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L77)):*
> ```cpp
>     transformation.AssertShape({4, 4});
>     // Use reserve() keyword.
>     core::Tensor transform;
> ```

I would just do `transformation.AssertDevice(device_);`, to be consistent with other pointcloud functions. E.g. `PointCloud::SetPoints()` does not accept a tensor from a different device.

Our current convention is to expose device transfers explicitly for the user (i.e. the user has to do it).
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 82 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0f4p49pH5CjL3gQ7E:-MO0f4p49pH5CjL3gQ7F:b-m2y6ai) ([raw file](https://github.com/intel-isl/open3d/blob/bb4873593fba135ff994606903b58afc3b3c7cee/cpp/open3d/t/geometry/PointCloud.cpp#L82)):*
> ```cpp
>                                   bool relative) {
>     translation.AssertShape({3});
>     core::Tensor transform = translation.Copy();
> ```

Same as above, let's assert the device directly.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 86 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0dk6HA4kmooAxgGbv:-MO0dk6HA4kmooAxgGbw:b-pdb0dl) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L86)):*
> ```cpp
>         transform = transformation;  // Use Shallow Copy, if on the same device.
> 
>     core::Tensor &points = GetPoints();
> ```

move this to right before where it is first used
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 88 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0aMwzE96WR9iLrS5r:-MO0aMx-7MuRhtx7g7dJ:b-jt3abf) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L88)):*
> ```cpp
>     core::Tensor &points = GetPoints();
> 
>     //  Extract s, R, t from Transformation
> ```

Put this in the `PointCloud::Transform` docstring in `PointCloud.h`. This information is useful for the user.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 95 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0b9Ye1Ls0eS70_yTH:-MO0b9Ye1Ls0eS70_yTI:bcmslfj) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L95)):*
> ```cpp
>     core::Tensor t = transform.Slice(0, 0, 3).Slice(1, 3, 4);
> 
>     // To be considered for future opitmisation:
> ```

Let's use `// TODO:` to get syntax highlighting for some editors. 

I like the first idea better than the second. The first idea seems to fit well with the BLAS [cblas_sgemm](https://developer.apple.com/documentation/accelerate/1513264-cblas_sgemm?language=objc) operation `AB + C` that we are using. We only use the `AB` part to implement `MatMul` but didn't use the `C`. 

Maybe we can summarize it as:
```
// TODO: consider adding a new op extending MatMul to support `AB + C` GEMM operation.
```
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 103 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0epG47UviKbEv226z:-MO0epG47UviKbEv227-:bs04hob) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L103)):*
> ```cpp
>     //   for sequencial and parallel calculation.
> 
>     //  points (3xN) = s.R(points) + t
> ```

let's remove this comment
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 107 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0euBA0613Nx4A8a7e:-MO0euBA0613Nx4A8a7f:bs04hob) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L107)):*
> ```cpp
> 
>     if (HasPointNormals()) {
>         // for normal: n.T() = R*n.T()
> ```

let's remove this comment
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 145 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0fI-O9K6QspfimwAD:-MO0fI-O9K6QspfimwAE:bhs5dpw) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L145)):*
> ```cpp
>     center.AssertShape({3});
>     core::Tensor Rot;
>     if (R.GetDevice() != device_) {
> ```

same as above, let's directly assert the device for both `R` and `center`
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 149 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0fGnA-vkH94U7ye56:-MO0fGnB7GSPhhX7g5aW:bujfly4) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L149)):*
> ```cpp
>                             R.GetDevice().ToString(), device_.ToString());
>         Rot = R.Copy(device_);  // Copy to 'this' device.
>     } else
> ```

use `{}`
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 154 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0fd-n9EYTc6TrQVcv:-MO0fd-n9EYTc6TrQVcw:b-89tevi) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L154)):*
> ```cpp
>     core::Tensor &points = GetPoints();
> 
>     // Create 'RotateAboutOrigin' function for Rotating about 0,0,0 to save
> ```

typically element-wise binary ops are pretty fast, `RotateAboutOrigin` may create extra burdens to the pointcloud API, I would remove this comment for now and revisit later when this becomes a bottleneck
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 159 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0fZ-dCqIks29ku0oL:-MO0fZ-dCqIks29ku0oM:bs04hob) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L159)):*
> ```cpp
> 
>     if (HasPointNormals()) {
>         // for normal: n.T() = R*n.T()
> ```

let's remove this comment

**Comment by reyanshsolis** [comment]
Changes Applied.
Additional Changes: Added Scale factor in Transform function.

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2704)* status: 2 of 4 files reviewed, 12 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 76 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0ZMaC06hlg5tEVd85:-MO11Pzx0zOIRXXUNVb7:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L76)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove this line?
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 77 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0ZSRF0KFQfpuN7F8w:-MO11R1z3xlnkbFZbGhL:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L77)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

I would just do `transformation.AssertDevice(device_);`, to be consistent with other pointcloud functions. E.g. `PointCloud::SetPoints()` does not accept a tensor from a different device.

Our current convention is to expose device transfers explicitly for the user (i.e. the user has to do it).
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 82 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0f4p49pH5CjL3gQ7E:-MO11dfo2nygAqyvdO2U:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/bb4873593fba135ff994606903b58afc3b3c7cee/cpp/open3d/t/geometry/PointCloud.cpp#L82)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Same as above, let's assert the device directly.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 86 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0dk6HA4kmooAxgGbv:-MO12kjR7BfnZwVUbEjt:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L86)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

move this to right before where it is first used
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 88 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0aMwzE96WR9iLrS5r:-MO12mAr05XXNHYOWy9I:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L88)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Put this in the `PointCloud::Transform` docstring in `PointCloud.h`. This information is useful for the user.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 95 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0b9Ye1Ls0eS70_yTH:-MO11lKG2N7qQGrr_Eiv:blnjysl) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L95)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Let's use `// TODO:` to get syntax highlighting for some editors. 

I like the first idea better than the second. The first idea seems to fit well with the BLAS [cblas_sgemm](https://developer.apple.com/documentation/accelerate/1513264-cblas_sgemm?language=objc) operation `AB + C` that we are using. We only use the `AB` part to implement `MatMul` but didn't use the `C`. 

Maybe we can summarize it as:
```
// TODO: consider adding a new op extending MatMul to support `AB + C` GEMM operation.
```
</blockquote></details>

I was also thinking of something optimized for operations where a common matrix is multiplied to two matrices.
In this case, the Rotation matrix is multiplied with Points and Normals. Should I remove this extra part of the comment for now?

Also, I have added the scale part. 
```cpp    
    core::Tensor s = transformation.Slice(0, 3, 4).Slice(1, 3, 4);
    R.Mul_(s);
```
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 103 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0epG47UviKbEv226z:-MO11bhA7J4yYDecPN2v:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L103)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

let's remove this comment
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 107 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0euBA0613Nx4A8a7e:-MO11byh7zq4oO0ypmHl:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L107)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

let's remove this comment
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 145 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0fI-O9K6QspfimwAD:-MO11filDq6nDSKHC8Gg:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L145)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

same as above, let's directly assert the device for both `R` and `center`
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 149 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0fGnA-vkH94U7ye56:-MO11fvc6wl8jzCudp5P:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L149)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

use `{}`
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 154 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0fd-n9EYTc6TrQVcv:-MO11gxpClxt5yufiXem:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L154)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

typically element-wise binary ops are pretty fast, `RotateAboutOrigin` may create extra burdens to the pointcloud API, I would remove this comment for now and revisit later when this becomes a bottleneck
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 159 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0fZ-dCqIks29ku0oL:-MO11hZNC_3hip7Vyu8E:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L159)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

let's remove this comment
</blockquote></details>

Done.

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2704)* status: 0 of 4 files reviewed, 12 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 95 at r2](https://reviewable.io/reviews/intel-isl/open3d/2704#-MO0b9Ye1Ls0eS70_yTH:-MO1t-CyB5XzQyz76f2v:brqv0xe) ([raw file](https://github.com/intel-isl/open3d/blob/7ea17f8bf8ad99035d11644fa341f12c85e9c919/cpp/open3d/t/geometry/PointCloud.cpp#L95)):*
> In this case, the Rotation matrix is multiplied with Points and Normals. Should I remove this extra part of the comment for now?

Okay, R.Mul_(s) is wrong, as it will affect normal.
So, now I have done:
```
core::Tensor Rn = R.Copy();
R.Mul_(s)
```
Test Case:
T : [[1, 1, 0, 1],
      [0, 1, 1, 1],
      [0, 1, 0, 1],
      [0, 0, 0, 2]];
P: [1, 1, 1] 
N: [1, 1, 1]

Transformed:
P: [5, 5, 3]
N: [2, 2, 1]

**Pull request merged**
