### PR TITLE
Remove attributes from pointcloud and trianglemesh

### PR DESCRIPTION
**Pull request by reyanshsolis**
Example use case:
- Normals computation might be required for an algorithm, but before passing to the visualizer, one might want to remove normals.
- Deleting some temp. attribute added for some function/algorithm. 
[Might also be useful when point cloud operator+= is created]

@yxlao not sure about the equivalent pybind, can you suggest something?

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3299)

### CODE REVIEW

**Review by ssheorey — COMMENTED** [review]
Looks good after we figure out the Python bindings.

**Comment by reyanshsolis** [comment]
The equivalent code in python can be just to `del pointcloud.point"attribute_key"']`. So, we might not need a pybind separately. It tried deleting an attribute using this, it works.

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3299)* status: all files reviewed, 3 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/t/geometry/PointCloud.h, line 206 at r2](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZH2xyn5B-sEeI2M8wF:-MZH2xyn5B-sEeI2M8wG:b-w66gch) ([raw file](https://github.com/intel-isl/open3d/blob/465d4b81fe6b2cea7859bb6069e2f2bbd22a1fa2/cpp/open3d/t/geometry/PointCloud.h#L206)):*
> ```objc
>     /// \param key Attribute name.
>     void DeletePointAttr(const std::string &key) {
>         if (HasPointAttr(key) && key != "points") {
> ```

```cpp
if (key == "points") {
    ...
} else if (HasPointAttr(key)) {
    ...
} else {
    ...
}
```
___
*[cpp/open3d/t/geometry/PointCloud.h, line 210 at r2](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZH37Vk41dpyEWmnsVF:-MZH37Vk41dpyEWmnsVG:b-9zwquy) ([raw file](https://github.com/intel-isl/open3d/blob/465d4b81fe6b2cea7859bb6069e2f2bbd22a1fa2/cpp/open3d/t/geometry/PointCloud.h#L210)):*
> ```objc
>         } else if (key == "points") {
>             utility::LogError(
>                     " DeletePointAttr: Not allowed to delete the attribute "
> ```

We don't need the `DeletePointAttr`, since `LogError` automatically comes with the function name. 
___
*[cpp/pybind/geometry/pointcloud.cpp, line 147 at r2](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZH3IBi4GtwaSVs258e:-MZH3IBi4GtwaSVs258f:b39j384) ([raw file](https://github.com/intel-isl/open3d/blob/12a50da047af5a6f87aabe2ce7edaa6d99240ac6/cpp/pybind/geometry/pointcloud.cpp#L147)):*
> ```cpp
>                  "For each point in the source point cloud, compute the "
>                  "distance to "
>                  "the target point cloud.",
> ```

restore the formating here?

**Comment by yxlao** [comment]
@reyanshsolis Yes, the `del` syntax would work as it is the default python syntax. But, we want to guard against people deleting the "points" attribute. 

I would recommend the following changes:

1. We shall do the implementation in `TensorMap::Erase()`. `TensorMap` inherits `std::unordered_map` and `TensorMap::Erase()` shall prevent user from deleting its `primary_key`. The `PointCloud::RemovePointAttr` will then call the `TensorMap::Erase()`.
2. For pybind, we first need to update `cpp/pybind/t/geometry/tensormap.cpp`. 
    - Notice that we use `py::bind_map<TensorMap>`, such that the python class will work similarly to a regular python dictionary. 
    - Now, check `py::bind_map` (https://github.com/pybind/pybind11/blob/54430436fee2afc4f8443691075a6208f9ea8eba/include/pybind11/stl_bind.h#L603). We need to figure out a way to replace `cl.def("__delitem__"`. For example, duplicate and create our own version of `bind_map` function, copy all the code and update the `__delitem__` to enforce the primary key constraints.
3. Lastly, add implementation for `TriangleMesh`. There, we have two maps and each has a primary key. This will validate that our approach in 1, 2 are transferable to other geometry classes.

**Comment by reyanshsolis** [comment]
> @reyanshsolis Yes, the `del` syntax would work as it is the default python syntax. But, we want to guard against people deleting the "points" attribute.
> 
> I would recommend the following changes:
> 
> 1. We shall do the implementation in `TensorMap::Erase()`. `TensorMap` inherits `std::unordered_map` and `TensorMap::Erase()` shall prevent user from deleting its `primary_key`. The `PointCloud::RemovePointAttr` will then call the `TensorMap::Erase()`.
> 2. For pybind, we first need to update `cpp/pybind/t/geometry/tensormap.cpp`.
>    
>    * Notice that we use `py::bind_map<TensorMap>`, such that the python class will work similarly to a regular python dictionary.
>    * Now, check `py::bind_map` (https://github.com/pybind/pybind11/blob/54430436fee2afc4f8443691075a6208f9ea8eba/include/pybind11/stl_bind.h#L603). We need to figure out a way to replace `cl.def("__delitem__"`. For example, duplicate and create our own version of `bind_map` function, copy all the code and update the `__delitem__` to enforce the primary key constraints.
> 3. Lastly, add implementation for `TriangleMesh`. There, we have two maps and each has a primary key. This will validate that our approach in 1, 2 are transferable to other geometry classes.

Done! It's working.
I will add the python unit tests soon.
image

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3299)* status: 1 of 9 files reviewed, 4 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/t/geometry/PointCloud.h, line 206 at r2](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZH2xyn5B-sEeI2M8wF:-MZJefSx0klyRn0y2r7T:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/4bdb8a6940619928a8b9e5c1325f2f24684f5de6/cpp/open3d/t/geometry/PointCloud.h#L206)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

```cpp
if (key == "points") {
    ...
} else if (HasPointAttr(key)) {
    ...
} else {
    ...
}
```
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.h, line 210 at r2](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZH37Vk41dpyEWmnsVF:-MZJegEsB1cWhVvG3_D7:bss4a2b) ([raw file](https://github.com/intel-isl/open3d/blob/4bdb8a6940619928a8b9e5c1325f2f24684f5de6/cpp/open3d/t/geometry/PointCloud.h#L210)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We don't need the `DeletePointAttr`, since `LogError` automatically comes with the function name. 
</blockquote></details>

Removed.
___
*[cpp/pybind/geometry/pointcloud.cpp, line 147 at r2](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZH3IBi4GtwaSVs258e:-MZJesnv73KkMQtrDpxE:b-ewyulo) ([raw file](https://github.com/intel-isl/open3d/blob/7eb73d3f57f7a3f8bc282d1ee416b63d0b4499a2/cpp/pybind/geometry/pointcloud.cpp#L147)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

restore the formating here?
</blockquote></details>

You might be referring to the prev. version. Formatting is improper in the current master, this PR fixes the same for this file.
___
*[cpp/pybind/t/geometry/tensormap.cpp, line 126 at r3](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZJfGKx8ClySHRTq7SE:-MZJfGKx8ClySHRTq7SF:b-hitumr) ([raw file](https://github.com/intel-isl/open3d/blob/ac61ccf13206a9b645bc4eb644b6720a44301395/cpp/pybind/t/geometry/tensormap.cpp#L126)):*
> ```cpp
>            [](TensorMap &m, const std::string &k) { return m.Erase(k); });
> 
>     tm.def("erase",
> ```

Do we need to have both `__delitem__` and `erase` to be consistent with C++ ?

**Review by yxlao — APPROVED** [review]
LGTM after minor changes

> Reviewed 8 of 8 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3299#-:-MZKVllv1I53e4xvyIl-:b-ose09f)* status: all files reviewed, 5 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/t/geometry/TensorMap.h, line 102 at r4](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZKUCWF9rtUXCEG8m8_:-MZKUCWF9rtUXCEG8m8a:bikc2gq) ([raw file](https://github.com/intel-isl/open3d/blob/ae9f646130d2e99ea59536d1a473bece130e0613/cpp/open3d/t/geometry/TensorMap.h#L102)):*
> ```objc
>     std::size_t Erase(const std::string key) {
>         if (key == primary_key_) {
>             utility::LogError(" Primary key: {} cannot be deleted.",
> ```

remove the space after `"`
___
*[cpp/open3d/t/geometry/TensorMap.h, line 106 at r4](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZKUKmPAmHyT3BrGEVE:-MZKUKmQ1heWwt6Ms-7q:be2nivz) ([raw file](https://github.com/intel-isl/open3d/blob/ae9f646130d2e99ea59536d1a473bece130e0613/cpp/open3d/t/geometry/TensorMap.h#L106)):*
> ```objc
>         } else if (!Contains(key)) {
>             utility::LogWarning(
>                     " [TensorMap::Erase Skipped] Key: {} is not present.", key);
> ```

remove the space after "
remove `  [TensorMap::Erase Skipped] `
___
*[cpp/open3d/t/geometry/TriangleMesh.h, line 206 at r4](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZKUYG-1AfAl9uHo-wh:-MZKUYG-1AfAl9uHo-wi:bro0enm) ([raw file](https://github.com/intel-isl/open3d/blob/ae9f646130d2e99ea59536d1a473bece130e0613/cpp/open3d/t/geometry/TriangleMesh.h#L206)):*
> ```objc
>     }
> 
>     /// Removes vertex attribute by key value. Primary attribute {vertices}
> ```

`primary attribute "vertices"` (use quotes, as it is a string)
___
*[cpp/open3d/t/geometry/TriangleMesh.h, line 238 at r4](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZKUgAu04lTSp_-XmNM:-MZKUgAu04lTSp_-XmNN:b-dt6dja) ([raw file](https://github.com/intel-isl/open3d/blob/ae9f646130d2e99ea59536d1a473bece130e0613/cpp/open3d/t/geometry/TriangleMesh.h#L238)):*
> ```objc
>     }
> 
>     /// Removes triangle attribute by key value. Primary attribute {triangles}
> ```

`primary attribute "triangles"` (use quotes, as it is a string)
___
*[cpp/pybind/t/geometry/tensormap.cpp, line 126 at r3](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZJfGKx8ClySHRTq7SE:-MZKVfdN-X5X8rY5W8P0:b-2bruc) ([raw file](https://github.com/intel-isl/open3d/blob/ac61ccf13206a9b645bc4eb644b6720a44301395/cpp/pybind/t/geometry/tensormap.cpp#L126)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Do we need to have both `__delitem__` and `erase` to be consistent with C++ ?
</blockquote></details>

yes, that looks good

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3299)* status: all files reviewed, 4 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/t/geometry/TensorMap.h, line 102 at r4](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZKUCWF9rtUXCEG8m8_:-MZMNLirCbeld-p2M4Lt:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/ae9f646130d2e99ea59536d1a473bece130e0613/cpp/open3d/t/geometry/TensorMap.h#L102)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove the space after `"`
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TensorMap.h, line 106 at r4](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZKUKmPAmHyT3BrGEVE:-MZMNMCyDjgchDc3ucqU:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/ae9f646130d2e99ea59536d1a473bece130e0613/cpp/open3d/t/geometry/TensorMap.h#L106)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove the space after "
remove `  [TensorMap::Erase Skipped] `
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TriangleMesh.h, line 206 at r4](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZKUYG-1AfAl9uHo-wh:-MZMNMnf1qXccAl3oTnV:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/ae9f646130d2e99ea59536d1a473bece130e0613/cpp/open3d/t/geometry/TriangleMesh.h#L206)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`primary attribute "vertices"` (use quotes, as it is a string)
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TriangleMesh.h, line 238 at r4](https://reviewable.io/reviews/intel-isl/open3d/3299#-MZKUgAu04lTSp_-XmNM:-MZMNNOI0B2JKHSjo79T:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/ae9f646130d2e99ea59536d1a473bece130e0613/cpp/open3d/t/geometry/TriangleMesh.h#L238)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`primary attribute "triangles"` (use quotes, as it is a string)
</blockquote></details>

Done.

**Review by yxlao — APPROVED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3299)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @reyanshsolis)

**Pull request merged**
