### PR TITLE
Poisson Disk Sampling of TriangleMesh

### PR DESCRIPTION
**Pull request by griegler**
Poisson Disk Sampling of TriangleMesh implementation. Points are sampled in such a way that the points uniformly cover the 3D surface.

Uniform Sampling
ScreenCapture_2019-05-09-15-26-53
ScreenCapture_2019-05-09-15-27-21
ScreenCapture_2019-05-09-15-27-40

Poisson Disk Sampling
ScreenCapture_2019-05-09-15-26-56
ScreenCapture_2019-05-09-15-27-26
ScreenCapture_2019-05-09-15-27-44

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/955)

### CODE REVIEW

**Comment by griegler** [comment]
CI failed, because it failed to download boost? @yxlao @germanros1987

**Comment by yxlao** [comment]
might be a glitch since it passes the other macOS test but only failed one, i've restarted the build

**Comment by rli32** [comment]
I tried your method, but got error:
AttributeError: 'open3d.open3d.geometry.TriangleMesh' object has no attribute 'sample_points_poisson_disk'

**Comment by Hippogriff** [comment]
Function "sample_points_poisson_disk" is available by doing from open3d import *.

**Comment by rli32** [comment]
I solved the problem by update my open3d library.

**Pull request merged**
