### PR TITLE
Python RSBagReader.open() crash on Ubuntu

### LINKED ISSUE #2837: Bug with RealSense bag reader
I was trying to use the sample code from "http://www.open3d.org/docs/release/tutorial/sensor/realsense.html". 
```
import open3d as o3d
bag_reader = o3d.t.io.RSBagReader()
bag_reader.open('L515_test.bag')
while not bag_reader.is_eof():
    im_rgbd = bag_reader.next_frame()
bag_reader.close()
```
However, open3d failed to open the bag but gave me the following error instead.
```
free(): invalid pointer
Aborted
```

**Environment:**

- Operating system:Ubuntu 18.04
- Python version: Python 3.7
- Open3D version: 0.12.0
- Is this remote workstation?:  no
- How did you install Open3D?:
  - conda create -n open3d
  - conda activate open3d
  - pip install open3d-0.12.0-cp37-cp37m-manylinux2014_x86_64.whl 
- Compiler version (if built from source): N/A

### PR DESCRIPTION
**Pull request by ssheorey**
Crash is due to possible bug in `std::regex` implementation in `libstdc++`, called from `ros_reader` in `librealsense`. This PR replaces some calls to `std::regex` with POSIX C regex when built with `libstdc++`

- Added Python unit test for RSBagReader: Skipped by default since test causes hang on Github Actions. Successful on local machine.
- `libusb` is now statically linked on Linux as well. `libusb` does not need to be installed while using Python package in docker. [Desktop Linux has `libusb` pre-installed]

Fixes #2837

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2876)

### CODE REVIEW

**Review by yxlao — COMMENTED** [review]
> Reviewed 10 of 15 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2876)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yxlao — APPROVED** [review]

**Comment by mikedh** [comment]
Thanks for the fix!!  I'm not sure this has this made it into PyPi wheels yet? As of 10 minutes ago on Python 3.8 on fresh wheels I was [still getting the libusb error](https://github.com/mikedh/trimesh/runs/1827718080?check_suite_focus=true).

**Comment by ssheorey** [comment]
No, we haven't made a release with the fix included yet. You can use the latest master wheels (development version) for now:
http://www.open3d.org/docs/latest/getting_started.html#development-version-pip

**Comment by mikedh** [comment]
Gotcha thanks! In another issue it had sounded like this was released, thanks for clearing that up.

**Pull request merged**
