### PR TITLE
Optimised kernel for ICP

### PR DESCRIPTION
**Pull request by reyanshsolis**
Aligning Input |  
-- | --
CPU | 4.661231
CUDA | 0.3769531

Aligned input to Pose | Current | New | Increase %
-- | -- | -- | --
CPU | 2.7844 | 1.7003 | 38.935%
CUDA | 0.6339 | 0.4013 | 36.693%

PoseToTransformation |  
-- | --
CPU | 0.0292382
CUDA | 0.0713623

"Aligning Input" and "Pose to Transformation" functions remain unchanged.
For "Aligned input to Pose" we get an average increase of around 37% for 7552 correspondences.
The performance increase will be even better for larger size input as the new method scales at a lower rate, with the size of the input, as compared to the current method, as the matrix size is fixed at the solving step. 

    Test Case: 
    examples/test_data/ICP/cloud_bin_0.pcd 
    examples/test_data/ICP/cloud_bin_1.pcd
    [Source Points: {198835, 3} Target Points: {137833, 3}]
  
    Results are taken average over 2 runs of 5 iterations each, PointToPlane ICP
    Accuracy: Same as the legacy

    System configuration:
    CPU: i7-7700hq (8 cores)
    GPU: NVIDIA GTX 1050Ti (4GB)
    RAM: 16GB

Detailed information available at: [[Link](https://docs.google.com/presentation/d/13lO01BKQWffsiWso6v0gEs_f73LCnUZwFPQyZD3vzl4/edit?usp=sharing)]
_______

This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2917)

### CODE REVIEW

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2917)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @reyanshsolis)

___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformPointToPlaneCPU.cpp, line 51 at r1](https://reviewable.io/reviews/intel-isl/open3d/2917#-MRQ7CZED2fMudmPhCH6:-MRQ7CZED2fMudmPhCH7:b-tx39ve) ([raw file](https://github.com/intel-isl/open3d/blob/bc19ab19f07a38cb5ea6b697289de49f9b503019/cpp/open3d/t/pipelines/kernel/ComputeTransformPointToPlaneCPU.cpp#L51)):*
> ```cpp
>     // This kernel computes the {n,21} shape atai tensor and {n,6} shape atbi
>     // tensor.
>     core::kernel::CPULauncher::LaunchGeneralKernel(
> ```

My plan was to make sum reduction inside the same kernel, like this: https://github.com/theNded/Open3D/blob/cuda/src/Cuda/Registration/RegistrationCudaKernel.cuh#L72. But that may not be critical for the performance, let's first profile this implementation, and check the other implementation later if possible.

**Review by theNded — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2917)* status: all files reviewed, 4 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/t/pipelines/kernel/ComputePosePointToPlane.h, line 43 at r2](https://reviewable.io/reviews/intel-isl/open3d/2917#-MRecRf_52ia1FCooOEC:-MRecRfa7XmcX--cuf8P:b-p121mh) ([raw file](https://github.com/intel-isl/open3d/blob/c61af0c391413d01f6a7fab1e4d84d984c88d5e5/cpp/open3d/t/pipelines/kernel/ComputePosePointToPlane.h#L43)):*
> ```objc
> /// gamma], a shape {6} tensor of dtype float32.
> core::Tensor ComputePosePointToPlane(
>         const core::Tensor &source_points_alligned,
> ```

Should it be `aligned`? So are other comments.
___
*[cpp/open3d/t/pipelines/registration/TransformationEstimation.cpp, line 143 at r2](https://reviewable.io/reviews/intel-isl/open3d/2917#-MRefa8MDSRPHbhYw2SG:-MRefa8MDSRPHbhYw2SH:bl43biy) ([raw file](https://github.com/intel-isl/open3d/blob/c61af0c391413d01f6a7fab1e4d84d984c88d5e5/cpp/open3d/t/pipelines/registration/TransformationEstimation.cpp#L143)):*
> ```cpp
>     // Get alligned source and target points and target normals, according to
>     // correspondences.
>     core::Tensor source_alligned =
> ```

Same, aligned?
___
*[cpp/open3d/t/pipelines/kernel/ComputePosePointToPlaneCPU.cpp, line 45 at r2](https://reviewable.io/reviews/intel-isl/open3d/2917#-MRefIZEDgyXNzIrT1ZL:-MRefIZEDgyXNzIrT1ZM:beyavlt) ([raw file](https://github.com/intel-isl/open3d/blob/c61af0c391413d01f6a7fab1e4d84d984c88d5e5/cpp/open3d/t/pipelines/kernel/ComputePosePointToPlaneCPU.cpp#L45)):*
> ```cpp
>                                 const core::Device device) {
>     // Float64 is used for solving for higher precision.
>     core::Dtype solve_dtype = core::Dtype::Float64;
> ```

It would also be interesting to check the performance by building the linear system via Float32 and cast it to double for Solving. According to my experience this could further improve the performance without losing much accuracy.

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2917)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @reyanshsolis and @theNded)

___
*[cpp/open3d/t/pipelines/kernel/ComputePosePointToPlane.h, line 43 at r2](https://reviewable.io/reviews/intel-isl/open3d/2917#-MRecRf_52ia1FCooOEC:-MRevLfEBcy4ss4YgxZF:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c61af0c391413d01f6a7fab1e4d84d984c88d5e5/cpp/open3d/t/pipelines/kernel/ComputePosePointToPlane.h#L43)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Should it be `aligned`? So are other comments.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/TransformationEstimation.cpp, line 143 at r2](https://reviewable.io/reviews/intel-isl/open3d/2917#-MRefa8MDSRPHbhYw2SG:-MReys6lEA1xcStJwrKJ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c61af0c391413d01f6a7fab1e4d84d984c88d5e5/cpp/open3d/t/pipelines/registration/TransformationEstimation.cpp#L143)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Same, aligned?
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputePosePointToPlaneCPU.cpp, line 45 at r2](https://reviewable.io/reviews/intel-isl/open3d/2917#-MRefIZEDgyXNzIrT1ZL:-MRevMnC4ee1fw3CDzDN:b9nreeu) ([raw file](https://github.com/intel-isl/open3d/blob/c61af0c391413d01f6a7fab1e4d84d984c88d5e5/cpp/open3d/t/pipelines/kernel/ComputePosePointToPlaneCPU.cpp#L45)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

It would also be interesting to check the performance by building the linear system via Float32 and cast it to double for Solving. According to my experience this could further improve the performance without losing much accuracy.
</blockquote></details>

Yes, I have been trying these changes. I will add the results soon. For now, I have made everything Float32, as the result is the same as the legacy in this case. The increase in accuracy in Float32 -> Float64 or the decrease in speed, both were not significant the last time I checked for this function. I will check it again.

**Review by theNded — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2917)* status: all files reviewed, 5 unresolved discussions (waiting on @reyanshsolis and @theNded)

___
*[cpp/open3d/t/pipelines/kernel/ComputePosePointToPlaneCUDA.cu, line 108 at r3](https://reviewable.io/reviews/intel-isl/open3d/2917#-MST4bCB2sj_CEuddUFI:-MST4bCB2sj_CEuddUFJ:booxubq) ([raw file](https://github.com/intel-isl/open3d/blob/e9c47873258a3bfef4fd3736bba0f90eea60f6f2/cpp/open3d/t/pipelines/kernel/ComputePosePointToPlaneCUDA.cu#L108)):*
> ```Cuda
>     // Get the ATA matrix back.
>     core::Tensor ATA = core::Tensor::Empty({6, 6}, solve_dtype, device);
>     float *ATA_ptr = static_cast<float *>(ATA.GetDataPtr());
> ```

AtA can be double, since 6x6 fill-in is trivial. It has a better numerical stability.

**Review by theNded — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2917)* status: all files reviewed, 5 unresolved discussions (waiting on @reyanshsolis and @theNded)

**Pull request merged**
