### PR TITLE
Alt-Enter to toggle Fullscreen mode

### PR DESCRIPTION
**Pull request by sammo2828**
Add new feature to toggle fullscreen visualizer with Alt-Enter

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1393)

### CODE REVIEW

**Comment by sammo2828** [comment]
Looks like CI is [currently failing](https://travis-ci.org/intel-isl/Open3D/jobs/624884092#L1641-L1648) because `'glfwSetWindowMonitor' was not declared in this scope`.

The [Travis CI log](https://travis-ci.org/intel-isl/Open3D/jobs/624884092#L1210) shows that it is using a very old version of *GLFW 3.1.2*, and the [GLFW Docs](https://www.glfw.org/docs/latest/group__window.html#ga81c76c418af80a1cce7055bccb0ae0a7) show that `glfwSetWindowMonitor` was added in *GLFW 3.2*.

The current version of GLFW is 3.3, which is the version that gets pulled into `Open3D/3rdparty`  when following the build instructions.

Can we please upgrade the CI environment to use GLFW 3.3?

**Comment by sammo2828** [comment]
This is getting out of date. Last I checked, CI needs to be upgraded to use GLFW 3.3.

If there is still interest, please update CI.

Otherwise, let's close this PR.

Thanks!

**Comment by yxlao** [comment]
Thanks @sammo2828 , we recently updated Travis to use Ubutnu 18.04, which shall come with GLFW `3.2` by default. I merged `master` to your branch and let's see if it can pass the CI.

**Comment by germanros1987** [comment]
@yxlao it seems that the changes that you suggested are easy to fix. Could you please take care of this?

**Comment by germanros1987** [comment]
@sammo2828 please, could you reopen the PR once the changes are ready?

**Comment by sammo2828** [comment]
All the change requests have been done.

I couldn't re-open this pull request, so please see the new pull request #1939.

**Pull request closed without merging**
