### PR TITLE
Assimp Base integration

### PR DESCRIPTION
**Pull request by errissa**
Integrates assimp into build and uses assimp to load GLTF and FBX files.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2132)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by prewettg** [comment]
___
*[cpp/tests/io/file_format/FileGLTF.cpp, line 50 at r5](https://reviewable.io/reviews/intel-isl/open3d/2132#-ME04JJu7X7RAUoEtEfI:-ME0X9sw01Es6EAiWtT_:b32wtd) ([raw file](https://github.com/intel-isl/open3d/blob/d69d9616d62c34fbad7826d42c3ea5323440cdb1/cpp/tests/io/file_format/FileGLTF.cpp#L50)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

the assimp integration only integrates using assimp for loading GLTF files not exporting them. The GLB files exported by TinyGLFT don't appear to work with Assimp's gltf importer. I don't know yet which library is 'incorrect' but, in any case, the problem is in a 3rdparty library and I don't have a good solution yet for this test case.
</blockquote></details>

ok

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ cpp/tests/io/file_format/FileGLTF.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5954903&bid=19516906)

**Pull request merged**
