### PR TITLE
Python docs fix

### LINKED ISSUE #2548: Open3D documentation in v0.11.0 has incorrect paths
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
All paths in the Open3D documentation (from v0.11.0) have an extra inclusion of cpu.pybind

for instance, 
http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html

__init__(self: open3d.cpu.pybind.geometry.PointCloud) -> None

the cpu.pybind should not be included when listing the path.

in v0.9.0 the paths are correctly listed without inclusion of pybind artefacts

*

### LINKED ISSUE #3282: Wrong Python documentation of open3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape
In the documentation the parameters are:
[http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.htm#l](url)
```
Parameters
    - alpha (float) – Parameter to control the shape. A very big value will give a shape close to the convex hull.
    - alpha – Parameter to control the shape. A very big value will give a shape close to the convex hull.
    - tetra_mesh (open3d.geometry.TetraMesh) – If not None, than uses this to construct the alpha shape. Otherwise, TetraMesh is computed from pcd.
    - pt_map (List[int]) – Optional map from tetra_mesh vertex indices to pcd points.
```
I think the first parameter is wrong and should be of type `open3d.geometry.PointCloud`

I saw it in the version `0.12.0`

### PR DESCRIPTION
**Pull request by ssheorey**
- Python docs formatting.
- Support for docs of overloaded pybind functions.
- Fix namespace: open3d.cpu.pybind.core -> open3d.core
- Restore internal links.
- Fix external broken links found with `sphinx-build -b linkcheck`.
- Process `__init__()`. (No `Returns:` in docs ). Remove `skip_init` flag.
- Add some docs to `Tensor.__init__()` as test.

**Old**
Screenshot 2021-05-02 at 10 54 04 AM
**New**
Screenshot 2021-05-02 at 3 46 03 PM

- Fixes #2548
- Fixes #3282

**Old**
Screenshot 2021-05-02 at 12 11 22 PM
**New**
Screenshot 2021-05-02 at 3 10 56 PM

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3373)

### CODE REVIEW

**Review by yxlao — APPROVED** [review]
> Reviewed 30 of 31 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3373)* status: all files reviewed, 3 unresolved discussions (waiting on @benjaminum, @ssheorey, and @stotko)

___
*[cpp/pybind/docstring.h, line 123 at r2](https://reviewable.io/reviews/intel-isl/open3d/3373#-MZkZt7K03mi5LfdcAqM:-MZkZt7K03mi5LfdcAqN:b-ycyzml) ([raw file](https://github.com/intel-isl/open3d/blob/ba92049643c19bdba8583826c47d7e0ca55bffee/cpp/pybind/docstring.h#L123)):*
> ```objc
> 
> public:
>     struct overload_docs_t {
> ```

nit: we could call it `OverloadDocs` to be consistent with other struct/classes.
___
*[cpp/pybind/docstring.cpp, line 103 at r2](https://reviewable.io/reviews/intel-isl/open3d/3373#-MZk_0LQ3mMj1afFBtw8:-MZk_0LQ3mMj1afFBtw9:bmxestg) ([raw file](https://github.com/intel-isl/open3d/blob/ba92049643c19bdba8583826c47d7e0ca55bffee/cpp/pybind/docstring.cpp#L103)):*
> ```cpp
>     for (auto& overload : fd.overload_docs_) {
>         for (ArgumentDoc& ad : overload.argument_docs_) {
>             if (map_parameter_body_docs.find(ad.name_) !=
> ```

nit: we could do `my_map.(key) != 0` to be more concise
___
*[cpp/pybind/docstring.cpp, line 134 at r2](https://reviewable.io/reviews/intel-isl/open3d/3373#-MZk_DD91xeahlP6kK-0:-MZk_DD91xeahlP6kK-1:b-k819oi) ([raw file](https://github.com/intel-isl/open3d/blob/ba92049643c19bdba8583826c47d7e0ca55bffee/cpp/pybind/docstring.cpp#L134)):*
> ```cpp
>     for (auto& overload : fd.overload_docs_) {
>         for (ArgumentDoc& ad : overload.argument_docs_) {
>             if (map_parameter_body_docs.find(ad.name_) !=
> ```

nit: same, we could do `my_map.(key) != 0` to be more concise

**Comment by yxlao** [comment]
These are great changes, especially the long-standing issue of overload functions -- it's non-trivial to do experiments and figure them out.

**Comment by stotko** [comment]
Great improvement. Just one comment: If there is multiple overloads, the indentation level of the overloads and its parameters and return values is the same which looks a bit strange. Is it possible to increase the level for the latter?

**Comment by ssheorey** [comment]
> Great improvement. Just one comment: If there is multiple overloads, the indentation level of the overloads and its parameters and return values is the same which looks a bit strange. Is it possible to increase the level for the latter?

As far as I can tell, that's not supported by Napoleon (the sphinx pre-processor for Google style docs). Adding extra indents just ruins the formatting.

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3373)* status: 29 of 33 files reviewed, 2 unresolved discussions (waiting on @benjaminum, @stotko, and @yxlao)

___
*[cpp/pybind/docstring.h, line 123 at r2](https://reviewable.io/reviews/intel-isl/open3d/3373#-MZkZt7K03mi5LfdcAqM:-MZnfAUZ35hDnBRGS233:bb6un1j) ([raw file](https://github.com/intel-isl/open3d/blob/ba92049643c19bdba8583826c47d7e0ca55bffee/cpp/pybind/docstring.h#L123)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: we could call it `OverloadDocs` to be consistent with other struct/classes.
</blockquote></details>

Done
___
*[cpp/pybind/docstring.cpp, line 103 at r2](https://reviewable.io/reviews/intel-isl/open3d/3373#-MZk_0LQ3mMj1afFBtw8:-MZnfJ-gAf5fXQVF1v-j:bi361zm) ([raw file](https://github.com/intel-isl/open3d/blob/ba92049643c19bdba8583826c47d7e0ca55bffee/cpp/pybind/docstring.cpp#L103)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: we could do `my_map.(key) != 0` to be more concise
</blockquote></details>

Changed to `my_map.count(key)>0`
___
*[cpp/pybind/docstring.cpp, line 134 at r2](https://reviewable.io/reviews/intel-isl/open3d/3373#-MZk_DD91xeahlP6kK-0:-MZnvPo-82dj-oDtfG14:bi361zm) ([raw file](https://github.com/intel-isl/open3d/blob/ba92049643c19bdba8583826c47d7e0ca55bffee/cpp/pybind/docstring.cpp#L134)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: same, we could do `my_map.(key) != 0` to be more concise
</blockquote></details>

Changed to `my_map.count(key)>0`

**Pull request merged**
