### PR TITLE
Migrate assert to OPEN3D_ASSERT

### PR DESCRIPTION
**Pull request by yxlao**
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3594)

### CODE REVIEW

**Review by stotko — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3594)* status: all files reviewed, 1 unresolved discussion (waiting on @yxlao)

___
*[cpp/open3d/core/Indexer.cpp, line 352 at r1](https://reviewable.io/reviews/intel-isl/open3d/3594#-McIlX9W8-_KAklYp1rc:-McIlX9XADPe2xj7yjC7:bd1ldgu) ([raw file](https://github.com/intel-isl/open3d/blob/fe6752896efeb90ffd603f23fae225d73aacfe8c/cpp/open3d/core/Indexer.cpp#L352)):*
> ```cpp
> void Indexer::ShrinkDim(int64_t dim, int64_t start, int64_t size) {
>     // inputs_ and output_'s shapes are not important.
>     if (dim < 0 && dim > ndims_) {
> ```

`dim < 0 || dim >= ndims_`. Alternatively `!(dim >= 0 && dim < ndims_)` like in above change.

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3594)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @stotko)

___
*[cpp/open3d/core/Indexer.cpp, line 352 at r1](https://reviewable.io/reviews/intel-isl/open3d/3594#-McIlX9W8-_KAklYp1rc:-McJ0ufGBXP0uHxkT2cC:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fe6752896efeb90ffd603f23fae225d73aacfe8c/cpp/open3d/core/Indexer.cpp#L352)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`dim < 0 || dim >= ndims_`. Alternatively `!(dim >= 0 && dim < ndims_)` like in above change.
</blockquote></details>

Done.

**Review by stotko — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3594)* status: all files reviewed, 2 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/Indexer.cpp, line 352 at r1](https://reviewable.io/reviews/intel-isl/open3d/3594#-McIlX9W8-_KAklYp1rc:-McJ1UdN5dupvPzgYmGV:b-20sqca) ([raw file](https://github.com/intel-isl/open3d/blob/fe6752896efeb90ffd603f23fae225d73aacfe8c/cpp/open3d/core/Indexer.cpp#L352)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not exactly. We should use `||` instead of `&&`, shouldn't we? Otherwise, for `ndims_ >= 0` which seems to always hold, the expressions is always `false` because the expression ends up to be`x >= 0 && x < 0`.

I would prefer `if(!(dim >= 0 && dim < ndims_))`, but the version with `||` is also fine.
___
*[cpp/open3d/ml/contrib/Cloud.cpp, line 50 at r2](https://reviewable.io/reviews/intel-isl/open3d/3594#-McJ2XjKAJbCZWGWzV8A:-McJ2XjKAJbCZWGWzV8B:bxsx8gj) ([raw file](https://github.com/intel-isl/open3d/blob/e3c275d37ee97e26b7c672ccfcc26bf0c253b7a3/cpp/open3d/ml/contrib/Cloud.cpp#L50)):*
> ```cpp
> namespace contrib {
> 
> static_assert(std::is_pod<PointXYZ>());
> ```

`static_assert` without a message is a C++17 feature. Add a message as the second argument to fix the CI errors.

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3594)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @stotko)

___
*[cpp/open3d/core/Indexer.cpp, line 352 at r1](https://reviewable.io/reviews/intel-isl/open3d/3594#-McIlX9W8-_KAklYp1rc:-McJ8IPIBjkkJHuUPTQc:bph42t6) ([raw file](https://github.com/intel-isl/open3d/blob/fe6752896efeb90ffd603f23fae225d73aacfe8c/cpp/open3d/core/Indexer.cpp#L352)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Not exactly. We should use `||` instead of `&&`, shouldn't we? Otherwise, for `ndims_ >= 0` which seems to always hold, the expressions is always `false` because the expression ends up to be`x >= 0 && x < 0`.

I would prefer `if(!(dim >= 0 && dim < ndims_))`, but the version with `||` is also fine.
</blockquote></details>

My bad. Changed to `if(!(dim >= 0 && dim < ndims_))`.
___
*[cpp/open3d/ml/contrib/Cloud.cpp, line 50 at r2](https://reviewable.io/reviews/intel-isl/open3d/3594#-McJ2XjKAJbCZWGWzV8A:-McJ8OJ06qjxmvDon5Xr:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/e3c275d37ee97e26b7c672ccfcc26bf0c253b7a3/cpp/open3d/ml/contrib/Cloud.cpp#L50)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`static_assert` without a message is a C++17 feature. Add a message as the second argument to fix the CI errors.
</blockquote></details>

Done.

**Review by stotko — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3594)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yxlao)

**Pull request merged**
