### PR TITLE
Enable python to render to image

### PR DESCRIPTION
**Pull request by prewettg**
See examples/python/render-to-image.py for example of how to use.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2413)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- examples/python/GUI/render-nowindow.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6271818&bid=20415865)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- examples/python/gui/render-to-image.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6271818&bid=20415865)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- examples/python/gui/render-to-image.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6271818&bid=20415865)

**Review by errissa — CHANGES_REQUESTED** [review]
> Reviewed 9 of 17 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2413)* status: all files reviewed, 1 unresolved discussion (waiting on @prewettg)

___
*[cpp/open3d/visualization/rendering/filament/FilamentRenderToBuffer.cpp, line 172 at r3](https://reviewable.io/reviews/intel-isl/open3d/2413#-MItTVUF7CmoSgiwIAlH:-MItTVUF7CmoSgiwIAlI:b-xjupva) ([raw file](https://github.com/intel-isl/open3d/blob/562477b884f13422ac0fb05e70b89460804b81e0/cpp/open3d/visualization/rendering/filament/FilamentRenderToBuffer.cpp#L172)):*
> ```cpp
> 
>         if (!shotDone) {
>             shotDone = true;
> ```

There's no loop here anymore so this code is not necessary.

**Review by prewettg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2413)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @errissa)

___
*[cpp/open3d/visualization/rendering/filament/FilamentRenderToBuffer.cpp, line 172 at r3](https://reviewable.io/reviews/intel-isl/open3d/2413#-MItTVUF7CmoSgiwIAlH:-MIuOD8a6W43VFCGmi_K:b-886gsx) ([raw file](https://github.com/intel-isl/open3d/blob/562477b884f13422ac0fb05e70b89460804b81e0/cpp/open3d/visualization/rendering/filament/FilamentRenderToBuffer.cpp#L172)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

There's no loop here anymore so this code is not necessary.
</blockquote></details>

Fixed

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- examples/python/gui/render-to-image.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6271818&bid=20415865)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- examples/python/gui/render-to-image.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6271818&bid=20415865)

**Review by errissa — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2413)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- examples/python/gui/render-to-image.py  1
         

Clones added
============
- cpp/open3d/visualization/gui/Application.cpp  1
- cpp/open3d/visualization/rendering/Renderer.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6271818&bid=20415865)

**Review by errissa — CHANGES_REQUESTED** [review]
I'm withdrawing my previous approval while I review the recent changes you made.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2413#-:-MJ4Xe1G4dH1lNJ55GUb:bxu43ct)* status: 9 of 28 files reviewed, all discussions resolved (waiting on @errissa)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- examples/python/gui/render-to-image.py  1
         

Clones added
============
- cpp/open3d/visualization/rendering/Renderer.cpp  1
- cpp/open3d/visualization/gui/Application.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6271818&bid=20415865)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- examples/python/gui/render-to-image.py  1
         

Clones added
============
- cpp/open3d/visualization/gui/Application.cpp  1
- cpp/open3d/visualization/rendering/Renderer.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6271818&bid=20415865)

**Review by errissa — APPROVED** [review]
> Reviewed 4 of 20 files at r5, 15 of 15 files at r6.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2413)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- examples/python/gui/render-to-image.py  1
         

Clones added
============
- cpp/open3d/visualization/rendering/Renderer.cpp  1
- cpp/open3d/visualization/gui/Application.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6271818&bid=20415865)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- examples/python/gui/render-to-image.py  1
         

Clones added
============
- cpp/open3d/visualization/rendering/Renderer.cpp  1
- cpp/open3d/visualization/gui/Application.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6271818&bid=20415865)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- examples/python/gui/render-to-image.py  1
         

Clones added
============
- cpp/open3d/visualization/gui/Application.cpp  1
- cpp/open3d/visualization/rendering/Renderer.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6271818&bid=20415865)

**Review by errissa — APPROVED** [review]
> Reviewed 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2413)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- examples/python/gui/render-to-image.py  1
         

Clones added
============
- cpp/open3d/visualization/rendering/Renderer.cpp  1
- cpp/open3d/visualization/gui/Application.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6271818&bid=20415865)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- examples/python/gui/render-to-image.py  1
         

Clones added
============
- cpp/open3d/visualization/gui/Application.cpp  1
- cpp/open3d/visualization/rendering/Renderer.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6271818&bid=20415865)

**Pull request merged**
