### PR TITLE
Caching Related Bug Fixes

### PR DESCRIPTION
**Pull request by errissa**
* Based on PR2449 that rolls Filament back to 1.8.1
* Fixes dialog boxes not immediately disappearing when closed
* Fixes potential issue with image export
* Uses colored sky box instead of clearing buffer to set background color

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2451)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6315182&bid=20532369)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6315182&bid=20532369)

**Review by prewettg — APPROVED** [review]
> Reviewed 14 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2451)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6315182&bid=20532369)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6315182&bid=20532369)

**Pull request merged**
