### PR TITLE
Release Python GIL for fast multithreaded IO

### PR DESCRIPTION
**Pull request by sammo2828**
This pull request allows multithreaded loading of PCD files, etc. by releasing the Global Interpreter Lock (GIL):

https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil

Here's a benchmark that reads 8 PCD files concurrently:

```python
import open3d as o3d

import time
from multiprocessing.dummy import Pool as ThreadPool

def worker(index):
    pcd_file = "examples/TestData/ICP/cloud_bin_0.pcd"
    worker_start = time.time()
    pcd = o3d.io.read_point_cloud(pcd_file)
    return pcd, time.time() - worker_start

def tt(index):
    time.sleep(0.5)
    print(index)
    return index * index


if __name__ == '__main__':
    p = ThreadPool(8)
    start = time.time()
    res = p.map(worker, range(8))
    print("Total time: %d ms" % (1000 * (time.time() - start)))
    p.close()
    for pcd, t in res:
        print("Loaded %s in %d ms" % (pcd, 1000 * t))

```

New *faster* time after this pull request:
```
Total time: 150 ms
Loaded geometry::PointCloud with 198835 points. in 136 ms
Loaded geometry::PointCloud with 198835 points. in 136 ms
Loaded geometry::PointCloud with 198835 points. in 128 ms
Loaded geometry::PointCloud with 198835 points. in 150 ms
Loaded geometry::PointCloud with 198835 points. in 150 ms
Loaded geometry::PointCloud with 198835 points. in 150 ms
Loaded geometry::PointCloud with 198835 points. in 150 ms
Loaded geometry::PointCloud with 198835 points. in 135 ms
```
Previous *slower* time before this pull request:
```
Total time: 745 ms
Loaded geometry::PointCloud with 198835 points. in 186 ms
Loaded geometry::PointCloud with 198835 points. in 281 ms
Loaded geometry::PointCloud with 198835 points. in 280 ms
Loaded geometry::PointCloud with 198835 points. in 464 ms
Loaded geometry::PointCloud with 198835 points. in 183 ms
Loaded geometry::PointCloud with 198835 points. in 277 ms
Loaded geometry::PointCloud with 198835 points. in 186 ms
Loaded geometry::PointCloud with 198835 points. in 96 ms
```

The following functions are affected:

* read_image
* write_image
* read_line_set
* write_line_set
* read_point_cloud
* write_point_cloud
* read_triangle_mesh
* write_triangle_mesh
* read_voxel_grid
* write_voxel_grid
* read_pinhole_camera_intrinsic
* write_pinhole_camera_intrinsic
* read_pinhole_camera_parameters
* write_pinhole_camera_parameters
* read_pinhole_camera_trajectory
* write_pinhole_camera_trajectory
* read_feature
* write_feature
* read_pose_graph
* write_pose_graph

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1936)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5656834&bid=18518349)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5656834&bid=18518349)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5656834&bid=18518349)

**Comment by sammo2828** [comment]
Not sure why this is not passing CI. Seems to be a bunch of style errors that with files that this PR has nothing to do with. Maybe I'm missing out on something?

**Comment by germanros1987** [comment]
@theNded could you have a quick look at this PR, please?

**Comment by theNded** [comment]
@germanros1987 idk if we should record all changes in `CHANGELOG.md`. Are we supposed to only write down major changes before the next release?

**Pull request merged**
