### PR TITLE
Tensor Geometry::Transform kernels for PointCloud and TriangleMesh.

### PR DESCRIPTION
**Pull request by reyanshsolis**
Added:
- Similar to `Legacy Geometry3D::X`, this PR adds `t::geometry::kernel::transform::X`.
 `X = TransformPoints, TransformNormals, RotatePoints, RotateNormals.`
- Using the same in `Tensor PointCloud and TriangleMesh`. 

```
PointCloud:

Before:
---------------------------------------------------------
Benchmark               Time             CPU   Iterations
---------------------------------------------------------
Transform/CPU        10.3 ms         8.61 ms           68
Transform/CUDA       2.35 ms         2.35 ms          265

After: 
---------------------------------------------------------
Benchmark               Time             CPU   Iterations
---------------------------------------------------------
Transform/CPU       0.436 ms        0.436 ms         1561
Transform/CUDA      0.143 ms        0.143 ms         8245
```

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3648)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 4 of 15 files at r2, 6 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3648)* status: 11 of 17 files reviewed, 5 unresolved discussions (waiting on @reyanshsolis and @theNded)

___
*[cpp/benchmarks/t/geometry/PointCloud.cpp, line 118 at r3](https://reviewable.io/reviews/intel-isl/open3d/3648#-MeUhQjw9biRUUt3LNv7:-MeUhQjw9biRUUt3LNv8:b6xzzmk) ([raw file](https://github.com/intel-isl/open3d/blob/8f9c9afdd9063db88f9d50a221015c01876e346b/cpp/benchmarks/t/geometry/PointCloud.cpp#L118)):*
> ```cpp
>     // Warm Up.
>     auto warm_up = pcd.Transform(transformation);
>     (void)warm_up;
> ```

`pcd_transformed = `
looks like we don't need the `(void)`
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 158 at r3](https://reviewable.io/reviews/intel-isl/open3d/3648#-MeUhZpR-NgZ7i5lKJyZ:-MeUhZpR-NgZ7i5lKJy_:b-ub8wd6) ([raw file](https://github.com/intel-isl/open3d/blob/8f9c9afdd9063db88f9d50a221015c01876e346b/cpp/open3d/t/geometry/PointCloud.cpp#L158)):*
> ```cpp
> 
> PointCloud &PointCloud::Transform(const core::Tensor &transformation) {
>     t::geometry::kernel::transform::TransformPoints(transformation,
> ```

looks like we can remove `t::geometry::` namespace (if it is applicable), do the same for the rest of this PR
___
*[cpp/open3d/t/geometry/kernel/Transform.cpp, line 41 at r2](https://reviewable.io/reviews/intel-isl/open3d/3648#-MeUdLt13fhOVe9YR_vX:-MeUdLt13fhOVe9YR_vY:b5ryhcz) ([raw file](https://github.com/intel-isl/open3d/blob/2a97b5547bde3a3a27c2b4ef927aa8d418a509bd/cpp/open3d/t/geometry/kernel/Transform.cpp#L41)):*
> ```cpp
> namespace transform {
> 
> void TransformPoints(const core::Tensor& transformation, core::Tensor& points) {
> ```

Also `points.AssertShapeCompatible({utility::nullopt, 3}));` same for normals, etc.
___
*[cpp/open3d/t/geometry/kernel/Transform.cpp, line 55 at r3](https://reviewable.io/reviews/intel-isl/open3d/3648#-MeUhwyf5sP8lhlLSSLy:-MeUhwyf5sP8lhlLSSLz:b-4aaatk) ([raw file](https://github.com/intel-isl/open3d/blob/8f9c9afdd9063db88f9d50a221015c01876e346b/cpp/open3d/t/geometry/kernel/Transform.cpp#L55)):*
> ```cpp
>         TransformPointsCPU(transformation_contiguous, points_contiguous);
>     } else if (device_type == core::Device::DeviceType::CUDA) {
>         CUDA_CALL(TransformPointsCUDA, transformation_contiguous,
> ```

It would be great if the maco is (i.e. it takes an expression inside):
```cpp
OPEN3D_CALL_IF_CUDA_ENABLED(TransformPointsCUDA(transformation_contiguous, points_contiguous));
```
___
*[cpp/open3d/t/geometry/kernel/TransformCUDA.cu, line 1 at r3](https://reviewable.io/reviews/intel-isl/open3d/3648#-MeUgKfd-IY67QSRCLrF:-MeUgKfd-IY67QSRCLrG:bsmg5of) ([raw file](https://github.com/intel-isl/open3d/blob/8f9c9afdd9063db88f9d50a221015c01876e346b/cpp/open3d/t/geometry/kernel/TransformCUDA.cu#L1)):*
> ```Cuda
> // ----------------------------------------------------------------------------
> ```

This file is almost the same as `TransformCPU`. Can we merge them into one file?

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3648)* status: 5 of 17 files reviewed, 5 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/benchmarks/t/geometry/PointCloud.cpp, line 118 at r3](https://reviewable.io/reviews/intel-isl/open3d/3648#-MeUhQjw9biRUUt3LNv7:-MecMlxo6M7nelFZod-2:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/8f9c9afdd9063db88f9d50a221015c01876e346b/cpp/benchmarks/t/geometry/PointCloud.cpp#L118)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`pcd_transformed = `
looks like we don't need the `(void)`
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 158 at r3](https://reviewable.io/reviews/intel-isl/open3d/3648#-MeUhZpR-NgZ7i5lKJyZ:-MecMmhG0hrwnAAwGzm5:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/8f9c9afdd9063db88f9d50a221015c01876e346b/cpp/open3d/t/geometry/PointCloud.cpp#L158)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

looks like we can remove `t::geometry::` namespace (if it is applicable), do the same for the rest of this PR
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/kernel/Transform.cpp, line 41 at r2](https://reviewable.io/reviews/intel-isl/open3d/3648#-MeUdLt13fhOVe9YR_vX:-MecMrJz9rz0q14WWXm0:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/2a97b5547bde3a3a27c2b4ef927aa8d418a509bd/cpp/open3d/t/geometry/kernel/Transform.cpp#L41)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Also `points.AssertShapeCompatible({utility::nullopt, 3}));` same for normals, etc.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/kernel/Transform.cpp, line 55 at r3](https://reviewable.io/reviews/intel-isl/open3d/3648#-MeUhwyf5sP8lhlLSSLy:-MecMsXc1SVlzeUnZhLs:b-7rtil4) ([raw file](https://github.com/intel-isl/open3d/blob/8f9c9afdd9063db88f9d50a221015c01876e346b/cpp/open3d/t/geometry/kernel/Transform.cpp#L55)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

It would be great if the maco is (i.e. it takes an expression inside):
```cpp
OPEN3D_CALL_IF_CUDA_ENABLED(TransformPointsCUDA(transformation_contiguous, points_contiguous));
```
</blockquote></details>

This is used at many places, may we try this in a separate PR ?
___
*[cpp/open3d/t/geometry/kernel/TransformCUDA.cu, line 1 at r3](https://reviewable.io/reviews/intel-isl/open3d/3648#-MeUgKfd-IY67QSRCLrF:-MecMzx7Agl_LQImrerw:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/8f9c9afdd9063db88f9d50a221015c01876e346b/cpp/open3d/t/geometry/kernel/TransformCUDA.cu#L1)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

This file is almost the same as `TransformCPU`. Can we merge them into one file?
</blockquote></details>

Done.

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3648)* status: 5 of 17 files reviewed, 6 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/t/geometry/kernel/TransformImpl.h, line 110 at r4](https://reviewable.io/reviews/intel-isl/open3d/3648#-MecN3r8DbOc5_FmgS37:-MecN3r8DbOc5_FmgS38:b-52kato) ([raw file](https://github.com/intel-isl/open3d/blob/1696c363ecac92969c766dbbfb450685a3d7312d/cpp/open3d/t/geometry/kernel/TransformImpl.h#L110)):*
> ```objc
> 
> #if defined(__CUDACC__)
> namespace launcher = core::kernel::cuda_launcher;
> ```

is it fine to declare this as global in a file like this, to keep functions clean ?

**Review by yxlao — APPROVED** [review]
> Reviewed 2 of 15 files at r2, 2 of 8 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3648)* status: 11 of 17 files reviewed, 1 unresolved discussion (waiting on @reyanshsolis, @theNded, and @yxlao)

___
*[cpp/open3d/t/geometry/kernel/TransformImpl.h, line 110 at r4](https://reviewable.io/reviews/intel-isl/open3d/3648#-MecN3r8DbOc5_FmgS37:-MfCxzLn26ujrsMI89ig:b-1a1mjr) ([raw file](https://github.com/intel-isl/open3d/blob/1696c363ecac92969c766dbbfb450685a3d7312d/cpp/open3d/t/geometry/kernel/TransformImpl.h#L110)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

is it fine to declare this as global in a file like this, to keep functions clean ?
</blockquote></details>

It will be refactored away. In the future, it will become `ParallelFor(device, n, func);`

**Pull request merged**
