### PR TITLE
improved doc for ml layers and ops

### PR DESCRIPTION
**Pull request by benjaminum**
This PR
- improves docstrings for layers and ops
- fixes some missing or wrong default args in torch layers/ops

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2296)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 19
           

Clones added
============
- python/open3d/ml/torch/python/layers/convolutions.py  1
- cpp/open3d/ml/impl/misc/KnnSearch.h  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6142032&bid=20079057)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- python/open3d/ml/torch/python/layers/convolutions.py  1
- cpp/open3d/ml/impl/misc/KnnSearch.h  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6142032&bid=20079057)

**Review by griegler — CHANGES_REQUESTED** [review]
> Reviewed 13 of 17 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2296)* status: all files reviewed, 2 unresolved discussions (waiting on @benjaminum)

___
*[cpp/open3d/ml/TensorFlow/ContinuousConv/ContinuousConvOps.cpp, line 188 at r2](https://reviewable.io/reviews/intel-isl/open3d/2296#-MGhYEfb-0cw72Oh8fcs:-MGhYEfcD-H3eTYhQxBq:b-19r93v) ([raw file](https://github.com/intel-isl/open3d/blob/ce8fc6293d89cbe6742b12a8422b45c8fa7af54b/cpp/open3d/ml/TensorFlow/ContinuousConv/ContinuousConvOps.cpp#L188)):*
> ```cpp
>                           )
> 
>   # or with pytorch
> ```

why the pytorch example in the TensorFlow file?
___
*[cpp/open3d/ml/TensorFlow/Misc/BuildSpatialHashTableOps.cpp, line 117 at r2](https://reviewable.io/reviews/intel-isl/open3d/2296#-MGhYRfvECAwmcqgsvxn:-MGhYRfvECAwmcqgsvxo:bnj7hl0) ([raw file](https://github.com/intel-isl/open3d/blob/ce8fc6293d89cbe6742b12a8422b45c8fa7af54b/cpp/open3d/ml/TensorFlow/Misc/BuildSpatialHashTableOps.cpp#L117)):*
> ```cpp
>   #         neighbors_distance   = []
> 
>   # or with pytorch
> ```

same as above

**Review by benjaminum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2296)* status: all files reviewed, 2 unresolved discussions (waiting on @benjaminum and @griegler)

___
*[cpp/open3d/ml/TensorFlow/ContinuousConv/ContinuousConvOps.cpp, line 188 at r2](https://reviewable.io/reviews/intel-isl/open3d/2296#-MGhYEfb-0cw72Oh8fcs:-MGh_eAeA_YoOd9CbCw0:bofd26h) ([raw file](https://github.com/intel-isl/open3d/blob/ce8fc6293d89cbe6742b12a8422b45c8fa7af54b/cpp/open3d/ml/TensorFlow/ContinuousConv/ContinuousConvOps.cpp#L188)):*
<details><summary><i>Previously, griegler (Gernot) wrote…</i></summary><blockquote>

why the pytorch example in the TensorFlow file?
</blockquote></details>

We use the same docstring for both wrappers. For TF we use the provided C++ macro to inject the doc. For torch we extract it from the .cpp file.

**Review by griegler — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2296)* status: all files reviewed, 1 unresolved discussion (waiting on @benjaminum)

___
*[cpp/open3d/ml/TensorFlow/ContinuousConv/ContinuousConvOps.cpp, line 188 at r2](https://reviewable.io/reviews/intel-isl/open3d/2296#-MGhYEfb-0cw72Oh8fcs:-MGhrmYT67ofWCI_Dw4K:btdsfzr) ([raw file](https://github.com/intel-isl/open3d/blob/ce8fc6293d89cbe6742b12a8422b45c8fa7af54b/cpp/open3d/ml/TensorFlow/ContinuousConv/ContinuousConvOps.cpp#L188)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

We use the same docstring for both wrappers. For TF we use the provided C++ macro to inject the doc. For torch we extract it from the .cpp file.
</blockquote></details>

I see.

**Pull request merged**
