### PR TITLE
Move io to open3d::t

### PR DESCRIPTION
**Pull request by yxlao**
Addressing: https://github.com/intel-isl/Open3D/pull/2403#issuecomment-702062184

This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2406)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 5
           

Clones added
============
- cpp/open3d/t/io/FileFormatIO.h  1
- cpp/open3d/t/io/PointCloudIO.h  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6267374&bid=20405039)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 5
           

Clones added
============
- cpp/open3d/t/io/FileFormatIO.h  1
- cpp/pybind/t/io/class_io.cpp  1
- cpp/pybind/io/class_io.cpp  1
- cpp/open3d/t/io/PointCloudIO.cpp  4
- cpp/open3d/t/io/PointCloudIO.h  2
- cpp/open3d/t/io/file_format/FileXYZI.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6267374&bid=20405039)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 5
           

Clones added
============
- cpp/open3d/t/io/PointCloudIO.cpp  4
- cpp/open3d/t/io/PointCloudIO.h  2
- cpp/open3d/t/io/file_format/FileXYZI.cpp  1
- cpp/pybind/t/io/class_io.cpp  1
- cpp/pybind/io/class_io.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6267374&bid=20405039)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 5
           

Clones added
============
- cpp/pybind/t/io/class_io.cpp  1
- cpp/open3d/t/io/PointCloudIO.cpp  5
- cpp/open3d/t/io/file_format/FileXYZI.cpp  1
- cpp/pybind/io/class_io.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6267374&bid=20405039)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 5
           

Clones added
============
- cpp/open3d/t/io/PointCloudIO.cpp  5
- cpp/pybind/io/class_io.cpp  1
- cpp/open3d/t/io/file_format/FileXYZI.cpp  1
- cpp/pybind/t/io/class_io.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6267374&bid=20405039)

**Review by ssheorey — APPROVED** [review]
Thanks. I think this should fix the `read_t_point_cloud` pybind documentation as well.

**Comment by yxlao** [comment]
> Thanks. I think this should fix the read_t_point_cloud pybind documentation as well.

Yes, exactly. It was due to function overloading.

**Pull request merged**
