### PR TITLE
Example jupyter tutorial for point cloud

### PR DESCRIPTION
**Pull request by griegler**
I created a Jupyter notebook for `PointCloud` based on http://www.open3d.org/docs/release/tutorial/Basic/pointcloud.html

I use a monkey patch for `o3d.visualization.draw_geometries` so that the last view of the visualizer is rendered in the notebook. This could be used to update our documentation. Also before a release we could easily rerun all notebooks and check if they evaluate without errors and the visualizations look like they should.
@germanros1987 @qianyizh @yxlao @benjaminum let me know what you think.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1631)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/Python/Basic/open3d_tutorial.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5196354&bid=17041631)

**Comment by griegler** [comment]
@benjaminum nbsphinx should be no problem if we go further with this approach. 
Binder/Colab might be more problematic at the moment, because we do not have a complete visualizer for jupyter atm. I still rely on the OpenGL visualizer in the example and monkey patch `draw_geometries` that the last view of the visualizer is shown after the cell.
I also agree with you comment regarding version control to keep the git repo size small.

**Comment by griegler** [comment]
I removed the notebook output in the current commit. In addition I extended the the `draw_geometries` function with the parameter `point_show_normal`.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- examples/Python/Basic/open3d_tutorial.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5196354&bid=17041631)

**Pull request merged**
