### PR TITLE
refactor color map optimization

### PR DESCRIPTION
**Pull request by yxlao**
- color map optimization is now a class
- the numerical results are exactly the same as before, see `python/test/test_color_map.py`
- separated rigid and non-rigid optimization options
- docstrings are updated, now docstring parsing non-overloaded `__init__ ` function are supported
- deleted cpp unit tests, most of the original unit test were commented out and unused
- add a ported [`std::optional<T>`](https://en.cppreference.com/w/cpp/utility/optional), to simplify code

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2026)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Clones added
============
- cpp/open3d/pipelines/color_map/NonRigidOptimizer.cpp  3
- cpp/open3d/pipelines/color_map/RigidOptimizer.h  3
- cpp/open3d/pipelines/color_map/RigidOptimizer.cpp  3
- cpp/open3d/utility/Optional.h  4
- cpp/open3d/pipelines/color_map/NonRigidOptimizer.h  3
- cpp/open3d/pipelines/color_map/ColorMapOptimizer.h  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5775661&bid=18903347)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Clones added
============
- cpp/open3d/pipelines/color_map/NonRigidOptimizer.h  3
- cpp/open3d/pipelines/color_map/RigidOptimizer.h  3
- cpp/open3d/pipelines/color_map/RigidOptimizer.cpp  3
- cpp/open3d/pipelines/color_map/NonRigidOptimizer.cpp  3
- cpp/open3d/pipelines/color_map/ColorMapOptimizer.h  1
- cpp/open3d/utility/Optional.h  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5775661&bid=18903347)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Clones added
============
- cpp/open3d/utility/Optional.h  4
- cpp/open3d/pipelines/color_map/RigidOptimizer.cpp  3
- cpp/open3d/pipelines/color_map/ColorMapOptimizer.h  1
- cpp/open3d/pipelines/color_map/RigidOptimizer.h  3
- cpp/open3d/pipelines/color_map/NonRigidOptimizer.h  3
- cpp/open3d/pipelines/color_map/NonRigidOptimizer.cpp  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5775661&bid=18903347)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Clones added
============
- cpp/open3d/pipelines/color_map/ColorMapOptimizer.h  1
- cpp/open3d/pipelines/color_map/RigidOptimizer.cpp  3
- cpp/open3d/pipelines/color_map/RigidOptimizer.h  3
- cpp/open3d/pipelines/color_map/NonRigidOptimizer.cpp  3
- cpp/open3d/utility/Optional.h  4
- cpp/open3d/pipelines/color_map/NonRigidOptimizer.h  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5775661&bid=18903347)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Clones added
============
- cpp/open3d/pipelines/color_map/RigidOptimizer.h  3
- cpp/open3d/pipelines/color_map/NonRigidOptimizer.h  3
- cpp/open3d/utility/Optional.h  4
- cpp/open3d/pipelines/color_map/NonRigidOptimizer.cpp  3
- cpp/open3d/pipelines/color_map/ColorMapOptimizer.h  1
- cpp/open3d/pipelines/color_map/RigidOptimizer.cpp  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5775661&bid=18903347)

**Comment by yxlao** [comment]
Both comments have been addressed, moving to new PR: #2832

**Pull request closed without merging**
