### PR TITLE
Added example to add geometry to a scene using the new GUI.

### PR DESCRIPTION
**Pull request by prewettg**
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2515)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- examples/python/gui/add-geometry.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6367307&bid=20662420)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- examples/python/gui/add-geometry.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6367307&bid=20662420)

**Review by errissa — APPROVED** [review]
FYI - every time a sphere is created you get a filament error output to the console about missing required attributes. I will fix that in a separate PR.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2515#-:-MKAUzzLDhj7TrGGR3_o:b3fceyt)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @germanros1987)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- examples/python/gui/add-geometry.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6367307&bid=20662420)

**Pull request merged**
