### PR TITLE
[FileSystem] Fix GetPathComponents and unit tests on Windows.

### PR DESCRIPTION
**Pull request by Dudulle**
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3070)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3070)* status: all files reviewed, 2 unresolved discussions (waiting on @Dudulle)

___
*[cpp/tests/utility/FileSystem.cpp, line 421 at r2](https://reviewable.io/reviews/intel-isl/open3d/3070#-MUClJlSDYBibMLxnPcm:-MUClJlSDYBibMLxnPcn:b-j476lk) ([raw file](https://github.com/intel-isl/open3d/blob/754bbb00cb7205a55884bfcad4c9cd91736c826a/cpp/tests/utility/FileSystem.cpp#L421)):*
> ```cpp
> 
>     for (size_t i = 0; i < fileNames.size(); i++) {
>         FILE *file = utility::filesystem::FOpen(fileNames[i].c_str(), "w");
> ```

looks like we don't need `.c_str()` here
___
*[cpp/tests/utility/FileSystem.cpp, line 475 at r2](https://reviewable.io/reviews/intel-isl/open3d/3070#-MUClPkJEYEzwu-WVE5I:-MUClPkJEYEzwu-WVE5J:b-j476lk) ([raw file](https://github.com/intel-isl/open3d/blob/754bbb00cb7205a55884bfcad4c9cd91736c826a/cpp/tests/utility/FileSystem.cpp#L475)):*
> ```cpp
> 
>     for (size_t i = 0; i < fileNames.size(); i++) {
>         FILE *file = utility::filesystem::FOpen(fileNames[i].c_str(), "w");
> ```

looks like we don't need `.c_str()` here

**Comment by yxlao** [comment]
In order for the Windows unit tests to fully compile, I remember we need to fix quite a few compiler warnings. Did you run into these warnings and did the Windows unit tests run successfully?

**Comment by Dudulle** [comment]
Yes like this there are still warnings about using deprecated methods and quite a few about converting numbers to smaller types.
The unit tests are compiling with PR #3036 so I ran them on that branch.

The filesystem tests were the only ones _actually_ failing and passed after those changes.

**Review by Dudulle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3070)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @yxlao)

___
*[cpp/tests/utility/FileSystem.cpp, line 421 at r2](https://reviewable.io/reviews/intel-isl/open3d/3070#-MUClJlSDYBibMLxnPcm:-MUCvwk22n6ygHgFVl0x:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/754bbb00cb7205a55884bfcad4c9cd91736c826a/cpp/tests/utility/FileSystem.cpp#L421)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

looks like we don't need `.c_str()` here
</blockquote></details>

Done.
___
*[cpp/tests/utility/FileSystem.cpp, line 475 at r2](https://reviewable.io/reviews/intel-isl/open3d/3070#-MUClPkJEYEzwu-WVE5I:-MUCw26h35yg7Y3xhxie:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/754bbb00cb7205a55884bfcad4c9cd91736c826a/cpp/tests/utility/FileSystem.cpp#L475)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

looks like we don't need `.c_str()` here
</blockquote></details>

Done.

**Review by yxlao — APPROVED** [review]
LGTM after CI.

Perfect, thanks @Dudulle . After these two PRs, we will be able to enable unit tests in the Windows CI.

**Pull request merged**
