### PR TITLE
Move vertexmap/normalmap related functions to t::Image

### PR DESCRIPTION
**Pull request by theNded**
This PR introduces depth image utility functions to t::Image, including
- Preprocessing
- Vertex map generation
- Normal map generation
- Depth colorization
- PyrDown with depth difference threshold

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3318)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3318)* status: all files reviewed, 15 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[cpp/open3d/t/geometry/Image.h, line 242 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBorbK6_7eR5tlXdls:-MZBorbK6_7eR5tlXdlt:b-ov0656) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.h#L242)):*
> ```objc
>     Image PyrDown() const;
> 
>     /// Preprocess a image of (H, W, 1), typically used for a depth image.
> ```

We can call it `(rows, cols, 1)` to be consistent. See the docstring for `Image::Image()`.

The idea is to avoid the mixed-use of `H, W, x, y, u, v` which could be confusing. E.g., if we look at `x`, `y` by themselves, we don't know the coordinate orientation; but it is always clear what `r` and `c` means.
___
*[cpp/open3d/t/geometry/Image.h, line 250 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBePgr0Z1p6Y2Jw6S9:-MZBePgr0Z1p6Y2Jw6SA:bvsvphi) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.h#L250)):*
> ```objc
>                         float min_value,
>                         float max_value,
>                         float clip_fill = 0.0f);
> ```

How do we deal with non-float images? I see we have some code enforcing the input dtype. We shall probably specify that in the comment. 

The same applies to the 4 functions. 
___
*[cpp/open3d/t/geometry/Image.h, line 252 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBp07D3lzr8K_ymgWo:-MZBp07D3lzr8K_ymgWp:b-4etbng) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.h#L252)):*
> ```objc
>                         float clip_fill = 0.0f);
> 
>     /// Create a vertex map (H, W, 3) in Float32 from an image of (H, W, 1) in
> ```

Same, we can call it `(rows, cols, 3)`, `(rows, cols, 1)` to be consistent.
___
*[cpp/open3d/t/geometry/Image.h, line 260 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBpX792dPP30DGAgTm:-MZBpX792dPP30DGAgTn:bzgku5t) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.h#L260)):*
> ```objc
>     Image CreateVertexMap(const core::Tensor &intrinsics, float invalid_fill);
> 
>     /// Create a normal map (H, W, 3) in Float32 from an image of (H, W, 3)
> ```

Same, we can use `rows, cols` for `H` and `W`.
___
*[cpp/open3d/t/geometry/Image.h, line 261 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBpXj24lqoU58yFM7f:-MZBpXj24lqoU58yFM7g:b-nvvog) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.h#L261)):*
> ```objc
> 
>     /// Create a normal map (H, W, 3) in Float32 from an image of (H, W, 3)
>     /// in Float32 using cross product of V(u, v+1)-V(u, v) and V(u+1, v)-V(u,
> ```

What are `V`, `u` and`v`? Do `u` and `v` mean `r` and `c`? Consider the standardized naming as well.
___
*[cpp/open3d/t/geometry/Image.h, line 270 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBgXFwDfCJYsjfAlrQ:-MZBgXFwDfCJYsjfAlrR:by4yjhn) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.h#L270)):*
> ```objc
> 
>     /// Colorize an input depth image with the Turbo colormap, rescaled within
>     /// (min_range, max_range)
> ```

If it is a closed interval, we can use `[min_range, max_range]`.

Also we can call it `min_value`, `max_value`, to be consistent with `ClipTransform()`.
___
*[cpp/open3d/t/geometry/Image.cpp, line 485 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBr9IU-YovbMb4Xjpn:-MZBr9IU-YovbMb4Xjpo:b3rwnqw) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.cpp#L485)):*
> ```cpp
>                 scale, min_value, max_value);
>     }
>     if (!(std::isnan(clip_fill) || std::isinf(clip_fill) || clip_fill == 0)) {
> ```

What if `clip_fill` is `Inf` but image type is `UInt16`? (`UInt16` doesn't have inf or nan)
___
*[cpp/open3d/t/geometry/Image.cpp, line 487 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBqzjrCsxSnn4Vw6f1:-MZBqzjrCsxSnn4Vw6f2:bih8mu0) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.cpp#L487)):*
> ```cpp
>     if (!(std::isnan(clip_fill) || std::isinf(clip_fill) || clip_fill == 0)) {
>         utility::LogWarning(
>                 "The clip_fill value {} is not recommended Inf, NaN or, 0",
> ```

```cpp
"The clip_fill value {} is not recommended, please use Inf, NaN or 0.",
```
___
*[cpp/open3d/t/geometry/Image.cpp, line 491 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZGS_Kt4UGkC28FvJ4C:-MZGS_Kt4UGkC28FvJ4D:b-egcscr) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.cpp#L491)):*
> ```cpp
>     }
> 
>     Image dst_im;
> ```

We can directly initialize the image:
```cpp
Image dst_im(rows, cols, channels, dtype, device);

```
___
*[cpp/open3d/t/geometry/Image.cpp, line 512 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZGSoL_642gi0BB1tYS:-MZGSoLa3Jy1Do7xWxAo:bi2xpbf) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.cpp#L512)):*
> ```cpp
>     }
> 
>     Image dst_im;
> ```

Same, we can directly initialize the image.
___
*[cpp/open3d/t/geometry/Image.cpp, line 532 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZGSpg_5NRQMeYPvdRs:-MZGSpg_5NRQMeYPvdRt:bi2xpbf) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.cpp#L532)):*
> ```cpp
>     }
> 
>     Image dst_im;
> ```

Same, we can directly initialize the image.
___
*[cpp/open3d/t/geometry/Image.cpp, line 558 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZGSq844A7aAEH8f-zg:-MZGSq844A7aAEH8f-zh:bi2xpbf) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.cpp#L558)):*
> ```cpp
>     }
> 
>     Image dst_im;
> ```

Same, we can directly initialize the image.
___
*[cpp/open3d/t/geometry/kernel/GeometryMacros.h, line 62 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZGT8YJEMEqkTaFUvxU:-MZGT8YJEMEqkTaFUvxV:b-tzf4s8) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L62)):*
> ```objc
> #endif
> 
> OPEN3D_HOST_DEVICE inline int sign(int x) {
> ```

`Sign`
___
*[cpp/pybind/t/geometry/image.cpp, line 180 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZGsrmv0xcjNkPAlwfB:-MZGsrmv0xcjNkPAlwfC:btwfrrv) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/pybind/t/geometry/image.cpp#L180)):*
> ```cpp
>     // Depth utilities.
>     image.def("clip_transform", &Image::ClipTransform,
>               "Preprocess a image of (H, W, 1), typically used for a depth "
> ```

same, use `rols, cols` to be consistent
same for other comments in this file
___
*[cpp/tests/t/geometry/Image.cpp, line 42 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZGt1Ea2p4M-GqtHmy3:-MZGt1Ea2p4M-GqtHmy4:b-308fpb) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/tests/t/geometry/Image.cpp#L42)):*
> ```cpp
> namespace tests {
> 
> core::Tensor CreateIntrinsics(float down_factor = 1.0f) {
> ```

`static` function

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3318)* status: all files reviewed, 15 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/t/geometry/Image.h, line 242 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBorbK6_7eR5tlXdls:-MZKucCkD5ft2u0dgqA_:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.h#L242)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We can call it `(rows, cols, 1)` to be consistent. See the docstring for `Image::Image()`.

The idea is to avoid the mixed-use of `H, W, x, y, u, v` which could be confusing. E.g., if we look at `x`, `y` by themselves, we don't know the coordinate orientation; but it is always clear what `r` and `c` means.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.h, line 250 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBePgr0Z1p6Y2Jw6S9:-MZKuhCK1CNoGw7x1UWZ:b-9o3qe0) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.h#L250)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

How do we deal with non-float images? I see we have some code enforcing the input dtype. We shall probably specify that in the comment. 

The same applies to the 4 functions. 
</blockquote></details>

Specified supported dtypes for all.
___
*[cpp/open3d/t/geometry/Image.h, line 252 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBp07D3lzr8K_ymgWo:-MZKullVDTDMazUqSKLj:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.h#L252)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Same, we can call it `(rows, cols, 3)`, `(rows, cols, 1)` to be consistent.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.h, line 260 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBpX792dPP30DGAgTm:-MZKuoot8M7Y4BWRaD2d:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.h#L260)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Same, we can use `rows, cols` for `H` and `W`.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.h, line 261 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBpXj24lqoU58yFM7f:-MZKupgmBiw8XbGoGHSv:bf03bql) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.h#L261)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

What are `V`, `u` and`v`? Do `u` and `v` mean `r` and `c`? Consider the standardized naming as well.
</blockquote></details>

u->r, v->c.
___
*[cpp/open3d/t/geometry/Image.h, line 270 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBgXFwDfCJYsjfAlrQ:-MZKuuQrDNG839KKm2H9:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.h#L270)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

If it is a closed interval, we can use `[min_range, max_range]`.

Also we can call it `min_value`, `max_value`, to be consistent with `ClipTransform()`.

</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.cpp, line 485 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBr9IU-YovbMb4Xjpn:-MZKuxWeC-98yJEYIfr_:b-zhm6qw) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.cpp#L485)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

What if `clip_fill` is `Inf` but image type is `UInt16`? (`UInt16` doesn't have inf or nan)
</blockquote></details>

In that case 0 should work. @thended ?
___
*[cpp/open3d/t/geometry/Image.cpp, line 487 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBqzjrCsxSnn4Vw6f1:-MZKvAyZ-K2jn4nYhkBL:bt2vr1b) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.cpp#L487)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

```cpp
"The clip_fill value {} is not recommended, please use Inf, NaN or 0.",
```

</blockquote></details>

Fixed.
___
*[cpp/open3d/t/geometry/Image.cpp, line 491 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZGS_Kt4UGkC28FvJ4C:-MZKvD1e7EfHJ-J3xj6q:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.cpp#L491)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We can directly initialize the image:
```cpp
Image dst_im(rows, cols, channels, dtype, device);

```
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.cpp, line 512 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZGSoL_642gi0BB1tYS:-MZKvET22C0LjPuVVtsd:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.cpp#L512)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Same, we can directly initialize the image.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.cpp, line 532 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZGSpg_5NRQMeYPvdRs:-MZKvFcmCW0WXzg_aHIm:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.cpp#L532)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Same, we can directly initialize the image.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.cpp, line 558 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZGSq844A7aAEH8f-zg:-MZKvGhi3Ljp9FqIbiLu:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.cpp#L558)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Same, we can directly initialize the image.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/kernel/GeometryMacros.h, line 62 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZGT8YJEMEqkTaFUvxU:-MZKvI9FAx6c-F_2C4A6:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L62)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`Sign`
</blockquote></details>

Done.
___
*[cpp/pybind/t/geometry/image.cpp, line 180 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZGsrmv0xcjNkPAlwfB:-MZKvLq4-dc2WniAdpzt:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/pybind/t/geometry/image.cpp#L180)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

same, use `rols, cols` to be consistent
same for other comments in this file
</blockquote></details>

Done.
___
*[cpp/tests/t/geometry/Image.cpp, line 42 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZGt1Ea2p4M-GqtHmy3:-MZKvNQ2EZKfxpBPia25:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/tests/t/geometry/Image.cpp#L42)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`static` function
</blockquote></details>

Done.

**Comment by reyanshsolis** [comment]
May we please add `\brief` and `\return` keywords, in the docstring, for `Image.h`?
Also, python unit tests for t::Image if possible.

**Review by yxlao — COMMENTED** [review]
LGTM after addressing this comment:

What if clip_fill is Inf but the image type is UInt16? (UInt16 doesn't have inf or nan)? In general, if `clip_fill` is out-of-the-range that is representable by the image type. 

> Reviewed 5 of 7 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3318#-:-MZUfOtVDSji9Bs2dTJY:bs2i6kz)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @theNded and @yxlao)

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3318)* status: 12 of 20 files reviewed, 1 unresolved discussion (waiting on @yxlao)

___
*[cpp/open3d/t/geometry/Image.cpp, line 485 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBr9IU-YovbMb4Xjpn:-MZY-Fin3a46MNIPoIvA:b-xpp7yz) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.cpp#L485)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

In that case 0 should work. @thended ?
</blockquote></details>

Clip fill is for the output. The output is always a Float32 image.

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3318)* status: 11 of 21 files reviewed, 3 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/t/geometry/Image.h, line 261 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBpXj24lqoU58yFM7f:-MZpZDnR9qHWO3T7mT5a:bi57bmm) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.h#L261)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

u->r, v->c.
</blockquote></details>

By convention it should be row - height - y - v; col - width - x - u, but this setup looks consistent
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 203 at r7](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZp_P759trbeTSksm_b:-MZp_P759trbeTSksm_c:bit1to8) ([raw file](https://github.com/intel-isl/open3d/blob/8d02201f91074167fb20fd99874bf4795b96bd17/cpp/open3d/t/geometry/PointCloud.cpp#L203)):*
> ```cpp
>                     ? 3
>                     : 5;
>     const float bilateral_value_sigma = depth_diff_threshold;
> ```

Empirically this should be large, like 5~10; 0.07 will result in almost a delta peak.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 225 at r7](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZp_kgk5EO0dO5G8IZW:-MZp_kgk5EO0dO5G8IZX:bxpueqr) ([raw file](https://github.com/intel-isl/open3d/blob/8d02201f91074167fb20fd99874bf4795b96bd17/cpp/open3d/t/geometry/PointCloud.cpp#L225)):*
> ```cpp
>     }
>     const int64_t im_size = depth.GetRows() * depth.GetCols();
>     depth = depth.FilterBilateral(bilateral_kernel_size, bilateral_value_sigma,
> ```

If it has been downsampled (i.e. stride >= 2), then bilateral filtering might not be required since PyrDownDepth has already done the job.

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3318)* status: 11 of 21 files reviewed, 3 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 203 at r7](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZp_P759trbeTSksm_b:-MZsR35CAD-k6uiVmyEI:bw8oyzo) ([raw file](https://github.com/intel-isl/open3d/blob/8d02201f91074167fb20fd99874bf4795b96bd17/cpp/open3d/t/geometry/PointCloud.cpp#L203)):*
> ```
> bilateral_value_sigma = depth_diff_threshold
> ```
Its set to default 10.0 now.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 225 at r7](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZp_kgk5EO0dO5G8IZW:-MZsQr124q98Sc6FlItA:b-p9bb5k) ([raw file](https://github.com/intel-isl/open3d/blob/8d02201f91074167fb20fd99874bf4795b96bd17/cpp/open3d/t/geometry/PointCloud.cpp#L225)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

If it has been downsampled (i.e. stride >= 2), then bilateral filtering might not be required since PyrDownDepth has already done the job.
</blockquote></details>

Updated so FilterBilateral is only enabled with stride=1

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3318)* status: 10 of 21 files reviewed, 1 unresolved discussion (waiting on @yxlao)

___
*[cpp/open3d/t/geometry/Image.cpp, line 485 at r2](https://reviewable.io/reviews/intel-isl/open3d/3318#-MZBr9IU-YovbMb4Xjpn:-MZt4QC8EYk5zg8E6KQ-:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6db7fb8ad3330e9a44ffb61207a40f024f987e5c/cpp/open3d/t/geometry/Image.cpp#L485)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Clip fill is for the output. The output is always a Float32 image.
</blockquote></details>

Done.

**Review by yxlao — APPROVED** [review]

**Pull request merged**
