### PR TITLE
ml-contrib subsample library

### PR DESCRIPTION
**Pull request by yxlao**
#### Use case
These are meant for temporary use to support with 3D-ML repo. They should be replaced by Open3D's own PointCloud subsampling methods in the future.

#### Review helper
- `cpp/open3d/ml/contrib/*`: 3rdparty code. Need to review CMake and directory structure. In particular, is this a good place to put the 3rdparty ML code?
- `cpp/pybind/ml/contrib.cpp`: main change. Includes our own python wrapper and input sanity checks.
- Related to `optional`: this PR introduces a back-ported C++17 `std::optional` as `open3d::utility::optional` to handle `None` parameter in pybind11.
- Unit tests: unit tests are dummy. @sanskar107 could you provide some unit tests in this PR or a separate PR?

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2254)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- python/test/ml/test_contrib.py  1
         

Clones added
============
- cpp/open3d/ml/contrib/GridSubsampling.h  4
- cpp/pybind/ml/contrib.cpp  8
- cpp/open3d/utility/Optional.h  4
- cpp/open3d/ml/contrib/GridSubsampling.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6092674&bid=19948496)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- python/test/ml/test_contrib.py  1
         

Clones added
============
- cpp/open3d/ml/contrib/GridSubsampling.cpp  2
- cpp/open3d/utility/Optional.h  4
- cpp/pybind/ml/contrib.cpp  8
- cpp/open3d/ml/contrib/GridSubsampling.h  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6092674&bid=19948496)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- python/test/ml/test_contrib.py  1
         

Clones added
============
- cpp/open3d/ml/contrib/GridSubsampling.h  4
- cpp/pybind/ml/contrib.cpp  8
- cpp/open3d/ml/contrib/GridSubsampling.cpp  2
- cpp/open3d/utility/Optional.h  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6092674&bid=19948496)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- python/test/ml/test_contrib.py  1
         

Clones added
============
- cpp/open3d/ml/contrib/GridSubsampling.cpp  2
- cpp/open3d/ml/contrib/GridSubsampling.h  4
- cpp/open3d/utility/Optional.h  4
- cpp/pybind/ml/contrib.cpp  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6092674&bid=19948496)

**Review by sanskar107 — COMMENTED** [review]
> Reviewed 16 of 19 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2254)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @benjaminum, @sanskar107, and @yxlao)

___
*[cpp/open3d/ml/CMakeLists.txt, line 14 at r2](https://reviewable.io/reviews/intel-isl/open3d/2254#-MG3DjSb27hg3mA1OSfR:-MG3DjSb27hg3mA1OSfS:b-jpknhv) ([raw file](https://github.com/intel-isl/open3d/blob/c781a0cdf457039d66218655ad303409edcba902/cpp/open3d/ml/CMakeLists.txt#L14)):*
> ```CMake
> endif ()
> 
> add_subdirectory(contrib)
> ```

Should we add this only if either of above ops are ON?

**Comment by sanskar107** [comment]
These `grid_subsampling.cpp`, and `cloud.cpp` are also present in `cpp/open3d/ml/impl/` in `o3dml_integration` branch and are used by TF ops. We have to decide which ones to keep. Should I remove them from `impl/` and use this one for TF ops?

**Review by benjaminum — COMMENTED** [review]
Yes, we have to consolidate the branches. Can we do the following?
1. Merge this PR to master (it contains some changes to core)
2. Merge master into o3dml_integration
3. Make the corresponding tf ops use the code in contrib.
4. Move remaining code to the respective contrib directories (having a contrib dir makes it easy to distinguish between our code and imported code)
5. Create a PR for o3dml_integration to master

Does this make sense @sanskar107 @yxlao ?

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2254#-:-MG3Q4XW7_AzSoZf69Kf:bqiabnl)* status: 18 of 19 files reviewed, 2 unresolved discussions (waiting on @benjaminum and @yxlao)

___
*[cpp/pybind/ml/contrib.cpp, line 368 at r2](https://reviewable.io/reviews/intel-isl/open3d/2254#-MG3Pw9lBSn7ZskcvZVO:-MG3Pw9lBSn7ZskcvZVP:bgxwea3) ([raw file](https://github.com/intel-isl/open3d/blob/c781a0cdf457039d66218655ad303409edcba902/cpp/pybind/ml/contrib.cpp#L368)):*
> ```cpp
> 
> void pybind_contrib(py::module& m) {
>     py::module m_contrib = m.def_submodule("contrib");
> ```

contrib namespace is a good idea!

**Comment by sanskar107** [comment]
Yes, sounds great to me. I'll add the unit tests in `o3dml_integration` branch.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/ml/test_contrib.py  17
         

Clones added
============
- cpp/open3d/ml/contrib/GridSubsampling.cpp  2
- python/test/ml/test_contrib.py  2
- cpp/pybind/ml/contrib.cpp  8
- cpp/open3d/ml/contrib/GridSubsampling.h  4
- cpp/open3d/utility/Optional.h  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6092674&bid=19948496)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/ml/test_contrib.py  17
         

Clones added
============
- cpp/open3d/ml/contrib/GridSubsampling.cpp  2
- cpp/open3d/utility/Optional.h  4
- cpp/pybind/ml/contrib.cpp  8
- python/test/ml/test_contrib.py  2
- cpp/open3d/ml/contrib/GridSubsampling.h  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6092674&bid=19948496)

**Pull request merged**
