### PR TITLE
pybind for tpoincloud

### PR DESCRIPTION
**Pull request by yxlao**
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2229)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- python/test/tgeometry/test_pointcloud.py  11
- python/test/tgeometry/test_tensorlistmap.py  9
         

Clones added
============
- cpp/pybind/tgeometry/geometry.h  1
- cpp/tests/tgeometry/PointCloud.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6065699&bid=19865513)

**Review by griegler — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2229)* status: all files reviewed, 1 unresolved discussion (waiting on @theNded and @yxlao)

___
*[python/test/tgeometry/test_pointcloud.py, line 46 at r1](https://reviewable.io/reviews/intel-isl/open3d/2229#-MFZhSYYEOZtfh7l52QB:-MFZhSYYEOZtfh7l52QC:b-fcitmy) ([raw file](https://github.com/intel-isl/open3d/blob/b10086d4b573799bda774abb4a0a6513c224308b/python/test/tgeometry/test_pointcloud.py#L46)):*
> ```Python
>     # Assignment.
>     pcd.point["points"] = o3c.TensorList(o3c.SizeVector([3]), dtype, device)
>     pcd.point["colors"] = o3c.TensorList(o3c.SizeVector([3]), dtype, device)
> ```

Is there a way in pybind to modify the `__dict__` of `pcd` in the sense that we can use `pcd.points` and `pcd_point_colors` directly? Or do we have to use a Python wrapper as we have for Tensor?

**Review by griegler — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2229)* status: all files reviewed, 1 unresolved discussion (waiting on @theNded and @yxlao)

___
*[python/test/tgeometry/test_pointcloud.py, line 46 at r1](https://reviewable.io/reviews/intel-isl/open3d/2229#-MFZhSYYEOZtfh7l52QB:-MFZnZBKEkvszYyJHkEO:bno6nnq) ([raw file](https://github.com/intel-isl/open3d/blob/b10086d4b573799bda774abb4a0a6513c224308b/python/test/tgeometry/test_pointcloud.py#L46)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

If your question is whether we can edit a 3D point directly, the answer is yes, e.g.

```python
pcd = o3d.tgeometry.PointCloud(dtype, device)
pcd.point["points"].push_back(one_point)

# Modify a tensor in tensorlist
pcd.point["points"][0] = o3c.Tensor([1, 2, 3], dtype, device)
assert pcd.point["points"][0].allclose(o3c.Tensor([1, 2, 3], dtype, device))
```

However, some python specific `Tensor` functions are implemented in the python wrapper in `core.py`, and not in C++ pybind. We need to cast `open3d.pybind.core.Tensor` to `open3d.core.Tensor` (pure python wrapper). 

```python
pcd.point["points"][0][1] = 100                     # won't work for now
cast_to_py_tensor(pcd.point["points"][0])[1] = 100  # works
```

The `cast_to_py_tensor` is used in `core.py` for conversion. Ideally, we shall figure out a way to avoid `cast_to_py_tensor` in PointCloud and subsequent classes, otherwise, we have to write a `PointCloud.py` python wrapper which is not ideal. Regardless, I plan to address this in a separate PR, as it may require changing some more code in the Tensor pybind code.
</blockquote></details>

No, I was referring to changing/adding

```python
pcd.point["points"] = tensor_with_points
pcd.point["normals"] = tensor_with_normals
```

to 

```python
pcd.points = tensor_with_points
pcd.point_normals = tensor_with_normals
```

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- python/test/open3d_test.py  2
- python/test/tgeometry/test_tensorlistmap.py  9
- python/test/tgeometry/test_pointcloud.py  12
         

Clones added
============
- cpp/pybind/tgeometry/geometry.h  1
- cpp/tests/tgeometry/PointCloud.cpp  2
- python/test/tgeometry/test_tensorlistmap.py  1
- python/test/tgeometry/test_pointcloud.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6065699&bid=19865513)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- python/test/tgeometry/test_tensorlistmap.py  9
- python/test/tgeometry/test_pointcloud.py  12
- python/test/open3d_test.py  2
         

Clones added
============
- cpp/tests/tgeometry/PointCloud.cpp  2
- cpp/pybind/tgeometry/geometry.h  1
- python/test/core/test_tensorlist.py  2
- python/test/tgeometry/test_tensorlistmap.py  2
- python/test/tgeometry/test_pointcloud.py  2
         

Clones removed
==============
+ python/test/core/test_linalg.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6065699&bid=19865513)

**Review by griegler — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2229)* status: all files reviewed, 3 unresolved discussions (waiting on @theNded and @yxlao)

___
*[python/test/open3d_test.py, line 33 at r3](https://reviewable.io/reviews/intel-isl/open3d/2229#-MFa6osC-FZhGmQiC_Mg:-MFa6osD2m0SZFjwxWVh:b-4q7x6v) ([raw file](https://github.com/intel-isl/open3d/blob/17162bf04cc67bb5ac9ca3fac608c7881ff194ca/python/test/open3d_test.py#L33)):*
> ```Python
>     """
>     import open3d as o3d
>     devices = [o3d.core.Device("CPU:" + str(0))]
> ```

why not `"CPU:0"` instead using `str(0)` ?
___
*[python/test/open3d_test.py, line 34 at r3](https://reviewable.io/reviews/intel-isl/open3d/2229#-MFa73yA1oG7nD-hqSST:-MFa73yA1oG7nD-hqSSU:b-ryonii) ([raw file](https://github.com/intel-isl/open3d/blob/17162bf04cc67bb5ac9ca3fac608c7881ff194ca/python/test/open3d_test.py#L34)):*
> ```Python
>     import open3d as o3d
>     devices = [o3d.core.Device("CPU:" + str(0))]
>     if torch_available() and o3d._build_config['BUILD_CUDA_MODULE']:
> ```

is this a general `list_devices` function? If yes, why ask if `torch` is available? If not, I would rename it.
___
*[python/test/tgeometry/test_pointcloud.py, line 46 at r1](https://reviewable.io/reviews/intel-isl/open3d/2229#-MFZhSYYEOZtfh7l52QB:-MFa7Wl5DIgzf4Ij0yD0:b-tz0rxz) ([raw file](https://github.com/intel-isl/open3d/blob/b10086d4b573799bda774abb4a0a6513c224308b/python/test/tgeometry/test_pointcloud.py#L46)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Technically that should be possible, we can provide getter/setter functions and let pybind treat it as an attribute.

However, I believe the python users are more used to the "typeless" nature of python objects. So keeping them as dictionaries is my preference since the syntax is much simpler and more consistent.

E.g. i would rather use:
```python
pcd.ponit["points"]
pcd.ponit["normals"]
pcd.ponit["labels"]
```

compared to:
```python
pcd.ponits
pcd.ponit_normals
pcd.ponit["labels"]
```
</blockquote></details>

I strongly prefer the latter (`points.points` and `pcd.point_normals`) for level 0 and level 1 types. It looks nicer, is less to type and would make the distinction clear. Of course, the user can still use the dict if he likes.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- python/test/tgeometry/test_pointcloud.py  12
- python/test/tgeometry/test_tensorlistmap.py  9
         

Clones added
============
- cpp/pybind/tgeometry/geometry.h  1
- cpp/tests/tgeometry/PointCloud.cpp  2
- python/test/tgeometry/test_pointcloud.py  2
- python/test/core/test_tensorlist.py  2
- python/test/tgeometry/test_tensorlistmap.py  2
         

Clones removed
==============
+ python/test/core/test_linalg.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6065699&bid=19865513)

**Pull request merged**
