### PR TITLE
Alt-Enter to toggle Fullscreen mode

### PR DESCRIPTION
**Pull request by sammo2828**
Can't Reopen the original pull request #1393, so creating a new one.

@yxlao requested some changes previously, so lets's continue the discussino.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1939)

### CODE REVIEW

**Comment by sammo2828** [comment]
https://github.com/intel-isl/Open3D/pull/1393#pullrequestreview-354219485
> I would call do `ToggleFullScreen` without argument, just like other `Toggle` methods in this class.

Added `ToggleFullScreen` https://github.com/intel-isl/Open3D/pull/1939/commits/32b8ee0f74f73ececc22494b067127e9c55037e2. Kept the existing `SetFullScreen`, which is also useful, and similar to `ToggleEditing` / `SetEditingMode`.

**Comment by sammo2828** [comment]
https://github.com/intel-isl/Open3D/pull/1393#pullrequestreview-354219485
> Add a helper message here for the full-screen mode.

Added helper message for full screen toggle https://github.com/intel-isl/Open3D/pull/1939/commits/520b81b3881fa8f4c150bbfd5203bf7e62d46ec7.

**Comment by sammo2828** [comment]
https://github.com/intel-isl/Open3D/pull/1393#pullrequestreview-354219485 @yxlao requested:

> Use `Eigen` here to be consistent with the rest of the library.
> 
> > ```objc
> > #include <GL/glew.h>
> > #include <GLFW/glfw3.h>
> > #include <array>
> > ```
> 
Not sure what this means. Do you mean I should use `Eigen::Array` instead of `<array>`? Can you show me what to change?

Note that `#include <array>` is also used in `TetraMesh.cpp` and `RendererHandle.h`.

**Comment by sammo2828** [comment]
Hey @yxlao @germanros1987 
What's breaking CI?

**Comment by germanros1987** [comment]
Sorry about that. The new CI seems to work fine @sammo2828 . Could you solve the new conflicts? Sorry again for the delay.

**Comment by germanros1987** [comment]
@sammo2828 please run the style check and apply the style to your code.

**Comment by sammo2828** [comment]
@germanros1987 how does this look now?

**Comment by sammo2828** [comment]
Hello @germanros1987 @yxlao ! Bumping this again. I just want to get it closed :)

**Comment by yxlao** [comment]
Thanks @sammo2828 for the contribution! Sorry for the delays.

**Review by yxlao — APPROVED** [review]

**Pull request merged**
