### PR TITLE
Updated ICP Demos.

### PR DESCRIPTION
**Pull request by reyanshsolis**
Changes:
- Camera follows `current scan` bounding box in ICPOdometry Example.
image

- Reduced `download_kitti.py` sequence options to only tested once.
- Upgraded the `ICPReconstruction` Example, with new GUI: `resume/pause` button, `delay` slider.
image

_____
Update:
- Fixed Color issue:
Before:
Screenshot from 2021-05-22 20-21-10

After:
Screenshot from 2021-05-22 20-19-42

Reason: `UInt8 was getting converted to Float32 directly.`

---

This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3463)

### CODE REVIEW

**Review by theNded — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3463)* status: all files reviewed, 4 unresolved discussions (waiting on @errissa and @reyanshsolis)

___
*[examples/cpp/TICPOdometry.cpp, line 658 at r1](https://reviewable.io/reviews/intel-isl/open3d/3463#-Ma0Eolm5CLZUP7Y_ngQ:-Ma0Eolm5CLZUP7Y_ngR:b-9yeco6) ([raw file](https://github.com/intel-isl/open3d/blob/b1772add4c2ef548de9333554f9343ec50d073f0/examples/cpp/TICPOdometry.cpp#L658)):*
> ```cpp
> 
>         geometry::AxisAlignedBoundingBox bbox_;
>     } pcd_;
> ```

Better rename? scan + bbox as a pcd could be misleading
___
*[examples/cpp/TICPReconstruction.cpp, line 87 at r1](https://reviewable.io/reviews/intel-isl/open3d/3463#-Ma0GbOw7CmL4LXXIWoY:-Ma0GbOw7CmL4LXXIWoZ:b-si6htd) ([raw file](https://github.com/intel-isl/open3d/blob/b1772add4c2ef548de9333554f9343ec50d073f0/examples/cpp/TICPReconstruction.cpp#L87)):*
> ```cpp
>     }
> 
>     void AddFloatSlider(const std::string& name,
> ```

Maybe remove unused functions?
@prewettg is it possible that we somehow expose these APIs, so that they can be shared between files? Could be done later.
___
*[examples/cpp/TICPReconstruction.cpp, line 328 at r1](https://reviewable.io/reviews/intel-isl/open3d/3463#-Ma0FvVp17olAZaAjTVe:-Ma0FvVp17olAZaAjTVf:b-8e4gbo) ([raw file](https://github.com/intel-isl/open3d/blob/b1772add4c2ef548de9333554f9343ec50d073f0/examples/cpp/TICPReconstruction.cpp#L328)):*
> ```cpp
>                 std::make_shared<PropertyPanel>(spacing, left_margin);
>         adjustable_props_->AddIntSlider(" Delay (ms)", &delay_, 100, 10, 500,
>                                         "Time delay between ICP iterations.");
> ```

Could be 'animation interval between iterations'? Delay might be less straightforward.
___
*[examples/cpp/registration_example_util/download_kitti.py, line 65 at r1](https://reviewable.io/reviews/intel-isl/open3d/3463#-Ma0GVk-BZxWPFcda29-:-Ma0GVk0EAvxow4diIvj:b-azksc4) ([raw file](https://github.com/intel-isl/open3d/blob/b1772add4c2ef548de9333554f9343ec50d073f0/examples/cpp/registration_example_util/download_kitti.py#L65)):*
> ```Python
>     filenames = get_file_list(source_folder, ".bin")
> 
>     print("Converting .bin to .ply files and pre-processing from frame " +
> ```

Use formatted string?

**Review by theNded — COMMENTED** [review]
LGTM. It would be good to attach a screenshot in the PR.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3463#-:-Ma0Gs8N2Ins7wz9DWck:b-nn02yc)* status: all files reviewed, 4 unresolved discussions (waiting on @errissa and @reyanshsolis)

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3463)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @errissa, @prewettg, and @theNded)

___
*[examples/cpp/TICPOdometry.cpp, line 658 at r1](https://reviewable.io/reviews/intel-isl/open3d/3463#-Ma0Eolm5CLZUP7Y_ngQ:-Ma0YdfMEah0tBoJyng7:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/b1772add4c2ef548de9333554f9343ec50d073f0/examples/cpp/TICPOdometry.cpp#L658)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Better rename? scan + bbox as a pcd could be misleading
</blockquote></details>

Done.
___
*[examples/cpp/TICPReconstruction.cpp, line 87 at r1](https://reviewable.io/reviews/intel-isl/open3d/3463#-Ma0GbOw7CmL4LXXIWoY:-Ma0YemPCDT__TFHl_Fq:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/b1772add4c2ef548de9333554f9343ec50d073f0/examples/cpp/TICPReconstruction.cpp#L87)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Maybe remove unused functions?
@prewettg is it possible that we somehow expose these APIs, so that they can be shared between files? Could be done later.
</blockquote></details>

Done.
___
*[examples/cpp/TICPReconstruction.cpp, line 328 at r1](https://reviewable.io/reviews/intel-isl/open3d/3463#-Ma0FvVp17olAZaAjTVe:-Ma0YgHc8_iF_y8tAgxS:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/b1772add4c2ef548de9333554f9343ec50d073f0/examples/cpp/TICPReconstruction.cpp#L328)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Could be 'animation interval between iterations'? Delay might be less straightforward.
</blockquote></details>

Done.
___
*[examples/cpp/registration_example_util/download_kitti.py, line 65 at r1](https://reviewable.io/reviews/intel-isl/open3d/3463#-Ma0GVk-BZxWPFcda29-:-Ma0YgqS0GM3sTDP0zH7:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/b1772add4c2ef548de9333554f9343ec50d073f0/examples/cpp/registration_example_util/download_kitti.py#L65)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Use formatted string?
</blockquote></details>

Done.

**Review by theNded — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3463)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @errissa)

**Pull request merged**
