### PR TITLE
GCE GPU CI docker (PyTorch + cuDNN)

### PR DESCRIPTION
**Pull request by ssheorey**
Entire CI run takes ~25-30 minutes and runs build configurations in parallel.
### Tasks:
- [x] Build docker image on GitHub, push to google container registry, create VM, run CI in docker container. Delete VM and docker image.
- [x] If resources are available, can handle up to 13 simultaneous commit CI runs (one per GCE US zone with Tesla T4 GPUs). For simultaneous commits, will run into quota limit in one zone and switch to next zone.
- [x] Update CI TF version from 2.0 -> 2.3
- [x] Test and enable Pytorch + cuDNN: Need cuDNN detection or auto-install.
- [ ] Add build config with Ubuntu 20.04: Linker error with Filament.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2211)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6048928&bid=19816474)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6048928&bid=19816474)

**Comment by ssheorey** [comment]
Out of space error in GHA for one Ubuntu test.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6048928&bid=19816474)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6048928&bid=19816474)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6048928&bid=19816474)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6048928&bid=19816474)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6048928&bid=19816474)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6048928&bid=19816474)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6048928&bid=19816474)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6048928&bid=19816474)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6048928&bid=19816474)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6048928&bid=19816474)

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2211)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @benjaminum and @yxlao)

___
*[util/install_deps_ubuntu.sh, line 5 at r6](https://reviewable.io/reviews/intel-isl/open3d/2211#-MFEu2gd5T2a9231wYuY:-MGFztvN7ZSm8kAMy7qy:b-n7719n) ([raw file](https://github.com/intel-isl/open3d/blob/e2b2c18a29b49f3066138e8317c84bbd6bb0f653/util/install_deps_ubuntu.sh#L5)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I went with your original suggestion. CUDA and CUDNN install are now moved to `util/run_ci.sh`. CUDA 10.1 pulls in cuBLAS 10.2 which gets installed in a different folder `/usr/local/cuda-10.2` and is not found by cmake. So I create symlinks from cuda-10.2 -> cuda10.1. Since this is pretty hacky, I removed it from `install_deps_ubuntu.sh`

**Pull request merged**
