### PR TITLE
Refactor contrib_nns

### PR DESCRIPTION
**Pull request by junha-l**
TODO
- [x] remove unnecessary data type conversion for dataset_points and query_points.
- [x] ~~remove unneccesary data type conversion for result inddices.~~
- [x] remove OpenMP block after PR#2305 get merged
- [x] implement prefix-sum for bathced radius search

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2337)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         

Clones removed
==============
+ cpp/pybind/ml/contrib/contrib_nns.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6180294&bid=20171988)

**Comment by junha-l** [comment]
Hi @yxlao 
This PR refactors ml/contrib_nns with new version of NanoFlannIndex class 

I have two questions 
1. Do the result indices have to be Int32 type? Currently, the default data type of indices in NanoFlannIndex is Int64 and we can not select the data type for indices using template variable. I think we need to change the contrib_nns to return Int64 indices or change NanoFlannIndex to return Int32 indices.

2. I assume that the reason why we need prefix sum in radius search is for returning compact, 1D indices tensor, rather than returning 2D tensor with unnecessary -1 elements. Is it correct?

**Comment by yxlao** [comment]
> Do the result indices have to be Int32 type? Currently, the default data type of indices in NanoFlannIndex is Int64 and we can not select the data type for indices using template variable. I think we need to change the contrib_nns to return Int64 indices or change NanoFlannIndex to return Int32 indices.

Returning `Int32` is actually requested by the ML team. So we need to perform a conversion from F64 to F32.

> I assume that the reason why we need prefix sum in radius search is for returning compact, 1D indices tensor, rather than returning 2D tensor with unnecessary -1 elements. Is it correct?

Yeah, having the prefix sum, we can compute the batching offsets more easily. But same as above, the `-1` is needed to satisfy the requested format by the ML team. So we can keep it as it is.

**Comment by junha-l** [comment]
seems that we need to link tbb to pybind target. 
I tried to follow the process of linking openmp, but I can't find the cmake script of it

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/ml/contrib/contrib_nns.cpp  2
         

Clones removed
==============
+ cpp/pybind/ml/contrib/contrib_nns.cpp  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6180294&bid=20171988)

**Comment by junha-l** [comment]
Hi @benjaminum 
I have an error while compiling a code that includes ```InclusivePrefixSum``` function in "open3d/utility/ParallelScan.h"

It says that tbb/parallel_for file is not found and it occurred only on MacOS and Windows. 
Do you have any idea?

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/ml/contrib/contrib_nns.cpp  2
         

Clones removed
==============
+ cpp/pybind/ml/contrib/contrib_nns.cpp  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6180294&bid=20171988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/ml/contrib/contrib_nns.cpp  2
         

Clones removed
==============
+ cpp/pybind/ml/contrib/contrib_nns.cpp  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6180294&bid=20171988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/ml/contrib/contrib_nns.cpp  2
         

Clones removed
==============
+ cpp/pybind/ml/contrib/contrib_nns.cpp  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6180294&bid=20171988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/ml/contrib/contrib_nns.cpp  2
         

Clones removed
==============
+ cpp/pybind/ml/contrib/contrib_nns.cpp  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6180294&bid=20171988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/ml/contrib/contrib_nns.cpp  2
         

Clones removed
==============
+ cpp/pybind/ml/contrib/contrib_nns.cpp  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6180294&bid=20171988)

**Review by yxlao — APPROVED** [review]
> Reviewed 1 of 5 files at r9, 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2337)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @benjaminum)

**Pull request merged**
