### PR TITLE
TSDF OpenMP Optimisations. + UniformTSDFVolume data access [#3152]

### PR DESCRIPTION
**Pull request by reyanshsolis**
Fixing PR #3152 and adding missing OpenMP pragma to other TSDF functions.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3423)

### CODE REVIEW

**Review by sam598 — APPROVED** [review]
Appreciated and approved.

**Comment by reyanshsolis** [comment]
@theNded may you please verify changes. 

@sam598 I will let you know, once the changes are added, and you may then pull this branch in yours (maybe re-base). We would then like to merge your branch directly to our master.

**Review by theNded — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3423)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @reyanshsolis)

**Comment by reyanshsolis** [comment]
@sam598 please merge this to your branch, then also merge the master, and let me know. 
Thanks!

**Pull request merged**
