### PR TITLE
Gui Rendering docs build

### PR DESCRIPTION
**Pull request by ssheorey**
Fix pip version in docs build to prevent policy change
uninstall Open3d before rebuilding with GUI
doxygen typo fixes
Realsense tutorial video

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2808)

### CODE REVIEW

**Comment by ssheorey** [comment]
@errissa Please download and review the documentation artifact from the CI.

**Review by yxlao — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2808)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @errissa and @germanros1987)

**Comment by yxlao** [comment]
LGTM, does this fix the empty gui/rendering doc problem?

**Comment by ssheorey** [comment]
> LGTM, does this fix the empty gui/rendering doc problem?

Yes, you can see the gui/rendering docs here: https://github.com/intel-isl/Open3D/suites/1713630432/artifacts/32360705

The problem was that pip would refuse to re-install the GUI Open3D python package over the headless one without forcing. So the 2nd make_docs run would still use the build without GUI. This PR fixes the pip version to prevent behaviour changes and uninstalls the headless open3d python package before building it with GUI.

**Review by errissa — APPROVED** [review]

**Pull request merged**
