### PR TITLE
Update faiss_build.cmake

### PR DESCRIPTION
**Pull request by junha-l**
Update pointer to faiss for resolving build error on RTX30xx

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2979)

### CODE REVIEW

**Comment by yxlao** [comment]
@junha-l sent an invite to you for https://github.com/intel-isl/faiss, could you try pushing to it? Moving this forked repo would make it easier to maintain. Thanks!

**Comment by ssheorey** [comment]
Hi @junha-l when building with `WITH_FAISS=OFF`, we get these failing C++ unit tests:

> [  FAILED  ] 5 tests, listed below:
> [  FAILED  ] NearestNeighborSearch/NNSPermuteDevices.KnnSearch/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
> [  FAILED  ] NearestNeighborSearch/NNSPermuteDevices.HybridSearch/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
> [  FAILED  ] Registration/RegistrationPermuteDevices.EvaluateRegistration/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
> [  FAILED  ] Registration/RegistrationPermuteDevices.RegistrationICPPointToPoint/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
> [  FAILED  ] Registration/RegistrationPermuteDevices.RegistrationICPPointToPlane/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>

The error is always the same:

> C++ exception with description "In function bool open3d::core::nns::NearestNeighborSearch::HybridIndex():
> /home/ssheorey/Documents/Open3D/Code/Open3D/cpp/open3d/core/nns/NearestNeighborSearch.cpp:88 [Open3D Error] [NearestNeighborSearch::HybridIndex] Currently, Faiss is disabled. Please recompile Open3D with WITH_FAISS=ON." thrown in the test body.

Can you disable / update these tests for this case?

**Comment by junha-l** [comment]
> @junha-l sent an invite to you for https://github.com/intel-isl/faiss, could you try pushing to it? Moving this forked repo would make it easier to maintain. Thanks!

I pushed the patch to this fork and updated the pointer in cmake

**Comment by junha-l** [comment]
> Hi @junha-l when building with `WITH_FAISS=OFF`, we get these failing C++ unit tests:
> 
> > [  FAILED  ] 5 tests, listed below:
> > [  FAILED  ] NearestNeighborSearch/NNSPermuteDevices.KnnSearch/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
> > [  FAILED  ] NearestNeighborSearch/NNSPermuteDevices.HybridSearch/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
> > [  FAILED  ] Registration/RegistrationPermuteDevices.EvaluateRegistration/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
> > [  FAILED  ] Registration/RegistrationPermuteDevices.RegistrationICPPointToPoint/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
> > [  FAILED  ] Registration/RegistrationPermuteDevices.RegistrationICPPointToPlane/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
> 
> The error is always the same:
> 
> > C++ exception with description "In function bool open3d::core::nns::NearestNeighborSearch::HybridIndex():
> > /home/ssheorey/Documents/Open3D/Code/Open3D/cpp/open3d/core/nns/NearestNeighborSearch.cpp:88 [Open3D Error] [NearestNeighborSearch::HybridIndex] Currently, Faiss is disabled. Please recompile Open3D with WITH_FAISS=ON." thrown in the test body.
> 
> Can you disable / update these tests for this case?

Updated. 
The tests that require Faiss are now disabled if ```WITH_FAISS=OFF```

**Review by yxlao — APPROVED** [review]

**Comment by reyanshsolis** [comment]
> WITH_FAISS=OFF

@yxlao Is this `WITH_FAISS=OFF` condition, also covered in our CI testing? If not, I will keep this in mind to test it separately on PR related to the failing unit tests with `WITH_FAISS=OFF`.

**Pull request merged**
