### PR TITLE
Implementation of Ball Pivoting algorithm

### PR DESCRIPTION
**Pull request by griegler**
Includes:
* Implementation of BPA
* Example script on some synthetic point clouds
* New intersection tests in IntersectionTests
* Some unit tests

Addresses #1056 and #270,

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1130)

### CODE REVIEW

**Comment by qianyizh** [comment]
This is awesome. I have been wanting it for a very very long time :D

**Comment by ibrahimLearning** [comment]
@yxlao @benjaminum @griegler 
Anyone tell me please for point cloud data with x y z x_nromal y_normal z_normal, How can I generate the points for ball pivoting algorithm?
Because in this case I am confused about the loop?

```
 for x in range(4):
        for y in range(4):
            points.append((np.random.uniform(-2, 2), np.random.uniform(-2,
```
Thanks

**Comment by griegler** [comment]
@ibrahimLearning sorry, but I do not get your question. You already have a point cloud with points and normals? Then it should be straight forward to use this algorithm? Where does this code snippet come from?
On another note, for questions it would be better to open an issue.

**Comment by ibrahimLearning** [comment]
@griegler 
TriangleSurface

Thank you very much for your reply. I think you can solve this problem. Please see the image below after calling ball pivoting algorithm, why all points are not connected?:

**Comment by griegler** [comment]
Maybe the normals do not agree (pointing to the same direction).

**Pull request merged**
