### PR TITLE
python-based parallel style check for py/cpp/jupyter

### PR DESCRIPTION
**Pull request by yxlao**
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2003)

### Usage
Same as before:
```shell
make check-style
make apply-style
```

### Added Jupyter support
Now supports:
```
.py
.ipynb
.cpp
.h
.cu
.cuh
```

### Faster formatting
```shell
(open3d3) ➜  ~/repo/Open3D (yixing/faster-style) python util/scripts/check_style.py
Checking C++/CUDA style...
Formatting takes 3.05s
Checking Python style...
Formatting takes 1.59s
Checking Jupyter style...
Formatting takes 0.35s
```

```shell
(open3d3) ➜  ~/repo/Open3D (yixing/faster-style) python util/scripts/check_style.py --no_parallel
Checking C++/CUDA style...
Formatting takes 18.61s
Checking Python style...
Formatting takes 7.75s
Checking Jupyter style...
Formatting takes 1.10s
```

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- util/scripts/check_style.py  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5754295&bid=18836666)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- util/scripts/check_style.py  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5754295&bid=18836666)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- util/scripts/check_style.py  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5754295&bid=18836666)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- util/scripts/check_style.py  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5754295&bid=18836666)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- util/scripts/check_style.py  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5754295&bid=18836666)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- util/scripts/check_style.py  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5754295&bid=18836666)

**Comment by yxlao** [comment]
- Intentionally introduced style error, `check-style` works as expected:
https://travis-ci.org/github/intel-isl/Open3D/jobs/701909261#L1718-L1724

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- util/scripts/check_style.py  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5754295&bid=18836666)

**Pull request merged**
