### PR TITLE
[Draft] Faiss Integration

### PR DESCRIPTION
**Pull request by junha-l**
Initial pull requests for integrating Faiss into Open3D

### Functionality

- Insert Faiss into Open3D build pipeline

- KnnFaiss module for brute force nearest neighbor search

- Connect open3d Tensor with KnnFaiss module

- Python bindings

- UnitTests

### To Do

- [x] Resolve segmentation fault when using Faiss with GPU Tensor

- [x] Implement GPU resource allocator API between Open3D and Faiss

- [x] Download pre-compiled OpenBlas in OSX

- [x] Add CMake script to download precompiled Faiss (Ubuntu/With CUDA)

- [x] Add CMake script to download precompiled Faiss (Ubuntu/Without CUDA)

- [x] Add CMake script to download precompiled Faiss (OSX/Without CUDA)

- [x] Disable Faiss related codes in Windows

- [ ] Resolve CI errors

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2077)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/geometry/KnnFaiss.cpp  4
- cpp/tests/geometry/KnnFaiss.cpp  21
- cpp/pybind/geometry/knnfaiss.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by yxlao** [comment]
I would recommend implementing new features in the TODO list in future PRs. For this PR, let's focus on the build system and passing all unit tests.

For the build system, I have two major concerns:
1. The dependency of OpenBLAS is installed on Ubuntu, but not on macOS and Windows. We need to fix this. There are two approaches.
    - Build OpenBLAS from source. If you choose this approach, here's a working example of building OpenBLAS from source (ubuntu,mac but not windows): https://github.com/intel-isl/Open3D/compare/yixing/openblas-cmake.
    - Download pre-compiled OpenBLAS library.
2. Even if building in all OSes is successful, the build time is still very high (currently 60 mins for CI). So potentially the download pre-compiled FAISS can be an option.
    - Here's the example of how we integrate with Filament: https://github.com/intel-isl/Open3D/tree/master/3rdparty/filament , where both options to compile from source and download pre-compiled binary are provided. 
    - You may also use the `FetchContent_Declare` CMake command for downloading the files.

**Comment by junha-l** [comment]
1. Got it. I’ll update install-deps-{macos,windows}
2. Yes. The Faiss compilation seems too slow. I’ll take a look at the examples you shared

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/tests/geometry/KnnFaiss.cpp  21
- python/test/test_faiss.py  1
- cpp/open3d/geometry/KnnFaiss.cpp  7
- cpp/pybind/geometry/knnfaiss.cpp  6
- cpp/open3d/geometry/NearestNeighborSearch.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by junha-l** [comment]
I have some questions

1. For windows, is every 3rdparty dependencies compiled from source? I can't find any script to download pre-compiled dependencies for the windows

2. It seems that the [Faiss](https://github.com/facebookresearch/faiss/releases) does not provide pre-compiled library. How should I do?

**Comment by yxlao** [comment]
> For windows, is every 3rdparty dependencies compiled from source?

Roughly speaking yes. For libraries like filament, a pre-compiled binary is downloaded on Windows.

> It seems that the Faiss does not provide pre-compiled library. How should I do?

1. Compile Faiss across the different OS separately.
    - Preferably, compile Faiss to one static library. Static library is much easier to integrate.
    - Also, provide the scripts for compiling Fiass.
    - For the time being, we can assume CUDA 10 should be used. For earlier CUDA versions, throw a cmake error. We can add more versions later.
    - Provide the scripts on how to compile Fiass.
2. Upload to a web hosting service such as Google Cloud.
    - Example for FIlament: https://github.com/intel-isl/Open3D/pull/2085/files.
    - When debugging, `FetchContent_Declare()`'s `URL` parameter can also point to a local file.
    - After the local file URL is working, send the pre-compiled binaries to us and we'll upload them to Google Cloud.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/open3d/geometry/KnnFaiss.cpp  5
- python/test/test_faiss.py  1
- cpp/open3d/geometry/NearestNeighborSearch.cpp  1
- cpp/tests/geometry/KnnFaiss.cpp  21
- cpp/pybind/geometry/knnfaiss.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- python/test/test_faiss.py  1
- cpp/open3d/geometry/KnnFaiss.cpp  5
- cpp/open3d/geometry/NearestNeighborSearch.cpp  1
- cpp/tests/geometry/KnnFaiss.cpp  21
- cpp/pybind/geometry/knnfaiss.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/open3d/geometry/KnnFaiss.cpp  4
- cpp/tests/geometry/KnnFaiss.cpp  21
- python/test/test_faiss.py  1
- cpp/pybind/geometry/knnfaiss.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/open3d/geometry/KnnFaiss.cpp  4
- cpp/pybind/geometry/knnfaiss.cpp  6
- cpp/tests/geometry/KnnFaiss.cpp  21
- python/test/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/pybind/geometry/knnfaiss.cpp  6
- cpp/tests/geometry/KnnFaiss.cpp  21
- cpp/open3d/geometry/KnnFaiss.cpp  4
- python/test/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/pybind/geometry/knnfaiss.cpp  6
- python/test/test_faiss.py  1
- cpp/open3d/geometry/KnnFaiss.cpp  4
- cpp/tests/geometry/KnnFaiss.cpp  21
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/tests/geometry/KnnFaiss.cpp  21
- cpp/pybind/geometry/knnfaiss.cpp  6
- cpp/open3d/geometry/KnnFaiss.cpp  4
- python/test/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/pybind/geometry/knnfaiss.cpp  6
- cpp/tests/geometry/KnnFaiss.cpp  21
- cpp/open3d/geometry/KnnFaiss.cpp  4
- python/test/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/pybind/geometry/knnfaiss.cpp  6
- python/test/test_faiss.py  1
- cpp/open3d/geometry/KnnFaiss.cpp  4
- cpp/tests/geometry/KnnFaiss.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/open3d/geometry/KnnFaiss.cpp  4
- cpp/pybind/geometry/knnfaiss.cpp  6
- cpp/tests/geometry/KnnFaiss.cpp  9
- python/test/test_faiss.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/pybind/geometry/knnfaiss.cpp  6
- python/test/test_faiss.py  1
- cpp/open3d/geometry/KnnFaiss.cpp  4
- cpp/tests/geometry/KnnFaiss.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/tests/geometry/KnnFaiss.cpp  9
- cpp/open3d/geometry/KnnFaiss.cpp  4
- python/test/test_faiss.py  1
- cpp/pybind/geometry/knnfaiss.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/pybind/geometry/knnfaiss.cpp  6
- cpp/tests/geometry/KnnFaiss.cpp  9
- cpp/open3d/geometry/KnnFaiss.cpp  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/tests/geometry/KnnFaiss.cpp  9
- cpp/pybind/geometry/knnfaiss.cpp  6
- cpp/open3d/geometry/KnnFaiss.cpp  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_faiss.py  5
         

Clones added
============
- cpp/open3d/geometry/KnnFaiss.cpp  4
- cpp/pybind/geometry/knnfaiss.cpp  6
- cpp/tests/geometry/KnnFaiss.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_faiss.py  1
         

Clones added
============
- cpp/open3d/geometry/KnnFaiss.cpp  4
- cpp/tests/geometry/KnnFaiss.cpp  9
- cpp/pybind/geometry/knnfaiss/knnfaiss.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/test_faiss.py  1
         

Clones added
============
- cpp/open3d/geometry/KnnFaiss.cpp  4
- cpp/tests/geometry/KnnFaiss.cpp  9
- cpp/pybind/geometry/knnfaiss/knnfaiss.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5853661&bid=19163510)

**Comment by junha-l** [comment]
Close due to duplication with #2400

**Pull request closed without merging**
