### PR TITLE
XYZI format IO with tgeometry::PointCloud

### PR DESCRIPTION
**Pull request by ssheorey**
Read `*.xyzi` ASCII files in the format:

> x y z I

space separated, double precision numbers

Test: Synthetic data -> write -> read -> compare 

TODO:
- Test with actual data files (?)
- Support for comments in xyzi files (http://help.arcgis.com/en/arcgisdesktop/10.0/help/index.html#//00q900000092000000)

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2356)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/io/file_format/FileXYZI.cpp  1
- cpp/open3d/io/tPointCloudIO.cpp  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6205324&bid=20240496)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Clones added
============
- cpp/open3d/io/tPointCloudIO.cpp  4
- cpp/open3d/io/file_format/FileXYZI.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6205324&bid=20240496)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Clones added
============
- cpp/open3d/io/tPointCloudIO.cpp  4
- cpp/open3d/io/file_format/FileXYZI.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6205324&bid=20240496)

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2356)* status: all files reviewed, 4 unresolved discussions (waiting on @ssheorey)

___
*[cpp/open3d/io/tPointCloudIO.h, line 1 at r3](https://reviewable.io/reviews/intel-isl/open3d/2356#-MHpprXT1AO5ipJkLn0-:-MHpprXU9sfHDI1tXrsr:bog3alj) ([raw file](https://github.com/intel-isl/open3d/blob/627375a0efdfe916fcdeec6209ec5b90c9217eda/cpp/open3d/io/tPointCloudIO.h#L1)):*
> ```objc
> // ----------------------------------------------------------------------------
> ```

shall we rename this to `TPointCloudIO.h`? other file names also start with capital letters.

same for other files in this PR.
___
*[cpp/open3d/io/tPointCloudIO.cpp, line 40 at r3](https://reviewable.io/reviews/intel-isl/open3d/2356#-MHpqEhwC2nPoBi5hr1P:-MHpqEhwC2nPoBi5hr1Q:b-yd7ldg) ([raw file](https://github.com/intel-isl/open3d/blob/627375a0efdfe916fcdeec6209ec5b90c9217eda/cpp/open3d/io/tPointCloudIO.cpp#L40)):*
> ```cpp
> 
> namespace {
> using namespace io;
> ```

could we also put this inside `namespace io`? it seems not necessary to create a separate namespace location for this.
___
*[cpp/tests/io/tPointCloudIO.cpp, line 124 at r3](https://reviewable.io/reviews/intel-isl/open3d/2356#-MHpwyXn9ukZ8PjtzaAo:-MHpwyXn9ukZ8PjtzaAp:b-6r8h4b) ([raw file](https://github.com/intel-isl/open3d/blob/627375a0efdfe916fcdeec6209ec5b90c9217eda/cpp/tests/io/tPointCloudIO.cpp#L124)):*
> ```cpp
>         const double max_error = attribute_max_err.second;
>         SCOPED_TRACE(attribute);
>         EXPECT_LT(MaxDistance(pc1.GetPointAttr(attribute),
> ```

would `Tensor::AllClose` work for tensor comparison?
___
*[cpp/tests/io/tPointCloudIO.cpp, line 139 at r3](https://reviewable.io/reviews/intel-isl/open3d/2356#-MHpxgyyAbQw1t2qfnaz:-MHpxgyz-IW8nzc_MXBB:b5n9q7j) ([raw file](https://github.com/intel-isl/open3d/blob/627375a0efdfe916fcdeec6209ec5b90c9217eda/cpp/tests/io/tPointCloudIO.cpp#L139)):*
> ```cpp
>         const std::string &attribute = attribute_max_err.first;
>         SCOPED_TRACE(attribute);
>         EXPECT_EQ(MaxDistance(pc3.GetPointAttr(attribute),
> ```

same, would `Tensor::AllClose` work for tensor comparison?

**Review by ssheorey — COMMENTED** [review]
These are false alarms. `cppcheck` doesn't recognize string literals.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2356#-:-MHrzqfX-IaLb9JQ19D5:bt83r5d)* status: all files reviewed, 4 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/io/tPointCloudIO.h, line 1 at r3](https://reviewable.io/reviews/intel-isl/open3d/2356#-MHpprXT1AO5ipJkLn0-:-MHrowOa5h2rkr7NFxnt:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/627375a0efdfe916fcdeec6209ec5b90c9217eda/cpp/open3d/io/tPointCloudIO.h#L1)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

shall we rename this to `TPointCloudIO.h`? other file names also start with capital letters.

same for other files in this PR.
</blockquote></details>

Done.
___
*[cpp/open3d/io/tPointCloudIO.cpp, line 40 at r3](https://reviewable.io/reviews/intel-isl/open3d/2356#-MHpqEhwC2nPoBi5hr1P:-MHrq4vO84cKYXTY00ez:b-cm24bw) ([raw file](https://github.com/intel-isl/open3d/blob/627375a0efdfe916fcdeec6209ec5b90c9217eda/cpp/open3d/io/tPointCloudIO.cpp#L40)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

could we also put this inside `namespace io`? it seems not necessary to create a separate namespace location for this.
</blockquote></details>

This is copied from `PointCloudIO.cpp`. I guess the intent was to hide this map from outside this file. I'll get rid of it from both files, but let me know if you want to keep it.
___
*[cpp/tests/io/tPointCloudIO.cpp, line 124 at r3](https://reviewable.io/reviews/intel-isl/open3d/2356#-MHpwyXn9ukZ8PjtzaAo:-MHrriaJCdSbSg-sDb99:bqp633w) ([raw file](https://github.com/intel-isl/open3d/blob/627375a0efdfe916fcdeec6209ec5b90c9217eda/cpp/tests/io/tPointCloudIO.cpp#L124)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

would `Tensor::AllClose` work for tensor comparison?
</blockquote></details>

Good idea. I'll replace it.
___
*[cpp/tests/io/tPointCloudIO.cpp, line 139 at r3](https://reviewable.io/reviews/intel-isl/open3d/2356#-MHpxgyyAbQw1t2qfnaz:-MHrzjvS4kcY1A51GiTN:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/627375a0efdfe916fcdeec6209ec5b90c9217eda/cpp/tests/io/tPointCloudIO.cpp#L139)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

same, would `Tensor::AllClose` work for tensor comparison?
</blockquote></details>

Done.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Clones added
============
- cpp/open3d/io/PointCloudIO.cpp  4
- cpp/open3d/io/tPointCloudIO.cpp  4
- cpp/open3d/io/file_format/FileXYZI.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6205324&bid=20240496)

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2356)* status: all files reviewed, 1 unresolved discussion (waiting on @yxlao)

___
*[cpp/open3d/io/tPointCloudIO.h, line 1 at r3](https://reviewable.io/reviews/intel-isl/open3d/2356#-MHpprXT1AO5ipJkLn0-:-MHuBWoE3FRSm_Z7XVkK:b-1y53n5) ([raw file](https://github.com/intel-isl/open3d/blob/627375a0efdfe916fcdeec6209ec5b90c9217eda/cpp/open3d/io/tPointCloudIO.h#L1)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Seems like the `#include` has been updated but the file name is not updated. Therefore, the Windows build is working but Ubuntu and macOS is failing since they are case-sensitive.
___
*[docs/Doxyfile, line 1 at r4](https://reviewable.io/reviews/intel-isl/open3d/2356#-MHuB8wp1FelSo7pzaMv:-MHuB8wp1FelSo7pzaMw:b62nqyp) ([raw file](https://github.com/intel-isl/open3d/blob/62a1d1ff788f4dd7c0436c7460ea3148e26463b9/docs/Doxyfile#L1)):*
> ```
> # Doxyfile 1.8.20
> ```

just for the information, what is the improvement of the new version?

**Comment by ssheorey** [comment]
> > Reviewed 4 of 4 files at r4.
> > _[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2356)_ status: all files reviewed, 1 unresolved discussion (waiting on @yxlao)
> 
> _[cpp/open3d/io/tPointCloudIO.h, line 1 at r3](https://reviewable.io/reviews/intel-isl/open3d/2356#-MHpprXT1AO5ipJkLn0-:-MHuBWoE3FRSm_Z7XVkK:b-1y53n5) ([raw file](https://github.com/intel-isl/open3d/blob/627375a0efdfe916fcdeec6209ec5b90c9217eda/cpp/open3d/io/tPointCloudIO.h#L1)):_
> Previously, ssheorey wrote…
> 
> Seems like the `#include` has been updated but the file name is not updated. Therefore, the Windows build is working but Ubuntu and macOS is failing since they are case-sensitive.

git didn't pick up the renames on my Mac. Looks like that's default behaviour on Mac. Explicitly renaming them with `git mv` fixed it.

> _[docs/Doxyfile, line 1 at r4](https://reviewable.io/reviews/intel-isl/open3d/2356#-MHuB8wp1FelSo7pzaMv:-MHuB8wp1FelSo7pzaMw:b62nqyp) ([raw file](https://github.com/intel-isl/open3d/blob/62a1d1ff788f4dd7c0436c7460ea3148e26463b9/docs/Doxyfile#L1)):_
> 
> > ```
> > # Doxyfile 1.8.20
> > ```
> 
> just for the information, what is the improvement of the new version?

Mostly bug fixes. Some C++ code parsing fixes should improve documentation. There's a new multi-threaded mode that looks promising. I upgraded since it complained about upgrading `Doxyfile` the Doxyfile format.

Going forward, I'd like to reduce the number of warnings from doxygen (undocumented items: partly to help me understand the code better. Also add more graphs and switch from `png` to `svg`.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Clones added
============
- cpp/open3d/io/TPointCloudIO.cpp  4
- cpp/open3d/io/PointCloudIO.cpp  4
- cpp/open3d/io/file_format/FileXYZI.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6205324&bid=20240496)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Clones added
============
- cpp/open3d/io/PointCloudIO.cpp  4
- cpp/open3d/io/TPointCloudIO.cpp  4
- cpp/open3d/io/file_format/FileXYZI.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6205324&bid=20240496)

**Review by yxlao — APPROVED** [review]
> Reviewed 3 of 3 files at r5, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2356)* status: all files reviewed, 1 unresolved discussion (waiting on @yxlao)

**Comment by rafael2k** [comment]
This broke compilation here on Debian 10, because of changes in cpp/CMakeLists.txt.

**Comment by griegler** [comment]
@rafael2k Could you please open an issue with more details on what broke, i.e., error outputs.

**Comment by rafael2k** [comment]
I'll open an issue. But I can confirm, at least in my "stock" Debian 10, Open3D fails to compile (I'm stuck with 0.9.0).

**Pull request merged**
