### PR TITLE
Merge covariance estimation methods

### PR DESCRIPTION
**Pull request by nachovizzo**
As mention in #1966 one tech debt was to somehow merge the covariance estimation methods between the normal estimation and the ISS Keypoint detector.

I found this solution to be the most optimal, except for the conversion of `std::vector<int>` to `std::vector<size_t>` with no real overhead, but that's a limitation on the `KDTreeFlann` API.

## Before
bunny_master
master_armadillo
normal_master

## After
bunny_prr
pr_armadillo
normal_pr

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2259)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ cpp/open3d/geometry/EstimateNormals.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6099159&bid=19966222)

**Review by griegler — CHANGES_REQUESTED** [review]
Thanks for the PR. 
I think we should not compromise on speed here (especially `ComputeNormal` is critical). I would therefore propose a dedicated function (maybe within `PointCloud`) that looks something like

```cpp
Eigen::Matrix3d ComputeCovariance(const std::vector<Eigen::Vector3d>& points, const std::vector<size_t>& indices) {
    Eigen::Matrix3d covariance;
    Eigen::Matrix<double, 9, 1> cumulants;
    cumulants.setZero();
    for (size_t idx : indices) {
        const Eigen::Vector3d &point = points[idx];
        cumulants(0) += point(0);
        cumulants(1) += point(1);
        cumulants(2) += point(2);
        cumulants(3) += point(0) * point(0);
        cumulants(4) += point(0) * point(1);
        cumulants(5) += point(0) * point(2);
        cumulants(6) += point(1) * point(1);
        cumulants(7) += point(1) * point(2);
        cumulants(8) += point(2) * point(2);
    }
    cumulants /= (double)indices.size();
    covariance(0, 0) = cumulants(3) - cumulants(0) * cumulants(0);
    covariance(1, 1) = cumulants(6) - cumulants(1) * cumulants(1);
    covariance(2, 2) = cumulants(8) - cumulants(2) * cumulants(2);
    covariance(0, 1) = cumulants(4) - cumulants(0) * cumulants(1);
    covariance(1, 0) = covariance(0, 1);
    covariance(0, 2) = cumulants(5) - cumulants(0) * cumulants(2);
    covariance(2, 0) = covariance(0, 2);
    covariance(1, 2) = cumulants(7) - cumulants(1) * cumulants(2);
    covariance(2, 1) = covariance(1, 2);
    return covariance;
}
```

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2259#-:-MG7U7d01nzGuTtE_clD:b-28jt8o)* status: 0 of 2 files reviewed, all discussions resolved

**Review by nachovizzo — COMMENTED** [review]
I also thought about that, and it actually makes sense.

Although I don't see much overhead besides for the "neighborhood" `PointCloud` extraction:
```cpp
std::vector<size_t> indices_(indices.begin(), indices.end());
std::shared_ptr<PointCloud> neighbors = cloud.SelectByIndex(indices_);
```

I'd rather put in in the utility section since it might be consumed by other data types, for example, if someone wants to estimate the covariance matrix of a given set of vertices in a `TriangleMesh`, then this function should be exposed to everyone.

But I'd also add a `std::tuple<Eigen::Vector3d, Eigen::Matrix3d> ComputeMeanAndCovariance` on the utility module. There will be duplicated code there of course, but this allows us to have a cleaner API usage(no `std::get<x>`)

I'm updating the PR so you can review my proposal.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2259#-:-MG7_tew-QFvfpvEQVJ_:b-mad0gl)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/utility/Eigen.cpp  4
         

Clones removed
==============
+ cpp/open3d/geometry/PointCloud.cpp  -2
+ cpp/open3d/geometry/EstimateNormals.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6099159&bid=19966222)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/utility/Eigen.cpp  4
         

Clones removed
==============
+ cpp/open3d/geometry/EstimateNormals.cpp  -2
+ cpp/open3d/geometry/PointCloud.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6099159&bid=19966222)

**Review by griegler — APPROVED** [review]
Nice. This looks good to me. Ideally, it would be great if you could also add benchmarks for the keypoint detection and normal estimation (`Open3D/cpp/benchmarks/`). This would enable us to detect performance regressions now and in the future.

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2259#-:-MG8byTh-Vp4QmmDREgs:b-g63xj8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by nachovizzo — COMMENTED** [review]
Sounds good, I tried to do benchmarks of this outside `Open3D` just for simplicity and failed to link against the propper `libbenchmark.a` library.  Since it's part of `${Open3D_LIBRARIES}` and there was a mismatch between the system-wide installed google-benchmark library and the one in Open3D, checking out the same commit and installing the library locally didn't help, so I end up quitting. But I'll add this to my Open3D ToDo list

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2259#-:-MG8hPIY8ODKrnJvpKm2:bjf6as5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
