### PR TITLE
Linear algebra module

### PR DESCRIPTION
**Pull request by theNded**
Follow up to closed #2020 that requires magma. Now we use MKL for CPU and cuSolver/cuBLAS for CUDA that are easier to configure.
- [x] Solve linear system `AX = B` using QR decomposition (supporting non-square A matrices)
- [x] SVD decomposition: `U, S, VT = SVD(A)`
- [x] Square matrix inversion: `inv_A = inv(A)` using LU decomposition 
- [x] Matmul: `AB`
- [x] Appropriately link `${CUDA_CUBLAS_LIBRARIES}` and `${CUDA_cusolver_LIBRARY}`
- [x] More boundary cases check
- [x] Move temp test to UnitTest
- [x] Pybind
- [x] Can be merged after #2086 is merged and todo list is cleared.

Problems: 
- ~~cublas/cusolver are directly linked to mkl target library (as a placeholder solution). Better approach needed in CMake @yixing.~~
- ~~mkl.h appears in headers. Need to find tricks to remove it if necessary.~~
- ~~In some ill-posed cases, `Solve` will not detect singular conditions. Needs more investigation.~~

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2103)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/core/op/linalg/TestSolve.cpp  2
- cpp/open3d/core/op/kernel/IndexGetSetCPU.cpp  2
- cpp/open3d/core/op/linalg/TestMatmul.cpp  1
- cpp/open3d/core/op/linalg/TestInverse.cpp  3
- cpp/open3d/core/op/linalg/TestSVD.cpp  3
- cpp/open3d/core/op/linalg/Inverse.cpp  2
- cpp/open3d/core/op/linalg/Solve.cpp  3
- cpp/open3d/core/op/linalg/Matmul.cpp  2
- cpp/open3d/core/op/kernel/CPULauncher.h  2
- cpp/open3d/core/op/linalg/SVD.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/core/op/linalg/Inverse.cpp  1
- cpp/open3d/core/op/linalg/SVD.cpp  1
- cpp/open3d/core/op/kernel/IndexGetSetCPU.cpp  2
- cpp/open3d/core/op/linalg/TestMatmul.cpp  1
- cpp/open3d/core/op/linalg/TestSVD.cpp  3
- cpp/open3d/core/op/linalg/Solve.cpp  1
- cpp/open3d/core/op/linalg/Matmul.cpp  1
- cpp/open3d/core/op/kernel/CPULauncher.h  2
- cpp/open3d/core/op/linalg/TestInverse.cpp  3
- cpp/open3d/core/op/linalg/TestSolve.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/core/op/kernel/CPULauncher.h  2
- cpp/open3d/core/op/kernel/IndexGetSetCPU.cpp  2
- cpp/open3d/core/op/linalg/TestSolve.cpp  2
- cpp/open3d/core/op/linalg/Inverse.cpp  1
- cpp/open3d/core/op/linalg/TestSVD.cpp  3
- cpp/open3d/core/op/linalg/TestInverse.cpp  3
- cpp/open3d/core/op/linalg/TestMatmul.cpp  1
- cpp/open3d/core/op/linalg/Matmul.cpp  1
- cpp/open3d/core/op/linalg/SVDCUDA.cpp  1
- cpp/open3d/core/op/linalg/SVD.cpp  1
- cpp/open3d/core/op/linalg/Solve.cpp  1
- cpp/open3d/core/op/linalg/InverseCUDA.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/core/linalg/TestMatmul.cpp  1
- cpp/open3d/core/linalg/SVD.cpp  1
- cpp/open3d/core/linalg/Matmul.cpp  3
- cpp/open3d/core/linalg/TestSVD.cpp  3
- cpp/open3d/core/linalg/Inverse.cpp  1
- cpp/open3d/core/linalg/SVDCUDA.cpp  2
- cpp/open3d/core/linalg/InverseCUDA.cpp  1
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/Solve.cpp  3
- cpp/open3d/core/linalg/TestInverse.cpp  3
- cpp/open3d/core/linalg/TestSolve.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  4
         

Clones added
============
- cpp/open3d/core/linalg/TestMatmul.cpp  1
- cpp/open3d/core/linalg/Inverse.cpp  1
- cpp/open3d/core/linalg/Matmul.cpp  3
- cpp/open3d/core/linalg/TestSolve.cpp  2
- cpp/open3d/core/linalg/SVD.cpp  1
- cpp/open3d/core/linalg/test.py  1
- python/test/core/test_linalg.py  1
- cpp/open3d/core/linalg/TestInverse.cpp  3
- cpp/open3d/core/linalg/InverseCUDA.cpp  1
- cpp/open3d/core/linalg/Solve.cpp  3
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/SVDCUDA.cpp  2
- cpp/open3d/core/linalg/TestSVD.cpp  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  4
         

Clones added
============
- cpp/open3d/core/linalg/Inverse.cpp  1
- cpp/open3d/core/linalg/SVD.cpp  1
- cpp/open3d/core/linalg/Matmul.cpp  3
- cpp/open3d/core/linalg/InverseCUDA.cpp  1
- cpp/open3d/core/linalg/Solve.cpp  3
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/SVDCUDA.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  4
         

Clones added
============
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/InverseCUDA.cpp  1
- cpp/open3d/core/linalg/SVD.cpp  1
- cpp/open3d/core/linalg/Solve.cpp  3
- cpp/open3d/core/linalg/Inverse.cpp  1
- cpp/open3d/core/linalg/Matmul.cpp  3
- cpp/open3d/core/linalg/SVDCUDA.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  4
         

Clones added
============
- cpp/open3d/core/linalg/Matmul.cpp  3
- cpp/open3d/core/linalg/SVDCUDA.cpp  2
- cpp/open3d/core/linalg/InverseCUDA.cpp  1
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/SVD.cpp  1
- cpp/open3d/core/linalg/Solve.cpp  3
- cpp/open3d/core/linalg/Inverse.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  4
         

Clones added
============
- cpp/open3d/core/linalg/Inverse.cpp  1
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/SVDCUDA.cpp  2
- cpp/open3d/core/linalg/InverseCUDA.cpp  1
- cpp/open3d/core/linalg/Matmul.cpp  3
- cpp/open3d/core/linalg/Solve.cpp  3
- cpp/open3d/core/linalg/SVD.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  4
         

Clones added
============
- cpp/open3d/core/linalg/Inverse.cpp  1
- cpp/open3d/core/linalg/SVDCUDA.cpp  2
- cpp/open3d/core/linalg/Matmul.cpp  3
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/Solve.cpp  3
- cpp/open3d/core/linalg/SVD.cpp  1
- cpp/open3d/core/linalg/InverseCUDA.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  4
         

Clones added
============
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/InverseCUDA.cpp  1
- cpp/open3d/core/linalg/Solve.cpp  3
- cpp/open3d/core/linalg/Matmul.cpp  3
- cpp/open3d/core/linalg/Inverse.cpp  1
- cpp/open3d/core/linalg/SVD.cpp  1
- cpp/open3d/core/linalg/SVDCUDA.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  4
         

Clones added
============
- cpp/open3d/core/linalg/Solve.cpp  3
- cpp/open3d/core/linalg/SVD.cpp  1
- cpp/open3d/core/linalg/InverseCUDA.cpp  1
- cpp/open3d/core/linalg/Matmul.cpp  3
- cpp/open3d/core/linalg/SVDCUDA.cpp  2
- cpp/open3d/core/linalg/Inverse.cpp  1
- cpp/open3d/core/linalg/SVDCPU.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  4
         

Clones added
============
- cpp/open3d/core/linalg/Matmul.cpp  3
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/SVD.cpp  1
- cpp/open3d/core/linalg/Inverse.cpp  1
- cpp/open3d/core/linalg/SVDCUDA.cpp  2
- cpp/open3d/core/linalg/Solve.cpp  3
- cpp/open3d/core/linalg/InverseCUDA.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  4
         

Clones added
============
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/Inverse.cpp  1
- cpp/open3d/core/linalg/SVDCUDA.cpp  2
- cpp/open3d/core/linalg/Matmul.cpp  3
- cpp/open3d/core/linalg/InverseCUDA.cpp  1
- cpp/open3d/core/linalg/SVD.cpp  1
- cpp/open3d/core/linalg/Solve.cpp  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  4
         

Clones added
============
- cpp/open3d/core/linalg/SVDCUDA.cpp  2
- cpp/open3d/core/linalg/Matmul.cpp  3
- cpp/open3d/core/linalg/SVD.cpp  1
- cpp/open3d/core/linalg/InverseCUDA.cpp  1
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/Inverse.cpp  1
- cpp/open3d/core/linalg/Solve.cpp  3
- python/test/core/test_linalg.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  4
         

Clones added
============
- python/test/core/test_linalg.py  2
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/SVDCUDA.cpp  2
- cpp/open3d/core/linalg/InverseCUDA.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  15
         

Clones added
============
- cpp/open3d/core/linalg/InverseCUDA.cpp  1
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/SVDCUDA.cpp  2
- python/test/core/test_linalg.py  13
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  15
         

Clones added
============
- cpp/open3d/core/linalg/SolveCUDA.cpp  3
- cpp/open3d/core/linalg/SVDCUDA.cpp  3
- python/test/core/test_linalg.py  19
- cpp/open3d/core/linalg/Matmul.cpp  2
- cpp/open3d/core/linalg/InverseCUDA.cpp  3
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/Solve.cpp  1
- cpp/open3d/core/linalg/LeastSquares.cpp  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  15
         

Clones added
============
- cpp/open3d/core/linalg/LeastSquares.cpp  3
- cpp/open3d/core/linalg/SVDCUDA.cpp  3
- cpp/open3d/core/linalg/Solve.cpp  1
- python/test/core/test_linalg.py  19
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/Matmul.cpp  2
- cpp/open3d/core/linalg/SolveCUDA.cpp  3
- cpp/open3d/core/linalg/InverseCUDA.cpp  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  15
         

Clones added
============
- python/test/core/test_linalg.py  19
- cpp/open3d/core/linalg/InverseCUDA.cpp  3
- cpp/open3d/core/linalg/LeastSquares.cpp  3
- cpp/open3d/core/linalg/Solve.cpp  1
- cpp/open3d/core/linalg/Matmul.cpp  2
- cpp/open3d/core/linalg/SolveCUDA.cpp  3
- cpp/open3d/core/linalg/SVDCUDA.cpp  3
- cpp/open3d/core/linalg/SVDCPU.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by yxlao** [comment]
@theNded The build is currently breaking due to lack of support for functions like `cusolverDnDDgesv` in CUDA 10.1. Do we have a way to work around this?

**Comment by theNded** [comment]
@yxlao gesv is removed, let's check remaining problems.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  15
         

Clones added
============
- cpp/open3d/core/linalg/LeastSquares.cpp  3
- cpp/open3d/core/linalg/SVDCUDA.cpp  3
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/SolveCUDA.cpp  3
- cpp/open3d/core/linalg/Solve.cpp  1
- python/test/core/test_linalg.py  19
- cpp/open3d/core/linalg/Matmul.cpp  2
- cpp/open3d/core/linalg/InverseCUDA.cpp  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  15
         

Clones added
============
- cpp/open3d/core/linalg/Matmul.cpp  2
- python/test/core/test_linalg.py  19
- cpp/open3d/core/linalg/LeastSquares.cpp  3
- cpp/open3d/core/linalg/Solve.cpp  1
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/SolveCUDA.cpp  3
- cpp/open3d/core/linalg/SVDCUDA.cpp  3
- cpp/open3d/core/linalg/InverseCUDA.cpp  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  15
         

Clones added
============
- cpp/open3d/core/linalg/SVDCUDA.cpp  3
- cpp/open3d/core/linalg/Matmul.cpp  2
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/LeastSquares.cpp  3
- python/test/core/test_linalg.py  19
- cpp/open3d/core/linalg/Solve.cpp  1
- cpp/open3d/core/linalg/InverseCUDA.cpp  3
- cpp/open3d/core/linalg/SolveCUDA.cpp  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  15
         

Clones added
============
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/InverseCUDA.cpp  3
- cpp/open3d/core/linalg/SVDCUDA.cpp  3
- cpp/open3d/core/linalg/SolveCUDA.cpp  3
- cpp/open3d/core/linalg/LeastSquares.cpp  3
- cpp/open3d/core/linalg/Solve.cpp  1
- python/test/core/test_linalg.py  19
- cpp/open3d/core/linalg/Matmul.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_linalg.py  15
         

Clones added
============
- python/test/core/test_linalg.py  19
- cpp/open3d/core/linalg/SVDCPU.cpp  1
- cpp/open3d/core/linalg/SolveCUDA.cpp  3
- cpp/open3d/core/linalg/InverseCUDA.cpp  3
- cpp/open3d/core/linalg/Solve.cpp  1
- cpp/open3d/core/linalg/SVDCUDA.cpp  3
- cpp/open3d/core/linalg/LeastSquares.cpp  3
- cpp/open3d/core/linalg/Matmul.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5903646&bid=19333034)

**Pull request merged**
