### PR TITLE
gui::TreeView now supports arbitrary widgets for its cells

### PR DESCRIPTION
**Pull request by prewettg**
A Python script testing this is attached below (note that you will need to rename it to .py, as GitHub won't accept a .py file)

[ml-vis.txt](https://github.com/intel-isl/Open3D/files/4974546/ml-vis.txt) (change line 288 to `dataset.visualize(0)` if using the small version of SemanticKITTI linked below
[microkitti.tar.gz](https://github.com/intel-isl/Open3D/files/4983757/microkitti.tar.gz) (very small version of SemanticKITTI)

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2105)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ cpp/open3d/visualization/gui/Checkbox.cpp  -1
+ cpp/open3d/visualization/gui/ListView.cpp  -1
+ cpp/open3d/visualization/gui/Label.cpp  -1
+ cpp/open3d/visualization/gui/TabControl.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5909244&bid=19358397)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ cpp/open3d/visualization/gui/Checkbox.cpp  -1
+ cpp/open3d/visualization/gui/TabControl.cpp  -1
+ cpp/open3d/visualization/gui/Label.cpp  -1
+ cpp/open3d/visualization/gui/ListView.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5909244&bid=19358397)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ cpp/open3d/visualization/gui/Label.cpp  -1
+ cpp/open3d/visualization/gui/ListView.cpp  -1
+ cpp/open3d/visualization/gui/TabControl.cpp  -1
+ cpp/open3d/visualization/gui/Checkbox.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5909244&bid=19358397)

**Comment by prewettg** [comment]
___
*[cpp/open3d/visualization/gui/TreeView.h, line 46 at r2](https://reviewable.io/reviews/intel-isl/open3d/2105#-MDHHp5T-v7IuawGzDRg:-MDLbffw-1cJLo2tTLzK:b-sdwh9c) ([raw file](https://github.com/intel-isl/open3d/blob/0d9c7163bf3b648991068db939e31ac7b8653868/cpp/open3d/visualization/gui/TreeView.h#L46)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Adding the ItemId as another parameter to on_toggled would simplify code on the python side.
</blockquote></details>

True, but I can't think of a good way to implement that. The cell doesn't know that it is in a tree because it is just a Widget. If I required tree cells to inherit from TreeViewCell or something then the cell could know, but then you can't just put any widget in the tree any more. Anything you put in the tree would need to inherit from TreeViewCell, so unless it's pre-built like this, that adds additional work. German doesn't like local functions, but for people that are okay with it, it would be any easy solution for Python, since the local function would act as a closure:
  cell = CheckableTextTreeCell(...)
  def on_clicked(did_click):
    if did_click:
      cell.turn_pink()

**Pull request merged**
