### PR TITLE
Procedural Ground Plane

### PR DESCRIPTION
**Pull request by errissa**
Open3DViewer UI has been updated with a check box to enable/disable ground plane.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2980)

### CODE REVIEW

**Comment by prewettg** [comment]
Looks great! Could you add to O3DVisualizer, too?

**Review by prewettg — CHANGES_REQUESTED** [review]
> Reviewed 5 of 16 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2980)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by prewettg — CHANGES_REQUESTED** [review]
After looking at this further, I think Open3DScene ought to have a ShowGroundPlane(), to be consistent with ShowAxes() and ShowSkybox(). Also, needs pybinds.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2980#-:-MSai6vJ0GmhaUQlwZxq:bpbkyuc)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by prewettg — CHANGES_REQUESTED** [review]
Could we have an option to change the plane's normal? The mobileeye dataset has z as up instead of y as up (also some Standford datasets have -y as up, I think, although I'm guessing that wouldn't matter here).

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2980#-:-MSaiTBp7mlIr4B0y1Nh:bqf8h8e)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by errissa** [comment]
> Looks great! Could you add to O3DVisualizer, too?

Done.

**Comment by errissa** [comment]
> After looking at this further, I think Open3DScene ought to have a ShowGroundPlane(), to be consistent with ShowAxes() and ShowSkybox(). Also, needs pybinds.

I had already added ShowGroundPlane() to Open3DScene but I just added the pybinds for it.

**Review by prewettg — APPROVED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2980)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
