### PR TITLE
Voxel hashing GUI

### PR DESCRIPTION
**Pull request by theNded**
This PR introduces the VoxelHashing's application. Depending on #3323.

To be fixed before merging:
- 2nd checkbox bug
- ~~Camera intrinsic's path and dataset file structure~~

Features:
- Real-time RGB-D tracking and reconstruction (~40Hz on GPU and ~5Hz on CPU)
- Interactive parameter selection
- Point cloud and trajectory output at exit

TBD in the future:
- Support streaming in/out GPU to enable larger scale reconstruction with a lower GPU budget
- More robust tracking
- File manager for customized input/output in the UI
image

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3363)

### CODE REVIEW

**Review by errissa — CHANGES_REQUESTED** [review]
> Reviewed 27 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3363)* status: 27 of 28 files reviewed, 4 unresolved discussions (waiting on @prewettg, @reyanshsolis, and @theNded)

___
*[examples/cpp/VoxelHashingGUI.cpp, line 14 at r1](https://reviewable.io/reviews/intel-isl/open3d/3363#-MZxyEOR0fpeL87SxCa6:-MZxyEOR0fpeL87SxCa7:b-9u2fic) ([raw file](https://github.com/intel-isl/open3d/blob/b62fab6a03a46db0fa5f502c838a58814c0eb4b5/examples/cpp/VoxelHashingGUI.cpp#L14)):*
> ```cpp
> static const Eigen::Vector3d kTangoSkyBlueDark(0.125, 0.290, 0.529);
> 
> std::shared_ptr<geometry::LineSet> CreateCameraFrustum(
> ```

Most of this function could be replaced with `LineSet::CreateCameraVisualization`
___
*[examples/cpp/VoxelHashingGUI.cpp, line 774 at r1](https://reviewable.io/reviews/intel-isl/open3d/3363#-MZy7U6u1MKBJKQMVl2Q:-MZy7U6vCIuNyL5f1r30:b-uco2f9) ([raw file](https://github.com/intel-isl/open3d/blob/b62fab6a03a46db0fa5f502c838a58814c0eb4b5/examples/cpp/VoxelHashingGUI.cpp#L774)):*
> ```cpp
> int main(int argc, char** argv) {
>     if (argc < 2) {
>         utility::LogError("Expected a dataset path as input.");
> ```

This should print a usage message and quit (return) gracefully.
___
*[examples/cpp/VoxelHashingGUI.cpp, line 779 at r1](https://reviewable.io/reviews/intel-isl/open3d/3363#-MZy80C3CR-VQ1DZb3Dr:-MZy80C3CR-VQ1DZb3Ds:b-pjr8ot) ([raw file](https://github.com/intel-isl/open3d/blob/b62fab6a03a46db0fa5f502c838a58814c0eb4b5/examples/cpp/VoxelHashingGUI.cpp#L779)):*
> ```cpp
>     std::string dataset_path = argv[1];
>     if (!utility::filesystem::DirectoryExists(dataset_path)) {
>         utility::LogError("Expected an existing directory {}", dataset_path);
> ```

`LogError` throws an exception that is uncaught which results in a crash. Since this is an expected possible error condition and we are in main I don't think it should crash the program. I recommend using `LogWarning` plus a `return -1` or some other return value.
___
*[examples/cpp/VoxelHashingGUI.cpp, line 787 at r1](https://reviewable.io/reviews/intel-isl/open3d/3363#-MZy856f2LtP2JSNqZKT:-MZy856f2LtP2JSNqZKU:blvst96) ([raw file](https://github.com/intel-isl/open3d/blob/b62fab6a03a46db0fa5f502c838a58814c0eb4b5/examples/cpp/VoxelHashingGUI.cpp#L787)):*
> ```cpp
>             utility::GetProgramOptionAsString(argc, argv, "--device", "CUDA:0");
>     if (device != "CPU:0" && device != "CUDA:0") {
>         utility::LogError("Unrecognized device {}. Expecting CPU:0 or CUDA:0.",
> ```

Please see previous comment.

**Review by errissa — COMMENTED** [review]
> Reviewed 1 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3363)* status: all files reviewed, 4 unresolved discussions (waiting on @prewettg, @reyanshsolis, and @theNded)

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3363)* status: 23 of 30 files reviewed, 4 unresolved discussions (waiting on @errissa, @prewettg, and @reyanshsolis)

___
*[examples/cpp/VoxelHashingGUI.cpp, line 14 at r1](https://reviewable.io/reviews/intel-isl/open3d/3363#-MZxyEOR0fpeL87SxCa6:-MZy_cLa-IfOdZ5wh06K:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/b62fab6a03a46db0fa5f502c838a58814c0eb4b5/examples/cpp/VoxelHashingGUI.cpp#L14)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

Most of this function could be replaced with `LineSet::CreateCameraVisualization`
</blockquote></details>

Done.
___
*[examples/cpp/VoxelHashingGUI.cpp, line 774 at r1](https://reviewable.io/reviews/intel-isl/open3d/3363#-MZy7U6u1MKBJKQMVl2Q:-MZy_dBg7BVkuEwKjDdX:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/b62fab6a03a46db0fa5f502c838a58814c0eb4b5/examples/cpp/VoxelHashingGUI.cpp#L774)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

This should print a usage message and quit (return) gracefully.
</blockquote></details>

Done.
___
*[examples/cpp/VoxelHashingGUI.cpp, line 779 at r1](https://reviewable.io/reviews/intel-isl/open3d/3363#-MZy80C3CR-VQ1DZb3Dr:-MZy_dqr-omR8rwUCjwV:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/b62fab6a03a46db0fa5f502c838a58814c0eb4b5/examples/cpp/VoxelHashingGUI.cpp#L779)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

`LogError` throws an exception that is uncaught which results in a crash. Since this is an expected possible error condition and we are in main I don't think it should crash the program. I recommend using `LogWarning` plus a `return -1` or some other return value.
</blockquote></details>

Done.
___
*[examples/cpp/VoxelHashingGUI.cpp, line 787 at r1](https://reviewable.io/reviews/intel-isl/open3d/3363#-MZy856f2LtP2JSNqZKT:-MZy_eLe3masRIpQ2Rsn:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/b62fab6a03a46db0fa5f502c838a58814c0eb4b5/examples/cpp/VoxelHashingGUI.cpp#L787)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

Please see previous comment.
</blockquote></details>

Done.

**Review by errissa — APPROVED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3363)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @prewettg and @reyanshsolis)

**Pull request merged**
