### PR TITLE
UV-Map for Box, Tetrahedron, Octahedron, Icosahedron

### PR DESCRIPTION
**Pull request by reyanshsolis**
Changes: 
- Corrected inconsistent use of `mesh` and `mesh_ptr`.
- Added UV Maps for Box, Tetrahedron, Octahedron, Icosahedron.

| Wireframe Shapes                                                                                                                      | Texture                                                                                                                                                                         | Shapes with Texture                                                                                                                                                 |
| ------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3097)

### CODE REVIEW

**Review by errissa — CHANGES_REQUESTED** [review]
How/why did you choose these specific mappings? For example, the cross pattern for the box. I could see that particular UV mapping being useful, but I think many users would expect/prefer a simpler mapping where each face gets the entire texture.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3097#-:-MUnpgvp-ZZ-e9ECl8PV:b-aha4he)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @yxlao)

**Comment by reyanshsolis** [comment]
As per the discussion, I have added `map_texture_to_each_face` parameter in the CreateBox function and provided both UV map options.
Here is the output when `map_texture_to_each_face is true`.
image

**Review by errissa — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3097)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yxlao)

**Review by yxlao — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3097)* status: all files reviewed, 3 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/geometry/TriangleMesh.h, line 605 at r3](https://reviewable.io/reviews/intel-isl/open3d/3097#-MVyDeAm6JvwtOOMR9MB:-MVyDeAn7o7z7BvNkt3L:bvj1o6c) ([raw file](https://github.com/intel-isl/open3d/blob/48f95a12374ea0cd16e8944e6291a88d8d1e453d/cpp/open3d/geometry/TriangleMesh.h#L605)):*
> ```objc
>     /// \param width is x-directional length.
>     /// \param height is y-directional length.
>     /// \param depth is z-directional length.
> ```

Add `\param map_texture_to_each_face` docstring.  Why is this `true` by default? Since other geometries essentially have`map_texture_to_each_face=false`

Add a reference to why we select the texture map in this way.
___
*[cpp/open3d/geometry/TriangleMeshFactory.cpp, line 55 at r3](https://reviewable.io/reviews/intel-isl/open3d/3097#-MVyj21y6oMrG59PG2iT:-MVyj21y6oMrG59PG2iU:bx1n00k) ([raw file](https://github.com/intel-isl/open3d/blob/48f95a12374ea0cd16e8944e6291a88d8d1e453d/cpp/open3d/geometry/TriangleMeshFactory.cpp#L55)):*
> ```cpp
>     mesh->triangles_.push_back(Eigen::Vector3i(1, 2, 3));
>     // UV Map.
>     mesh->triangle_uvs_.push_back(Eigen::Vector2d(0.866, 0.5));
> ```

Could you try if this works? it will simplify the `push_back` code by quite a bit. Same for the others.
```cpp
mesh->triangle_uvs_ = {
    {0.866, 0.5},
    {0.433, 0.75},
    ...
};
```
___
*[cpp/pybind/geometry/trianglemesh.cpp, line 365 at r3](https://reviewable.io/reviews/intel-isl/open3d/3097#-MVyjVWWBN0OhDdnr2-L:-MVyjVWWBN0OhDdnr2-M:b5ttxxe) ([raw file](https://github.com/intel-isl/open3d/blob/48f95a12374ea0cd16e8944e6291a88d8d1e453d/cpp/pybind/geometry/trianglemesh.cpp#L365)):*
> ```cpp
>                         "map, maps the entire texture to each face.",
>                         "width"_a = 1.0, "height"_a = 1.0, "depth"_a = 1.0,
>                         "map_texture_to_each_face"_a = false)
> ```

add docstring for `map_texture_to_each_face`, with `ClassMethodDocInject`

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3097)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @errissa and @yxlao)

___
*[cpp/open3d/geometry/TriangleMesh.h, line 605 at r3](https://reviewable.io/reviews/intel-isl/open3d/3097#-MVyDeAm6JvwtOOMR9MB:-MWUPVeX2oxs2IHSU_0u:b-74ala9) ([raw file](https://github.com/intel-isl/open3d/blob/48f95a12374ea0cd16e8944e6291a88d8d1e453d/cpp/open3d/geometry/TriangleMesh.h#L605)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Add `\param map_texture_to_each_face` docstring.  Why is this `true` by default? Since other geometries essentially have`map_texture_to_each_face=false`

Add a reference to why we select the texture map in this way.
</blockquote></details>

Done. Set to `false`.
___
*[cpp/open3d/geometry/TriangleMeshFactory.cpp, line 55 at r3](https://reviewable.io/reviews/intel-isl/open3d/3097#-MVyj21y6oMrG59PG2iT:-MWULqO_5__apzlVDLBE:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/48f95a12374ea0cd16e8944e6291a88d8d1e453d/cpp/open3d/geometry/TriangleMeshFactory.cpp#L55)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Could you try if this works? it will simplify the `push_back` code by quite a bit. Same for the others.
```cpp
mesh->triangle_uvs_ = {
    {0.866, 0.5},
    {0.433, 0.75},
    ...
};
```
</blockquote></details>

Done.
___
*[cpp/pybind/geometry/trianglemesh.cpp, line 365 at r3](https://reviewable.io/reviews/intel-isl/open3d/3097#-MVyjVWWBN0OhDdnr2-L:-MWUPZJpDCwo1ZZOh0LL:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/48f95a12374ea0cd16e8944e6291a88d8d1e453d/cpp/pybind/geometry/trianglemesh.cpp#L365)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add docstring for `map_texture_to_each_face`, with `ClassMethodDocInject`
</blockquote></details>

Done.

**Review by yxlao — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3097)* status: all files reviewed, 2 unresolved discussions (waiting on @yxlao)

**Comment by yxlao** [comment]
LGTM, let's add the UV map documentation (Jupyter notebook) in a new PR

**Pull request merged**
