### PR TITLE
RealSense fix for wrong duration

### PR DESCRIPTION
**Pull request by ssheorey**
- Colormap optimization supports RS bag 
- Faster seeking
- Style improvements

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2801)

### CODE REVIEW

**Review by theNded — COMMENTED** [review]
> Reviewed 12 of 13 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2801)* status: all files reviewed, 6 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[cpp/open3d/t/io/sensor/RGBDVideoReader.cpp, line 81 at r2](https://reviewable.io/reviews/intel-isl/open3d/2801#-MP6cydH8HtPxXMv04UK:-MP6cydH8HtPxXMv04UL:bctrhbx) ([raw file](https://github.com/intel-isl/open3d/blob/1a422faf18f556a3a6d78384e43304ae0b7e52bc/cpp/open3d/t/io/sensor/RGBDVideoReader.cpp#L81)):*
> ```cpp
>             auto color_file =
>                     fmt::format("{0}/color/{1:05d}.jpg", frame_path, idx);
>             open3d::io::WriteImage(color_file, im_color);
> ```

Will we switch back to io::WriteImage once everything is tensorized?
___
*[cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp, line 70 at r2](https://reviewable.io/reviews/intel-isl/open3d/2801#-MP6m7hT1hQiker9of2h:-MP6m7hT1hQiker9of2i:bi5e81) ([raw file](https://github.com/intel-isl/open3d/blob/1a422faf18f556a3a6d78384e43304ae0b7e52bc/cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp#L70)):*
> ```cpp
>                 RealSenseSensorConfig::GetMetadataJson(profile));
>         RealSenseSensorConfig::GetPixelDtypes(profile, metadata_);
>         if (seek_to_ == UINT64_MAX)
> ```

Add {} for if clause
___
*[cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp, line 95 at r2](https://reviewable.io/reviews/intel-isl/open3d/2801#-MP6n4iR-jtl3kDkedtI:-MP6n4iR-jtl3kDkedtJ:b-pgn8j7) ([raw file](https://github.com/intel-isl/open3d/blob/1a422faf18f556a3a6d78384e43304ae0b7e52bc/cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp#L95)):*
> ```cpp
>     std::unique_lock<std::mutex> lock(frame_buffer_mutex);
>     const unsigned int RS2_PLAYBACK_TIMEOUT_MS =
>             (unsigned int)(10 * 1000.0 / metadata_.fps_);
> ```

static_cast<>
___
*[cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp, line 209 at r2](https://reviewable.io/reviews/intel-isl/open3d/2801#-MP6m-yv50T3X1vViLwF:-MP6m-yv50T3X1vViLwG:b8kz49v) ([raw file](https://github.com/intel-isl/open3d/blob/1a422faf18f556a3a6d78384e43304ae0b7e52bc/cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp#L209)):*
> ```cpp
>     }
>     seek_to_ = timestamp;  // atomic
>     if (is_eof_)
> ```

Will it be better to keep {} for if else?
___
*[cpp/pybind/t/io/sensor.cpp, line 93 at r2](https://reviewable.io/reviews/intel-isl/open3d/2801#-MP6mKJU-DaDw3DdXww5:-MP6mKJU-DaDw3DdXww6:blms5zj) ([raw file](https://github.com/intel-isl/open3d/blob/1a422faf18f556a3a6d78384e43304ae0b7e52bc/cpp/pybind/t/io/sensor.cpp#L93)):*
> ```cpp
>                            "Pixel Dtype for depth data.")
>             .def_readwrite("depth_scale", &RGBDVideoMetadata::depth_scale_,
>                            "Number of depth units per meter (Inverse of "
> ```

Can we be more explicit? Something like "`depth_scale` converts a uint16 depth value `d` to meter by `d / depth_scale`"
___
*[docs/tutorial/sensor/realsense.rst, line 165 at r2](https://reviewable.io/reviews/intel-isl/open3d/2801#-MP6mtG7DKInYbA3P25R:-MP6mtG7DKInYbA3P25S:bv2lxv) ([raw file](https://github.com/intel-isl/open3d/blob/1a422faf18f556a3a6d78384e43304ae0b7e52bc/docs/tutorial/sensor/realsense.rst#L165)):*
> ```reStructuredText
>   supported width or height.
> * **depth_format**: Pixel format for depth frames.
> * **depth_resolution**: (width, height): Leave 0 to let RealSense pick a
> ```

Will `depth_scale` present here?

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2801)* status: all files reviewed, 6 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/t/io/sensor/RGBDVideoReader.cpp, line 81 at r2](https://reviewable.io/reviews/intel-isl/open3d/2801#-MP6cydH8HtPxXMv04UK:-MP6qdMZBrKcmKb9d1Uv:b2nhswy) ([raw file](https://github.com/intel-isl/open3d/blob/1a422faf18f556a3a6d78384e43304ae0b7e52bc/cpp/open3d/t/io/sensor/RGBDVideoReader.cpp#L81)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Will we switch back to io::WriteImage once everything is tensorized?
</blockquote></details>

Yes
___
*[cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp, line 70 at r2](https://reviewable.io/reviews/intel-isl/open3d/2801#-MP6m7hT1hQiker9of2h:-MP6rFNH7CJNGQgwBBtc:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1a422faf18f556a3a6d78384e43304ae0b7e52bc/cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp#L70)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Add {} for if clause
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp, line 95 at r2](https://reviewable.io/reviews/intel-isl/open3d/2801#-MP6n4iR-jtl3kDkedtI:-MP6rFw6BGU4USEpGkMU:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1a422faf18f556a3a6d78384e43304ae0b7e52bc/cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp#L95)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

static_cast<>
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp, line 209 at r2](https://reviewable.io/reviews/intel-isl/open3d/2801#-MP6m-yv50T3X1vViLwF:-MP6rPJd0RaORJm2MfgQ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1a422faf18f556a3a6d78384e43304ae0b7e52bc/cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp#L209)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Will it be better to keep {} for if else?
</blockquote></details>

Done.
___
*[cpp/pybind/t/io/sensor.cpp, line 93 at r2](https://reviewable.io/reviews/intel-isl/open3d/2801#-MP6mKJU-DaDw3DdXww5:-MP6tCqR-sP_rNCmapry:bkyyy7d) ([raw file](https://github.com/intel-isl/open3d/blob/1a422faf18f556a3a6d78384e43304ae0b7e52bc/cpp/pybind/t/io/sensor.cpp#L93)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Can we be more explicit? Something like "`depth_scale` converts a uint16 depth value `d` to meter by `d / depth_scale`"
</blockquote></details>

Done. 
Number of depth units per meter (depth in m = depth_pixel_value/depth_scale).
___
*[docs/tutorial/sensor/realsense.rst, line 165 at r2](https://reviewable.io/reviews/intel-isl/open3d/2801#-MP6mtG7DKInYbA3P25R:-MP6tSmG2Lt6Vfo8E_8N:b-appoxx) ([raw file](https://github.com/intel-isl/open3d/blob/1a422faf18f556a3a6d78384e43304ae0b7e52bc/docs/tutorial/sensor/realsense.rst#L165)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Will `depth_scale` present here?
</blockquote></details>

No. It's not something the user can configure. It's read only.

**Review by theNded — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2801)* status: all files reviewed, 1 unresolved discussion (waiting on @theNded and @yxlao)

**Review by theNded — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2801)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yxlao)

**Pull request merged**
