### PR TITLE
Better algorithm for downsampling

### PR DESCRIPTION
**Pull request by prewettg**
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2355)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6204444&bid=20238317)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6204444&bid=20238317)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6204444&bid=20238317)

**Review by errissa — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2355)* status: all files reviewed, 1 unresolved discussion (waiting on @prewettg)

___
*[cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp, line 116 at r3](https://reviewable.io/reviews/intel-isl/open3d/2355#-MHaWYD1AG4gsPxGEmsC:-MHaWYD1AG4gsPxGEmsD:b-mbu3t) ([raw file](https://github.com/intel-isl/open3d/blob/1349077446e72f9ec84cb7c7c187d4d9f10059c0/cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp#L116)):*
> ```cpp
>         // Since this is the common case, and is used for every entity,
>         // special-case this to make it fast.
>         std::iota(uint_indices, uint_indices + n_indices, 0);
> ```

Faster than what? the for loop in the else/if below? On my mac, `for (size_t i = 0; i < n_indices; ++i) { uint_indices[i] = IndexType(i); }` was a little faster than `std::iota`. I don't know if this is universally true but something to think about before we merge this.

**Pull request merged**
