### PR TITLE
Hashmap refactor

### PR DESCRIPTION
**Pull request by theNded**
This PR changes non-templated hashmaps to half-templated hashmaps internally for easier integrating downstream libraries (`tbb`, `stdgpu`). The interface is unchanged.
- Now `Key` is templated; internal hashmaps take <Key, uint32_t> as key-value pairs. We explicitly manage value data by ourselves.
- `stdgpu` is ready for use. Initial improvement: ray casting from ~30ms -> ~5ms. 

Part of the benchmark results, with 1M `int3` inputs, of which 1/32 are expected insertions (others are duplicates).
```
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
HashInsertInt3/Backend::TBB_1000000_32          32.0 ms         32.0 ms           22
HashInsertInt3/Backend::Slab_1000000_32         2.60 ms         2.60 ms          256
HashInsertInt3/Backend::StdGPU_1000000_32      0.914 ms        0.913 ms          745
HashFindInt3/Backend::TBB_1000000_32            23.2 ms         23.2 ms           29
HashFindInt3/Backend::Slab_1000000_32           2.41 ms         2.41 ms          291
HashFindInt3/Backend::StdGPU_1000000_32        0.965 ms        0.965 ms          724
```
TODO:
- [x] Switchable backend for hashmaps
- [x] Benchmark setup

Future work:
- [ ] HashSet
- [ ] Templated `eq' function
- [ ] Templated hashmap from C++/CUDA users.

Ready to merge once thrust cmake issue is fixed.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3211)

### CODE REVIEW

**Comment by yxlao** [comment]
Future investigation: there seems to be some issue when there are multiple GPUs in one machine.

This works (GPU 0 is GTX 1080Ti)
```bash
$ make tests -j && CUDA_VISIBLE_DEVICES=0 ./bin/tests --gtest_filter="*Hashmap*"
```

This doesn't work (GPU 1 is GTX 1080)
```bash
$ make tests -j && CUDA_VISIBLE_DEVICES=1 ./bin/tests --gtest_filter="*Hashmap*"
```

The error is
```bash
[ RUN      ] Hashmap/HashmapPermuteDevices.Erase/1
stdgpu : CUDA ERROR :
  Error     : an illegal memory access was encountered
  File      : /home/yixing/repo/Open3D/build/stdgpu/src/ext_stdgpu/src/stdgpu/cuda/impl/memory.cpp:147
  Function  : void stdgpu::cuda::dispatch_memcpy(void*, const void*, stdgpu::index64_t, stdgpu::dynamic_memory_type, stdgpu::dynamic_memory_type)
terminate called without an active exception
```

**Comment by yxlao** [comment]
```
/home/runner/work/Open3D/Open3D/cpp/open3d/core/hashmap/Dispatch.h:42:0: error: ignoring #pragma unroll  [-Werror=unknown-pragmas]
cpp/open3d/core/CMakeFiles/core.dir/build.make:910: recipe for target 'cpp/open3d/core/CMakeFiles/core.dir/hashmap/CUDA/CreateCUDAHashmap.cu.o' failed
         for (size_t i = 0; i < N; ++i) {
 
/home/runner/work/Open3D/Open3D/cpp/open3d/core/hashmap/Dispatch.h:52:0: error: ignoring #pragma unroll  [-Werror=unknown-pragmas]
         for (size_t i = 0; i < N; ++i) {
 
/home/runner/work/Open3D/Open3D/cpp/open3d/core/hashmap/Dispatch.h:73:0: error: ignoring #pragma unroll  [-Werror=unknown-pragmas]
         for (size_t i = 0; i < N; ++i) {
```
I'll be pushing some comments to try to address this

**Comment by yxlao** [comment]
Update: CI failed on `Hashmap/HashmapPermuteDevices.Erase/1` as well
image

**Comment by theNded** [comment]
> Update: CI failed on `Hashmap/HashmapPermuteDevices.Erase/1` as well
> image

I think I find the issue, let me fix soon

**Comment by yxlao** [comment]
> I think I find the issue, let me fix soon. Not happening on my machine though.
Yes, it fixed the problem on my local machine as well.

**Review by yxlao — CHANGES_REQUESTED** [review]
LGTM in general with a few comments

> Reviewed 6 of 31 files at r1, 2 of 5 files at r2, 29 of 33 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 5 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3211#-:-MXZuvb85pKrY_LwhJBs:b2gawi1)* status: 45 of 46 files reviewed, 15 unresolved discussions (waiting on @theNded)

___
*[cpp/benchmarks/core/Hashmap.cpp, line 58 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWlepf77XAl08HdU4D:-MXWlepf77XAl08HdU4E:b-1vlli1) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/core/Hashmap.cpp#L58)):*
> ```cpp
>         for (int i = 0; i < count; ++i) {
>             int v = indices[i] % slots;
>             keys_[i] = v * k_factor_;
> ```

i would do `K(v * k_factor_)` to be more explicit, currently, this relies on implicit type conversion
___
*[cpp/benchmarks/core/Hashmap.cpp, line 59 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWln_L2gE5VRLzzznJ:-MXWfexg7Zpp4YeAhx3J:bnj7hl0) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/core/Hashmap.cpp#L59)):*
> ```cpp
>             int v = indices[i] % slots;
>             keys_[i] = v * k_factor_;
>             vals_[i] = v;
> ```

same as above
___
*[cpp/benchmarks/core/Hashmap.cpp, line 78 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWlrOQ33p8rL4h9tLn:-MXWlrOQ33p8rL4h9tLo:brolj9a) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/core/Hashmap.cpp#L78)):*
> ```cpp
> 
> #ifdef BUILD_CUDA_MODULE
>     if (backend == Backend::Slab || backend == Backend::StdGPU) {
> ```

we don't need to check backends as long as it is `BUILD_CUDA_MODULE`, same for other instances
___
*[cpp/benchmarks/core/Hashmap.cpp, line 87 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWn2gE1XAZPbOE2a1M:-MXWn2gE1XAZPbOE2a1N:bse87co) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/core/Hashmap.cpp#L87)):*
> ```cpp
>     Hashmap hashmap(capacity, Dtype::Int32, Dtype::Int32, {1}, {1}, device,
>                     backend);
>     Tensor addrs, masks;
> ```

Recommend adding warm-up (that is, do a `Insert()`) before the main benchmark loop.
Especially for CUDA, depending on the compiler flags, it might need to do JIT at the first run.
___
*[cpp/benchmarks/core/Hashmap.cpp, line 90 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWoORbDBEnru22chbc:-MXWoORbDBEnru22chbd:b-msf8r4) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/core/Hashmap.cpp#L90)):*
> ```cpp
> 
>     for (auto _ : state) {
>         hashmap.Insert(keys, values, addrs, masks);
> ```

The performance could be different when we insert to a new map v.s. insert to a map with existing values (e.g. it may need to resolve more conflicts).

We shall probably create a new map for each loop and test it from scratch. This should be possible with timer controls: https://github.com/google/benchmark/blob/master/README.md#controlling-timers . So, probably something like this:

```cpp
state.PauseTiming();
Hashmap hashmap(capacity, ...);
state.ResumeTiming();

hashmap.Insert(xxx);

state.PauseTiming();
sanity_checks();
state.ResumeTiming();
```

We may apply the same idea to the other benchmarks as well, e.g. the other `Insert` test for `Int3`.
___
*[cpp/benchmarks/core/Hashmap.cpp, line 126 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWpTqn3r_pZxY1WrRg:-MXWpTqn3r_pZxY1WrRh:b-jh36ek) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/core/Hashmap.cpp#L126)):*
> ```cpp
> }
> 
> class int3 {
> ```

`int3` -> `Int3` 
___
*[cpp/benchmarks/core/Hashmap.cpp, line 201 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXYuRAZ7dLn8Q_2s7uU:-MXYuRAZ7dLn8Q_2s7uV:bxpf1o4) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/core/Hashmap.cpp#L201)):*
> ```cpp
> }
> 
> /// No-duplicate
> ```

remove comments?
___
*[cpp/benchmarks/t/geometry/PointCloud.cpp, line 88 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWrE5o4bUWdxBB5m3V:-MXWrE5pCngSycQ521GJ:bi5z79r) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/t/geometry/PointCloud.cpp#L88)):*
> ```cpp
>                      float voxel_size,
>                      const core::Backend& backend) {
>     auto pcd = io::CreatePointCloudFromFile(path);
> ```

- can we use `t::io`
- the legacy point cloud is `double`, the new point cloud is `float32`, how does that impact the benchmark? does the `VoxelDownSample` support `double` as well?
___
*[cpp/open3d/core/hashmap/DeviceHashmap.h, line 37 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXYzPC16xQOanePxudH:-MXYzPC16xQOanePxudI:b13jpbo) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/open3d/core/hashmap/DeviceHashmap.h#L37)):*
> ```objc
> namespace core {
> 
> enum class Backend;
> ```

i would call this `HashMapBackend`, otherwise `core::Backend` maybe confused with `core::Device`
___
*[cpp/open3d/core/hashmap/Dispatch.h, line 84 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXZRf7E0OVLfwSdMYde:-MXZRf7E0OVLfwSdMYdf:b2fmna) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/open3d/core/hashmap/Dispatch.h#L84)):*
> ```objc
> 
> // TODO: dispatch more combinations.
> #define DISPATCH_DTYPE_AND_DIM_TO_TEMPLATE(DTYPE, DIM, ...)                  \
> ```

we can put this `#define` on top
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 31 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXYwjG27Sp6R7oJJGmw:-MXYwjG38NJRsUgp531M:bwdx7mu) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/open3d/core/hashmap/Hashmap.h#L31)):*
> ```objc
> #include "open3d/core/hashmap/HashmapBuffer.h"
> 
> #pragma once
> ```

move this to the top?
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 37 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXZibml4wAp2luAhEjf:-MXZibml4wAp2luAhEjg:b-u393u0) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/open3d/core/hashmap/Hashmap.h#L37)):*
> ```objc
> class DeviceHashmap;
> 
> enum class Backend { Slab, StdGPU, TBB, Default };
> ```

I would call them `SLAB, STDGPU, TBB, DEFAULT`. 
In other locations we use the name e.g. `STDGPUHashmap.h`, it would be good to be consistent.
___
*[cpp/open3d/core/hashmap/CUDA/STDGPUHashmap.h, line 146 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXZlM0HBG-IQRVhUkWd:-MXZlM0HBG-IQRVhUkWe:b-o1do7t) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/open3d/core/hashmap/CUDA/STDGPUHashmap.h#L146)):*
> ```objc
>                                         bool* output_masks,
>                                         int64_t count) {
>     int64_t new_size = Size() + count;
> ```

Can we directly call `Insert(input_keys, nullptr, output_masks, count);`? The code is pretty much the same.
___
*[cpp/open3d/core/hashmap/CUDA/STDGPUHashmap.h, line 235 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXZtxSjAqBQnj5Rx3MI:-MXZtxSjAqBQnj5Rx3MJ:bfsv8e2) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/open3d/core/hashmap/CUDA/STDGPUHashmap.h#L235)):*
> ```objc
> 
> template <typename Key>
> struct collect {
> ```

capitalize `Collect()`, probably something more meaningful like `ExtractValue()`
___
*[examples/CMakeLists.txt, line 4 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWXs2_BHTbC_fcOXn4:-MXWXs2a58BUvmlsw0KV:bo3wlrm) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/examples/CMakeLists.txt#L4)):*
> ```CMake
> 
> if (BUILD_CUDA_MODULE)
>     # TODO: remove
> ```

we could remove `examples/hashmap/*`, previously it is mainly used for debugging

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3211)* status: 23 of 45 files reviewed, 15 unresolved discussions (waiting on @yxlao)

___
*[cpp/benchmarks/core/Hashmap.cpp, line 58 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWlepf77XAl08HdU4D:-MXdFB9g9Lu9CLuuxbdy:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/core/Hashmap.cpp#L58)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

i would do `K(v * k_factor_)` to be more explicit, currently, this relies on implicit type conversion
</blockquote></details>

Done.
___
*[cpp/benchmarks/core/Hashmap.cpp, line 59 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWln_L2gE5VRLzzznJ:-MXdFFDn3Bq-8H0bZxr6:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/core/Hashmap.cpp#L59)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[cpp/benchmarks/core/Hashmap.cpp, line 78 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWlrOQ33p8rL4h9tLn:-MXdFP9xE3VylaCY4fYf:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/core/Hashmap.cpp#L78)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we don't need to check backends as long as it is `BUILD_CUDA_MODULE`, same for other instances
</blockquote></details>

Done.
___
*[cpp/benchmarks/core/Hashmap.cpp, line 87 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWn2gE1XAZPbOE2a1M:-MXdFrCa09cfMv-QD1kd:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/core/Hashmap.cpp#L87)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Recommend adding warm-up (that is, do a `Insert()`) before the main benchmark loop.
Especially for CUDA, depending on the compiler flags, it might need to do JIT at the first run.
</blockquote></details>

Done.
___
*[cpp/benchmarks/core/Hashmap.cpp, line 90 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWoORbDBEnru22chbc:-MXdITEu-qhZZZxKByx3:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/core/Hashmap.cpp#L90)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

The performance could be different when we insert to a new map v.s. insert to a map with existing values (e.g. it may need to resolve more conflicts).

We shall probably create a new map for each loop and test it from scratch. This should be possible with timer controls: https://github.com/google/benchmark/blob/master/README.md#controlling-timers . So, probably something like this:

```cpp
state.PauseTiming();
Hashmap hashmap(capacity, ...);
state.ResumeTiming();

hashmap.Insert(xxx);

state.PauseTiming();
sanity_checks();
state.ResumeTiming();
```

We may apply the same idea to the other benchmarks as well, e.g. the other `Insert` test for `Int3`.
</blockquote></details>

Done.
___
*[cpp/benchmarks/core/Hashmap.cpp, line 126 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWpTqn3r_pZxY1WrRg:-MXdJX5IA9BG0LwGLFKv:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/core/Hashmap.cpp#L126)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`int3` -> `Int3` 
</blockquote></details>

Done.
___
*[cpp/benchmarks/core/Hashmap.cpp, line 201 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXYuRAZ7dLn8Q_2s7uU:-MXdJ_dj8KZK601vfOI0:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/core/Hashmap.cpp#L201)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove comments?
</blockquote></details>

Done.
___
*[cpp/benchmarks/t/geometry/PointCloud.cpp, line 88 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWrE5o4bUWdxBB5m3V:-MXdJg-95tH30HRyASl4:b-mv9h7d) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/benchmarks/t/geometry/PointCloud.cpp#L88)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

- can we use `t::io`
- the legacy point cloud is `double`, the new point cloud is `float32`, how does that impact the benchmark? does the `VoxelDownSample` support `double` as well?
</blockquote></details>

The legacy implementation is not fundamentally the same operation, put here only for reference. double shouldn't affect though, since all points are converted to int types before insertion.
___
*[cpp/open3d/core/hashmap/DeviceHashmap.h, line 37 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXYzPC16xQOanePxudH:-MXdMjVu5QROuKTZFvWa:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/open3d/core/hashmap/DeviceHashmap.h#L37)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

i would call this `HashMapBackend`, otherwise `core::Backend` maybe confused with `core::Device`
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/Dispatch.h, line 84 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXZRf7E0OVLfwSdMYde:-MXdN8pn4rnQPmNNlsVC:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/open3d/core/hashmap/Dispatch.h#L84)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we can put this `#define` on top
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 31 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXYwjG27Sp6R7oJJGmw:-MXdNDyN1huWpdbfQUiV:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/open3d/core/hashmap/Hashmap.h#L31)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

move this to the top?
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 37 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXZibml4wAp2luAhEjf:-MXdOCXf7RSfG1Wlc1V2:b-aioj7i) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/open3d/core/hashmap/Hashmap.h#L37)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

I would call them `SLAB, STDGPU, TBB, DEFAULT`. 
In other locations we use the name e.g. `STDGPUHashmap.h`, it would be good to be consistent.
</blockquote></details>

I feel like all uppercase feels more like macros, plus we have SlabHashmap.h. So I changed `STDGPUHashmap.h` to `StdGPUHashmap.h` instead.
___
*[examples/CMakeLists.txt, line 4 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXWXs2_BHTbC_fcOXn4:-MXdP6R8-6zvsnLJgOcN:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/examples/CMakeLists.txt#L4)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we could remove `examples/hashmap/*`, previously it is mainly used for debugging
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/CUDA/STDGPUHashmap.h, line 146 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXZlM0HBG-IQRVhUkWd:-MXdOmWQDiyzIa-oEj9Y:bhkvep6) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/open3d/core/hashmap/CUDA/STDGPUHashmap.h#L146)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Can we directly call `Insert(input_keys, nullptr, output_masks, count);`? The code is pretty much the same.
</blockquote></details>

Good point. Also updated for SlabHash and TBB.
___
*[cpp/open3d/core/hashmap/CUDA/STDGPUHashmap.h, line 235 at r7](https://reviewable.io/reviews/intel-isl/open3d/3211#-MXZtxSjAqBQnj5Rx3MI:-MXdOwjLCIn0xi51beHr:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/e4635d4dda04e44a5940fb3c29926c1844829d0d/cpp/open3d/core/hashmap/CUDA/STDGPUHashmap.h#L235)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

capitalize `Collect()`, probably something more meaningful like `ExtractValue()`
</blockquote></details>

Done.

**Review by yxlao — APPROVED** [review]
> Reviewed 23 of 25 files at r8.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3211)* status: all files reviewed, 1 unresolved discussion (waiting on @yxlao)

**Pull request merged**
