### PR TITLE
nms op for pytorch and tensorflow

### PR DESCRIPTION
**Pull request by yxlao**
Some notes:
1. In the original impl, the op is implemented in Python + CPP. Where the Python part does the sorting in PyTorch. In this implementation, the sorting part is moved to C++ and it is done by thrust. This is required since in TensorFlow we cannot use PyTorch's sorting. 
2. Added CPU implementation.
3. Same as the original impl, the CUDA op requires host + device operations.

This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2615)

### CODE REVIEW

**Comment by yxlao** [comment]
Benchmark for 1000 boxes:
```
$ pytest  ../python/test/ml_ops/test_nms_bench.py -s
nms_cpu      takes 0.0453237057 seconds
nms_cuda     takes 0.0020058155 seconds
nms_author   takes 0.0019804001 seconds
```

Benchmark scripts
```python
import open3d as o3d
import numpy as np
import torch
import iou3d_cuda
import time
import open3d.ml.torch


def timeit(func):

    def timed_func(*args, **kwargs):
        # Warm up.
        func(*args, **kwargs)

        # Benchmark.
        repeat = 5
        s = time.time()
        for _ in range(repeat):
            result = func(*args, **kwargs)
        elapsed_time = time.time() - s
        avg_time = elapsed_time / repeat
        func_name = "{: <12}".format(func.__name__)
        print(f"{func_name} takes {avg_time:.10f} seconds")
        return result

    return timed_func


@timeit
def nms_cpu(boxes, scores, thresh):
    return o3d.ml.torch.ops.nms(boxes, scores, thresh)


@timeit
def nms_cuda(boxes, scores, thresh):
    return o3d.ml.torch.ops.nms(boxes, scores, thresh)


@timeit
def nms_author(boxes, scores, thresh):
    order = scores.sort(0, descending=True)[1]
    boxes = boxes[order].contiguous()
    keep = torch.LongTensor(boxes.size(0))
    num_out = iou3d_cuda.nms_gpu(boxes, keep, thresh)
    return order[keep[:num_out].cuda()].contiguous()


def run_impls(np_boxes, np_scores, thresh):
    cpu_boxes = torch.Tensor(np_boxes)
    cpu_scores = torch.Tensor(np_scores)
    cuda_boxes = cpu_boxes.cuda()
    cuda_scores = cpu_scores.cuda()

    print()
    result_cpu = nms_cpu(cpu_boxes, cpu_scores, thresh).cpu().numpy()
    result_cuda = nms_cuda(cuda_boxes, cuda_scores, thresh).cpu().numpy()
    result_author = nms_author(cuda_boxes, cuda_scores, thresh).cpu().numpy()

    np.testing.assert_equal(result_cpu, result_author)
    np.testing.assert_equal(result_cuda, result_author)


def test_rand():
    num_boxes = 1000
    np_boxes = np.random.rand(num_boxes, 5)
    np_scores = np.random.rand(num_boxes,)
    thresh = np.random.rand()
    run_impls(np_boxes, np_scores, thresh)
```

**Review by benjaminum — CHANGES_REQUESTED** [review]
Do you think it is possible to add support for streams in the now or in the future? Other comments are mostly minor stuff.

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2615#-:-MM9hbm_4QB05mxGSmxZ:b-oqjq7s)* status: all files reviewed, 6 unresolved discussions (waiting on @Prantl, @sanskar107, and @yxlao)

___
*[cpp/open3d/ml/Helper.h, line 45 at r1](https://reviewable.io/reviews/intel-isl/open3d/2615#-MM9cIHx-TA_7A2SIsfi:-MM9cIHx-TA_7A2SIsfj:b-mwpmmz) ([raw file](https://github.com/intel-isl/open3d/blob/38b0f9f4c623a35d925405d96efb19d917be5dd2/cpp/open3d/ml/Helper.h#L45)):*
> ```objc
> 
> #ifdef BUILD_CUDA_MODULE
> /// TODO: Link Open3D and use OPEN3D_CUDA_CHECK instead.
> ```

I am working on it
___
*[cpp/open3d/ml/impl/misc/Nms.cpp, line 45 at r1](https://reviewable.io/reviews/intel-isl/open3d/2615#-MM9cuFd4J-2XGt8AljX:-MM9cuFe0fMjk_gLkdsh:b37cjlu) ([raw file](https://github.com/intel-isl/open3d/blob/38b0f9f4c623a35d925405d96efb19d917be5dd2/cpp/open3d/ml/impl/misc/Nms.cpp#L45)):*
> ```cpp
> #include "open3d/ml/impl/misc/NmsImpl.h"
> 
> #define DIVUP(m, n) ((m) / (n) + ((m) % (n) > 0))
> ```

There is a DivUp in utility/Helper.h, too
___
*[cpp/open3d/ml/impl/misc/Nms.cu, line 45 at r1](https://reviewable.io/reviews/intel-isl/open3d/2615#-MM9dh3OBLvUBIk8qxqx:-MM9dh3OBLvUBIk8qxqy:byr4ffv) ([raw file](https://github.com/intel-isl/open3d/blob/38b0f9f4c623a35d925405d96efb19d917be5dd2/cpp/open3d/ml/impl/misc/Nms.cu#L45)):*
> ```Cuda
> #include "open3d/ml/impl/misc/NmsImpl.h"
> 
> #define DIVUP(m, n) ((m) / (n) + ((m) % (n) > 0))
> ```

see above
___
*[cpp/open3d/ml/impl/misc/NmsImpl.h, line 60 at r1](https://reviewable.io/reviews/intel-isl/open3d/2615#-MM9eJKa1UOvsrrnESza:-MM9eJKb4OxUJQIzKpzd:b-gx4zub) ([raw file](https://github.com/intel-isl/open3d/blob/38b0f9f4c623a35d925405d96efb19d917be5dd2/cpp/open3d/ml/impl/misc/NmsImpl.h#L60)):*
> ```objc
> }
> 
> OPEN3D_HOST_DEVICE inline float Cross(const Point &p1,
> ```

Maybe we can add it to the MiniVec class?
___
*[cpp/open3d/ml/tensorflow/misc/NmsOps.cpp, line 59 at r1](https://reviewable.io/reviews/intel-isl/open3d/2615#-MM9gmou-xi3wokErdl7:-MM9gmou-xi3wokErdl8:b2nh4j4) ([raw file](https://github.com/intel-isl/open3d/blob/38b0f9f4c623a35d925405d96efb19d917be5dd2/cpp/open3d/ml/tensorflow/misc/NmsOps.cpp#L59)):*
> ```cpp
>         })
>         .Doc(R"doc(
> undocumented for now
> ```

:-(
___
*[python/test/ml_ops/test_nms.py, line 34 at r1](https://reviewable.io/reviews/intel-isl/open3d/2615#-MM9gtfw1f0yw2-jlNCw:-MM9gtfw1f0yw2-jlNCx:b-2xmxbn) ([raw file](https://github.com/intel-isl/open3d/blob/38b0f9f4c623a35d925405d96efb19d917be5dd2/python/test/ml_ops/test_nms.py#L34)):*
> ```Python
> pytestmark = mltest.default_marks
> ```

Can we add some extreme cases, e.g., empty boxes with shape [0,5]? Not sure if this is likely but sometimes things can happen like all point are invalid etc.
Additional tests with larger random data could improve coverage.

**Review by Prantl — APPROVED** [review]

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2615)* status: 10 of 15 files reviewed, 6 unresolved discussions (waiting on @benjaminum and @sanskar107)

___
*[cpp/open3d/ml/Helper.h, line 45 at r1](https://reviewable.io/reviews/intel-isl/open3d/2615#-MM9cIHx-TA_7A2SIsfi:-MMQ0IkR-b0VMFz7Lqta:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/38b0f9f4c623a35d925405d96efb19d917be5dd2/cpp/open3d/ml/Helper.h#L45)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

I am working on it
</blockquote></details>

Done.
___
*[cpp/open3d/ml/impl/misc/Nms.cpp, line 45 at r1](https://reviewable.io/reviews/intel-isl/open3d/2615#-MM9cuFd4J-2XGt8AljX:-MMQ0K7n7TIIasXwiEYQ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/38b0f9f4c623a35d925405d96efb19d917be5dd2/cpp/open3d/ml/impl/misc/Nms.cpp#L45)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

There is a DivUp in utility/Helper.h, too
</blockquote></details>

Done.
___
*[cpp/open3d/ml/impl/misc/Nms.cu, line 45 at r1](https://reviewable.io/reviews/intel-isl/open3d/2615#-MM9dh3OBLvUBIk8qxqx:-MMQ0K_R45QfSRl-0hzu:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/38b0f9f4c623a35d925405d96efb19d917be5dd2/cpp/open3d/ml/impl/misc/Nms.cu#L45)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[cpp/open3d/ml/impl/misc/NmsImpl.h, line 60 at r1](https://reviewable.io/reviews/intel-isl/open3d/2615#-MM9eJKa1UOvsrrnESza:-MMQ0LHF5hphRHk-DzIl:b-tuqqut) ([raw file](https://github.com/intel-isl/open3d/blob/38b0f9f4c623a35d925405d96efb19d917be5dd2/cpp/open3d/ml/impl/misc/NmsImpl.h#L60)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Maybe we can add it to the MiniVec class?
</blockquote></details>

Typically cross product is between 3d vectors, and we're calling it informally "cross" here. I would skip this one and add cross to MiniVec later when we have the typical cross products.
___
*[cpp/open3d/ml/tensorflow/misc/NmsOps.cpp, line 59 at r1](https://reviewable.io/reviews/intel-isl/open3d/2615#-MM9gmou-xi3wokErdl7:-MMQ0wyT1uDHKX_ehenI:b-vvgyn4) ([raw file](https://github.com/intel-isl/open3d/blob/38b0f9f4c623a35d925405d96efb19d917be5dd2/cpp/open3d/ml/tensorflow/misc/NmsOps.cpp#L59)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

:-(
</blockquote></details>

docs added
___
*[python/test/ml_ops/test_nms.py, line 34 at r1](https://reviewable.io/reviews/intel-isl/open3d/2615#-MM9gtfw1f0yw2-jlNCw:-MMQ0ySG1DsOqwrjO1wg:bu1bxdn) ([raw file](https://github.com/intel-isl/open3d/blob/38b0f9f4c623a35d925405d96efb19d917be5dd2/python/test/ml_ops/test_nms.py#L34)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Can we add some extreme cases, e.g., empty boxes with shape [0,5]? Not sure if this is likely but sometimes things can happen like all point are invalid etc.
Additional tests with larger random data could improve coverage.
</blockquote></details>

that's a good point, this actually breaks the cuda impl, and now it is handled.

**Review by benjaminum — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2615)* status: all files reviewed, 6 unresolved discussions (waiting on @benjaminum, @sanskar107, and @yxlao)

___
*[cpp/open3d/ml/tensorflow/misc/NmsOps.cpp, line 59 at r1](https://reviewable.io/reviews/intel-isl/open3d/2615#-MM9gmou-xi3wokErdl7:-MMRV4zUC8Us45qx0yLJ:b2nh4j5) ([raw file](https://github.com/intel-isl/open3d/blob/38b0f9f4c623a35d925405d96efb19d917be5dd2/cpp/open3d/ml/tensorflow/misc/NmsOps.cpp#L59)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

docs added
</blockquote></details>

:-)

**Pull request merged**
