### PR TITLE
test import of torch and tensorflow

### PR DESCRIPTION
**Pull request by benjaminum**
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2496)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ python/open3d/ml/torch/__init__.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6353141&bid=20628204)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ python/open3d/ml/torch/__init__.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6353141&bid=20628204)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ python/open3d/ml/torch/__init__.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6353141&bid=20628204)

**Review by ssheorey — APPROVED** [review]
This looks good. As a consequence of this though we'll need to provide CUDA version specific wheels, like PyTorch. Or package torch_ops library with multiple CUDA versions in our wheel.

**Pull request merged**
