### PR TITLE
Port to CMAKE_CUDA_ARCHITECTURES

### PR DESCRIPTION
**Pull request by stotko**
- Port to modern `CMAKE_CUDA_ARCHITECTURES` and drop the old `FindCUDA` approach.
- Support for CUDA 11.0 and initial work to support CUDA 11.1 and CC 8.6 (RTX 30XX) GPUs.
- Architecture detection is now implemented by our own.
- Explicit bump to C++14 since this is already implicitly required.

Replaces #3228.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3316)

### CODE REVIEW

**Review by benjaminum — COMMENTED** [review]
> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3316)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @stotko and @yxlao)

___
*[3rdparty/CMake/FindPytorch.cmake, line 40 at r1](https://reviewable.io/reviews/intel-isl/open3d/3316#-MYoK25rBVocKH0P-kuu:-MYoK25rBVocKH0P-kuv:b45wuk9) ([raw file](https://github.com/intel-isl/open3d/blob/72ef5d70e3467a91e5cf836df435c64649f6b9b9/3rdparty/CMake/FindPytorch.cmake#L40)):*
> ```CMake
>                  NO_DEFAULT_PATH)
> 
>     if(BUILD_CUDA_MODULE)
> ```

Moving this inside the if body seems right but there could be an issue if CUDA is not installed in the standard location, we build without CUDA, and torch was build with CUDA. I will check..

**Review by benjaminum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3316)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @stotko and @yxlao)

___
*[3rdparty/CMake/FindPytorch.cmake, line 40 at r1](https://reviewable.io/reviews/intel-isl/open3d/3316#-MYoK25rBVocKH0P-kuu:-MYoSSZM1Y9gnZMBkUtN:bo8dl6a) ([raw file](https://github.com/intel-isl/open3d/blob/72ef5d70e3467a91e5cf836df435c64649f6b9b9/3rdparty/CMake/FindPytorch.cmake#L40)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Moving this inside the if body seems right but there could be an issue if CUDA is not installed in the standard location, we build without CUDA, and torch was build with CUDA. I will check..
</blockquote></details>

It works

**Review by yxlao — COMMENTED** [review]
> Reviewed 7 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3316)* status: all files reviewed, 2 unresolved discussions (waiting on @stotko)

___
*[3rdparty/stdgpu/stdgpu.cmake, line 22 at r2](https://reviewable.io/reviews/intel-isl/open3d/3316#-MYp8jqB8TKBmVBgqTMa:-MYp8jqB8TKBmVBgqTMb:b-wegjqr) ([raw file](https://github.com/intel-isl/open3d/blob/ffa2b929f1a8a54c8b86defa1e3a69b1ca404100/3rdparty/stdgpu/stdgpu.cmake#L22)):*
> ```CMake
>         -DCMAKE_CXX_COMPILER_LAUNCHER=${CMAKE_CXX_COMPILER_LAUNCHER}
>         -DCMAKE_CUDA_COMPILER_LAUNCHER=${CMAKE_CUDA_COMPILER_LAUNCHER}
>         -DCMAKE_CUDA_ARCHITECTURES=${CMAKE_CUDA_ARCHITECTURES}
> ```

just to confirm, if there are multiple CUDA architectures, could a CMake pass `-DCMAKE_CUDA_ARCHITECTURES` as a list?

**Review by stotko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3316)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @benjaminum, @stotko, and @yxlao)

___
*[3rdparty/stdgpu/stdgpu.cmake, line 22 at r2](https://reviewable.io/reviews/intel-isl/open3d/3316#-MYp8jqB8TKBmVBgqTMa:-MYptxT_Eqd72tSYOIuN:b-1jyue3) ([raw file](https://github.com/intel-isl/open3d/blob/ffa2b929f1a8a54c8b86defa1e3a69b1ca404100/3rdparty/stdgpu/stdgpu.cmake#L22)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

just to confirm, if there are multiple CUDA architectures, could a CMake pass `-DCMAKE_CUDA_ARCHITECTURES` as a list?
</blockquote></details>

Good catch. That was causing the CI failures. Fixed.

**Review by yxlao — APPROVED** [review]
LGTM. 

BTW, since GitHub squashs the commits at merge, we don't need to squash them manually. This will also be more friendly for Reviewable since it operates on commit history.

**Review by benjaminum — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3316)* status: all files reviewed, 2 unresolved discussions (waiting on @stotko and @yxlao)

**Pull request merged**
