### PR TITLE
NanoFlann Parallel Search

### PR DESCRIPTION
**Pull request by junha-l**
parallelize knn & radius search in NanoFlannIndex using tbb

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2305)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/core/nns/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/core/nns/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Review by benjaminum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2305)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @benjaminum, @junha-l, and @yxlao)

___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 122 at r2](https://reviewable.io/reviews/intel-isl/open3d/2305#-MGmYpP751q0DdUpdvN7:-MGmYpP751q0DdUpdvN8:b-jmny2q) ([raw file](https://github.com/intel-isl/open3d/blob/af7fb3ee896af4a06626a89a7c57b58acf5110af/cpp/open3d/core/nns/NanoFlannIndex.cpp#L122)):*
> ```cpp
>                 tbb::blocked_range<size_t>(0, num_query_points),
>                 [&](const tbb::blocked_range<size_t> &r) {
>                     std::vector<size_t> single_indices(knn);
> ```

For the knn search we can directly allocate the [num_queries, k] tensors. If there are less than k points in the data we can use -1 as index. This way we can avoid the intermediate vectors.

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2305)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @benjaminum and @yxlao)

___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 122 at r2](https://reviewable.io/reviews/intel-isl/open3d/2305#-MGmYpP751q0DdUpdvN7:-MGnYNP904GOXYsAU-j_:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/af7fb3ee896af4a06626a89a7c57b58acf5110af/cpp/open3d/core/nns/NanoFlannIndex.cpp#L122)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

For the knn search we can directly allocate the [num_queries, k] tensors. If there are less than k points in the data we can use -1 as index. This way we can avoid the intermediate vectors.
</blockquote></details>

Done.

**Comment by junha-l** [comment]
seems that there is a build error on windows and it is related to tbb, but I don't know what is wrong exactly.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Review by benjaminum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2305)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @junha-l and @yxlao)

___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 122 at r2](https://reviewable.io/reviews/intel-isl/open3d/2305#-MGmYpP751q0DdUpdvN7:-MGnt4Vl0tM5dFWtsErN:b7zu23n) ([raw file](https://github.com/intel-isl/open3d/blob/af7fb3ee896af4a06626a89a7c57b58acf5110af/cpp/open3d/core/nns/NanoFlannIndex.cpp#L122)):*
<details><summary><i>Previously, junha-l (Junha Lee) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is it possible to let nanoflann directly write to the batched_indices and batched_distances tensors or is there a problem with the types?

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2305)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @benjaminum and @yxlao)

___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 122 at r2](https://reviewable.io/reviews/intel-isl/open3d/2305#-MGmYpP751q0DdUpdvN7:-MGo53It8oSY7itNA5c1:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/af7fb3ee896af4a06626a89a7c57b58acf5110af/cpp/open3d/core/nns/NanoFlannIndex.cpp#L122)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Is it possible to let nanoflann directly write to the batched_indices and batched_distances tensors or is there a problem with the types?
</blockquote></details>

Done.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 2 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2305)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @benjaminum, @junha-l, and @yxlao)

___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 113 at r5](https://reviewable.io/reviews/intel-isl/open3d/2305#-MGo6xoo19dZoWz_KNde:-MGo6xopBwJf2WEwGP89:b-wrnpaz) ([raw file](https://github.com/intel-isl/open3d/blob/de99bbee9e4026d5a72c88d090fa94e4930b663d/cpp/open3d/core/nns/NanoFlannIndex.cpp#L113)):*
> ```cpp
>     DISPATCH_FLOAT32_FLOAT64_DTYPE(dtype, [&]() {
>         Tensor batch_indices =
>                 Tensor::Ones({num_query_points, knn}, Dtype::Int64);
> ```

Tensor::Full() can initialize with value
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 205 at r5](https://reviewable.io/reviews/intel-isl/open3d/2305#-MGoADtj1cVUmBTcWCrR:-MGoADtk99pUKlaJfNn9:b5b5di9) ([raw file](https://github.com/intel-isl/open3d/blob/de99bbee9e4026d5a72c88d090fa94e4930b663d/cpp/open3d/core/nns/NanoFlannIndex.cpp#L205)):*
> ```cpp
>         nanoflann::SearchParams params;
> 
>         // check if the raii has negative values;
> ```

let's update all the comments with capitalization and punctuation:

```cpp
// Check if the raii has negative values.
```
In general, we follow: https://google.github.io/styleguide/cppguide.html#Punctuation,_Spelling_and_Grammar

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2305)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @benjaminum and @yxlao)

___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 113 at r5](https://reviewable.io/reviews/intel-isl/open3d/2305#-MGo6xoo19dZoWz_KNde:-MGqsOJjCK4C1zPgoBH4:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/de99bbee9e4026d5a72c88d090fa94e4930b663d/cpp/open3d/core/nns/NanoFlannIndex.cpp#L113)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Tensor::Full() can initialize with value
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 205 at r5](https://reviewable.io/reviews/intel-isl/open3d/2305#-MGoADtj1cVUmBTcWCrR:-MGqsPD24nrnbioJmQZD:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/de99bbee9e4026d5a72c88d090fa94e4930b663d/cpp/open3d/core/nns/NanoFlannIndex.cpp#L205)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

let's update all the comments with capitalization and punctuation:

```cpp
// Check if the raii has negative values.
```
In general, we follow: https://google.github.io/styleguide/cppguide.html#Punctuation,_Spelling_and_Grammar
</blockquote></details>

Done.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Comment by yxlao** [comment]
@junha-l looks like we're almost there, the approach you use is very close, seems like we need to enable CMP0091 policy in TBB's cmake

I tried manually patching TBB with the following code and it works:
```cmake
##### begin open3d patch
if(POLICY CMP0091)
    cmake_policy(SET CMP0091 NEW)
endif()
option(STATIC_WINDOWS_RUNTIME "Use static (MT/MTd) Windows runtime" OFF)
if(STATIC_WINDOWS_RUNTIME)
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()
##### end open3d patch
```
Alternatively, we may need to use the old policy and modify the CXX flags explicitly.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Comment by junha-l** [comment]
> @junha-l looks like we're almost there, the approach you use is very close, seems like we need to enable CMP0091 policy in TBB's cmake
> 
> I tried manually patching TBB with the following code and it works:
> 
> ```cmake
> ##### begin open3d patch
> if(POLICY CMP0091)
>     cmake_policy(SET CMP0091 NEW)
> endif()
> option(STATIC_WINDOWS_RUNTIME "Use static (MT/MTd) Windows runtime" OFF)
> if(STATIC_WINDOWS_RUNTIME)
>     set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
> endif()
> ##### end open3d patch
> ```
> 
> Alternatively, we may need to use the old policy and modify the CXX flags explicitly.

Awesome! Thanks for the help @yxlao

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r8, 2 of 3 files at r12, 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2305)* status: all files reviewed, 4 unresolved discussions (waiting on @benjaminum, @junha-l, and @yxlao)

___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 115 at r13](https://reviewable.io/reviews/intel-isl/open3d/2305#-MHKd2L33Y-HA_ozWF8N:-MHKd2L4AdN0UjlwAlM2:bb94h5a) ([raw file](https://github.com/intel-isl/open3d/blob/54b30402568bf251f511176c4b59cbb4622e3e0c/cpp/open3d/core/nns/NanoFlannIndex.cpp#L115)):*
> ```cpp
>                 Tensor::Full({num_query_points, knn}, -1, Dtype::Int64);
>         Tensor batch_distances = Tensor::Full({num_query_points, knn}, -1,
>                                               Dtype::FromType<scalar_t>());
> ```

`Dtype::FromType<scalar_t>()` -> `dtype`
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 204 at r13](https://reviewable.io/reviews/intel-isl/open3d/2305#-MHKe77L9Zl_5R-iM8S5:-MHKe77L9Zl_5R-iM8S6:byv0hv3) ([raw file](https://github.com/intel-isl/open3d/blob/54b30402568bf251f511176c4b59cbb4622e3e0c/cpp/open3d/core/nns/NanoFlannIndex.cpp#L204)):*
> ```cpp
> 
>         // Check if the raii has negative values.
>         Tensor below_zero = radii.Le<scalar_t>(0);
> ```

does `Le` work without `<scalar_t>`

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2305)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @benjaminum and @yxlao)

___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 115 at r13](https://reviewable.io/reviews/intel-isl/open3d/2305#-MHKd2L33Y-HA_ozWF8N:-MHKmB9p68se6nz9DsmS:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/54b30402568bf251f511176c4b59cbb4622e3e0c/cpp/open3d/core/nns/NanoFlannIndex.cpp#L115)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`Dtype::FromType<scalar_t>()` -> `dtype`
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 204 at r13](https://reviewable.io/reviews/intel-isl/open3d/2305#-MHKe77L9Zl_5R-iM8S5:-MHKmCEREXCg3Iwh-pF4:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/54b30402568bf251f511176c4b59cbb4622e3e0c/cpp/open3d/core/nns/NanoFlannIndex.cpp#L204)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

does `Le` work without `<scalar_t>`
</blockquote></details>

Done.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6149103&bid=20095837)

**Review by yxlao — APPROVED** [review]
> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2305)* status: all files reviewed, 1 unresolved discussion (waiting on @benjaminum)

**Pull request merged**
