### PR TITLE
Introduce generic CachedMemoryManager

### PR DESCRIPTION
**Pull request by stotko**
This PR introduces a generic cached memory manager that can be used to speed-up allocations for arbitrary true memory managers, including `CPUMemoryManager` and `CUDAMemoryManager`.

Highlights:

- Decoupled design for cached allocations (via `MemoryCache`) and true allocations (via provided `DeviceMemoryManager`).
- Thread-safe cache management. No blocking for true (de-)allocations.
- Single per-device memory pool with adaptive block selection criteria.
- Automatic cache releasing if true allocation attempt fails.
- Extensive unit tests to cover different caching scenarios.

Further changes:

- Removed "randomly occurring" cache release calls. Only leave those where 3rdparty code allocates CUDA memory on their own.
- Replaced `CUDACachedMemoryManager` by new generic one.

Benchmarks on Intel i7-10750H + NVIDIA RTX 2070 Max-Q with 8 GB VRAM @ CUDA 11.0:

- Caching is only beneficial for very large CPU allocations. Instead faster direct implementations like `jemalloc` might be considered in the future. Thus, caching is not considered by default for `CPUMemoryManager`.
- Caching for CUDA 11.0 is always beneficial. Thus, caching is considered by default for `CUDAMemoryManager`.

```
----------------------------------------------------------------------------------------------
Benchmark                                                    Time             CPU   Iterations
----------------------------------------------------------------------------------------------
Malloc/MemoryManagerBackend::Direct_100_CPU              0.157 us        0.159 us      4414142
Malloc/MemoryManagerBackend::Direct_1000_CPU             0.155 us        0.156 us      4471579
Malloc/MemoryManagerBackend::Direct_10000_CPU            0.171 us        0.172 us      4095111
Malloc/MemoryManagerBackend::Direct_100000_CPU           0.170 us        0.172 us      4047832
Malloc/MemoryManagerBackend::Direct_1000000_CPU          0.171 us        0.172 us      4039242
Malloc/MemoryManagerBackend::Direct_10000000_CPU         0.170 us        0.172 us      4066251
Malloc/MemoryManagerBackend::Direct_100000000_CPU         1.27 us         1.27 us       538339
Malloc/MemoryManagerBackend::Direct_1000000000_CPU        1.42 us         1.43 us       487466
Malloc/MemoryManagerBackend::Cached_100_CPU              0.632 us        0.633 us      1072960
Malloc/MemoryManagerBackend::Cached_1000_CPU             0.649 us        0.650 us      1066593
Malloc/MemoryManagerBackend::Cached_10000_CPU            0.631 us        0.632 us      1093144
Malloc/MemoryManagerBackend::Cached_100000_CPU           0.631 us        0.633 us      1106523
Malloc/MemoryManagerBackend::Cached_1000000_CPU          0.630 us        0.632 us      1106949
Malloc/MemoryManagerBackend::Cached_10000000_CPU         0.630 us        0.631 us      1105203
Malloc/MemoryManagerBackend::Cached_100000000_CPU        0.631 us        0.632 us      1107429
Malloc/MemoryManagerBackend::Cached_1000000000_CPU       0.629 us        0.631 us      1108278
Malloc/MemoryManagerBackend::Direct_100_CUDA              57.8 us         57.8 us        11555
Malloc/MemoryManagerBackend::Direct_1000_CUDA             57.7 us         57.6 us        12016
Malloc/MemoryManagerBackend::Direct_10000_CUDA            57.7 us         57.7 us        12026
Malloc/MemoryManagerBackend::Direct_100000_CUDA           57.6 us         57.6 us        11896
Malloc/MemoryManagerBackend::Direct_1000000_CUDA          57.6 us         57.6 us        12028
Malloc/MemoryManagerBackend::Direct_10000000_CUDA          198 us          198 us         3536
Malloc/MemoryManagerBackend::Direct_100000000_CUDA        1700 us          940 us          727
Malloc/MemoryManagerBackend::Direct_1000000000_CUDA      17908 us         1774 us          400
Malloc/MemoryManagerBackend::Cached_100_CUDA             0.630 us        0.631 us      1130577
Malloc/MemoryManagerBackend::Cached_1000_CUDA            0.640 us        0.641 us      1102558
Malloc/MemoryManagerBackend::Cached_10000_CUDA           0.636 us        0.637 us      1103381
Malloc/MemoryManagerBackend::Cached_100000_CUDA          0.634 us        0.635 us      1101323
Malloc/MemoryManagerBackend::Cached_1000000_CUDA         0.634 us        0.636 us      1096877
Malloc/MemoryManagerBackend::Cached_10000000_CUDA        0.634 us        0.636 us      1090386
Malloc/MemoryManagerBackend::Cached_100000000_CUDA       0.634 us        0.636 us      1093111
Malloc/MemoryManagerBackend::Cached_1000000000_CUDA      0.635 us        0.637 us      1104474
Free/MemoryManagerBackend::Direct_100_CPU                0.159 us        0.161 us      4364806
Free/MemoryManagerBackend::Direct_1000_CPU               0.159 us        0.161 us      4331917
Free/MemoryManagerBackend::Direct_10000_CPU              0.175 us        0.177 us      3978805
Free/MemoryManagerBackend::Direct_100000_CPU             0.171 us        0.173 us      4063305
Free/MemoryManagerBackend::Direct_1000000_CPU            0.170 us        0.173 us      4069034
Free/MemoryManagerBackend::Direct_10000000_CPU           0.171 us        0.172 us      4082457
Free/MemoryManagerBackend::Direct_100000000_CPU           1.71 us         1.72 us       398689
Free/MemoryManagerBackend::Direct_1000000000_CPU          3.54 us         3.54 us       197195
Free/MemoryManagerBackend::Cached_100_CPU                0.646 us        0.647 us      1073284
Free/MemoryManagerBackend::Cached_1000_CPU               0.645 us        0.646 us      1067404
Free/MemoryManagerBackend::Cached_10000_CPU              0.650 us        0.651 us      1066385
Free/MemoryManagerBackend::Cached_100000_CPU             0.644 us        0.646 us      1081287
Free/MemoryManagerBackend::Cached_1000000_CPU            0.649 us        0.651 us      1069147
Free/MemoryManagerBackend::Cached_10000000_CPU           0.649 us        0.651 us      1075301
Free/MemoryManagerBackend::Cached_100000000_CPU          0.643 us        0.645 us      1078701
Free/MemoryManagerBackend::Cached_1000000000_CPU         0.654 us        0.656 us      1087658
Free/MemoryManagerBackend::Direct_100_CUDA                37.1 us         37.1 us        17994
Free/MemoryManagerBackend::Direct_1000_CUDA               37.1 us         37.1 us        18876
Free/MemoryManagerBackend::Direct_10000_CUDA              37.1 us         37.1 us        18856
Free/MemoryManagerBackend::Direct_100000_CUDA             37.5 us         37.2 us        18756
Free/MemoryManagerBackend::Direct_1000000_CUDA            37.2 us         37.2 us        18849
Free/MemoryManagerBackend::Direct_10000000_CUDA           46.1 us         45.2 us        15590
Free/MemoryManagerBackend::Direct_100000000_CUDA           112 us          112 us         6211
Free/MemoryManagerBackend::Direct_1000000000_CUDA          553 us          552 us         1276
Free/MemoryManagerBackend::Cached_100_CUDA               0.644 us        0.645 us      1086189
Free/MemoryManagerBackend::Cached_1000_CUDA              0.646 us        0.647 us      1083361
Free/MemoryManagerBackend::Cached_10000_CUDA             0.647 us        0.648 us      1075042
Free/MemoryManagerBackend::Cached_100000_CUDA            0.647 us        0.648 us      1084826
Free/MemoryManagerBackend::Cached_1000000_CUDA           0.644 us        0.646 us      1084383
Free/MemoryManagerBackend::Cached_10000000_CUDA          0.648 us        0.649 us      1087443
Free/MemoryManagerBackend::Cached_100000000_CUDA         0.645 us        0.646 us      1085616
Free/MemoryManagerBackend::Cached_1000000000_CUDA        0.646 us        0.647 us      1082487
```

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3678)

### CODE REVIEW

**Review by theNded — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3678)* status: all files reviewed, 3 unresolved discussions (waiting on @reyanshsolis, @ssheorey, @stotko, and @yxlao)

___
*[cpp/open3d/core/MemoryManagerCached.cpp, line 345 at r1](https://reviewable.io/reviews/intel-isl/open3d/3678#-Me5Z37q2YKjDb_aEz8Z:-Me5Z37q2YKjDb_aEz8_:b-qh61pq) ([raw file](https://github.com/intel-isl/open3d/blob/effcdae8793323d2034dd4ba1f5d78ba92acac1d/cpp/open3d/core/MemoryManagerCached.cpp#L345)):*
> ```cpp
> 
>     /// Heuristic constant to bound fragmentation.
>     double max_fragmentation = 4;
> ```

const double MAX_FRAGMENTATION or kMaxFragmentation
___
*[cpp/open3d/core/MemoryManagerCached.cpp, line 469 at r1](https://reviewable.io/reviews/intel-isl/open3d/3678#-Me7oY0y6ZAnE9Ud5Mjm:-Me7oY0y6ZAnE9Ud5Mjn:b-5hrioh) ([raw file](https://github.com/intel-isl/open3d/blob/effcdae8793323d2034dd4ba1f5d78ba92acac1d/cpp/open3d/core/MemoryManagerCached.cpp#L469)):*
> ```cpp
>     /// Resolves race conditions and avoids locking in the operations.
>     /// Must be called at the beginning of all operations.
>     void Init(const Device& device) {
> ```

Maybe rename it to 'Acquire' or something else? Init seems more related to a constructor.
___
*[cpp/tests/core/MemoryManager.cpp, line 173 at r1](https://reviewable.io/reviews/intel-isl/open3d/3678#-Me7nUtm6jgXuGyBDsfK:-Me7nUtn8vJtrJBqqAma:b-c7e1v3) ([raw file](https://github.com/intel-isl/open3d/blob/effcdae8793323d2034dd4ba1f5d78ba92acac1d/cpp/tests/core/MemoryManager.cpp#L173)):*
> ```cpp
> 
> TEST(MemoryManagerPermuteDevices, CachedSingle) {
>     core::Device device("CUDA:9999");
> ```

Declare a dummy device and reuse it in tests?

**Review by stotko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3678)* status: 15 of 17 files reviewed, 3 unresolved discussions (waiting on @reyanshsolis, @ssheorey, @theNded, and @yxlao)

___
*[cpp/open3d/core/MemoryManagerCached.cpp, line 345 at r1](https://reviewable.io/reviews/intel-isl/open3d/3678#-Me5Z37q2YKjDb_aEz8Z:-Me9KS9C1f0Gj3SVrwJh:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/effcdae8793323d2034dd4ba1f5d78ba92acac1d/cpp/open3d/core/MemoryManagerCached.cpp#L345)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

const double MAX_FRAGMENTATION or kMaxFragmentation
</blockquote></details>

Done.
___
*[cpp/open3d/core/MemoryManagerCached.cpp, line 469 at r1](https://reviewable.io/reviews/intel-isl/open3d/3678#-Me7oY0y6ZAnE9Ud5Mjm:-Me9KVVNELQNbPoRbLkI:b-7i44oh) ([raw file](https://github.com/intel-isl/open3d/blob/effcdae8793323d2034dd4ba1f5d78ba92acac1d/cpp/open3d/core/MemoryManagerCached.cpp#L469)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Maybe rename it to 'Acquire' or something else? Init seems more related to a constructor.
</blockquote></details>

I did not rename it to `Acquire` to avoid confusion with `MemoryCache::Acquire` which is responsible for taking ownership of real allocated memory block. The name `Init` is probably not that bad as it actually initializes an entry in the unordered map. There might still be a better name, but I cannot think of one for now.
___
*[cpp/tests/core/MemoryManager.cpp, line 173 at r1](https://reviewable.io/reviews/intel-isl/open3d/3678#-Me7nUtm6jgXuGyBDsfK:-Me9KTqV-TMMUZXZKNr-:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/effcdae8793323d2034dd4ba1f5d78ba92acac1d/cpp/tests/core/MemoryManager.cpp#L173)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Declare a dummy device and reuse it in tests?
</blockquote></details>

Done.

**Review by theNded — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3678)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @reyanshsolis, @ssheorey, and @yxlao)

**Review by yxlao — APPROVED** [review]
> Reviewed 15 of 17 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3678)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @reyanshsolis and @ssheorey)

**Review by ssheorey — CHANGES_REQUESTED** [review]
> Reviewed 4 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3678)* status: all files reviewed, 4 unresolved discussions (waiting on @reyanshsolis and @stotko)

___
*[cpp/benchmarks/core/MemoryManager.cpp, line 155 at r2](https://reviewable.io/reviews/intel-isl/open3d/3678#-MeQtO1u28d91F5h4dqg:-MeQtO1v8o2HJGBPQl8Q:b-j54ppg) ([raw file](https://github.com/intel-isl/open3d/blob/2eda00734dc3ccb3aea5e344346610116daffc59/cpp/benchmarks/core/MemoryManager.cpp#L155)):*
> ```cpp
> 
> ENUM_BM_BACKEND(Malloc)
> ENUM_BM_BACKEND(Free)
> ```

Can you post the results of these benchmarks on your computer?
Also, how do they compare with platform malloc / free? Essentially, when should users use the cached memory managers? Especially for CUDA, the native memory manager is  likely to improve over time so it would be good to have benchmark comparisons with the native memory manager.
___
*[cpp/open3d/core/MemoryManager.h, line 79 at r2](https://reviewable.io/reviews/intel-isl/open3d/3678#-MeQSdDu7BCaIHYpvoP7:-MeQSdDu7BCaIHYpvoP8:bs1o6lz) ([raw file](https://github.com/intel-isl/open3d/blob/2eda00734dc3ccb3aea5e344346610116daffc59/cpp/open3d/core/MemoryManager.h#L79)):*
> ```objc
> };
> 
> class CachedMemoryManager : public DeviceMemoryManager {
> ```

Can you add doxygen docs here (also for the other classes / functions in this file), describing behavior and use (expanding on your PR description)? It will be pretty useful for future  contributors to Open3D.
___
*[cpp/open3d/core/MemoryManagerCached.cpp, line 98 at r2](https://reviewable.io/reviews/intel-isl/open3d/3678#-MeQWCKz8zF3Kwnt6v-J:-MeQWCKz8zF3Kwnt6v-K:b-tgd40q) ([raw file](https://github.com/intel-isl/open3d/blob/2eda00734dc3ccb3aea5e344346610116daffc59/cpp/open3d/core/MemoryManagerCached.cpp#L98)):*
> ```cpp
>     MemoryCache& operator=(const MemoryCache&) = delete;
> 
>     /// Computes an internal byte size that enures a proper alignment of the
> ```

typo: ensures
___
*[cpp/open3d/core/MemoryManagerCached.cpp, line 345 at r2](https://reviewable.io/reviews/intel-isl/open3d/3678#-MeQXUv2DJ4RaMZo2YAj:-MeQXUv2DJ4RaMZo2YAk:bvtk1le) ([raw file](https://github.com/intel-isl/open3d/blob/2eda00734dc3ccb3aea5e344346610116daffc59/cpp/open3d/core/MemoryManagerCached.cpp#L345)):*
> ```cpp
> 
>     /// Heuristic constant to bound fragmentation.
>     const double kMaxFragmentation = 4;
> ```

Should this be `size_t`?

**Review by stotko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3678)* status: 13 of 18 files reviewed, 4 unresolved discussions (waiting on @reyanshsolis, @ssheorey, @theNded, and @yxlao)

___
*[cpp/benchmarks/core/MemoryManager.cpp, line 155 at r2](https://reviewable.io/reviews/intel-isl/open3d/3678#-MeQtO1u28d91F5h4dqg:-MeU8QPD1ECxlt-nXutU:b-b8j8g2) ([raw file](https://github.com/intel-isl/open3d/blob/2eda00734dc3ccb3aea5e344346610116daffc59/cpp/benchmarks/core/MemoryManager.cpp#L155)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can you post the results of these benchmarks on your computer?
Also, how do they compare with platform malloc / free? Essentially, when should users use the cached memory managers? Especially for CUDA, the native memory manager is  likely to improve over time so it would be good to have benchmark comparisons with the native memory manager.
</blockquote></details>

See the updated description of the PR.
___
*[cpp/open3d/core/MemoryManager.h, line 79 at r2](https://reviewable.io/reviews/intel-isl/open3d/3678#-MeQSdDu7BCaIHYpvoP7:-MeU8UpoBmmqaEX8IfzW:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/2eda00734dc3ccb3aea5e344346610116daffc59/cpp/open3d/core/MemoryManager.h#L79)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can you add doxygen docs here (also for the other classes / functions in this file), describing behavior and use (expanding on your PR description)? It will be pretty useful for future  contributors to Open3D.
</blockquote></details>

Done.
___
*[cpp/open3d/core/MemoryManagerCached.cpp, line 98 at r2](https://reviewable.io/reviews/intel-isl/open3d/3678#-MeQWCKz8zF3Kwnt6v-J:-MeU8W0HAv2RzV_XtrMn:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/2eda00734dc3ccb3aea5e344346610116daffc59/cpp/open3d/core/MemoryManagerCached.cpp#L98)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

typo: ensures
</blockquote></details>

Done.
___
*[cpp/open3d/core/MemoryManagerCached.cpp, line 345 at r2](https://reviewable.io/reviews/intel-isl/open3d/3678#-MeQXUv2DJ4RaMZo2YAj:-MeU8WnF70cK9kn3GcrN:b-viz9yo) ([raw file](https://github.com/intel-isl/open3d/blob/2eda00734dc3ccb3aea5e344346610116daffc59/cpp/open3d/core/MemoryManagerCached.cpp#L345)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Should this be `size_t`?
</blockquote></details>

`double` is intentional. From a theoretical point of view, it is not clear that the heuristic constant must be an integer. Fractional or irrational numbers might also work well. Added casts and made the constant look more like an intentional floating-point number.

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3678)* status: 13 of 18 files reviewed, all discussions resolved (waiting on @reyanshsolis, @ssheorey, @theNded, and @yxlao)

**Pull request merged**
