### PR TITLE
Mode For Light To Follow Camera

### PR DESCRIPTION
**Pull request by errissa**
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2944)

### CODE REVIEW

**Review by prewettg — CHANGES_REQUESTED** [review]
Several problems:
1) I was not able to get this to work when I tried it. I turned HDR lighting off and the sun on bright for easier evaluation, and then checked Sun Follows Camera. Rotating the model made it sometimes white and sometimes black
2) The UI was not consistent:
    a) when Sun Follows Camera is checked, the sun direction widget should be disabled (but I maybe it should update as the camera moves?) 
    b) the "Sun" button under Mouse Controls should be disabled
    c) the keyboard shortcut for sun rotation (Ctrl + left drag on macOS) should be disabled and do nothing
    d) I think setting a lighting profile from the pulldown menu should reset the Sun Follows Camera to off (either that or Sun Follows Camera should be brought outside Advanced Lighting and made a peer to the lighting profile).

> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2944#-:-MS594_q5W76YeaCPxY0:blantup)* status: 7 of 8 files reviewed, all discussions resolved

**Review by errissa — COMMENTED** [review]
1) I will follow up with you offline as it definitely works for me on linux
2) All good ideas - now done.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2944#-:-MS8xpxs1333L_KKgDnn:b-hdfate)* status: 4 of 10 files reviewed, all discussions resolved (waiting on @prewettg)

**Review by prewettg — APPROVED** [review]
1) Sorry, I think something may have been wrong with my build before, it worked today with no changes.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2944#-:-MSA37LbEiIWJw83srAC:b-8pj4z8)* status: 4 of 10 files reviewed, all discussions resolved (waiting on @prewettg)

**Review by prewettg — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2944)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
