### PR TITLE
Helper functions for CUDA device synchronization

### PR DESCRIPTION
**Pull request by yxlao**
- Added C++ helper functions and Pybind for CUDA device synchronization
- Update benchmarks to always synchronize (although some of them do not affect the results)

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3795)

### CODE REVIEW

**Review by stotko — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3795)* status: all files reviewed, 7 unresolved discussions (waiting on @yxlao)

___
*[cpp/benchmarks/core/MemoryManager.cpp, line 82 at r1](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWsbcS1qYJwWkeZMLC:-MfWsbcS1qYJwWkeZMLD:bs0lhfw) ([raw file](https://github.com/intel-isl/open3d/blob/21ce8f4e3241e3e8213f5ca58817941c55de31fb/cpp/benchmarks/core/MemoryManager.cpp#L82)):*
> ```cpp
>         void* ptr = device_mm->Malloc(size, device);
>         device_mm->Free(ptr, device);
>         core::cuda::Synchronize(device);
> ```

nit: Use shorter`cuda::Synchronize()` call as this is called from `open3d::core` namespace
___
*[cpp/open3d/core/CUDAUtils.h, line 244 at r1](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWt5qP1ne_j0hUCvyT:-MfWt5qP1ne_j0hUCvyU:b-9fujrp) ([raw file](https://github.com/intel-isl/open3d/blob/21ce8f4e3241e3e8213f5ca58817941c55de31fb/cpp/open3d/core/CUDAUtils.h#L244)):*
> ```objc
> bool IsAvailable();
> 
> /// Release CUDA memory manger cache. This is typically used for debugging.
> ```

`Release` -> `Releases`
`manger` -> `manager`
___
*[cpp/open3d/core/CUDAUtils.h, line 249 at r1](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWtH6z9xEFf0DeX6HF:-MfWtH6z9xEFf0DeX6HG:b-5mder2) ([raw file](https://github.com/intel-isl/open3d/blob/21ce8f4e3241e3e8213f5ca58817941c55de31fb/cpp/open3d/core/CUDAUtils.h#L249)):*
> ```objc
> /// Call cudaDeviceSynchronize() for the current CUDA device. If Open3D is not
> /// compiled with CUDA this function has no effect.
> void Synchronize();
> ```

Should the semantic of this call be to sync *every* device rather than the *current*  device? `ReleaseCache` also operates on all (CUDA) devices, so we should make sure all the functions defined here have a consistent interface.
___
*[cpp/open3d/core/CUDAUtils.h, line 251 at r1](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWu8LsD60_FtBr-E1P:-MfWu8LtE_buJufpehhp:b2wyyo3) ([raw file](https://github.com/intel-isl/open3d/blob/21ce8f4e3241e3e8213f5ca58817941c55de31fb/cpp/open3d/core/CUDAUtils.h#L251)):*
> ```objc
> void Synchronize();
> 
> /// Call cudaDeviceSynchronize() for the specified device. If Open3D is not
> ```

`Call`-> `Calls`
___
*[cpp/pybind/core/cuda_utils.cpp, line 44 at r1](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWuiH72slsCgEBbBvw:-MfWuiH72slsCgEBbBvx:bys7ema) ([raw file](https://github.com/intel-isl/open3d/blob/21ce8f4e3241e3e8213f5ca58817941c55de31fb/cpp/pybind/core/cuda_utils.cpp#L44)):*
> ```cpp
>                "least one compatible CUDA device is detected.");
>     m_cuda.def("release_cache", cuda::ReleaseCache,
>                "Release CUDA memory manger cache. This is typically used for "
> ```

See above for mentioned typos.
___
*[cpp/pybind/core/cuda_utils.cpp, line 48 at r1](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWuuiDAUgwO-JiWHww:-MfWuuiDAUgwO-JiWHwx:b-zgfnjg) ([raw file](https://github.com/intel-isl/open3d/blob/21ce8f4e3241e3e8213f5ca58817941c55de31fb/cpp/pybind/core/cuda_utils.cpp#L48)):*
> ```cpp
>     m_cuda.def(
>             "synchronize",
>             [](const utility::optional<Device>& device) {
> ```

See above for consistency question.
___
*[cpp/pybind/core/cuda_utils.cpp, line 57 at r1](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWuohRAfubSK9SjdCg:-MfWuohRAfubSK9SjdCh:bcbjcpp) ([raw file](https://github.com/intel-isl/open3d/blob/21ce8f4e3241e3e8213f5ca58817941c55de31fb/cpp/pybind/core/cuda_utils.cpp#L57)):*
> ```cpp
>             "Wait for the CUDA device to finish. If the device is not "
>             "specified, the current CUDA device will be assumed. No effect if "
>             "the deive is not a CUDA device."
> ```

`deive` -> `device`

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3795)* status: 16 of 20 files reviewed, 6 unresolved discussions (waiting on @stotko)

___
*[cpp/open3d/core/CUDAUtils.h, line 244 at r1](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWt5qP1ne_j0hUCvyT:-MfWwAUAANHTVU5UnEMV:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/21ce8f4e3241e3e8213f5ca58817941c55de31fb/cpp/open3d/core/CUDAUtils.h#L244)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`Release` -> `Releases`
`manger` -> `manager`
</blockquote></details>

Done.
___
*[cpp/open3d/core/CUDAUtils.h, line 249 at r1](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWtH6z9xEFf0DeX6HF:-MfWxAaQ9h50k_rEh8MV:b-y91hd1) ([raw file](https://github.com/intel-isl/open3d/blob/21ce8f4e3241e3e8213f5ca58817941c55de31fb/cpp/open3d/core/CUDAUtils.h#L249)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Should the semantic of this call be to sync *every* device rather than the *current*  device? `ReleaseCache` also operates on all (CUDA) devices, so we should make sure all the functions defined here have a consistent interface.
</blockquote></details>

Yes. Agree that synchronizing all devices is more user-friendly in most scenarios.
___
*[cpp/open3d/core/CUDAUtils.h, line 251 at r1](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWu8LsD60_FtBr-E1P:-MfWwD6KE7ml12kvD6xV:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/21ce8f4e3241e3e8213f5ca58817941c55de31fb/cpp/open3d/core/CUDAUtils.h#L251)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`Call`-> `Calls`
</blockquote></details>

Done.
___
*[cpp/pybind/core/cuda_utils.cpp, line 44 at r1](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWuiH72slsCgEBbBvw:-MfWxH3TBbp7dMFdgvEX:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/21ce8f4e3241e3e8213f5ca58817941c55de31fb/cpp/pybind/core/cuda_utils.cpp#L44)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See above for mentioned typos.
</blockquote></details>

Done.
___
*[cpp/pybind/core/cuda_utils.cpp, line 48 at r1](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWuuiDAUgwO-JiWHww:-MfWxIWH34ipjSjC4cTr:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/21ce8f4e3241e3e8213f5ca58817941c55de31fb/cpp/pybind/core/cuda_utils.cpp#L48)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See above for consistency question.
</blockquote></details>

Done.
___
*[cpp/pybind/core/cuda_utils.cpp, line 57 at r1](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWuohRAfubSK9SjdCg:-MfWxIqLC-m5RUkh9t5f:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/21ce8f4e3241e3e8213f5ca58817941c55de31fb/cpp/pybind/core/cuda_utils.cpp#L57)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`deive` -> `device`
</blockquote></details>

Done.

**Review by stotko — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3795)* status: all files reviewed, 2 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/CUDAUtils.h, line 247 at r3](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWyxdMDeHK_fB5741_:-MfWyxdMDeHK_fB5741a:b-k07qfe) ([raw file](https://github.com/intel-isl/open3d/blob/c437449272b801811f2260e9e4d673bf5b3a220f/cpp/open3d/core/CUDAUtils.h#L247)):*
> ```objc
> void ReleaseCache();
> 
> /// Calls cudaDeviceSynchronize() for all CUDA device(s). If Open3D is not
> ```

nit: `device(s)` -> `devices`
___
*[cpp/pybind/core/cuda_utils.cpp, line 55 at r3](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWzNdV3D5Q6khHpckJ:-MfWzNdW1BPoOmVGemYq:b-hkmv9m) ([raw file](https://github.com/intel-isl/open3d/blob/c437449272b801811f2260e9e4d673bf5b3a220f/cpp/pybind/core/cuda_utils.cpp#L55)):*
> ```cpp
>                 }
>             },
>             "Synchronize CUDA device(s). If no device is specified, all CUDA "
> ```

`Synchronize` -> `Synchronizes`
`device(s)` -> `devices`
`syncrhonized` -> `synchronized`

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3795)* status: 18 of 20 files reviewed, 1 unresolved discussion (waiting on @stotko)

___
*[cpp/pybind/core/cuda_utils.cpp, line 55 at r3](https://reviewable.io/reviews/intel-isl/open3d/3795#-MfWzNdV3D5Q6khHpckJ:-MfX-lTP38OFcFszJZMV:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c437449272b801811f2260e9e4d673bf5b3a220f/cpp/pybind/core/cuda_utils.cpp#L55)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`Synchronize` -> `Synchronizes`
`device(s)` -> `devices`
`syncrhonized` -> `synchronized`
</blockquote></details>

Done.

**Review by stotko — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3795)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yxlao)

**Pull request merged**
