### PR TITLE
Fixes for Regression from upgrade to Filament 1.9.3

### PR DESCRIPTION
**Pull request by errissa**
* Screen turning black on changing menus
* Screen flashing black when manipulating scene with mouse
* Occasional black background on image export
* Also, fixed Dialog boxes not disappearing immediately when closed

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2442)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6309349&bid=20515490)

**Review by prewettg — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2442)* status: all files reviewed, 4 unresolved discussions (waiting on @errissa)

___
*[cpp/open3d/visualization/gui/Window.cpp, line 604 at r1](https://reviewable.io/reviews/intel-isl/open3d/2442#-MJ9CrPrD8uLM4-bVemR:-MJ9CrPsAJTy8isJ8Qi6:b8fxfsi) ([raw file](https://github.com/intel-isl/open3d/blob/5ff6df5be744b9d9e08aafb970566bd110b4d53b/cpp/open3d/visualization/gui/Window.cpp#L604)):*
> ```cpp
> }
> 
> void Window::ForceRedrawSceneWidget() {
> ```

Suggestion: this might be a good place for a comment describing how the whole scene widget caching works and why. Seems kind of weird to have a special-case function here.
___
*[cpp/open3d/visualization/gui/Window.cpp, line 619 at r1](https://reviewable.io/reviews/intel-isl/open3d/2442#-MJ9DXsu0Rz5UVivtfbr:-MJ9DXsu0Rz5UVivtfbs:b-shr2c7) ([raw file](https://github.com/intel-isl/open3d/blob/5ff6df5be744b9d9e08aafb970566bd110b4d53b/cpp/open3d/visualization/gui/Window.cpp#L619)):*
> ```cpp
>     impl_->active_dialog_.reset();
> 
>     ForceRedrawSceneWidget();
> ```

This doesn't seem to work for me on Linux. If I select the About box from the menu, moving the cursor, I still see the menu flickering on and off, and when I click ok, the dialog goes away but flashes on and off when I move the mouse. Until I rotate, then everything is correct again.
___
*[cpp/open3d/visualization/rendering/Scene.h, line 176 at r1](https://reviewable.io/reviews/intel-isl/open3d/2442#-MJ9D9M-8P38pseNVvO9:-MJ9D9M-8P38pseNVvOA:b-e81kyk) ([raw file](https://github.com/intel-isl/open3d/blob/5ff6df5be744b9d9e08aafb970566bd110b4d53b/cpp/open3d/visualization/rendering/Scene.h#L176)):*
> ```objc
>     virtual Transform GetIndirectLightRotation() = 0;
>     virtual void ShowSkybox(bool show) = 0;
>     virtual void SetBackgroundColor(const Eigen::Vector4f& color) = 0;
> ```

Excellent! It needs a pybind, though: examples/python/gui/vis-gui.py can no longer set colors.
___
*[cpp/open3d/visualization/visualizer/GuiVisualizer.cpp, line 406 at r1](https://reviewable.io/reviews/intel-isl/open3d/2442#-MJ9DNqGDHAZGfCvoI2O:-MJ9DNqGDHAZGfCvoI2P:b-2es7fa) ([raw file](https://github.com/intel-isl/open3d/blob/5ff6df5be744b9d9e08aafb970566bd110b4d53b/cpp/open3d/visualization/visualizer/GuiVisualizer.cpp#L406)):*
> ```cpp
>     void UpdateFromModel(rendering::Renderer &renderer, bool material_changed) {
>         auto bcolor = settings_.model_.GetBackgroundColor();
>         scene_wgt_->GetScene()->GetScene()->SetBackgroundColor(
> ```

Would it make sense to add a SetBackgroundColor to Open3DScene?

**Comment by prewettg** [comment]
I still see flickering between the penultimate rotation and the last rotation frames (Intel graphics, Linux only) if I don't wait long enough after rotating, but it is not consistently reproducible.

**Review by errissa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2442)* status: 7 of 14 files reviewed, 4 unresolved discussions (waiting on @errissa and @prewettg)

___
*[cpp/open3d/visualization/gui/Window.cpp, line 604 at r1](https://reviewable.io/reviews/intel-isl/open3d/2442#-MJ9CrPrD8uLM4-bVemR:-MJ9L6OE2lp77YQMtLBq:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/5ff6df5be744b9d9e08aafb970566bd110b4d53b/cpp/open3d/visualization/gui/Window.cpp#L604)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

Suggestion: this might be a good place for a comment describing how the whole scene widget caching works and why. Seems kind of weird to have a special-case function here.
</blockquote></details>

Done.
___
*[cpp/open3d/visualization/rendering/Scene.h, line 176 at r1](https://reviewable.io/reviews/intel-isl/open3d/2442#-MJ9D9M-8P38pseNVvO9:-MJ9L9jf6KZsMCm3z7o1:b-kbuid0) ([raw file](https://github.com/intel-isl/open3d/blob/5ff6df5be744b9d9e08aafb970566bd110b4d53b/cpp/open3d/visualization/rendering/Scene.h#L176)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

Excellent! It needs a pybind, though: examples/python/gui/vis-gui.py can no longer set colors.
</blockquote></details>

Added pybind and updated vis-gui.py
___
*[cpp/open3d/visualization/visualizer/GuiVisualizer.cpp, line 406 at r1](https://reviewable.io/reviews/intel-isl/open3d/2442#-MJ9DNqGDHAZGfCvoI2O:-MJ9LJjW0l0deRGYxQvQ:byvyago) ([raw file](https://github.com/intel-isl/open3d/blob/5ff6df5be744b9d9e08aafb970566bd110b4d53b/cpp/open3d/visualization/visualizer/GuiVisualizer.cpp#L406)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

Would it make sense to add a SetBackgroundColor to Open3DScene?
</blockquote></details>

Yes. Done.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6309349&bid=20515490)

**Review by prewettg — COMMENTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2442)* status: all files reviewed, 1 unresolved discussion (waiting on @errissa)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6309349&bid=20515490)

**Comment by errissa** [comment]
Reverting to Filament 1.8.1. This PR is no longer relevant.

**Pull request closed without merging**
