### PR TITLE
Integration of Custom Filament Headless Backend

### PR DESCRIPTION
**Pull request by errissa**
Note: Headless is only enabled for Linux.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2572)

### CODE REVIEW

**Review by prewettg — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2572)* status: all files reviewed, 1 unresolved discussion (waiting on @errissa and @yxlao)

*[a discussion](https://reviewable.io/reviews/intel-isl/open3d/2572#-MN-t4Fz4xEat81d1ZtV:-MN-t4G-2wdH0f_jhDf3:b-fjwgne) (no related file):*
Code seems fine, but adding `headless=True` crashes when run from SSH and hangs on filament::Engine::destroy() in join() when run from a windowing system. (Ubuntu 18.04.3)

---

**Review by errissa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2572)* status: all files reviewed, 1 unresolved discussion (waiting on @prewettg and @yxlao)

*[a discussion](https://reviewable.io/reviews/intel-isl/open3d/2572#-MN-t4Fz4xEat81d1ZtV:-MNQCR1z8Wt3TgV0HO-z:b-q4rs77) (no related file):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

Code seems fine, but adding `headless=True` crashes when run from SSH and hangs on filament::Engine::destroy() in join() when run from a windowing system. (Ubuntu 18.04.3)
</blockquote></details>

The EGL backend is intended to work with Nvidia GPUs.

---

**Review by errissa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2572)* status: all files reviewed, 1 unresolved discussion (waiting on @prewettg and @yxlao)

*[a discussion](https://reviewable.io/reviews/intel-isl/open3d/2572#-MN-t4Fz4xEat81d1ZtV:-MNQCZJWDIlzL13HsZJ1:b-896fix) (no related file):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

The EGL backend is intended to work with Nvidia GPUs.
</blockquote></details>

Done.

---

**Review by prewettg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2572)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yxlao)

**Pull request merged**
