### PR TITLE
Fix bug in examples.

### PR DESCRIPTION
**Pull request by scimad**
Related with #1501, #1528 
To avoid such repetitive commits of such nature.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1537)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/Python/Advanced/remove_geometry.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5059966&bid=16653616)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/Python/Advanced/remove_geometry.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5059966&bid=16653616)

**Comment by scimad** [comment]
On `azure_kinect_mkv_reader.py`, the loop would `continue` when `rgbd` is `None` in which case it won't reach to `vis.update_geometry(rgbd)`.

On `mesh_properties.py`, since I didn't look in detail of the expected behavior of the example, I thought that output (the intersection of mesh at the end of the example) was the expected behavior. Sorry for overlooking that. Fixed and pushed.

BTW, what is preferred, a new commit to correct old commit or a single commit force pushed?

**Comment by germanros1987** [comment]
Please, @scimad could you resolve the issues pointed by Gernot?

**Comment by scimad** [comment]
Was out for brother's wedding.
@griegler sir, was wondering just what approach to use for the issue you pointed out, because:

As `flag_play` is initialized `True` at constructor, the case you mentioned i.e. `flag_play` is set to False then `update_geometry` is called with `rgbd` which is not initialized / `None` can arise only if a space is pressed after the program is started and the first frame is read (which is not realistic in ~10e-6 sec). So we can simply ignore the issue you mentioned and continue.

Otherwise I can validate before `update_geometry()` to make sure `rgbd` isn't `None`! (In which case, I think it's good to do the same validation in many other similar examples.

Should I still validate and make more changes on all other similar examples or just let it be assuming this code to be practically good?

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/Python/Advanced/remove_geometry.py  1
- examples/Python/ReconstructionSystem/sensors/azure_kinect_mkv_reader.py  1
- examples/Python/ReconstructionSystem/sensors/azure_kinect_recorder.py  1
- examples/Python/ReconstructionSystem/sensors/azure_kinect_viewer.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5059966&bid=16653616)

**Comment by scimad** [comment]
@griegler , As `flag_play` is initialized `True` at constructor, the case you mentioned i.e. `flag_play` is set to `False` then `update_geometry` is called with `rgbd` which is not initialized / `None` can arise only if a `[space]` is pressed after the program is started and the first frame is read (which is not realistic in ~10e-6 sec). So we can simply ignore the issue you mentioned and continue.

Should I still validate and make more changes on all other similar examples or just let it be assuming this code to be practically good?

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/Python/Advanced/remove_geometry.py  1
- examples/Python/ReconstructionSystem/sensors/azure_kinect_mkv_reader.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5059966&bid=16653616)

**Pull request merged**
