### PR TITLE
Azure Kinect support for the next release

### PR DESCRIPTION
**Pull request by theNded**
Merge `record` branch to `master` 
- major functionalities are described in: #1119, #1120 and #1121 
- dynamic k4a library loading strategies are specified in #1132 and #1136

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1141)

### CODE REVIEW

**Comment by griegler** [comment]
Changes look good to me. We should address (4) in another PR, where we also get rid of the asserts and use the logging system to be consistent with the rest of Open3D.

**Comment by griegler** [comment]
Yes, (5) was referring to `ConvertBGRAToRGB`. Could you remove the asserts then?
Maybe @benjaminum, or @qianyizh can have another look before merging? It is a quite big PR, not sure if I spotted everything.

**Comment by griegler** [comment]
The asserts are still there? https://github.com/intel-isl/Open3D/pull/1141/commits/4432fdc001c9e3aa1a0813167adf2348946c78a2#diff-e94752f1b936181997ff50a2c9a6be59R175-R177

**Comment by theNded** [comment]
@griegler Sorry for the mis-operation for re-review...

**Pull request merged**
