### PR TITLE
python slice for Tensor class

### PR DESCRIPTION
**Pull request by yxlao**
- numpy-like tensor slice
- fixed `WrapDim`
- allows index-take at a specified dimension
- allows negative wrap-around start, stop, and dim index.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1545)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/UnitTest/Container/Tensor.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5083250&bid=16719806)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/UnitTest/Container/Tensor.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5083250&bid=16719806)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/UnitTest/Container/Tensor.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5083250&bid=16719806)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/UnitTest/Container/Tensor.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5083250&bid=16719806)

**Comment by yxlao** [comment]
@theNded downcasting is added in 7b98508, ready to be reviewed again. Thanks!

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/UnitTest/Container/Tensor.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5083250&bid=16719806)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/UnitTest/Container/Tensor.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5083250&bid=16719806)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/UnitTest/Container/Tensor.cpp  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5083250&bid=16719806)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/UnitTest/Container/Tensor.cpp  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5083250&bid=16719806)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Python/open3d/__init__.py  1
- src/Python/open3d/core.py  7
         

Clones added
============
- src/Open3D/Core/Tensor.cpp  2
- src/UnitTest/Container/Tensor.cpp  162
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5083250&bid=16719806)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/UnitTest/Container/Tensor.cpp  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5083250&bid=16719806)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/UnitTest/Container/Tensor.cpp  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5083250&bid=16719806)

**Pull request merged**
