### PR TITLE
Add support for FPS-style mouselook to visualizer

### PR DESCRIPTION
**Pull request by turtlesoupy**
This adds "mouselook" to the visualizer, so when holding the alt key you manipulate the rotation of the camera local to it's reference frame. It's similar to how a first person shooter camera operates.

I've also exposed a camera local translate function which permits "WASD" style controls when using the appropriate key callbacks.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2551)

### CODE REVIEW

**Comment by turtlesoupy** [comment]
Cat ping!  @prewettg anything needed to merge?

**Review by prewettg — COMMENTED** [review]
Apologies for not responding earlier, I had not seen this until your ping. I should not that the old visualizers are being deprecated in favor of the new visualizer (O3DVisualizer, or just `draw` instead of `draw_geometries`), and the new visualizer does have a fly mode. However, I would be happy to merge this. Two questions, though:
1) you exported `camera_local_translate` in the pybinds, but I did not see `camera_local_rotate`, but maybe that would be useful to rotate, too? (In case you wanted to bind the arrow keys for rotating, for instance)
2) I don't seem to be able to get the key bindings to work (although since I have not worked that much with the old visualizer it's likely to be an error on my part), here's what I have:
```
#!/usr/bin/env python
import open3d as o3d

def go_forward(vis):
    vis.view_control.camera_local_translate(0.1, 0, 0)
    return False

def go_backward(vis):
    vis.view_control.camera_local_translate(-0.1, 0, 0)
    return False

def strafe_left(vis):
    vis.view_control.camera_local_translate(0, -0.1, 0)
    return False

def strafe_right(vis):
    vis.view_control.camera_local_translate(0, 0.1, 0)
    return False

def go_up(vis):
    vis.view_control.camera_local_translate(0, 0, 0.1)
    return False

def go_down(vis):
    vis.view_control.camera_local_translate(0, 0, -0.1)
    return False

obj = o3d.geometry.TriangleMesh.create_torus()
obj.compute_vertex_normals()
obj.paint_uniform_color([0.7, 0.0, 0.6])

o3d.visualization.draw_geometries_with_key_callbacks(
    [obj],
    { ord("a"): strafe_left,
      ord("d"): strafe_right,
      ord("w"): go_forward,
      ord("s"): go_backward,
      ord("q"): go_up,
      ord("z"): go_down }
)
```

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2551#-:-MS5Pf8F1fPUytvvb4Fw:b469u6u)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @prewettg)

**Comment by turtlesoupy** [comment]
Hmm, this is the code I have that seems to work:

```
def _wasd_move_fn(forward=0.0, right=0.0, up=0.0):
    return lambda vis: vis.get_view_control().camera_local_translate(forward, right, up)


def _wasd_callbacks(inputs, move_amt=None):
    if move_amt is None:
        move_amt = -float("inf")
        for e in inputs:
            if isinstance(e, (VoxelGrid, PointCloud)):
                move_amt = max(
                    move_amt, (e.xyz.max(axis=0) - e.xyz.min(axis=0)).mean() / 15
                )
        if move_amt < 0:
            move_amt = 0.5

    return {
        ord("W"): _wasd_move_fn(forward=move_amt),
        ord("S"): _wasd_move_fn(forward=-move_amt),
        ord("A"): _wasd_move_fn(right=-move_amt),
        ord("D"): _wasd_move_fn(right=move_amt),
        ord("Q"): _wasd_move_fn(up=move_amt),
        ord("E"): _wasd_move_fn(up=-move_amt),
    }

vis = open3d.visualization.VisualizerWithKeyCallback()
for key, cb in _wasd_callbacks(objs, move_amt=1.0).items():
    vis.register_key_callback(key, cb)

vis.create_window()
# Some geometry addition via vis.add_geometry(...)
vis.run()
```

Holding alt will then give mouselook with the above callbacks giving WASD controls. Can you let me know if this code works? I'd be happy to expose the rotate if so.

I'll give the new visualizer a try as well; I wasn't aware of it!

**Comment by prewettg** [comment]
Thanks, that does seem to work. If you would expose `camera_local_rotate` I'll merge it.

**Comment by turtlesoupy** [comment]
@prewettg Done! Let me know if you can merge. Thanks!

**Review by prewettg — APPROVED** [review]

**Comment by prewettg** [comment]
@turtlesoupy I've approved, but need to wait for CI to finish.

**Review by prewettg — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2551)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by prewettg** [comment]
@turtlesoupy Sorry this took so long to get merged, thanks for your PR!

**Pull request merged**
