### PR TITLE
reorg: Tests and Benchmarks

### PR DESCRIPTION
**Pull request by pvarvak**
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1978)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 14
           

Clones added
============
- cpp/tests/core/DLPack/DLPackConverter.cpp  4
- cpp/tests/io/FileFormat/FileGLTF.cpp  2
- cpp/tests/test_utility/Compare.cpp  2
- cpp/tests/geometry/LineSet.cpp  21
- cpp/tests/test_utility/Print.h  6
- cpp/tests/utility/FileSystem.cpp  14
- cpp/tests/pipelines/odometry/RGBDOdometryJacobianFromColorTerm.cpp  2
- cpp/tests/io/FileFormat/FileSTL.cpp  1
- cpp/tests/geometry/TriangleMesh.cpp  117
- cpp/tests/core/Tensor.cpp  284
- cpp/tests/geometry/Image.cpp  60
- cpp/tests/io/Sensor/AzureKinect/AzureKinectSensorConfig.cpp  1
- cpp/tests/pipelines/color_map/ColorMapOptimization.cpp  342
- cpp/tests/geometry/HalfEdgeTriangleMesh.cpp  18
- cpp/tests/test_utility/Rand.cpp  11
- cpp/tests/core/Indexer.cpp  2
- cpp/tests/io/ClassIO/PointCloudIO.cpp  40
- cpp/tests/geometry/RGBDImage.cpp  43
- cpp/tests/test_utility/Compare.h  2
- cpp/tests/utility/Eigen.cpp  6
- cpp/tests/test_utility/Sort.cpp  2
- cpp/benchmarks/io/PointCloudIO.cpp  2
- cpp/tests/pipelines/odometry/RGBDOdometryJacobianFromHybridTerm.cpp  2
- cpp/tests/geometry/IntersectionTest.cpp  2
- cpp/tests/camera/PinholeCameraIntrinsic.cpp  11
- cpp/tests/test_utility/Raw.cpp  2
- cpp/tests/pipelines/odometry/OdometryTools.cpp  2
- cpp/tests/geometry/Octree.cpp  6
- cpp/tests/geometry/PointCloud.cpp  30
- cpp/tests/io/ClassIO/OctreeIO.cpp  3
- cpp/tests/geometry/TetraMesh.cpp  30
- cpp/tests/geometry/KDTreeFlann.cpp  7
- cpp/tests/core/TensorList.cpp  63
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5728148&bid=18739644)

**Comment by yxlao** [comment]
1. remove `reorg` folder
2. change `cmake` target name (binary name) to `benchmarks` and `tests`?

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 14
           

Clones added
============
- cpp/tests/pipelines/odometry/RGBDOdometryJacobianFromHybridTerm.cpp  2
- cpp/tests/test_utility/Compare.h  2
- cpp/tests/geometry/HalfEdgeTriangleMesh.cpp  18
- cpp/tests/io/ClassIO/PointCloudIO.cpp  40
- cpp/tests/core/Indexer.cpp  2
- cpp/tests/test_utility/Compare.cpp  2
- cpp/tests/utility/FileSystem.cpp  14
- cpp/tests/pipelines/odometry/OdometryTools.cpp  2
- cpp/tests/io/FileFormat/FileGLTF.cpp  2
- cpp/tests/geometry/TetraMesh.cpp  30
- cpp/tests/geometry/IntersectionTest.cpp  2
- cpp/tests/io/ClassIO/OctreeIO.cpp  3
- cpp/tests/geometry/LineSet.cpp  21
- cpp/tests/core/DLPack/DLPackConverter.cpp  4
- cpp/tests/pipelines/odometry/RGBDOdometryJacobianFromColorTerm.cpp  2
- cpp/tests/core/TensorList.cpp  63
- cpp/tests/test_utility/Sort.cpp  2
- cpp/tests/test_utility/Print.h  6
- cpp/tests/io/Sensor/AzureKinect/AzureKinectSensorConfig.cpp  1
- cpp/tests/geometry/Image.cpp  60
- cpp/tests/geometry/PointCloud.cpp  30
- cpp/tests/test_utility/Rand.cpp  11
- cpp/benchmarks/io/PointCloudIO.cpp  2
- cpp/tests/core/Tensor.cpp  284
- cpp/tests/geometry/RGBDImage.cpp  43
- cpp/tests/geometry/TriangleMesh.cpp  117
- cpp/tests/geometry/Octree.cpp  6
- cpp/tests/geometry/KDTreeFlann.cpp  7
- cpp/tests/utility/Eigen.cpp  6
- cpp/tests/io/FileFormat/FileSTL.cpp  1
- cpp/tests/test_utility/Raw.cpp  2
- cpp/tests/pipelines/color_map/ColorMapOptimization.cpp  342
- cpp/tests/camera/PinholeCameraIntrinsic.cpp  11
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5728148&bid=18739644)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/Indexer.cpp  2
- cpp/tests/pipelines/odometry/RGBDOdometryJacobianFromColorTerm.cpp  2
- cpp/tests/utility/FileSystem.cpp  14
- cpp/tests/geometry/Octree.cpp  6
- cpp/tests/test_utility/Print.h  6
- cpp/tests/utility/Eigen.cpp  6
- cpp/tests/geometry/KDTreeFlann.cpp  7
- cpp/tests/geometry/PointCloud.cpp  30
- cpp/tests/test_utility/Compare.cpp  2
- cpp/tests/io/Sensor/AzureKinect/AzureKinectSensorConfig.cpp  1
- cpp/tests/camera/PinholeCameraIntrinsic.cpp  11
- cpp/tests/io/FileFormat/FileGLTF.cpp  2
- cpp/tests/core/Tensor.cpp  284
- cpp/tests/test_utility/Compare.h  2
- cpp/tests/geometry/HalfEdgeTriangleMesh.cpp  18
- cpp/tests/pipelines/odometry/RGBDOdometryJacobianFromHybridTerm.cpp  2
- cpp/tests/core/DLPack/DLPackConverter.cpp  4
- cpp/tests/test_utility/Raw.cpp  2
- cpp/tests/geometry/RGBDImage.cpp  43
- cpp/tests/geometry/IntersectionTest.cpp  2
- cpp/tests/io/ClassIO/PointCloudIO.cpp  40
- cpp/tests/geometry/Image.cpp  60
- cpp/tests/pipelines/color_map/ColorMapOptimization.cpp  342
- cpp/tests/test_utility/Rand.cpp  11
- cpp/tests/geometry/LineSet.cpp  21
- cpp/tests/core/TensorList.cpp  63
- cpp/tests/geometry/TriangleMesh.cpp  117
- cpp/tests/geometry/TetraMesh.cpp  30
- cpp/tests/io/ClassIO/OctreeIO.cpp  3
- cpp/benchmarks/io/PointCloudIO.cpp  2
- cpp/tests/test_utility/Sort.cpp  2
- cpp/tests/pipelines/odometry/OdometryTools.cpp  2
- cpp/tests/io/FileFormat/FileSTL.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5728148&bid=18739644)

**Comment by pvarvak** [comment]
1. reorg removed
2. bin/tests and bin/benchmarks

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/geometry/TriangleMesh.cpp  117
- cpp/tests/test_utility/Sort.cpp  2
- cpp/tests/geometry/TetraMesh.cpp  30
- cpp/tests/test_utility/Rand.cpp  11
- cpp/tests/geometry/KDTreeFlann.cpp  7
- cpp/tests/core/Tensor.cpp  284
- cpp/tests/pipelines/odometry/RGBDOdometryJacobianFromColorTerm.cpp  2
- cpp/tests/utility/Eigen.cpp  6
- cpp/tests/test_utility/Compare.cpp  2
- cpp/tests/geometry/IntersectionTest.cpp  2
- cpp/benchmarks/io/PointCloudIO.cpp  2
- cpp/tests/test_utility/Print.h  6
- cpp/tests/io/ClassIO/OctreeIO.cpp  3
- cpp/tests/geometry/PointCloud.cpp  30
- cpp/tests/utility/FileSystem.cpp  14
- cpp/tests/geometry/LineSet.cpp  21
- cpp/tests/core/Indexer.cpp  2
- cpp/tests/geometry/Octree.cpp  6
- cpp/tests/test_utility/Raw.cpp  2
- cpp/tests/io/FileFormat/FileSTL.cpp  1
- cpp/tests/io/FileFormat/FileGLTF.cpp  2
- cpp/tests/pipelines/color_map/ColorMapOptimization.cpp  342
- cpp/tests/io/ClassIO/PointCloudIO.cpp  40
- cpp/tests/pipelines/odometry/OdometryTools.cpp  2
- cpp/tests/camera/PinholeCameraIntrinsic.cpp  11
- cpp/tests/geometry/RGBDImage.cpp  43
- cpp/tests/core/DLPack/DLPackConverter.cpp  4
- cpp/tests/geometry/Image.cpp  60
- cpp/tests/io/Sensor/AzureKinect/AzureKinectSensorConfig.cpp  1
- cpp/tests/geometry/HalfEdgeTriangleMesh.cpp  18
- cpp/tests/pipelines/odometry/RGBDOdometryJacobianFromHybridTerm.cpp  2
- cpp/tests/core/TensorList.cpp  63
- cpp/tests/test_utility/Compare.h  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5728148&bid=18739644)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/pipelines/color_map/ColorMapOptimization.cpp  342
- cpp/tests/geometry/HalfEdgeTriangleMesh.cpp  18
- cpp/tests/core/Tensor.cpp  284
- cpp/tests/geometry/TriangleMesh.cpp  117
- cpp/tests/core/TensorList.cpp  63
- cpp/tests/core/DLPack/DLPackConverter.cpp  4
- cpp/tests/io/Sensor/AzureKinect/AzureKinectSensorConfig.cpp  1
- cpp/tests/pipelines/odometry/RGBDOdometryJacobianFromHybridTerm.cpp  2
- cpp/tests/geometry/RGBDImage.cpp  43
- cpp/tests/io/ClassIO/OctreeIO.cpp  3
- cpp/tests/geometry/Image.cpp  60
- cpp/tests/io/ClassIO/PointCloudIO.cpp  40
- cpp/tests/test_utility/Rand.cpp  11
- cpp/tests/pipelines/odometry/RGBDOdometryJacobianFromColorTerm.cpp  2
- cpp/tests/test_utility/Print.h  6
- cpp/tests/io/FileFormat/FileGLTF.cpp  2
- cpp/tests/pipelines/odometry/OdometryTools.cpp  2
- cpp/tests/test_utility/Raw.cpp  2
- cpp/tests/test_utility/Compare.cpp  2
- cpp/tests/geometry/LineSet.cpp  21
- cpp/tests/geometry/PointCloud.cpp  30
- cpp/benchmarks/io/PointCloudIO.cpp  2
- cpp/tests/geometry/KDTreeFlann.cpp  7
- cpp/tests/test_utility/Compare.h  2
- cpp/tests/geometry/Octree.cpp  6
- cpp/tests/core/Indexer.cpp  2
- cpp/tests/utility/FileSystem.cpp  14
- cpp/tests/utility/Eigen.cpp  6
- cpp/tests/geometry/TetraMesh.cpp  30
- cpp/tests/camera/PinholeCameraIntrinsic.cpp  11
- cpp/tests/test_utility/Sort.cpp  2
- cpp/tests/io/FileFormat/FileSTL.cpp  1
- cpp/tests/geometry/IntersectionTest.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5728148&bid=18739644)

**Pull request merged**
