### PR TITLE
RPC receiver for visualizer

### PR DESCRIPTION
**Pull request by benjaminum**
This PR adds a receiver to the visualizer
- new receiver class for the visualizer with support for pointcloud and trianglemesh
- added convenience shape and type checking functions to the Array message
- moved helper function from DummyReceiver to MessageUtils

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2182)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/visualization/visualizer/Receiver.cpp  28
- cpp/open3d/io/rpc/ReceiverBase.cpp  6
- cpp/open3d/io/rpc/MessageUtils.cpp  1
         

Clones removed
==============
+ cpp/open3d/io/rpc/DummyReceiver.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6021005&bid=19736573)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/io/rpc/MessageUtils.cpp  1
- cpp/open3d/visualization/visualizer/Receiver.cpp  28
- cpp/open3d/io/rpc/ReceiverBase.cpp  6
         

Clones removed
==============
+ cpp/open3d/io/rpc/DummyReceiver.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6021005&bid=19736573)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/io/rpc/ReceiverBase.cpp  6
- cpp/open3d/io/rpc/MessageUtils.cpp  1
- cpp/open3d/visualization/visualizer/Receiver.cpp  28
         

Clones removed
==============
+ cpp/open3d/io/rpc/DummyReceiver.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6021005&bid=19736573)

**Comment by germanros1987** [comment]
@benjaminum bring the PR up to speed?

**Review by prewettg — APPROVED** [review]
> Reviewed 12 of 16 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2182)* status: all files reviewed, 1 unresolved discussion (waiting on @benjaminum)

___
*[cpp/apps/Open3DViewer/Open3DViewer.cpp, line 61 at r3](https://reviewable.io/reviews/intel-isl/open3d/2182#-MJZ8trD-dwXOJKwkIt0:-MJZ8trE7ydaxrUdSoyg:bikteru) ([raw file](https://github.com/intel-isl/open3d/blob/e51cd912f9a349e7ca8f9cdf2c5e4c26bcfc2121/cpp/apps/Open3DViewer/Open3DViewer.cpp#L61)):*
> ```cpp
>             argc, (char **)argv, "--bind",
>             io::rpc::Connection::DefaultAddress());
>     vis->StartRPCInterface(address, 1000);
> ```

Is BUILD_RPC_INTERFACE is OFF by default? Otherwise I don't think we should have this on without the user enabling it. It seems like it could be a security hole, and it certainly would be unexpected. 
___
*[cpp/open3d/visualization/visualizer/GuiVisualizer.cpp, line 1045 at r3](https://reviewable.io/reviews/intel-isl/open3d/2182#-MJZB5MBCZrQGIw-ynCn:-MJZB5MBCZrQGIw-ynCo:biixhux) ([raw file](https://github.com/intel-isl/open3d/blob/e51cd912f9a349e7ca8f9cdf2c5e4c26bcfc2121/cpp/open3d/visualization/visualizer/GuiVisualizer.cpp#L1045)):*
> ```cpp
>             this, impl_->scene_wgt_->GetScene(), address, timeout);
>     try {
>         utility::LogInfo("Starting to listen on {}", address);
> ```

I like that we inform the user that we are listening to RPC requests.

**Comment by prewettg** [comment]
Is Open3DViewer where you want this feature? I thought you were thinking more along the lines of the ML3D viewer?

**Review by benjaminum — COMMENTED** [review]
I want it in everything that runs as its own independent process.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2182#-:-MJuIaAi-2kmxh9xAUst:b3oii4z)* status: all files reviewed, 1 unresolved discussion (waiting on @prewettg)

___
*[cpp/apps/Open3DViewer/Open3DViewer.cpp, line 61 at r3](https://reviewable.io/reviews/intel-isl/open3d/2182#-MJZ8trD-dwXOJKwkIt0:-MJuIEpe985loGbKDcvn:bb0x1va) ([raw file](https://github.com/intel-isl/open3d/blob/e51cd912f9a349e7ca8f9cdf2c5e4c26bcfc2121/cpp/apps/Open3DViewer/Open3DViewer.cpp#L61)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

Is BUILD_RPC_INTERFACE is OFF by default? Otherwise I don't think we should have this on without the user enabling it. It seems like it could be a security hole, and it certainly would be unexpected. 
</blockquote></details>

It is ON for building the release packages. We can add a cmd line parameter for enabling it

**Review by prewettg — APPROVED** [review]
> Reviewed 7 of 8 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2182)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
