### PR TITLE
Move Numpy I/O to t/io/NumpyIO.h

### PR DESCRIPTION
**Pull request by yxlao**
- Move numpy IO to the `t/io` directory. 
- Hide `NumpyArray` class as implementation details. 
- This is a pure refactoring PR to prepare us for future support for `.npz` file format.

This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3752)

### CODE REVIEW

**Review by theNded — APPROVED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3752)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ssheorey)

**Review by ssheorey — COMMENTED** [review]
LGTM after the minor comments.

Once we have `npz` support, can we use Numpy I/O to implement pickling for Tensors and TGeometry types? (#218). I think this just needs implementing `__setstate__` and `__getstate__` pybinds.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3752#-:-MezUBFP9CFszCmZmBJc:bomrscj)* status: all files reviewed, 3 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/t/io/NumpyIO.cpp, line 72 at r1](https://reviewable.io/reviews/intel-isl/open3d/3752#-MezPWYVCJCGGhNkIrsK:-MezNbUo2-QzY0h72EDC:bwa5j4x) ([raw file](https://github.com/intel-isl/open3d/blob/c3bb7d98abb75ecaa636cf7fa07cf1c68abbc1a1/cpp/open3d/t/io/NumpyIO.cpp#L72)):*
> ```cpp
> static char BigEndianChar() {
>     int x = 1;
>     return (((char*)&x)[0]) ? '<' : '>';
> ```

`reinterpret_cast`
___
*[cpp/open3d/t/io/NumpyIO.cpp, line 104 at r1](https://reviewable.io/reviews/intel-isl/open3d/3752#-MezPang5EpXsXdAu6DM:-MezPang5EpXsXdAu6DN:b4nn0lk) ([raw file](https://github.com/intel-isl/open3d/blob/c3bb7d98abb75ecaa636cf7fa07cf1c68abbc1a1/cpp/open3d/t/io/NumpyIO.cpp#L104)):*
> ```cpp
>     std::stringstream ss;
>     for (size_t i = 0; i < sizeof(T); i++) {
>         char val = *((char*)&rhs + i);
> ```

`reinterpret_cast`
`memcpy` may be faster than byte streaming.
___
*[cpp/open3d/t/io/NumpyIO.cpp, line 246 at r1](https://reviewable.io/reviews/intel-isl/open3d/3752#-MezQvnAEzEvqAgkLxco:-MezQvnAEzEvqAgkLxcp:b-8gxch8) ([raw file](https://github.com/intel-isl/open3d/blob/c3bb7d98abb75ecaa636cf7fa07cf1c68abbc1a1/cpp/open3d/t/io/NumpyIO.cpp#L246)):*
> ```cpp
>           fortran_order_(false),
>           num_elements_(t.GetShape().NumElements()) {
>         blob_ = t.Contiguous().To(core::Device("CPU:0")).GetBlob();
> ```

If `t` is CUDA and not contiguous, would this copy twice? `Contiguous` should not be necessary.

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3752)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[cpp/open3d/t/io/NumpyIO.cpp, line 72 at r1](https://reviewable.io/reviews/intel-isl/open3d/3752#-MezPWYVCJCGGhNkIrsK:-Mf-Xhra-BHLHtfLUw4Q:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c3bb7d98abb75ecaa636cf7fa07cf1c68abbc1a1/cpp/open3d/t/io/NumpyIO.cpp#L72)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

`reinterpret_cast`
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/NumpyIO.cpp, line 104 at r1](https://reviewable.io/reviews/intel-isl/open3d/3752#-MezPang5EpXsXdAu6DM:-Mf-XiGa30CkOMDwPs08:b-30czw3) ([raw file](https://github.com/intel-isl/open3d/blob/c3bb7d98abb75ecaa636cf7fa07cf1c68abbc1a1/cpp/open3d/t/io/NumpyIO.cpp#L104)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

`reinterpret_cast`
`memcpy` may be faster than byte streaming.
</blockquote></details>

Change to `reinterpret_cast`.
The `ToByteString` function is only used to parse array headers, so the performance impact would be rather small.
___
*[cpp/open3d/t/io/NumpyIO.cpp, line 246 at r1](https://reviewable.io/reviews/intel-isl/open3d/3752#-MezQvnAEzEvqAgkLxco:-Mf-Xrwx3mh0iVbFv591:bj8gass) ([raw file](https://github.com/intel-isl/open3d/blob/c3bb7d98abb75ecaa636cf7fa07cf1c68abbc1a1/cpp/open3d/t/io/NumpyIO.cpp#L246)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

If `t` is CUDA and not contiguous, would this copy twice? `Contiguous` should not be necessary.
</blockquote></details>

Reverted order to:`To(CPU).Contiguous()`

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3752)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @ssheorey and @theNded)

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3752)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @ssheorey, @theNded, and @yxlao)

___
*[cpp/open3d/t/io/NumpyIO.cpp, line 318 at r2](https://reviewable.io/reviews/intel-isl/open3d/3752#-Mf-zY6EDJ_FNn_1hCIr:-Mf-zY6EDJ_FNn_1hCIs:bwoduvb) ([raw file](https://github.com/intel-isl/open3d/blob/543062db67aa09158c42210b28aef433cddccfd8/cpp/open3d/t/io/NumpyIO.cpp#L318)):*
> ```
> fp
> ```
Is this assert redundant?

**Pull request merged**
