### PR TITLE
New Mesh Class Structure

### PR DESCRIPTION
**Pull request by griegler**
Reorganizing the mesh geometries: There is a new `MeshBase` class that only contains `vertices_` and related attributes. `TriangleMesh` and `HalfEdgeTriangleMesh` are children of `MeshBase`.  Edit: `TetraMesh` is also a child of `MeshBase` now. ~~Further, this PR adds `TexturedTriangleMesh` which contains `uvs_` (3 per triangle) and a `texture_`.~~
`TriangleMesh` can now contain uv coordinates in `triangle_uvs_` (3 per triangle) and a `texture_` image.

The script `half_edge_mesh.py` does not segfault on execution anymore (addressing #1179), but the results still look weird. @yxlao could you please have a look, as the code mostly builds on your initial `HalfEdgeTriangleMesh` class.

~~`TexturedTriangleMesh` is bare bones, there are no IO, nor visualization capabilities. I think @theNded  wanted to look into this?~~

~~Right now the `TriangleMesh` operations, e.g. `Filter*`, `Simplification*` do not touch the `uvs_`, should we print a warning for now?~~
All `TriangleMesh` methods that change the number of `triangles_` print a warning if the mesh contains uv coordinates. In future PRs we can extend these methods to handle the uv coordinates correctly.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1184)

### CODE REVIEW

**Comment by theNded** [comment]
Ah, actually I just did something similar. I cannot figure out a good way to load obj into varying meshtypes (`TriangleMesh` vs `TexturedTriangleMesh`, so my current solution is to hardcode uvs inside `TriangleMesh` class.
With this `MeshBase` class I think we need to change some of the function signatures to support polymorphism? 

For example, we can change
```cpp
bool ReadTriangleMeshFromOBJ(const std::string& filename,
                             geometry::TriangleMesh& mesh,
                             bool print_progress)
```
to something like
```cpp
bool ReadTriangleMeshFromOBJ(const std::string& filename,
                             std::shared_ptr<geometry::MeshBase>& mesh,
                             bool print_progress) 
```
and return the correct meshtype according to the file content parser.

**Comment by griegler** [comment]
@theNded hmm, returning `std::shared_ptr<geometry::MeshBase>` does not seem to be ideal. Maybe `std::shared_ptr<geometry::TriangleMesh>`, but I still do not like that we would test for the real instance at runtime. 
Maybe we really can merge `TriangleMesh` and `TexturedTriangleMesh`? We have the `Has*` methods anyway.

**Comment by theNded** [comment]
@griegler I have an initial implementation (haven't covered boundary cases though). If it makes sense maybe we can do this.
https://github.com/theNded/Open3D/blob/texture/src/Open3D/Geometry/TriangleMesh.h
https://github.com/theNded/Open3D/blob/texture/src/Open3D/IO/FileFormat/FileOBJ.cpp

**Comment by griegler** [comment]
@theNded Yes, I am fine with having `uvs` and `texture` in `TriangleMesh`, but I think it shouldn't be `vertex_uvs`. `triangle_uvs` (3 uvs coordinates per triangle) seems to be a better choice and is also closer to the `obj` format.

**Comment by theNded** [comment]
@griegler I agree. Should we temporarily remove `TexturedTriangleMesh` in this PR and let me modify `TriangleMesh` in another PR?

**Comment by griegler** [comment]
@theNded I will merge `TexturedTriangleMesh` into `TriangleMesh` in this PR based on this discussion. Then, I can also add warnings to other methods (`Filter*`, ...) if `uvs` are set. Does this work for you?

**Comment by theNded** [comment]
@griegler Sure, thanks!

**Comment by yxlao** [comment]
@griegler HalfEdgeTriangleMesh fixes pushed

**Comment by griegler** [comment]
@yxlao Thanks. LGTM. I just have one question, why does the `HalfTriangleMesh` needs the `triangles_` vector? All the information should be in the `half_edges_`?

**Comment by yxlao** [comment]
@griegler that seems right, in that way we can keep the `HalfEdgeTriangleMesh` minimalistic. I will do that in a separate PR, since that will require a new `SimpleShaderForHalfEdgeTriangleMesh`. 

If that's okay for you we can merge this PR.

**Comment by griegler** [comment]
@yxlao I think we are then ready to merge.

**Pull request merged**
