### PR TITLE
Fast compression mode for png writing (issue #846)

### PR DESCRIPTION
**Pull request by ssheorey**
Enable PNG_IMAGE_FLAG_FAST with quality<=2
Write time: 86ms->19ms
File size: 374KB->596KB
for lena_color (512x512)

Issue #846

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2325)

### CODE REVIEW

**Review by errissa — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2325)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @errissa, @ssheorey, and @yxlao)

___
*[cpp/open3d/io/ImageIO.h, line 46 at r1](https://reviewable.io/reviews/intel-isl/open3d/2325#-MH1q-MNEsUyuS9s4u5u:-MH1q-MNEsUyuS9s4u5v:b30ppg8) ([raw file](https://github.com/intel-isl/open3d/blob/159842872be0655a75394f96bc6f2c0a99043750/cpp/open3d/io/ImageIO.h#L46)):*
> ```objc
> bool ReadImage(const std::string &filename, geometry::Image &image);
> 
> #define OPEN3D_IO_IMAGEIO_DEFAULT_QUALITY -1
> ```

Google C++ style guide discourages the use of preprocessor macros in a context like this. I defer to @yxlao on this but, you may consider `const int kOpen3DImageIODefaultQuality = -1` instead.

**Review by errissa — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2325)* status: all files reviewed, 1 unresolved discussion (waiting on @ssheorey and @yxlao)

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2325)* status: all files reviewed, 1 unresolved discussion (waiting on @errissa)

___
*[cpp/open3d/io/ImageIO.h, line 46 at r1](https://reviewable.io/reviews/intel-isl/open3d/2325#-MH1q-MNEsUyuS9s4u5u:-MH3otiF1SukYo-0fzIK:bdbs0oj) ([raw file](https://github.com/intel-isl/open3d/blob/159842872be0655a75394f96bc6f2c0a99043750/cpp/open3d/io/ImageIO.h#L46)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

Google C++ style guide discourages the use of preprocessor macros in a context like this. I defer to @yxlao on this but, you may consider `const int kOpen3DImageIODefaultQuality = -1` instead.
</blockquote></details>

agreed, shall we directly give the default value?

```cpp
constexpr int kOpen3DImageIODefaultQuality = 6;
```

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2325)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @errissa)

___
*[cpp/open3d/io/ImageIO.h, line 46 at r1](https://reviewable.io/reviews/intel-isl/open3d/2325#-MH1q-MNEsUyuS9s4u5u:-MH8nXdO9PIkjVnacfN4:b-m860qb) ([raw file](https://github.com/intel-isl/open3d/blob/159842872be0655a75394f96bc6f2c0a99043750/cpp/open3d/io/ImageIO.h#L46)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

agreed, shall we directly give the default value?

```cpp
constexpr int kOpen3DImageIODefaultQuality = 6;
```
</blockquote></details>

Changed to `constexpr int`. The default quality is different for jpg (90) and png (6). The -1 is interpreted by each format writer to use it's own default.

**Review by errissa — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2325)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
