### PR TITLE
TransformConverter supports Float32 and Float64 

### PR DESCRIPTION
**Pull request by reyanshsolis**
Changes:
-  Float32 and Float64 support added for PoseToTransformation and RtToTransformation.
-  Changed `DTYPE == Dtype...` to `DTYPE == core::Dtype...`  `DISPATCH_FLOAT32_FLOAT64_DTYPE`, in core/CoreUtil.h, as for t:: modules. not inside core namespace, dispatching the code to just Dtype::... throws error. 
-  Modified Unit Tests.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3098)

### CODE REVIEW

**Review by theNded — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3098)* status: all files reviewed, 3 unresolved discussions (waiting on @reyanshsolis and @yxlao)

___
*[cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp, line 88 at r1](https://reviewable.io/reviews/intel-isl/open3d/3098#-MUfSTS3CnhPhFyEGIt9:-MUfSTS3CnhPhFyEGItA:bfndlt2) ([raw file](https://github.com/intel-isl/open3d/blob/4a327a3f4f26315173ba0410e9e4931e0382c522/cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp#L88)):*
> ```cpp
>     core::Tensor pose_ = pose.Contiguous();
> 
>     DISPATCH_FLOAT32_FLOAT64_DTYPE(dtype, [&]() {
> ```

This breaks CI, put them in kernels. Refactor kernel as PoseToTransformDEVICE(trans_ptr, pose_ptr, dtype)
___
*[cpp/open3d/t/pipelines/kernel/TransformationConverter.cu, line 40 at r1](https://reviewable.io/reviews/intel-isl/open3d/3098#-MUfSku60btQzleoNWMi:-MUfSku60btQzleoNWMj:b-849m2f) ([raw file](https://github.com/intel-isl/open3d/blob/4a327a3f4f26315173ba0410e9e4931e0382c522/cpp/open3d/t/pipelines/kernel/TransformationConverter.cu#L40)):*
> ```Cuda
> __global__ void PoseToTransformationKernel(scalar_t *transformation_ptr,
>                                            const scalar_t *X_ptr) {
>     PoseToTransformationImpl(transformation_ptr, X_ptr);
> ```

PoseToTransformationImpl(trans_ptr, X_ptr, dtype)
___
*[cpp/open3d/t/pipelines/kernel/TransformationConverterImpl.h, line 43 at r1](https://reviewable.io/reviews/intel-isl/open3d/3098#-MUfSr-E8jk-PAEcVCp3:-MUfSr-E8jk-PAEcVCp4:b-fby07h) ([raw file](https://github.com/intel-isl/open3d/blob/4a327a3f4f26315173ba0410e9e4931e0382c522/cpp/open3d/t/pipelines/kernel/TransformationConverterImpl.h#L43)):*
> ```objc
> /// Shared implementation for PoseToTransformation function.
> template <typename scalar_t>
> OPEN3D_HOST_DEVICE inline void PoseToTransformationImpl(
> ```

DISPATCH dtype here

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3098)* status: all files reviewed, 5 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/core/CoreUtil.h, line 36 at r1](https://reviewable.io/reviews/intel-isl/open3d/3098#-MUhBual3tl6vd8L4A3l:-MUhBual3tl6vd8L4A3m:b-47wy87) ([raw file](https://github.com/intel-isl/open3d/blob/4a327a3f4f26315173ba0410e9e4931e0382c522/cpp/open3d/core/CoreUtil.h#L36)):*
> ```objc
> #define DISPATCH_FLOAT32_FLOAT64_DTYPE(DTYPE, ...)       \
>     [&] {                                                \
>         if (DTYPE == core::Dtype::Float32) {             \
> ```

we are in `namespace core {`, is this needed? 
___
*[cpp/tests/t/pipelines/TransformationConverter.cpp, line 73 at r1](https://reviewable.io/reviews/intel-isl/open3d/3098#-MUhELat-_lYp7mIua3z:-MUhELau3foScnOcUIAE:bp2w1q8) ([raw file](https://github.com/intel-isl/open3d/blob/4a327a3f4f26315173ba0410e9e4931e0382c522/cpp/tests/t/pipelines/TransformationConverter.cpp#L73)):*
> ```cpp
>     dtype[1] = core::Dtype::Float64;
> 
>     for (int i = 0; i < 2; i++) {
> ```

this may be done in a more compact way, could you try:

```cpp
    for (const core::Dtype& dtype :
         {core::Dtype::Float32, core::Dtype::Float64}) {
        core::Tensor pose = core::Tensor::Zeros({6}, dtype, device);
        core::Tensor transformation_ =
                t::pipelines::kernel::PoseToTransformation(pose);

        core::Tensor transformation = core::Tensor::Eye(4, dtype, device);
        EXPECT_TRUE(transformation_.AllClose(transformation));
    }
```

same for the one above

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3098)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @theNded)

___
*[cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp, line 88 at r1](https://reviewable.io/reviews/intel-isl/open3d/3098#-MUfSTS3CnhPhFyEGIt9:-MUiWdX47vNMm7BolxhY:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/4a327a3f4f26315173ba0410e9e4931e0382c522/cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp#L88)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

This breaks CI, put them in kernels. Refactor kernel as PoseToTransformDEVICE(trans_ptr, pose_ptr, dtype)
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/TransformationConverter.cu, line 40 at r1](https://reviewable.io/reviews/intel-isl/open3d/3098#-MUfSku60btQzleoNWMi:-MUiWka-1LqxsG-JztOS:b-m40iwx) ([raw file](https://github.com/intel-isl/open3d/blob/4a327a3f4f26315173ba0410e9e4931e0382c522/cpp/open3d/t/pipelines/kernel/TransformationConverter.cu#L40)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

PoseToTransformationImpl(trans_ptr, X_ptr, dtype)
</blockquote></details>

Took a slightly different approach, as `PoseToTransformationImpl(trans_ptr, X_ptr)` is called inside a CUDA kernel, so using Tensor members is not possible. But it is working fine now.
___
*[cpp/open3d/t/pipelines/kernel/TransformationConverterImpl.h, line 43 at r1](https://reviewable.io/reviews/intel-isl/open3d/3098#-MUfSr-E8jk-PAEcVCp3:-MUiXAtd8TQdu86maJzZ:b722fh1) ([raw file](https://github.com/intel-isl/open3d/blob/4a327a3f4f26315173ba0410e9e4931e0382c522/cpp/open3d/t/pipelines/kernel/TransformationConverterImpl.h#L43)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

DISPATCH dtype here
</blockquote></details>

Not allowed to use core::Dtype here, so it might not be possible to DISPATCH here.

**Comment by reyanshsolis** [comment]
> _[cpp/open3d/core/CoreUtil.h, line 36 at r1](https://reviewable.io/reviews/intel-isl/open3d/3098#-MUhBual3tl6vd8L4A3l:-MUhBual3tl6vd8L4A3m:b-47wy87) ([raw file](https://github.com/intel-isl/open3d/blob/4a327a3f4f26315173ba0410e9e4931e0382c522/cpp/open3d/core/CoreUtil.h#L36)):_
> 
> > ```objc
> > #define DISPATCH_FLOAT32_FLOAT64_DTYPE(DTYPE, ...)       \
> >     [&] {                                                \
> >         if (DTYPE == core::Dtype::Float32) {             \
> > ```
> 
> we are in `namespace core {`, is this needed?

It was throwing error of `Dtype not declared` in cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp, without this change. I think, it only `dispatches the snippet` where the template is called, so if that happens to be in a part of code where we are not inside core namespace such as this function open3d::t::pipelines::kernel, the dispatched snippet will throw an error.

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3098)* status: all files reviewed, 4 unresolved discussions (waiting on @reyanshsolis and @theNded)

___
*[cpp/open3d/core/CoreUtil.h, line 36 at r1](https://reviewable.io/reviews/intel-isl/open3d/3098#-MUhBual3tl6vd8L4A3l:-MUhBual3tl6vd8L4A3m:b-j3vx7r) ([raw file](https://github.com/intel-isl/open3d/blob/4a327a3f4f26315173ba0410e9e4931e0382c522/cpp/open3d/core/CoreUtil.h#L36)):*
> ```objc
> #define DISPATCH_FLOAT32_FLOAT64_DTYPE(DTYPE, ...)       \
>     [&] {                                                \
>         if (DTYPE == core::Dtype::Float32) {             \
> ```

please update it to `::open3d::core::Dtype` and move outside of all namespaces

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3098)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/core/CoreUtil.h, line 36 at r1](https://reviewable.io/reviews/intel-isl/open3d/3098#-MUhBual3tl6vd8L4A3l:-MUn0z83EaaM85LyUxOU:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/4a327a3f4f26315173ba0410e9e4931e0382c522/cpp/open3d/core/CoreUtil.h#L36)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

please update it to `::open3d::core::Dtype` and move outside of all namespaces
</blockquote></details>

Done.

**Review by yxlao — APPROVED** [review]

**Pull request merged**
