### PR TITLE
Adds menu option on macOS to make Open3D viewer default for file types

### PR DESCRIPTION
**Pull request by prewettg**
Also makes macOS menu more Mac-like, and fixes problems with auto-centering windows. Menu option only exists on macOS.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2031)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/visualization/gui/Menu.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5790595&bid=18954021)

**Comment by prewettg** [comment]
___
*[cpp/apps/Open3DViewer/Open3DViewer.cpp, line 45 at r2](https://reviewable.io/reviews/intel-isl/open3d/2031#-MBCpRfk3S-iRVLRHIn0:-MBDUHvf-XyiB1UnGLOv:b-22q3vo) ([raw file](https://github.com/intel-isl/open3d/blob/6cb9f8f0ff9ec35a622f4d927350f3671b5c5764/cpp/apps/Open3DViewer/Open3DViewer.cpp#L45)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

do you care to make these named constants?
</blockquote></details>

This function is deleted (I hope!), the constants go away and now the window will be centered.

**Comment by prewettg** [comment]
___
*[cpp/apps/Open3DViewer/Open3DViewer.cpp, line 57 at r2](https://reviewable.io/reviews/intel-isl/open3d/2031#-MBCpX6d8-tjEiurFXYL:-MBDUUPA9QGIPo2mxwcf:bv71n64) ([raw file](https://github.com/intel-isl/open3d/blob/6cb9f8f0ff9ec35a622f4d927350f3671b5c5764/cpp/apps/Open3DViewer/Open3DViewer.cpp#L57)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

more named constants?
</blockquote></details>

Also deleted, I hope

**Comment by prewettg** [comment]
___
*[cpp/open3d/visualization/gui/Window.cpp, line 828 at r2](https://reviewable.io/reviews/intel-isl/open3d/2031#-MBCqE3NEStTZTHjxZEI:-MBFPvsuBvxllS__WIRq:bgva598) ([raw file](https://github.com/intel-isl/open3d/blob/40ead2c431290de7b255bd2507df2c96b9222592/cpp/open3d/visualization/gui/Window.cpp#L828)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

do you care to have these constants in a more visible place? 
</blockquote></details>

Made them constants at the top of the file

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/visualization/gui/Menu.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5790595&bid=18954021)

**Pull request merged**
