### PR TITLE
Set a valid shader name when model is added

### PR DESCRIPTION
**Pull request by errissa**
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3498)

### CODE REVIEW

**Review by prewettg — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3498)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @errissa)

___
*[cpp/open3d/visualization/visualizer/O3DVisualizer.cpp, line 941 at r1](https://reviewable.io/reviews/intel-isl/open3d/3498#-MaZnnjS-LApFQXt3FDC:-MaZnnjS-LApFQXt3FDD:b-ir6jjd) ([raw file](https://github.com/intel-isl/open3d/blob/0f103f7fefa300c83a16874465417ef27d04a3ad/cpp/open3d/visualization/visualizer/O3DVisualizer.cpp#L941)):*
> ```cpp
>                 mat.anisotropy_img = mesh_material.anisotropy;
>             }
>         } else {
> ```

Since this is so short, I think it would be easier to understand if we did:
    if (material) {...}
    else if (model) { ... }
    else { ... } // this is regular geometry
I had to walk through the logic to make sure that this was correct, while my suggestion seems pretty clear what's going on.

**Review by errissa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3498)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @prewettg)

___
*[cpp/open3d/visualization/visualizer/O3DVisualizer.cpp, line 941 at r1](https://reviewable.io/reviews/intel-isl/open3d/3498#-MaZnnjS-LApFQXt3FDC:-MaZsL7Z1zebkUwFPoPE:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0f103f7fefa300c83a16874465417ef27d04a3ad/cpp/open3d/visualization/visualizer/O3DVisualizer.cpp#L941)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

Since this is so short, I think it would be easier to understand if we did:
    if (material) {...}
    else if (model) { ... }
    else { ... } // this is regular geometry
I had to walk through the logic to make sure that this was correct, while my suggestion seems pretty clear what's going on.
</blockquote></details>

Done.

**Review by prewettg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3498)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @errissa)

**Review by prewettg — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3498)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @errissa)

**Pull request merged**
