### PR TITLE
Shortcuts for Dtypes

### PR DESCRIPTION
**Pull request by yxlao**
Adding shortcuts for Dtypes, making it NumPy-like.

### Before and after this PR
```python
import open3d as o3d

# Before
o3d.core.Dtype.Float32
o3d.core.Dtype.Int32

# After
o3d.core.float32
o3d.core.int32
```

```cpp
// Before
open3d::core::Dtype::Float32;
open3d::core::Dtype::Int32;

// After
open3d::core::Float32;
open3d::core::Int32;
```
The old API still works as well.

### Comparing with PyTorch and Numpy
```python
import torch
torch.float32
torch.int32

import numpy
numpy.float32
numpy.int32
```

```cpp
// PyTorch C++
torch::kInt32;
torch::kFloat32;
at::kFloat;
at::kInt;
```

This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3741)

### CODE REVIEW

**Review by stotko — CHANGES_REQUESTED** [review]
> Reviewed 5 of 154 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3741)* status: 5 of 154 files reviewed, 5 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[replace_all.py, line 1 at r1](https://reviewable.io/reviews/intel-isl/open3d/3741#-Meyefs36_ptwZmL3Ba6:-Meyefs36_ptwZmL3Ba7:b-wtgygt) ([raw file](https://github.com/intel-isl/open3d/blob/016128362237c1d4846d892b84afddba497a7f87/replace_all.py#L1)):*
> ```Python
> from pathlib import Path
> ```

This script is only required for finding all usages of the `Dtype` and will be removed before merging, right?
___
*[replace_all_py.py, line 1 at r1](https://reviewable.io/reviews/intel-isl/open3d/3741#-MeyeyW8B-1inW1NwDf-:-MeyeyW8B-1inW1NwDf0:b-q64pkt) ([raw file](https://github.com/intel-isl/open3d/blob/016128362237c1d4846d892b84afddba497a7f87/replace_all_py.py#L1)):*
> ```Python
> from pathlib import Path
> ```

See above.
___
*[cpp/open3d/core/Dtype.h, line 94 at r1](https://reviewable.io/reviews/intel-isl/open3d/3741#-Meyf8j5EdPoIBHafnc2:-Meyf8j6Du-RzaBosGQk:b35hsg) ([raw file](https://github.com/intel-isl/open3d/blob/016128362237c1d4846d892b84afddba497a7f87/cpp/open3d/core/Dtype.h#L94)):*
> ```objc
> };
> 
> OPEN3D_API extern const Dtype kUndefined;
> ```

Although the convention is to prefix constants with `k`, would it be instead better to remove that prefix and treat these statements as some sort of "using" statement? The original `Dtype::Undefined`, etc. values are already constants and not prefixed, so they should be consistent.
___
*[python/open3d/core.py, line 30 at r1](https://reviewable.io/reviews/intel-isl/open3d/3741#-MeyghGZAyFiYWehSlEC:-MeyghG_9n__VU9hvEcO:b-jfmb40) ([raw file](https://github.com/intel-isl/open3d/blob/016128362237c1d4846d892b84afddba497a7f87/python/open3d/core.py#L30)):*
> ```Python
> 
> if o3d.__DEVICE_API__ == 'cuda':
>     from open3d.cuda.pybind.core import *
> ```

This is a good change in general. Before doing this, we should go through all bindings in `core` and check if they are included here. For all non-included binding, we should evaluate if it is not needed and can be removed, or if we should keep it and intentionally expose it in our Python API.
___
*[python/test/core/test_core.py, line 82 at r1](https://reviewable.io/reviews/intel-isl/open3d/3741#-MeyhYnu4a2wfL0sLFgE:-MeyhYnu4a2wfL0sLFgF:bbl06k7) ([raw file](https://github.com/intel-isl/open3d/blob/016128362237c1d4846d892b84afddba497a7f87/python/test/core/test_core.py#L82)):*
> ```Python
>         o3c.uint32: np.uint32,
>         o3c.uint64: np.uint64,
>         o3c.bool: np.bool8,  # np.bool deprecated
> ```

Should we follow numpy convention and use `o3c.bool8` instead?

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3741)* status: 5 of 154 files reviewed, 5 unresolved discussions (waiting on @stotko and @yxlao)

___
*[cpp/open3d/core/Dtype.h, line 94 at r1](https://reviewable.io/reviews/intel-isl/open3d/3741#-Meyf8j5EdPoIBHafnc2:-MezLIR0A1_iM_--b4dh:b-krvjp5) ([raw file](https://github.com/intel-isl/open3d/blob/016128362237c1d4846d892b84afddba497a7f87/cpp/open3d/core/Dtype.h#L94)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Although the convention is to prefix constants with `k`, would it be instead better to remove that prefix and treat these statements as some sort of "using" statement? The original `Dtype::Undefined`, etc. values are already constants and not prefixed, so they should be consistent.
</blockquote></details>

Agree. It's very clear from context that these are constants.

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3741)* status: 1 of 154 files reviewed, 5 unresolved discussions (waiting on @stotko)

___
*[cpp/open3d/core/Dtype.h, line 94 at r1](https://reviewable.io/reviews/intel-isl/open3d/3741#-Meyf8j5EdPoIBHafnc2:-Mf2SCnS1DKHdTZMKPZt:b-hff6wv) ([raw file](https://github.com/intel-isl/open3d/blob/016128362237c1d4846d892b84afddba497a7f87/cpp/open3d/core/Dtype.h#L94)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Agree. It's very clear from context that these are constants.
</blockquote></details>

renamed
___
*[python/open3d/core.py, line 30 at r1](https://reviewable.io/reviews/intel-isl/open3d/3741#-MeyghGZAyFiYWehSlEC:-Mf2SFS1D0BZzjWjf5l3:bcixye2) ([raw file](https://github.com/intel-isl/open3d/blob/016128362237c1d4846d892b84afddba497a7f87/python/open3d/core.py#L30)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

This is a good change in general. Before doing this, we should go through all bindings in `core` and check if they are included here. For all non-included binding, we should evaluate if it is not needed and can be removed, or if we should keep it and intentionally expose it in our Python API.
</blockquote></details>

Listed all attributes under `open3d.core`, they all look good to me:

```
| Attr Name         |
|-------------------|
| Blob              |                            
| Device            |                              
| Dtype             |                             
| DynamicSizeVector |                                         
| Hashmap           |                               
| Scalar            |                              
| SizeVector        |                                  
| Tensor            |                              
| __doc__           |                               
| __loader__        |                                  
| __name__          |                                
| __package__       |                                   
| __spec__          |                                
| bool              |                            
| bool8             |                             
| cuda              |                            
| det               |                           
| float32           |                               
| float64           |                               
| int16             |                             
| int32             |                             
| int64             |                             
| int8              |                            
| inv               |                           
| kernel            |                              
| lstsq             |                             
| lu                |                          
| lu_ipiv           |                               
| matmul            |                              
| nns               |                           
| solve             |                             
| svd               |                           
| tril              |                            
| triu              |                            
| triul             |                             
| uint16            |                              
| uint32            |                              
| uint64            |                              
| uint8             |                             
| undefined         |                                 

```
___
*[python/test/core/test_core.py, line 82 at r1](https://reviewable.io/reviews/intel-isl/open3d/3741#-MeyhYnu4a2wfL0sLFgE:-Mf2S4Y9-dFTOwsOSwKP:b-gobwhj) ([raw file](https://github.com/intel-isl/open3d/blob/016128362237c1d4846d892b84afddba497a7f87/python/test/core/test_core.py#L82)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Should we follow numpy convention and use `o3c.bool8` instead?
</blockquote></details>

Done. Added bool8 alias.
___
*[replace_all.py, line 1 at r1](https://reviewable.io/reviews/intel-isl/open3d/3741#-Meyefs36_ptwZmL3Ba6:-Mf2S9NA-aVf2VIvkEHD:b-hfpv0l) ([raw file](https://github.com/intel-isl/open3d/blob/016128362237c1d4846d892b84afddba497a7f87/replace_all.py#L1)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

This script is only required for finding all usages of the `Dtype` and will be removed before merging, right?
</blockquote></details>

removed
___
*[replace_all_py.py, line 1 at r1](https://reviewable.io/reviews/intel-isl/open3d/3741#-MeyeyW8B-1inW1NwDf-:-Mf2SB4e8EliDtqVQUfq:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/016128362237c1d4846d892b84afddba497a7f87/replace_all_py.py#L1)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.

**Review by stotko — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3741)* status: 1 of 154 files reviewed, 1 unresolved discussion (waiting on @stotko and @yxlao)

___
*[python/test/core/test_core.py, line 82 at r1](https://reviewable.io/reviews/intel-isl/open3d/3741#-MeyhYnu4a2wfL0sLFgE:-Mf2UU1mAGVljoAOT68C:bqhqr50) ([raw file](https://github.com/intel-isl/open3d/blob/016128362237c1d4846d892b84afddba497a7f87/python/test/core/test_core.py#L82)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Done. Added bool8 alias.
</blockquote></details>

Just for double checking: There seems to be a slight but important difference between `np.bool` and `np.bool_` (with `np.bool8` being an alias for `np.bool_`). Although our `Dtype.Bool` already points to `np.bool8` for a long time, it might be a good idea to check if this decision was consistent and the changes in this PR are also consistent.

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3741)* status: 1 of 154 files reviewed, 1 unresolved discussion (waiting on @stotko)

___
*[python/test/core/test_core.py, line 82 at r1](https://reviewable.io/reviews/intel-isl/open3d/3741#-MeyhYnu4a2wfL0sLFgE:-Mf63vor98a_3W8eU0no:b-ixzz9d) ([raw file](https://github.com/intel-isl/open3d/blob/016128362237c1d4846d892b84afddba497a7f87/python/test/core/test_core.py#L82)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Just for double checking: There seems to be a slight but important difference between `np.bool` and `np.bool_` (with `np.bool8` being an alias for `np.bool_`). Although our `Dtype.Bool` already points to `np.bool8` for a long time, it might be a good idea to check if this decision was consistent and the changes in this PR are also consistent.
</blockquote></details>

Yes, the current decision is consistent. As in `open3d.core` we cannot specify dtype as the built-in Python `bool` (which is the alias for the deprecated `np.bool`) yet, we almost always want the `np.bool_` or `np.bool8`. This is also consistent with other dtypes, e.g. `np.float32`

**Pull request merged**
