### PR TITLE
cleanup jsoncpp

### PR DESCRIPTION
**Pull request by pherman**
Changes:
1. update jsoncpp to version 0.10.7
2. use git submodule instead of hardcopy

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1092)

### CODE REVIEW

**Comment by busymeister** [comment]
On my end, I'm finished with my changes until further notice.  Without a detailed error message, I cannot debug why continuous-integration/appveyor/pr failed.  If you need any support from me to finish the pull request, please let me know.  The changes are pretty simple...I just updated the jsoncpp library to the current release version, replaced the 3rdparty directory with a git submodule, and then (hopefully) fixed the build.

**Comment by pherman** [comment]
On my end, I'm finished with my changes until further notice. Without a detailed error message, I cannot debug why continuous-integration/appveyor/pr failed. If you need any support from me to finish the pull request, please let me know. The changes are pretty simple...I just updated the jsoncpp library to the current release version, replaced the 3rdparty directory with a git submodule, and then (hopefully) fixed the build.

**Comment by pherman** [comment]
The errors in continuous-integration/travis-ci/pr appear to be network issues which I cannot solve.
Regarding the errors in continuous-integration/appveyor/pr: unfortunately, I cannot test a Visual Studio setup because I'm working in a Linux environment so I'd need help fixing it.  Perhaps some of the other pkg config variables need to be updated? See https://cmake.org/cmake/help/v3.15/module/FindPkgConfig.html

**Comment by griegler** [comment]
Maybe @yxlao can have a look?

**Comment by syncle** [comment]
@pherman Could you try with jsoncpp 1.8.4? Open3D currently uses jsoncpp 1.8.4 version and this version passes CI. In addition, jsoncpp 1.x is intended for C++11 and Open3D also [recommends to use C++11](http://www.open3d.org/docs/release/contribute.html#maintain-sanity-of-the-project). In short, I bet jsoncpp 1.x should be better fit.

**Comment by syncle** [comment]
@pherman just reminder

**Comment by busymeister** [comment]
We've been using 0.10.7 because it's the latest version marked as release.  Certainly I would also prefer to use C++11.  I can see if I be convincing enough to upgrade to the latest pre-release version.  Maintaining multiple versions is a nightmare.  I guess we can close this request then.  If there are any updates I would like to share, I'll start a new request.

**Comment by pherman** [comment]
We've been using 0.10.7 because it's the latest version marked as release. Certainly I would also prefer to use C++11. I can see if I be convincing enough to upgrade to the latest pre-release version. Maintaining multiple versions is a nightmare. I guess we can close this request then. If there are any updates I would like to share, I'll start a new request.

**Comment by syncle** [comment]
Got it. Thanks! @pherman

**Pull request closed without merging**
