### PR TITLE
RealSense sensor configuration, live capture and recording

### PR DESCRIPTION
**Pull request by ssheorey**
RealSense camera discovery, configuration, live capture and recording.
Python bindings.
C++ example.
RealSense tutorial.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2748)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2748)* status: all files reviewed, 13 unresolved discussions (waiting on @prewettg, @ssheorey, and @theNded)

___
*[cpp/open3d/io/IJsonConvertibleIO.h, line 76 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOhylYm75204rTxV2Wy:-MOhylYm75204rTxV2Wz:b-30ti1e) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/io/IJsonConvertibleIO.h#L76)):*
> ```objc
> /// ENUM_TYPE for conversion between the enum and string. Invalid string values
> /// are apped to the first specified option in the macro.
> #define DECLARE_STRINGIFY_ENUM(ENUM_TYPE)    \
> ```

does this work for `enum` and/or `enum class`?
___
*[cpp/open3d/t/io/CMakeLists.txt, line 2 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOi-K4MBmMX1PbSoNPE:-MOi-K4MBmMX1PbSoNPF:bgc9n6l) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/t/io/CMakeLists.txt#L2)):*
> ```CMake
> set(FILE_IO_SRC
>     "PointCloudIO.cpp"
> ```

we can probably go without the `"`, since other cmake files are not having them
___
*[cpp/open3d/t/io/sensor/RGBDSensor.h, line 45 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOiy2P9AjnppoeQrM2T:-MOiy2P9AjnppoeQrM2U:b-5elwqa) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/t/io/sensor/RGBDSensor.h#L45)):*
> ```objc
>     /// Default constructor. Initialize with default settings.
>     RGBDSensor() {}
>     virtual ~RGBDSensor(){};
> ```

remove `;`
___
*[cpp/open3d/t/io/sensor/RGBDSensor.h, line 65 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOiy6paAAfzat9HBNYo:-MOiy6paAAfzat9HBNYp:b-ujf8db) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/t/io/sensor/RGBDSensor.h#L65)):*
> ```objc
>     virtual bool InitSensor(const RGBDSensorConfig &sensor_config,
>                             size_t sensor_index = 0,
>                             const std::string &filename = std::string{}) = 0;
> ```

nit: `const std::string &filename = ""` would be a bit simpler
___
*[cpp/open3d/t/io/sensor/realsense/RealSense-private.h, line 27 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOiz54m0fzh5e_RGanF:-MOiz54nE_5kJ0WzM4LU:bupqsd4) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/t/io/sensor/realsense/RealSense-private.h#L27)):*
> ```objc
> // ----------------------------------------------------------------------------
> 
> // PRIVATE RealSense header for compiling Open3D. Do not #include outside
> ```

this notice is great!
maybe we can rename the file to `RealSensePrivate.h` for consistency?
___
*[cpp/open3d/t/io/sensor/realsense/RealSenseSensor.h, line 82 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOizGDq3kd9sBoznX1X:-MOizGDq3kd9sBoznX1Y:b-1dz3sa) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/t/io/sensor/realsense/RealSenseSensor.h#L82)):*
> ```objc
>                                     RealSenseSensorConfig{},
>                             size_t sensor_index = 0,
>                             const std::string &filename = std::string{});
> ```

`= ""` for simplicity
___
*[cpp/open3d/t/io/sensor/realsense/RealSenseSensor.h, line 134 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOizK1a5XeAbHm-zciv:-MOizK1a5XeAbHm-zciw:b-xbobgn) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/t/io/sensor/realsense/RealSenseSensor.h#L134)):*
> ```objc
> 
> private:
>     bool enable_recording_ = false, is_recording_ = false,
> ```

let's separate this into 3 lines.
___
*[cpp/open3d/t/io/sensor/realsense/RealSenseSensor.cpp, line 148 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOizUzrAkjh9RXjBoc9:-MOizUzrAkjh9RXjBocA:baqhx7b) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/t/io/sensor/realsense/RealSenseSensor.cpp#L148)):*
> ```cpp
>                     "Using default device, if any.",
>                     sensor_index, device_list.size());
>         } else
> ```

nit: shall we add add `{}` here? same for the rest of this file.

According to our [C++ style guide](https://google.github.io/styleguide/cppguide.html#Conditionals), for historical reasons, the exception case for omitting `{}` is when (1) the if condition doesn't have else, and (2) the if condition with the code is in single line. i.e.

```cpp
// Good
if (xxx) yyy; 

// Bad
if (xxx)
    yyy; 
```
___
*[cpp/pybind/CMakeLists.txt, line 35 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOj0VI6-EwOvgBpINni:-MOj0VI7BmkdROLzl4Mt:b5dm8d7) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/pybind/CMakeLists.txt#L35)):*
> ```CMake
> set(PACKAGE_NAME pybind)
> 
> set(PY_ALL_SOURCE_FILES
> ```

this is great!
can we go without `${CMAKE_CURRENT_SOURCE_DIR}` and `""`? they don't seem to be required.
___
*[examples/cpp/RealSenseRecorder.cpp, line 32 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOj0oks1mHV1_ShRSfA:-MOj0oks1mHV1_ShRSfB:b-u3r7qo) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/examples/cpp/RealSenseRecorder.cpp#L32)):*
> ```cpp
> 
> #include "open3d/Open3D.h"
> #include "open3d/t/io/sensor/realsense/RealSenseSensor.h"
> ```

Possible to put this inside `open3d.h`? Similar to other examples, including `open3d.h` shall be sufficient
___
*[examples/cpp/RealSenseRecorder.cpp, line 76 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOj19aB6TXXclLAqjGM:-MOj19aB6TXXclLAqjGN:bajh8m1) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/examples/cpp/RealSenseRecorder.cpp#L76)):*
> ```cpp
> 
>     if (utility::ProgramOptionExists(argc, argv, "-c"))
>         config_file = utility::GetProgramOptionAsString(argc, argv, "-c");
> ```

same as the previous comments, let's add the `{}` unless it is a one-liner and does not have `else`
___
*[examples/cpp/RealSenseRecorder.cpp, line 96 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOj14VA9TVWJfB_vxtl:-MOj14VA9TVWJfB_vxtm:b-26ssmv) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/examples/cpp/RealSenseRecorder.cpp#L96)):*
> ```cpp
>     rs.ListDevices();
>     rs.InitSensor(rs_cfg, 0, bag_file);
>     std::cout << rs.GetMetadata().ToString() << std::endl;
> ```

let's also use `loginfo` here?
___
*[util/ci_utils.sh, line 275 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOj1PJYARQdHEkRH4RR:-MOj1PJYARQdHEkRH4RS:b-nohw5g) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/util/ci_utils.sh#L275)):*
> ```Shell
>         -DDEVELOPER_BUILD="$DEVELOPER_BUILD"
>         -DBUILD_AZURE_KINECT="$BUILD_AZURE_KINECT"
>         -DBUILD_LIBREALSENSE=ON
> ```

Could you remind me of whether this will lead to DLL not found errors if a user installs the pip package in a fresh machine?

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2748)* status: all files reviewed, 11 unresolved discussions (waiting on @prewettg, @theNded, and @yxlao)

___
*[cpp/open3d/io/IJsonConvertibleIO.h, line 76 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOhylYm75204rTxV2Wy:-MOjC6pp6l61hbqYCvaT:b-8qhbd4) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/io/IJsonConvertibleIO.h#L76)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

does this work for `enum` and/or `enum class`?
</blockquote></details>

It should work with both, though I have only tried it with enum. With C++17, there's a Magic Enum library that uses reflection, so there is no need to manually specify the enum -> string mapping.
___
*[cpp/open3d/t/io/CMakeLists.txt, line 2 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOi-K4MBmMX1PbSoNPE:-MOjE1WJELpXJ0j0BQAS:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/t/io/CMakeLists.txt#L2)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we can probably go without the `"`, since other cmake files are not having them
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/sensor/RGBDSensor.h, line 45 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOiy2P9AjnppoeQrM2T:-MOjEYHU8U6DDh0w7v-C:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/t/io/sensor/RGBDSensor.h#L45)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove `;`
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/sensor/realsense/RealSense-private.h, line 27 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOiz54m0fzh5e_RGanF:-MOjEzYA5zh9KGh3nLn1:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/t/io/sensor/realsense/RealSense-private.h#L27)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

this notice is great!
maybe we can rename the file to `RealSensePrivate.h` for consistency?
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/sensor/realsense/RealSenseSensor.h, line 82 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOizGDq3kd9sBoznX1X:-MOjFlre-TkuVCkxqbCB:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/t/io/sensor/realsense/RealSenseSensor.h#L82)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`= ""` for simplicity
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/sensor/realsense/RealSenseSensor.h, line 134 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOizK1a5XeAbHm-zciv:-MOjG1iH-UyQBofcxL2u:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/t/io/sensor/realsense/RealSenseSensor.h#L134)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

let's separate this into 3 lines.
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/sensor/realsense/RealSenseSensor.cpp, line 148 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOizUzrAkjh9RXjBoc9:-MOjHASf-5xW07QKYwpC:bb6un1j) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/open3d/t/io/sensor/realsense/RealSenseSensor.cpp#L148)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: shall we add add `{}` here? same for the rest of this file.

According to our [C++ style guide](https://google.github.io/styleguide/cppguide.html#Conditionals), for historical reasons, the exception case for omitting `{}` is when (1) the if condition doesn't have else, and (2) the if condition with the code is in single line. i.e.

```cpp
// Good
if (xxx) yyy; 

// Bad
if (xxx)
    yyy; 
```
</blockquote></details>

Done
___
*[cpp/pybind/CMakeLists.txt, line 35 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOj0VI6-EwOvgBpINni:-MOjIFCk5-hA5VlSFXaT:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/pybind/CMakeLists.txt#L35)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

this is great!
can we go without `${CMAKE_CURRENT_SOURCE_DIR}` and `""`? they don't seem to be required.
</blockquote></details>

Done.
___
*[examples/cpp/RealSenseRecorder.cpp, line 32 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOj0oks1mHV1_ShRSfA:-MOjJDfs0SAF2Bkv7qoH:b6zrrkh) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/examples/cpp/RealSenseRecorder.cpp#L32)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Possible to put this inside `open3d.h`? Similar to other examples, including `open3d.h` shall be sufficient
</blockquote></details>

Good catch.
___
*[examples/cpp/RealSenseRecorder.cpp, line 76 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOj19aB6TXXclLAqjGM:-MOjJya_-5UZNzCvqcUh:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/examples/cpp/RealSenseRecorder.cpp#L76)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

same as the previous comments, let's add the `{}` unless it is a one-liner and does not have `else`
</blockquote></details>

Done.
___
*[examples/cpp/RealSenseRecorder.cpp, line 96 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOj14VA9TVWJfB_vxtl:-MOjK0DL9ay62gudpMG5:b-65o475) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/examples/cpp/RealSenseRecorder.cpp#L96)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

let's also use `loginfo` here?
</blockquote></details>

JSON ToString output has braces {}, which `fmt` tries to interpret as a format string and throws an error. Hmmm.. this should fix it:
`utility::LogInfo("{}", rs.GetMetadata().ToString());`
___
*[util/ci_utils.sh, line 275 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOj1PJYARQdHEkRH4RR:-MOjLQKs4TJxJkcqgHaH:b99evbf) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/util/ci_utils.sh#L275)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Could you remind me of whether this will lead to DLL not found errors if a user installs the pip package in a fresh machine?
</blockquote></details>

Should not. On macOS and Windows, everything is linked in statically (including `libusb`). On Linux, `librealsense` is linked statically and`libusb`is linked dynamically, but it comes with the default OS.

**Review by yxlao — APPROVED** [review]
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2748)* status: all files reviewed, 11 unresolved discussions (waiting on @prewettg, @theNded, and @yxlao)

**Review by theNded — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2748)* status: all files reviewed, 12 unresolved discussions (waiting on @prewettg, @ssheorey, and @yxlao)

___
*[examples/python/misc/realsense.py, line 19 at r4](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOlprE-9-Co40GeEXG5:-MOlprE-9-Co40GeEXG6:b-tzhphs) ([raw file](https://github.com/intel-isl/open3d/blob/ce42ec7a135a1cb4b55b6b5f88ba6d2243a9a85a/examples/python/misc/realsense.py#L19)):*
> ```Python
>     for fid in range(5):
>         rgbd_frame = rscam.capture_frame()
>         o3d.io.write_image(f"color{fid:04d}.jpg",
> ```

Maybe 05d? Some of the sequences can be pretty long, e.g. Indoor LiDAR RGBD dataset.

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2748)* status: all files reviewed, 12 unresolved discussions (waiting on @prewettg, @theNded, and @yxlao)

___
*[examples/python/misc/realsense.py, line 19 at r4](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOlprE-9-Co40GeEXG5:-MOlqnT50BuZfqS-XDDD:bw7mgyg) ([raw file](https://github.com/intel-isl/open3d/blob/ce42ec7a135a1cb4b55b6b5f88ba6d2243a9a85a/examples/python/misc/realsense.py#L19)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Maybe 05d? Some of the sequences can be pretty long, e.g. Indoor LiDAR RGBD dataset.
</blockquote></details>

Good point. This example is just something very basic that I wrote to test things. I'll update it in the next PR with a more useful example, including a Python viewer / recorder using the new imgui visualization. It's hard to capture a dataset without looking at the images :-)

**Review by prewettg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2748)* status: all files reviewed, 15 unresolved discussions (waiting on @ssheorey, @theNded, and @yxlao)

___
*[cpp/open3d/t/io/sensor/RGBDVideoMetadata.cpp, line 44 at r4](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOlvHXx3_RNI2D-Lhbx:-MOlvHXx3_RNI2D-Lhby:b-t8ad7p) ([raw file](https://github.com/intel-isl/open3d/blob/ce42ec7a135a1cb4b55b6b5f88ba6d2243a9a85a/cpp/open3d/t/io/sensor/RGBDVideoMetadata.cpp#L44)):*
> ```cpp
>     value["color_format"] = color_format_;
>     value["depth_format"] = depth_format_;
>     value["depth_scale"] = depth_scale_;
> ```

Do we need to handle the case where these keys do not exist?  (Is the source for this JSON reliable? It looks like we're using RapidJSON here, and if I recall correctly, RapidJSON crashes if you ask for a non-existent key. But if the source is the RealSense driver, maybe we don't need to check, at least until they change their JSON format?)
___
*[cpp/open3d/t/io/sensor/realsense/RealSenseSensor.h, line 86 at r4](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOlw2Bl8aH9F_OfYxjV:-MOlw2Bl8aH9F_OfYxjW:b-tnskms) ([raw file](https://github.com/intel-isl/open3d/blob/ce42ec7a135a1cb4b55b6b5f88ba6d2243a9a85a/cpp/open3d/t/io/sensor/realsense/RealSenseSensor.h#L86)):*
> ```objc
>             const RGBDSensorConfig &sensor_config,
>             size_t sensor_index = 0,
>             const std::string &filename = std::string{}) override {
> ```

= "" for simplicity, as above?
___
*[cpp/open3d/t/io/sensor/realsense/RealSenseSensor.cpp, line 136 at r4](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOlwIHs0p8_RzHFbo5F:-MOlwIHs0p8_RzHFbo5G:bibe0rw) ([raw file](https://github.com/intel-isl/open3d/blob/ce42ec7a135a1cb4b55b6b5f88ba6d2243a9a85a/cpp/open3d/t/io/sensor/realsense/RealSenseSensor.cpp#L136)):*
> ```cpp
> 
> bool RealSenseSensor::InitSensor(const RealSenseSensorConfig& sensor_config,
>                                  size_t sensor_index,
> ```

Not required, but I find it helpful to readers to include default parameters in the definition (e.g. `size_t sensor_index /*= 0*/,` here and elsewhere in this file)
___
*[cpp/pybind/CMakeLists.txt, line 35 at r1](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOj0VI6-EwOvgBpINni:-MOlx-ztBlfrmXr-JilK:b-kbhs1o) ([raw file](https://github.com/intel-isl/open3d/blob/24e8ce2ba8c03a2bde1deff65268eb18eb7b1c88/cpp/pybind/CMakeLists.txt#L35)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Requiring manual addition of files is clearer, but is going to surprise people who are used to the rest of the Open3D library, when their new file(s) are not automatically discovered. I think we might either want to get a team opinion on this, or at the very least advertise that you need to manually add pybind files now.

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2748)* status: all files reviewed, 15 unresolved discussions (waiting on @prewettg, @theNded, and @yxlao)

___
*[cpp/open3d/t/io/sensor/RGBDVideoMetadata.cpp, line 44 at r4](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOlvHXx3_RNI2D-Lhbx:-MOm2RmC8Hs1k8yULjvU:bvten2) ([raw file](https://github.com/intel-isl/open3d/blob/ce42ec7a135a1cb4b55b6b5f88ba6d2243a9a85a/cpp/open3d/t/io/sensor/RGBDVideoMetadata.cpp#L44)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

Do we need to handle the case where these keys do not exist?  (Is the source for this JSON reliable? It looks like we're using RapidJSON here, and if I recall correctly, RapidJSON crashes if you ask for a non-existent key. But if the source is the RealSense driver, maybe we don't need to check, at least until they change their JSON format?)
</blockquote></details>

We use JsonCpp and it currently just creates the key if it doesn't exist. We start from an empty Json value in the current code.
___
*[cpp/open3d/t/io/sensor/realsense/RealSenseSensor.h, line 86 at r4](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOlw2Bl8aH9F_OfYxjV:-MOm132E2cViJvy0C11T:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/ce42ec7a135a1cb4b55b6b5f88ba6d2243a9a85a/cpp/open3d/t/io/sensor/realsense/RealSenseSensor.h#L86)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

= "" for simplicity, as above?
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/sensor/realsense/RealSenseSensor.cpp, line 136 at r4](https://reviewable.io/reviews/intel-isl/open3d/2748#-MOlwIHs0p8_RzHFbo5F:-MOm5bH51-1p8DSjrWwR:b-x745n0) ([raw file](https://github.com/intel-isl/open3d/blob/ce42ec7a135a1cb4b55b6b5f88ba6d2243a9a85a/cpp/open3d/t/io/sensor/realsense/RealSenseSensor.cpp#L136)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

Not required, but I find it helpful to readers to include default parameters in the definition (e.g. `size_t sensor_index /*= 0*/,` here and elsewhere in this file)
</blockquote></details>

That's a good idea. I might not get around to adding all of them now, though.

**Pull request merged**
