### PR TITLE
torch continuous conv wrappers

### PR DESCRIPTION
**Pull request by benjaminum**
This PR
- adds torch wrappers for the cconv 
- adds cconv and sparse conv layers
- extends unit tests to torch

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2287)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- python/test/ml_ops/test_sparseconv.py  2
- python/test/ml_ops/mltest.py  4
- python/open3d/ml/torch/python/layers/convolutions.py  15
         

Clones added
============
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOpKernel.h  9
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOpKernel.h  9
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOpKernel.cpp  8
- python/test/ml_ops/test_sparseconv.py  2
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.cpp  6
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.h  9
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvBackpropFilterOpKernel.h  7
- cpp/open3d/ml/PyTorch/Misc/VoxelPoolingOpKernel.cpp  2
- cpp/open3d/ml/PyTorch/Misc/VoxelPoolingOps.cpp  4
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOps.cpp  13
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOps.cpp  13
- python/open3d/ml/tf/python/layers/convolutions.py  6
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cpp  6
- python/test/ml_ops/test_fixed_radius_search.py  2
- python/test/ml_ops/test_cconv.py  6
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOpKernel.cpp  7
- python/open3d/ml/torch/python/layers/convolutions.py  15
         

Clones removed
==============
+ cpp/open3d/ml/PyTorch/Misc/InvertNeighborsListOps.cpp  -1
+ cpp/open3d/ml/PyTorch/Misc/InvertNeighborsListOpKernel.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6125619&bid=20038503)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/ml/torch/python/layers/convolutions.py  15
- python/test/ml_ops/test_sparseconv.py  2
         

Complexity decreasing per file
==============================
+ python/test/ml_ops/mltest.py  -1
         

Clones added
============
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.cpp  6
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOps.cpp  13
- python/open3d/ml/torch/python/layers/convolutions.py  15
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOpKernel.h  9
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cpp  6
- python/test/ml_ops/test_sparseconv.py  2
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOpKernel.cpp  7
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOpKernel.cpp  8
- python/test/ml_ops/test_cconv.py  6
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOpKernel.h  9
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.h  9
- python/open3d/ml/tf/python/layers/convolutions.py  6
- python/test/ml_ops/test_fixed_radius_search.py  2
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOps.cpp  13
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvBackpropFilterOpKernel.h  7
         

Clones removed
==============
+ cpp/open3d/ml/PyTorch/Misc/InvertNeighborsListOps.cpp  -1
+ cpp/open3d/ml/PyTorch/Misc/InvertNeighborsListOpKernel.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6125619&bid=20038503)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/ml/torch/python/layers/convolutions.py  15
- python/test/ml_ops/test_sparseconv.py  2
         

Complexity decreasing per file
==============================
+ python/test/ml_ops/mltest.py  -1
         

Clones added
============
- python/open3d/ml/torch/python/layers/convolutions.py  15
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvBackpropFilterOpKernel.h  7
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.cpp  6
- python/open3d/ml/tf/python/layers/convolutions.py  6
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOpKernel.cpp  7
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOpKernel.h  9
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cpp  6
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOpKernel.cpp  8
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOps.cpp  13
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOpKernel.h  9
- python/test/ml_ops/test_cconv.py  6
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.h  9
- python/test/ml_ops/test_sparseconv.py  2
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOps.cpp  13
- python/test/ml_ops/test_fixed_radius_search.py  2
         

Clones removed
==============
+ cpp/open3d/ml/PyTorch/Misc/InvertNeighborsListOpKernel.cpp  -1
+ cpp/open3d/ml/PyTorch/Misc/InvertNeighborsListOps.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6125619&bid=20038503)

**Review by griegler — CHANGES_REQUESTED** [review]
Not specific for this PR, but I think there is a general lack of documentation of the ml classes and functions (from what I saw from a quick look into the already existing torch and tf files).

> Reviewed 36 of 44 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2287#-:-MGO4Uij4YIGHArQ7jju:b-ikjyl3)* status: all files reviewed, 2 unresolved discussions (waiting on @benjaminum)

___
*[cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOps.cpp, line 231 at r3](https://reviewable.io/reviews/intel-isl/open3d/2287#-MGO6u2S6kuhm07OJy0-:-MGO6u2S6kuhm07OJy00:b-v6cip4) ([raw file](https://github.com/intel-isl/open3d/blob/406f429f22ef27f0415730d4a75d061d1e452ceb/cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOps.cpp#L231)):*
> ```cpp
>                         "'linear_border', 'nearest_neighbor') but got " +
>                                 interpolation_str);
>         }
> ```

Can we move the checks for `interpolation` and `coordinate_mapping` into a separate method as it is also used above.
___
*[cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.cu, line 103 at r3](https://reviewable.io/reviews/intel-isl/open3d/2287#-MGO7sXr5nIHx-VKIuU_:-MGO7sXr5nIHx-VKIuUa:b-hdcqvb) ([raw file](https://github.com/intel-isl/open3d/blob/406f429f22ef27f0415730d4a75d061d1e452ceb/cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.cu#L103)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     temp_size = std::max(
>             std::min(size_t(max_temp_mem_MB) * 1024 * 1024, max_temp_size),
>             temp_size);
>     torch::Tensor temp_tensor = torch::empty(
>             {int64_t(temp_size)},
>             torch::dtype(ToTorchDtype<uint8_t>()).device(device, device_idx));
>     temp_ptr = temp_tensor.data_ptr<uint8_t>();
> ```
</details>

This seems to be a very common pattern, can we create a function for this?

**Review by benjaminum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2287)* status: 29 of 40 files reviewed, 2 unresolved discussions (waiting on @griegler)

___
*[cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOps.cpp, line 231 at r3](https://reviewable.io/reviews/intel-isl/open3d/2287#-MGO6u2S6kuhm07OJy0-:-MGP7eGp149_rX_tJvlm:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/406f429f22ef27f0415730d4a75d061d1e452ceb/cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOps.cpp#L231)):*
<details><summary><i>Previously, griegler (Gernot) wrote…</i></summary><blockquote>

Can we move the checks for `interpolation` and `coordinate_mapping` into a separate method as it is also used above.
</blockquote></details>

Done.
___
*[cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.cu, line 103 at r3](https://reviewable.io/reviews/intel-isl/open3d/2287#-MGO7sXr5nIHx-VKIuU_:-MGP7fe9CAOpnwOUnrjq:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/406f429f22ef27f0415730d4a75d061d1e452ceb/cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.cu#L103)):*
<details><summary><i>Previously, griegler (Gernot) wrote…</i></summary><blockquote>

> ```
>     temp_size = std::max(
>             std::min(size_t(max_temp_mem_MB) * 1024 * 1024, max_temp_size),
>             temp_size);
>     torch::Tensor temp_tensor = torch::empty(
>             {int64_t(temp_size)},
>             torch::dtype(ToTorchDtype<uint8_t>()).device(device, device_idx));
>     temp_ptr = temp_tensor.data_ptr<uint8_t>();
> ```
This seems to be a very common pattern, can we create a function for this?
</blockquote></details>

Done.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/ml_ops/test_sparseconv.py  2
- python/open3d/ml/torch/python/layers/convolutions.py  15
         

Complexity decreasing per file
==============================
+ python/test/ml_ops/mltest.py  -1
         

Clones added
============
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.cpp  6
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvBackpropFilterOpKernel.h  7
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOpKernel.h  9
- python/open3d/ml/tf/python/layers/convolutions.py  6
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOps.cpp  11
- python/test/ml_ops/test_cconv.py  6
- python/test/ml_ops/test_sparseconv.py  2
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.h  9
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOpKernel.cpp  7
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cpp  6
- python/open3d/ml/torch/python/layers/convolutions.py  15
- python/test/ml_ops/test_fixed_radius_search.py  2
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOpKernel.cpp  8
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOps.cpp  11
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOpKernel.h  9
         

Clones removed
==============
+ cpp/open3d/ml/PyTorch/Misc/InvertNeighborsListOps.cpp  -1
+ cpp/open3d/ml/PyTorch/Misc/InvertNeighborsListOpKernel.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6125619&bid=20038503)

**Review by griegler — APPROVED** [review]
> Reviewed 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2287)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/open3d/ml/torch/python/layers/convolutions.py  15
- python/test/ml_ops/test_sparseconv.py  2
         

Complexity decreasing per file
==============================
+ python/test/ml_ops/mltest.py  -1
         

Clones added
============
- python/open3d/ml/torch/python/layers/convolutions.py  15
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cpp  6
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.h  9
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOpKernel.cpp  7
- python/test/ml_ops/test_cconv.py  6
- python/test/ml_ops/test_sparseconv.py  2
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOpKernel.h  9
- python/test/ml_ops/test_fixed_radius_search.py  2
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOps.cpp  11
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvOpKernel.h  9
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvBackpropFilterOpKernel.h  7
- python/open3d/ml/tf/python/layers/convolutions.py  6
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.cpp  6
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOps.cpp  11
- cpp/open3d/ml/PyTorch/ContinuousConv/ContinuousConvTransposeOpKernel.cpp  8
         

Clones removed
==============
+ cpp/open3d/ml/PyTorch/Misc/InvertNeighborsListOpKernel.cpp  -1
+ cpp/open3d/ml/PyTorch/Misc/InvertNeighborsListOps.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6125619&bid=20038503)

**Pull request merged**
