### PR TITLE
Use assimp to load STL, enable ASCII read

### LINKED ISSUE #2479: memory leak while loading stl file
**Describe the bug**
when I load stl file generated from openscad I got `MemoryError: std::bad_alloc`
and try to run the same code on a server with 128 g memory, I found the memory is keeping increase and eventually fails to load stl file. Convert the stl file using meshlab can solve the problem.
**To Reproduce**

```
import open3d as o3d
o3d.io.read_triangle_mesh("mesh.stl")
```
**Environment (please complete the following information):**

- Operating system:  Ubuntu 18.04
- Python version:  Python 3.7
- Open3D version: 0.10
- Is this remote workstation?:  no
- How did you install Open3D?:  conda

**Additional context**
stl file I used:

[mesh.zip](https://github.com/intel-isl/Open3D/files/5384151/mesh.zip)

### PR DESCRIPTION
**Pull request by yxlao**
Fixes #2479 

Previously, we always assume STL files are in binary format. This results in incorrect triangle counts. For simplicity, we just use Assimp to support both ASCII and binary format.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2506)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Clones removed
==============
+ cpp/open3d/io/file_format/FileSTL.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6357631&bid=20638785)

**Review by errissa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2506)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @errissa and @yxlao)

___
*[cpp/open3d/io/TriangleMeshIO.h, line 77 at r1](https://reviewable.io/reviews/intel-isl/open3d/2506#-MK07Mfs9ICbOOjmdLoA:-MK07Mft9uh_Z68jBk5F:bhfjm62) ([raw file](https://github.com/intel-isl/open3d/blob/f2aec54e801728043c1f80d6198bde5289ed13d9/cpp/open3d/io/TriangleMeshIO.h#L77)):*
> ```objc
>                             bool print_progress);
> 
> bool ReadTriangleMeshFromSTL(const std::string &filename,
> ```

Is it necessary to remove this? Switching to load STL with assimp makes this function unnecessary but it works. We kept `ReadTriangleMeshFromOBJ` and `ReadTriangleMeshFromGLTF`

**Review by errissa — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2506)* status: all files reviewed, 2 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/io/file_format/FileASSIMP.cpp, line 55 at r2](https://reviewable.io/reviews/intel-isl/open3d/2506#-MNenJusEE6JKgTK38xH:-MNenJusEE6JKgTK38xI:b-s67t8e) ([raw file](https://github.com/intel-isl/open3d/blob/278b730467460d54e8b225134bf93c8c88b645af/cpp/open3d/io/file_format/FileASSIMP.cpp#L55)):*
> ```cpp
> }
> 
> unsigned int kPostProcessFlags =
> ```

I recommend keeping this `const`. See below for related comments.
___
*[cpp/open3d/io/file_format/FileASSIMP.cpp, line 145 at r2](https://reviewable.io/reviews/intel-isl/open3d/2506#-MNemn2r2Z912oJHLw1F:-MNemn2s46M1F6WQHfg0:b-b5sxps) ([raw file](https://github.com/intel-isl/open3d/blob/278b730467460d54e8b225134bf93c8c88b645af/cpp/open3d/io/file_format/FileASSIMP.cpp#L145)):*
> ```cpp
>     Assimp::Importer importer;
> 
>     if (!enablePostProcessing) {
> ```

This will cause bugs. If a user specifies `enablePostProcessing = false` the global variable `kPostProcessFlags` will get set to 0 and stay 0 for future ASSIMP IO loads. I recommend using a local variable to store the flags so the global value doesn't get modified.

**Review by ShubhamAgarwal12 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2506)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @errissa)

___
*[cpp/open3d/io/file_format/FileASSIMP.cpp, line 55 at r2](https://reviewable.io/reviews/intel-isl/open3d/2506#-MNenJusEE6JKgTK38xH:-MO1btmf5ZVhh8AFvnRw:b-896fjx) ([raw file](https://github.com/intel-isl/open3d/blob/278b730467460d54e8b225134bf93c8c88b645af/cpp/open3d/io/file_format/FileASSIMP.cpp#L55)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

I recommend keeping this `const`. See below for related comments.
</blockquote></details>

Done
___
*[cpp/open3d/io/file_format/FileASSIMP.cpp, line 145 at r2](https://reviewable.io/reviews/intel-isl/open3d/2506#-MNemn2r2Z912oJHLw1F:-MO1bquDEhfTDlyHZVKw:b-896fjx) ([raw file](https://github.com/intel-isl/open3d/blob/278b730467460d54e8b225134bf93c8c88b645af/cpp/open3d/io/file_format/FileASSIMP.cpp#L145)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

This will cause bugs. If a user specifies `enablePostProcessing = false` the global variable `kPostProcessFlags` will get set to 0 and stay 0 for future ASSIMP IO loads. I recommend using a local variable to store the flags so the global value doesn't get modified.
</blockquote></details>

Done

**Review by ShubhamAgarwal12 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2506)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @errissa)

**Review by errissa — APPROVED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2506)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
