### PR TITLE
Minimize download size of 3rdparty dependencies

### PR DESCRIPTION
**Pull request by stotko**
### Improvements:

- Define `OPEN3D_THIRD_PARTY_DOWNLOAD_DIR` to point to `3rdparty_downloads` directory and exclude it in `.gitignore`
- Replace `set_local_or_remote_url` by the `DOWNLOAD_DIR` option of CMake's `ExternalProject_add` to automatically cache the downloaded files without requiring any user interaction anymore
- Port all git clone versions to URL downloading (except `boost` which requires submodule initialization)

### Benchmarks for building the 3rd party dependencies with slow Internet connection:

- Configuration: `cmake -DCMAKE_INSTALL_PREFIX=../bin -DBUILD_CUDA_MODULE=ON -DBUILD_UNIT_TESTS=ON -DBUILD_BENCHMARKS=ON -DBUILD_PYTORCH_OPS=ON -DBUILD_TENSORFLOW_OPS=ON -DBUNDLE_OPEN3D_ML=ON -DOPEN3D_ML_ROOT=../../Open3D-ML -DBUILD_JUPYTER_EXTENSION=ON -DBUILD_RPC_INTERFACE=ON -DBUILD_LIBREALSENSE=ON -DBUILD_AZURE_KINECT=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..`
- Build: `make -j6` @ Intel i7-10750H 6 Cores/12 Threads

#### Before:
- Total download time: ~13 mins @ ~1.2 MiB/s => ~920 MiB download size
- Total build time: ~24 mins

#### After:
- Total download time: ~1 min @ ~1.2 MiB/s => ~70 MiB download size
- Total build time: ~13:45 mins

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3569)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3569)* status: all files reviewed, 2 unresolved discussions (waiting on @ssheorey and @stotko)

___
*[3rdparty/assimp/assimp.cmake, line 16 at r1](https://reviewable.io/reviews/intel-isl/open3d/3569#-MbtQn6d2fEgHQNcsHb_:-MbtQn6d2fEgHQNcsHba:b-1jojtb) ([raw file](https://github.com/intel-isl/open3d/blob/fca5ac4320c54abdca3ac8a4ed555e776650eb73/3rdparty/assimp/assimp.cmake#L16)):*
> ```CMake
>     ext_assimp
>     PREFIX assimp
>     GIT_REPOSITORY https://github.com/assimp/assimp
> ```

We can convert ALL `ExternalProject_Add`'s GitHub/GitLab downloads to use the `tar` or `zip` file from their corresponding releases. (Except for those that need `git apply` to apply a patch).

The tar/zip files will not contain the git history and they can be cached to the download directory.
___
*[3rdparty/azure_kinect/azure_kinect.cmake, line 30 at r1](https://reviewable.io/reviews/intel-isl/open3d/3569#-MbtROG9EqeM0Lfh4GUE:-MbtROG9EqeM0Lfh4GUF:bc87jvl) ([raw file](https://github.com/intel-isl/open3d/blob/fca5ac4320c54abdca3ac8a4ed555e776650eb73/3rdparty/azure_kinect/azure_kinect.cmake#L30)):*
> ```CMake
>         URL https://www.nuget.org/api/v2/package/Microsoft.Azure.Kinect.Sensor/1.4.1
>         URL_HASH MD5=4a6cd4ffcaab8c332d8842c94bc17c35
>         DOWNLOAD_DIR "${OPEN3D_THIRD_PARTY_DOWNLOAD_DIR}/k4a"
> ```

Just curious: can we do `${OPEN3D_THIRD_PARTY_DOWNLOAD_DIR}/<prefix>` or `${OPEN3D_THIRD_PARTY_DOWNLOAD_DIR}/<PREFIX>`?

Since we can refer to the install dir as `<INSTALL_DIR>` for instance.

**Review by stotko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3569)* status: 14 of 19 files reviewed, 2 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[3rdparty/assimp/assimp.cmake, line 16 at r1](https://reviewable.io/reviews/intel-isl/open3d/3569#-MbtQn6d2fEgHQNcsHb_:-Mbu9f1v7k5Oxhnnc_MY:bhaqfbi) ([raw file](https://github.com/intel-isl/open3d/blob/fca5ac4320c54abdca3ac8a4ed555e776650eb73/3rdparty/assimp/assimp.cmake#L16)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We can convert ALL `ExternalProject_Add`'s GitHub/GitLab downloads to use the `tar` or `zip` file from their corresponding releases. (Except for those that need `git apply` to apply a patch).

The tar/zip files will not contain the git history and they can be cached to the download directory.
</blockquote></details>

Done for all eligible candidates. Remaining users of `GIT_REPOSITORY` are:
- `boost`: Has submodules that are not contained in the tar/zip files. We could remove this dependency entirely in the future if we port away from `boost/predef` .
- `faiss`: Uses `open3d_patch` branch of our fork which does not come with a corresponding tag. We could either add a tag or move to the upstream repository if the patch is not needed anymore.
- `filament`: The build version uses a commit in our fork which seems to be identical to the 1.9.19 release. Could potentially be ported as well, but needs confirmation.
- `jsoncpp`: Requires local patch.
- `librealsense`: Requires local patch.
- `tbb`: Requires specific commit and local patch.
- `stdgpu`: Requires specific commit.
___
*[3rdparty/azure_kinect/azure_kinect.cmake, line 30 at r1](https://reviewable.io/reviews/intel-isl/open3d/3569#-MbtROG9EqeM0Lfh4GUE:-Mbu93s26Ge7h7GE77_t:b-39nvb7) ([raw file](https://github.com/intel-isl/open3d/blob/fca5ac4320c54abdca3ac8a4ed555e776650eb73/3rdparty/azure_kinect/azure_kinect.cmake#L30)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Just curious: can we do `${OPEN3D_THIRD_PARTY_DOWNLOAD_DIR}/<prefix>` or `${OPEN3D_THIRD_PARTY_DOWNLOAD_DIR}/<PREFIX>`?

Since we can refer to the install dir as `<INSTALL_DIR>` for instance.
</blockquote></details>

Unfortunately, this does not work. The download directory is taken as is without performing any replacement of `<PREFIX>`.

**Review by yxlao — APPROVED** [review]
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3569)* status: all files reviewed, 1 unresolved discussion (waiting on @ssheorey and @yxlao)

**Review by ssheorey — CHANGES_REQUESTED** [review]
Thanks Patrick, this is really useful.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3569#-:-MbwmpfaAPaFFK1mAOQ0:biirh8b)* status: all files reviewed, 6 unresolved discussions (waiting on @stotko and @yxlao)

___
*[CMakeLists.txt, line 137 at r2](https://reviewable.io/reviews/intel-isl/open3d/3569#-MbwoiZ57gurhaUCld00:-MbwoiZ6EIS9ZjFUjIU5:brb522u) ([raw file](https://github.com/intel-isl/open3d/blob/67e60be090479f7f932860a6fbae5395bbad4aef/CMakeLists.txt#L137)):*
> ```CMake
> endif()
> if(NOT OPEN3D_THIRD_PARTY_DOWNLOAD_DIR_FOUND)
>     set(OPEN3D_THIRD_PARTY_DOWNLOAD_DIR "${CMAKE_CURRENT_BINARY_DIR}/3rdparty_downloads")
> ```

If we use `"${CMAKE_CURRENT_SOURCE_DIR}/3rdparty_downloads"` instead, then the downloads will not need to be repeated after clearing the build folder.
___
*[CMakeLists.txt, line 138 at r2](https://reviewable.io/reviews/intel-isl/open3d/3569#-MbwpYhR7qvGNqimbBHw:-MbwpYhR7qvGNqimbBHx:b-utctpk) ([raw file](https://github.com/intel-isl/open3d/blob/67e60be090479f7f932860a6fbae5395bbad4aef/CMakeLists.txt#L138)):*
> ```
> "Downloading directly without OPEN3D_THIRD_PARTY_DOWNLOAD_DIR"
> ```
"Downloading 3rdparty dependencies to ${CMAKE_CURRENT_SOURCE_DIR}/3rdparty_downloads"
___
*[3rdparty/assimp/assimp.cmake, line 16 at r2](https://reviewable.io/reviews/intel-isl/open3d/3569#-MbwpfhM0jlt7CZlaoHD:-MbwpfhM0jlt7CZlaoHE:b-rfumri) ([raw file](https://github.com/intel-isl/open3d/blob/67e60be090479f7f932860a6fbae5395bbad4aef/3rdparty/assimp/assimp.cmake#L16)):*
> ```CMake
>     ext_assimp
>     PREFIX assimp
>     URL https://github.com/assimp/assimp/archive/refs/tags/v5.0.1.tar.gz
> ```

Keep the comment: # Jan 2020
___
*[3rdparty/filament/filament_build.cmake, line 47 at r2](https://reviewable.io/reviews/intel-isl/open3d/3569#-Mbwr1EI2kdvG27UryNi:-Mbwr1EI2kdvG27UryNj:b8p9v08) ([raw file](https://github.com/intel-isl/open3d/blob/67e60be090479f7f932860a6fbae5395bbad4aef/3rdparty/filament/filament_build.cmake#L47)):*
> ```CMake
>     GIT_REPOSITORY https://github.com/intel-isl/filament.git
>     GIT_TAG d1d873d27f43ba0cee1674a555cc0f18daac3008
>     GIT_SHALLOW OFF # Does not work with commit hashes
> ```

Download commit archive directly (see `stdgpu.cmake`).
___
*[3rdparty/stdgpu/stdgpu.cmake, line 12 at r2](https://reviewable.io/reviews/intel-isl/open3d/3569#-MbwmKDk0yMb7opo_6IK:-MbwmKDk0yMb7opo_6IL:b-ttnwjs) ([raw file](https://github.com/intel-isl/open3d/blob/67e60be090479f7f932860a6fbae5395bbad4aef/3rdparty/stdgpu/stdgpu.cmake#L12)):*
> ```CMake
>     GIT_REPOSITORY https://github.com/stotko/stdgpu.git
>     GIT_TAG 6005da976fe97c035909da6ea64cd7420949002a
>     GIT_SHALLOW OFF # Does not work with commit hashes
> ```

We can download a zip archive for a specific commit with a URL:
`https://github.com/stotko/stdgpu/archive/6005da976fe97c035909da6ea64cd7420949002a.zip`
See here:
https://stackoverflow.com/a/13636954

**Review by stotko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3569)* status: 8 of 21 files reviewed, 6 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[CMakeLists.txt, line 137 at r2](https://reviewable.io/reviews/intel-isl/open3d/3569#-MbwoiZ57gurhaUCld00:-Mc9GlO_3uhNO6IEZwyP:b-3p04ao) ([raw file](https://github.com/intel-isl/open3d/blob/67e60be090479f7f932860a6fbae5395bbad4aef/CMakeLists.txt#L137)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

If we use `"${CMAKE_CURRENT_SOURCE_DIR}/3rdparty_downloads"` instead, then the downloads will not need to be repeated after clearing the build folder.
</blockquote></details>

This is an excellent comment! Changed accordingly and also removed all external detection logic to have a single, uniform, and simple solution for all of our dependencies.
___
*[CMakeLists.txt, line 138 at r2](https://reviewable.io/reviews/intel-isl/open3d/3569#-MbwpYhR7qvGNqimbBHw:-Mc9HRJJ6Dp66RKUr_Gq:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/67e60be090479f7f932860a6fbae5395bbad4aef/CMakeLists.txt#L138)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> "Downloading directly without OPEN3D_THIRD_PARTY_DOWNLOAD_DIR"
> ```
"Downloading 3rdparty dependencies to ${CMAKE_CURRENT_SOURCE_DIR}/3rdparty_downloads"
</blockquote></details>

Done.
___
*[3rdparty/assimp/assimp.cmake, line 16 at r2](https://reviewable.io/reviews/intel-isl/open3d/3569#-MbwpfhM0jlt7CZlaoHD:-Mc9HTBT5pvmYVoeTUmM:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/67e60be090479f7f932860a6fbae5395bbad4aef/3rdparty/assimp/assimp.cmake#L16)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Keep the comment: # Jan 2020
</blockquote></details>

Done.
___
*[3rdparty/filament/filament_build.cmake, line 47 at r2](https://reviewable.io/reviews/intel-isl/open3d/3569#-Mbwr1EI2kdvG27UryNi:-Mc9HXlb1OMBHnvadi4q:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/67e60be090479f7f932860a6fbae5395bbad4aef/3rdparty/filament/filament_build.cmake#L47)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Download commit archive directly (see `stdgpu.cmake`).
</blockquote></details>

Done.
___
*[3rdparty/stdgpu/stdgpu.cmake, line 12 at r2](https://reviewable.io/reviews/intel-isl/open3d/3569#-MbwmKDk0yMb7opo_6IK:-Mc9Ha7l5JP6367hFE7n:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/67e60be090479f7f932860a6fbae5395bbad4aef/3rdparty/stdgpu/stdgpu.cmake#L12)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

We can download a zip archive for a specific commit with a URL:
`https://github.com/stotko/stdgpu/archive/6005da976fe97c035909da6ea64cd7420949002a.zip`
See here:
https://stackoverflow.com/a/13636954
</blockquote></details>

Done.

**Comment by stotko** [comment]
I ported all MD5 checksums to SHA256 because MD5 is not secure and the runtime overhead of SHA256 checksum computation is negligible.

In addition, almost all `GIT_REPOSITORY` uses (except `boost` which requires `git submodules`) are ported to `URL` downloading including the patched libraries. `git apply` works without a git repository, i.e.  `"[...], the command applies the patch only to files, and does not require them to be in a Git repository"` (see https://git-scm.com/docs/git-apply).

Regarding Open3D's usage of `ExternalProject_Add`, I believe this is close to the best we can do now to reduce download time.

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3569)* status: 8 of 21 files reviewed, 1 unresolved discussion (waiting on @yxlao)

**Pull request merged**
