### PR TITLE
Add missing module

### PR DESCRIPTION
**Pull request by nachovizzo**
One line I've missed in #1966

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2260)

### CODE REVIEW

**Review by griegler — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2260)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by griegler** [comment]
@yxlao can you tell us why the CI is failing here?

**Comment by yxlao** [comment]
My guess: github action tests uses an encrypted key that is only decrypted when the PR is submitted from a branch in the main Open3D repo. @ssheorey do we have a way to skip GPU CI on PR for community contributors?

**Comment by ssheorey** [comment]
Yes, that's correct. The ssh key for Google cloud service account is not available to pull requests from forks. 
Opened PR #2262 to skip GCE CI if the key is not available.

[This will need some testing -- Github Actions syntax is strange]

**Comment by yxlao** [comment]
@ssheorey 's fix has been merged to master (thanks!), @nachovizzo could you merge the new mater to trigger CI?

**Comment by nachovizzo** [comment]
@yxlao done!

**Pull request merged**
