### PR TITLE
ParallelFor and count # of physical CPU cores

### PR DESCRIPTION
**Pull request by yxlao**
- Get the number of physical/logical CPU cores via the `CPUInfo` class.
- Print CPU information before each unit test and benchmark runs.
- `ParallelFor` launches # threads == # physical CPU cores by default. If `OMP_NUM_THREADS` or  `OMP_DYNAMIC` are set, will fall back to OpenMP's default. 
- Move some launchers to the corresponding source files, since they are only used once. E.g. `LaunchBinaryEWKernel`.
- Move parallel utils to `utility/Parallel.h`

This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3716)

### CODE REVIEW

**Review by stotko — CHANGES_REQUESTED** [review]
> Reviewed 42 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3716)* status: all files reviewed, 6 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[cpp/benchmarks/CMakeLists.txt, line 29 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePpPY-0nsT8jKf8dZn:-MePpPY-0nsT8jKf8dZo:b-qu5ofu) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/benchmarks/CMakeLists.txt#L29)):*
> ```CMake
> 
> target_link_libraries(benchmarks PRIVATE benchmark::benchmark)
> target_sources(benchmarks PRIVATE
> ```

nit: Put `target_sources` above `target_link_libraries` for a consistent ordering.
___
*[cpp/open3d/utility/CPUInfo.h, line 36 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePsK48EDbvHfsm2Idr:-MePsK48EDbvHfsm2Ids:b83d71q) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.h#L36)):*
> ```objc
> class CPUInfo {
> public:
>     virtual ~CPUInfo();
> ```

Is there a reason to mark this `virtual`?
___
*[cpp/open3d/utility/CPUInfo.h, line 41 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePrwDH7FAV3J8yQkj2:-MePrwDH7FAV3J8yQkj3:b-np004w) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.h#L41)):*
> ```objc
>     /// Returns the number of physical CPU cores.
>     /// This is similar to boost::thread::physical_concurrency().
>     unsigned int NumCores() const;
> ```

Use `int` or `int32_t` instead. `unsigned int` should not be used to indicate non-negative numbers. 
___
*[cpp/open3d/utility/CPUInfo.h, line 46 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePsDgz5To-tNmBbOCF:-MePsDgz5To-tNmBbOCG:b-q64pkt) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.h#L46)):*
> ```objc
>     /// This returns the same result as std::thread::hardware_concurrency() or
>     /// boost::thread::hardware_concurrency().
>     unsigned int NumThreads() const;
> ```

See above.
___
*[cpp/open3d/utility/CPUInfo.h, line 49 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePrW63-Ncm-3oSMBY2:-MePrW63-Ncm-3oSMBY3:b-5yhspi) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.h#L49)):*
> ```objc
> 
>     /// Prints CPUInfo in the console.
>     void PrintInfo() const;
> ```

Perhaps a shorter name like `Print()`?
```
CPUInfo::GetInstance().PrintInfo();
```
vs.
```
CPUInfo::GetInstance().Print();
```
___
*[cpp/open3d/utility/CPUInfo.cpp, line 52 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePsTxj9FYgnBbJP1LI:-MePsTxj9FYgnBbJP1LJ:bxce43z) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.cpp#L52)):*
> ```cpp
> 
> struct CPUInfo::Impl {
>     unsigned int num_cores_;
> ```

See comments for `CPUInfo.h`.

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3716)* status: all files reviewed, 5 unresolved discussions (waiting on @ssheorey, @stotko, and @yxlao)

___
*[cpp/open3d/utility/CPUInfo.h, line 36 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePsK48EDbvHfsm2Idr:-MeQzxem--8HQ56LcjKU:be3xsa5) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.h#L36)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Is there a reason to mark this `virtual`?
</blockquote></details>

Done. Not really, it is only useful if `CPUInfo` is inherited.
___
*[cpp/open3d/utility/CPUInfo.h, line 41 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePrwDH7FAV3J8yQkj2:-MeR-1DU0p15e2IL9STg:bvqlc83) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.h#L41)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Use `int` or `int32_t` instead. `unsigned int` should not be used to indicate non-negative numbers. 
</blockquote></details>

`unsinged int` was used since `std::thread::hardware_concurrency()` returns `unsinged int` (also for the boost counterpart).

I do think `int` looks better for the `CPUInfo` class. Changed to `int`.
___
*[cpp/open3d/utility/CPUInfo.h, line 49 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePrW63-Ncm-3oSMBY2:-MeR-ucADz7eZFYrJ4Qw:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.h#L49)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Perhaps a shorter name like `Print()`?
```
CPUInfo::GetInstance().PrintInfo();
```
vs.
```
CPUInfo::GetInstance().Print();
```
</blockquote></details>

Done.
___
*[cpp/open3d/utility/CPUInfo.cpp, line 52 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePsTxj9FYgnBbJP1LI:-MeR-vArCzP8Vs-0VKy1:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.cpp#L52)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See comments for `CPUInfo.h`.
</blockquote></details>

Done.

**Review by ssheorey — CHANGES_REQUESTED** [review]
Did you see improved benchmark (or perhaps pipeline) timing from this update?

> Reviewed 4 of 42 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3716#-:-MeSIJjM5bL7g4tVAV7p:b-rb743m)* status: all files reviewed, 12 unresolved discussions (waiting on @stotko and @yxlao)

___
*[cpp/benchmarks/Main.cpp, line 45 at r2](https://reviewable.io/reviews/intel-isl/open3d/3716#-MeS2H2V3eAiS7rHkxPl:-MeS2H2V3eAiS7rHkxPm:b-fg5mo) ([raw file](https://github.com/intel-isl/open3d/blob/94c214ae90a1123b12ba396232a39c1cae005ca7/cpp/benchmarks/Main.cpp#L45)):*
> ```cpp
> 
> int main(int argc, char** argv) {
>     open3d::utility::CPUInfo::GetInstance().Print();
> ```

(Later PR) For completeness, report CUDA GPU info as well.
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 41 at r2](https://reviewable.io/reviews/intel-isl/open3d/3716#-MeSBFcqAbOXW2nqDwQQ:-MeSBBfl5yfCHp7JbnGQ:bopdded) ([raw file](https://github.com/intel-isl/open3d/blob/94c214ae90a1123b12ba396232a39c1cae005ca7/cpp/open3d/core/kernel/CPULauncher.h#L41)):*
> ```objc
> // Value taken from PyTorch's at::internal::GRAIN_SIZE. The value is chosen
> // heuristically for small element-wise ops.
> static constexpr int64_t SMALL_OP_GRAIN_SIZE = 32767;
> ```

Add doxygen comment. How is this used?
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 72 at r2](https://reviewable.io/reviews/intel-isl/open3d/3716#-MeSBUFz20W26ZQw_ZjU:-MeSBUFz20W26ZQw_ZjV:b5cu3gq) ([raw file](https://github.com/intel-isl/open3d/blob/94c214ae90a1123b12ba396232a39c1cae005ca7/cpp/open3d/core/kernel/CPULauncher.h#L72)):*
> ```objc
> void ParallelFor(int64_t n, const func_t& func) {
> #pragma omp parallel for if (!utility::InParallel()) \
>         num_threads(utility::EstimateMaxThreads())
> ```

Checking for nested parallelism should not be needed. It is disabled by default.
https://stackoverflow.com/a/31522514
If a user enables it explicitly, they probably know what they are doing.
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 89 at r2](https://reviewable.io/reviews/intel-isl/open3d/3716#-MeSCgve0liMMUq0KBLx:-MeSCgve0liMMUq0KBLy:b-2gvxs4) ([raw file](https://github.com/intel-isl/open3d/blob/94c214ae90a1123b12ba396232a39c1cae005ca7/cpp/open3d/core/kernel/CPULauncher.h#L89)):*
> ```objc
> void ParallelFor(int64_t n, int64_t grain_size, const func_t& func) {
> #pragma omp parallel for schedule(static) if (n > grain_size &&       \
>                                               !utility::InParallel()) \
> ```

See above comment about `InParallel()`
___
*[cpp/open3d/utility/CPUInfo.cpp, line 60 at r2](https://reviewable.io/reviews/intel-isl/open3d/3716#-MeS7SrjAgn27S4l82mb:-MeS7SrjAgn27S4l82mc:bfqvctn) ([raw file](https://github.com/intel-isl/open3d/blob/94c214ae90a1123b12ba396232a39c1cae005ca7/cpp/open3d/utility/CPUInfo.cpp#L60)):*
> ```cpp
>     try {
> #ifdef __linux__
>         // Ref: boost::thread::physical_concurrency().
> ```

Nit: There's `cpu cores : 6` entry in my output of `/proc/cpuinfo` that is a quicker way to get this. Do you know if boost doesn't use this since it's too new?
___
*[cpp/open3d/utility/CPUInfo.cpp, line 125 at r2](https://reviewable.io/reviews/intel-isl/open3d/3716#-MeSIVuz1tzq-wVhIQQj:-MeSIVuz1tzq-wVhIQQk:b-pys53y) ([raw file](https://github.com/intel-isl/open3d/blob/94c214ae90a1123b12ba396232a39c1cae005ca7/cpp/open3d/utility/CPUInfo.cpp#L125)):*
> ```cpp
>             offset += current_info->Size;
>             ++nb_physical_cores;
>         } while (offset < length);
> ```

MSVC signed / unsigned match warning in CI here.
___
*[cpp/open3d/utility/Parallel.cpp, line 69 at r2](https://reviewable.io/reviews/intel-isl/open3d/3716#-MeS8y5R9delbvlZPT1x:-MeS8y5R9delbvlZPT1y:bpcyy1) ([raw file](https://github.com/intel-isl/open3d/blob/94c214ae90a1123b12ba396232a39c1cae005ca7/cpp/open3d/utility/Parallel.cpp#L69)):*
> ```cpp
> bool InParallel() {
> #ifdef _OPENMP
>     return omp_in_parallel();
> ```

Can we adapt  this to work with TBB / parallel STL too?

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3716)* status: all files reviewed, 12 unresolved discussions (waiting on @ssheorey and @stotko)

___
*[cpp/benchmarks/Main.cpp, line 45 at r2](https://reviewable.io/reviews/intel-isl/open3d/3716#-MeS2H2V3eAiS7rHkxPl:-MeSXCFPE4e1D4Gv7tRO:bf9t983) ([raw file](https://github.com/intel-isl/open3d/blob/94c214ae90a1123b12ba396232a39c1cae005ca7/cpp/benchmarks/Main.cpp#L45)):*
> (Later PR) For completeness, report CUDA GPU info as well.
Yes, `GPUInfo` will be in the next PR. There are CUDA APIs to get the info.
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 41 at r2](https://reviewable.io/reviews/intel-isl/open3d/3716#-MeSBFcqAbOXW2nqDwQQ:-MeSXoG45-wz9PYlxVau:bs3mhdg) ([raw file](https://github.com/intel-isl/open3d/blob/94c214ae90a1123b12ba396232a39c1cae005ca7/cpp/open3d/core/kernel/CPULauncher.h#L41)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add doxygen comment. How is this used?
</blockquote></details>

Comment added.
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 72 at r2](https://reviewable.io/reviews/intel-isl/open3d/3716#-MeSBUFz20W26ZQw_ZjU:-MeSXxjgBv1YLvm5YFJ7:b-wnfmk9) ([raw file](https://github.com/intel-isl/open3d/blob/94c214ae90a1123b12ba396232a39c1cae005ca7/cpp/open3d/core/kernel/CPULauncher.h#L72)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Checking for nested parallelism should not be needed. It is disabled by default.
https://stackoverflow.com/a/31522514
If a user enables it explicitly, they probably know what they are doing.
</blockquote></details>

Done. Removed.
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 89 at r2](https://reviewable.io/reviews/intel-isl/open3d/3716#-MeSCgve0liMMUq0KBLx:-MeSXzTM7zS_8xlwsz46:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/94c214ae90a1123b12ba396232a39c1cae005ca7/cpp/open3d/core/kernel/CPULauncher.h#L89)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

See above comment about `InParallel()`
</blockquote></details>

Done.
___
*[cpp/open3d/utility/CPUInfo.h, line 36 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePsK48EDbvHfsm2Idr:-MeSY-2E-14cVvMq6lPq:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.h#L36)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Done. Not really, it is only useful if `CPUInfo` is inherited.
</blockquote></details>

Done.
___
*[cpp/open3d/utility/CPUInfo.h, line 41 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePrwDH7FAV3J8yQkj2:-MeSY-SVErMpVZh_kjVf:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.h#L41)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`unsinged int` was used since `std::thread::hardware_concurrency()` returns `unsinged int` (also for the boost counterpart).

I do think `int` looks better for the `CPUInfo` class. Changed to `int`.
</blockquote></details>

Done.
___
*[cpp/open3d/utility/CPUInfo.h, line 46 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePsDgz5To-tNmBbOCF:-MeSY-p2CSlkUiPrtruX:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.h#L46)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[cpp/open3d/utility/CPUInfo.h, line 49 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePrW63-Ncm-3oSMBY2:-MeSY0Ky6HFyTVnVJbNH:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.h#L49)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[cpp/open3d/utility/CPUInfo.cpp, line 52 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePsTxj9FYgnBbJP1LI:-MeSY0yVB1_MxN1awyFl:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.cpp#L52)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[cpp/open3d/utility/CPUInfo.cpp, line 60 at r2](https://reviewable.io/reviews/intel-isl/open3d/3716#-MeS7SrjAgn27S4l82mb:-MeSY9l24YQb7VPDGGJA:b-9exo1g) ([raw file](https://github.com/intel-isl/open3d/blob/94c214ae90a1123b12ba396232a39c1cae005ca7/cpp/open3d/utility/CPUInfo.cpp#L60)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Nit: There's `cpu cores : 6` entry in my output of `/proc/cpuinfo` that is a quicker way to get this. Do you know if boost doesn't use this since it's too new?
</blockquote></details>

For X86, it is located here:
https://github.com/torvalds/linux/blob/7fef2edf7cc753b51f7ccc74993971b0a9c81eca/arch/x86/kernel/cpu/proc.c#L25

For ARM, this `cpu cores` entry is not found in Linux source code. An example output looks like: https://www.phoronix.com/image-viewer.php?id=nvidia-carmel-quick&image=nvidia_carmel_quick_lrg
___
*[cpp/open3d/utility/CPUInfo.cpp, line 125 at r2](https://reviewable.io/reviews/intel-isl/open3d/3716#-MeSIVuz1tzq-wVhIQQj:-MeSZUwu3OlbYA3HCHa9:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/94c214ae90a1123b12ba396232a39c1cae005ca7/cpp/open3d/utility/CPUInfo.cpp#L125)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

MSVC signed / unsigned match warning in CI here.
</blockquote></details>

Done.
___
*[cpp/open3d/utility/Parallel.cpp, line 69 at r2](https://reviewable.io/reviews/intel-isl/open3d/3716#-MeS8y5R9delbvlZPT1x:-MeSZMW6AL-awByMJNFG:bslk8r9) ([raw file](https://github.com/intel-isl/open3d/blob/94c214ae90a1123b12ba396232a39c1cae005ca7/cpp/open3d/utility/Parallel.cpp#L69)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can we adapt  this to work with TBB / parallel STL too?
</blockquote></details>

Added a comment, when we add TBB/Parallel STL support to ParallelFor, this shall be updated.

**Comment by yxlao** [comment]
> Did you see improved benchmark (or perhaps pipeline) timing from this update?

@ssheorey Yes, by default, we can avoid the catastrophic time increase when there's another active process in the system. 

benchmark_parallel_for

**Review by stotko — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3716)* status: all files reviewed, 12 unresolved discussions (waiting on @ssheorey, @stotko, and @yxlao)

___
*[cpp/open3d/utility/CPUInfo.cpp, line 52 at r1](https://reviewable.io/reviews/intel-isl/open3d/3716#-MePsTxj9FYgnBbJP1LI:-MeThNMU035FQ5XFzx1X:b-xztxra) ([raw file](https://github.com/intel-isl/open3d/blob/2b9fc3c1ed9a0c9a16cb0bc3b62cae4366faba2d/cpp/open3d/utility/CPUInfo.cpp#L52)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In that case, we can remove the custom destructor entirely and rely on the implicitly defined one.

**Review by ssheorey — APPROVED** [review]
:+1: 

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3716#-:-MeVl1kgAcAOgaWZHraM:b-8fx2u7)* status: all files reviewed, 5 unresolved discussions (waiting on @stotko and @yxlao)

**Pull request merged**
