### PR TITLE
osMesa headless rendering fixed

### PR DESCRIPTION
**Pull request by Xardvor**
Bug with headless rendering fixed, appears that problem was in GLFW_OPENGL_FORWARD_COMPAT set to true - osMesa doesn't support this mode.
So, switched this hint off when building with headless rendering.
Needs tests on MacOS, if we support headless rendering there.

Fix for issue #940

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1358)

### CODE REVIEW

**Comment by Xardvor** [comment]
> It works for me in Linux, but I wasn't able to build it in MacOS. @qianyizh could you give it a try?
> Otherwise, perhaps we could just add a disclaimer to the documentation stating that it doesn't work in MacOS.
> 
> > Reviewed 2 of 2 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1358#-:-Lv8T-bg5R16jsV7VLzN:bk652dw)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @syncle)

Could you please provide build log from macOS?

**Comment by qianyizh** [comment]
I can compile. But when I run ViewGeometry I got this:
```
[qianyizh@Qianyis-MacBook-Pro build]$ bin/ViewGeometry --pointcloud ../examples/TestData/color.ply
[Open3D DEBUG] GLFW init.
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: [Open3D ERROR] GLFW Error: OSMesa: Library not found
Abort trap: 6
```

I think forward_compact is mandatory for OSX, based on this doc:
https://www.glfw.org/faq.html#41---how-do-i-create-an-opengl-30-context

Can we add a check in the CMake file:
1. When it is OSX and ENABLE_HEADLESS_RENDERING, we report an error headless rendering is not support on OSX
2. Otherwise, disable FORWARD_COMPAT as in this PR
3. Change the doc to reflect the change

**Comment by Xardvor** [comment]
> I manage to compile it and make the headless_rendering.py script work after using:
> 
> sudo port install mesa.
> 
> I couldn't use any other mesa installation. Also, I obtain the same error message than Qianyi when running bin/ViewGeometry --pointcloud ../examples/TestData/color.ply
> 
> > _[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1358#-:-Lv9j1GE0SXGXGZEfYT5:b-v17rse)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @syncle)

So, example for headless rendering works fine on your macOS?
Because, on mac OpenGL wouldn't create context without forward compatibility...
I got a mac, so I will try fix things if we would like to support headless rendering on mac.

**Comment by Xardvor** [comment]
Okay, I managed to compile Open3D with headless rendering using brew version of OSMesa. With some hacks for library search path I'm also managed to to get past "OSMesa: Library not found" error.
But, as I expected, I got another error - "OSMesa: Failed to create context". Because on macOS we can't create context withou forward compatiblity.
I will fix cmake scripts to throw error on macOS with headless rendering enabled then.

**Comment by yaya0805** [comment]
Hi, I've tried the latest commit, but still got an error.
`(open3d_headless) scoly@Scoly:~/Open3D/examples/Python/Advanced$ python headless_rendering.py
Customized visualization playing a camera trajectory. Ctrl+z to terminate
Traceback (most recent call last):
  File "headless_rendering.py", line 69, in <module>
    custom_draw_geometry_with_camera_trajectory(pcd)
  File "headless_rendering.py", line 55, in custom_draw_geometry_with_camera_trajectory
    vis.create_window()
RuntimeError: [Open3D ERROR] GLFW Error: OSMesa: Failed to create context
`
I'm working on Ubuntu 16.04.6 LTS
Any idea about this? Thanks a lot.

**Comment by yaya0805** [comment]
Hi, I've tried the latest commit, but still got an error.
```
(open3d_headless) scoly@Scoly:~/Open3D/examples/Python/Advanced$ python headless_rendering.py
Customized visualization playing a camera trajectory. Ctrl+z to terminate
Traceback (most recent call last):
  File "headless_rendering.py", line 69, in <module>
    custom_draw_geometry_with_camera_trajectory(pcd)
  File "headless_rendering.py", line 55, in custom_draw_geometry_with_camera_trajectory
    vis.create_window()
RuntimeError: [Open3D ERROR] GLFW Error: OSMesa: Failed to create context
```
I'm working on Ubuntu 16.04.6 LTS
Any idea about this? Thanks a lot.

**Comment by JackLangerman** [comment]
Hi all,

Thanks again for all your hard work. I'm still having trouble with this (follow up from my comment on #940): I'd really love to get this figured out, and then I would be happy to update the docs to be crystal clear about how to do this (and provide a setup script). 

This is what I am doing now:

First I spin up a new VM on gcp

gcp_config

I am using this version of Ubuntu
-> Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-1055-gcp x86_64)

I then upload my setup script `setup.sh`
```bash
# update packages
sudo apt-get update -y
sudo apt-get upgrade -y

 
# install OSMesa
sudo apt-get install libosmesa6-dev -y

# setup virtualenv
sudo apt-get install virtualenv python3-pip -y

virtualenv -p /usr/bin/python3 py3env

# enter python env
source py3env/bin/activate

# install numpy / matplotlib
pip install numpy matplotlib

# download Open3D v0.9.0 source
git clone --recursive -b "v0.9.0" https://github.com/intel-isl/Open3D Open3D
cd Open3D/


# install deps
sudo apt-get install cmake -y
yes | bash util/scripts/install-deps-ubuntu.sh
sudo apt-get install -y nasm


# configure build
cmake -DENABLE_HEADLESS_RENDERING=ON \
      -DBUILD_GLEW=ON \
      -DBUILD_GLFW=ON \
      -DBUILD_PYBIND11=ON \
      -DBUILD_SHARED_LIBS=ON \
      -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 \
      CMakeLists.txt

# compile
make

# build python lib
make install-pip-package
```

I then run it like this

```bash
chmod +x setup.sh
./setup.sh &> build_output.out
```

which generates this output -> https://gist.github.com/JackLangerman/7efa941ed84c21a8660e82d8746812ba

I then run this test script:
```bash
###### now test   #######
source ~/py3env/bin/activate
cd ~/Open3D/examples/Python/Advanced/

printf "\n\n\n\n\n\n-----------------------------------------------------------------------------\n\
                    System Info\n\
-----------------------------------------------------------------------------\n\n"
# print some system info
# python info
which python
python -V

# mesa info
sudo apt list --installed | grep mesa



# run tests
printf "\n\n\n\n\n\n-----------------------------------------------------------------------------\n\
                    Now let's run some tests\n\
-----------------------------------------------------------------------------\n\n"

# this works
python -c "import open3d" && printf "it worked\n"


# this breaks -- throws "RuntimeError: [Open3D ERROR] GLFW Error: OSMesa: Failed to create context"
python headless_rendering.py && printf "it worked\n"
```

which prints the following:
```
-----------------------------------------------------------------------------
                    System Info
-----------------------------------------------------------------------------

/home/jack/py3env/bin/python
Python 3.5.2

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libgl1-mesa-dev/xenial-updates,now 18.0.5-0ubuntu0~16.04.1 amd64 [installed,automatic]
libgl1-mesa-dri/xenial-updates,now 18.0.5-0ubuntu0~16.04.1 amd64 [installed,automatic]
libgl1-mesa-glx/xenial-updates,now 18.0.5-0ubuntu0~16.04.1 amd64 [installed]
libglapi-mesa/xenial-updates,now 18.0.5-0ubuntu0~16.04.1 amd64 [installed,automatic]
libglu1-mesa/xenial,now 9.0.0-2.1 amd64 [installed,automatic]
libglu1-mesa-dev/xenial,now 9.0.0-2.1 amd64 [installed]
libosmesa6/xenial-updates,now 18.0.5-0ubuntu0~16.04.1 amd64 [installed,automatic]
libosmesa6-dev/xenial-updates,now 18.0.5-0ubuntu0~16.04.1 amd64 [installed]
mesa-common-dev/xenial-updates,now 18.0.5-0ubuntu0~16.04.1 amd64 [installed,automatic]
mir-client-platform-mesa-dev/xenial-updates,xenial-security,now 0.26.3+16.04.20170605-0ubuntu1.1 amd64 [installed,auto-removable]






-----------------------------------------------------------------------------
                    Now let's run some tests
-----------------------------------------------------------------------------

try to import Open3D....
it worked


try to run headless_rendering.py....
Customized visualization playing a camera trajectory. Ctrl+z to terminate
Traceback (most recent call last):
  File "headless_rendering.py", line 69, in <module>
    custom_draw_geometry_with_camera_trajectory(pcd)
  File "headless_rendering.py", line 55, in custom_draw_geometry_with_camera_trajectory
    vis.create_window()
RuntimeError: [Open3D ERROR] GLFW Error: OSMesa: Failed to create context

```

Am I missing something obvious? I am trying to follow these two pages from the docs:
http://www.open3d.org/docs/release/compilation.htm
http://www.open3d.org/docs/release/tutorial/Advanced/headless_rendering.html

Thanks again for your hard work, and for any light you can shed on this!

**Comment by JackLangerman** [comment]
@Xardvor could you please provide your precise build/install procedure and system specs? Does it align with what I am doing? (https://github.com/intel-isl/Open3D/pull/1358#issuecomment-594763459)

Thanks!

**Comment by germanros1987** [comment]
@Xardvor let's give this some priority. I will follow up with you.

**Pull request merged**
