### PR TITLE
Allow building without Python

### LINKED ISSUE #3173: Open3D build from source fails during make step
I've been trying to install Open3D by following the instructions given at http://www.open3d.org/docs/release/compilation.html

I am running Ubuntu 18.04 with gcc 10.1.0, clang 10.0.0 and cmake version 3.18.0.

Everything is fine up until I have to build the project with `make`. These are the exact commands I used:
```
git clone --recursive https://github.com/intel-isl/Open3D
cd Open3D
git submodule update --init --recursive
util/install_deps_ubuntu.sh
mkdir build
cd build
cmake -DBUILD_PYTHON_MODULE=OFF ..
make -j$(nproc)
```

The first error I see is near the end of the build process, where I get:
```
[ 99%] Building C object code/CMakeFiles/assimp.dir/__/contrib/zip/src/zip.c.o
[100%] Linking CXX static library libassimp.a
[100%] Built target assimp
[ 12%] Performing install step for 'ext_assimp'
[  0%] Built target IrrXML
[  7%] Built target zlibstatic
[ 14%] Built target zlib
[100%] Built target assimp
Install the project...
-- Install configuration: "Release"
-- Installing: /home/alex/Open3D/build/assimp/lib/cmake/assimp-5.0/assimp-config.cmake
-- Installing: /home/alex/Open3D/build/assimp/lib/cmake/assimp-5.0/assimp-config-version.cmake
-- Installing: /home/alex/Open3D/build/assimp/lib/cmake/assimp-5.0/assimpTargets.cmake
-- Installing: /home/alex/Open3D/build/assimp/lib/cmake/assimp-5.0/assimpTargets-release.cmake
-- Installing: /home/alex/Open3D/build/assimp/lib/pkgconfig/assimp.pc
-- Installing: /home/alex/Open3D/build/assimp/lib/libzlibstatic.a
.
.
.
-- Installing: /home/alex/Open3D/build/assimp/include/assimp/Compiler/pushpack1.h
-- Installing: /home/alex/Open3D/build/assimp/include/assimp/Compiler/poppack1.h
-- Installing: /home/alex/Open3D/build/assimp/include/assimp/Compiler/pstdint.h
[ 12%] Completed 'ext_assimp'
[ 12%] Built target ext_assimp
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
```

Any help would be appreciated. If any more information is required from my side, I'd be happy to provide this. Thanks.

### LINKED ISSUE #3376: GUI build is failing on open3d_downloads
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Trying to build the GUI application

**To Reproduce**

1. VS build GUI project

**Expected behavior**
A successful build

**Screenshots**
```
2>Creating directories for 'open3d_downloads'
2>Performing download step for 'open3d_downloads'
2>'PYTHON_IN_PATH-NOTFOUND' is not recognized as an internal or external command,
2>operable program or batch file.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: Custom build for 'C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\fe3cc6bf8faee750f26adb85cc9dfb27\open3d_downloads-mkdir.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\fe3cc6bf8faee750f26adb85cc9dfb27\open3d_downloads-download.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\fe3cc6bf8faee750f26adb85cc9dfb27\open3d_downloads-update.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\fe3cc6bf8faee750f26adb85cc9dfb27\open3d_downloads-patch.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\fe3cc6bf8faee750f26adb85cc9dfb27\open3d_downloads-configure.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\fe3cc6bf8faee750f26adb85cc9dfb27\open3d_downloads-build.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\fe3cc6bf8faee750f26adb85cc9dfb27\open3d_downloads-install.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\96650b1fe0967a01a2a7e91b04f28ed1\open3d_downloads-complete.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\3f81b1540b3459cd380024a11e6b4b55\open3d_downloads.rule' exited with code 9009.
2>Done building project "open3d_downloads.vcxproj" -- FAILED.
```

- Operating system: Windows 10 64-bit
- Python version: Python 3.8.5
- Open3D version: commit https://github.com/intel-isl/Open3D/commit/0f59e75e73757c9b52fdfb69b42a09e2581a8b30
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): VS 16.9.3

**Additional context**

### PR DESCRIPTION
**Pull request by stotko**
- Enable Python-related code conditionally based on `BUILD_PYTHON_MODULE`
- Add native CMake script for downloading test data, requires CMake 3.19
- Simplify patch step for `assimp` to fix conflict with `CMP0114` policy introduced in CMake 3.19
- Remove buggy `FindPythonExecutable` module and use CMake's modern `FindPython3` module with version range check (3.6-3.8) instead
- Port away from `PYTHON_EXECUTABLE` variable coming from CMake's deprecated `FindPythonInterp` module, but set it internally for backwards compatibility with our 3rdparty modules

Fixes #3173
Fixes #3376

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3560)

### CODE REVIEW

**Comment by stotko** [comment]
There are some Windows CI build failures due to Python 3.8 being detected and used instead of version 3.6. To properly fix this, I would need some help:

CMake's `FindPython3` module (see https://cmake.org/cmake/help/latest/module/FindPython3.html) is very powerful and provides multiple search strategies along with good defaults. In particular, the default value `FIRST` for `Python3_FIND_VIRTUALENV` makes CMake prefer the Python executable from the virtual environment. I think this should already be sufficient to account for most use cases (tested on Ubuntu 20.04 with `virtualenv`). Therefore, I would propose to setup a virtual  environment in the CI or fix it if it is already available.

Since moving to the modern `FindPython3` is a larger change, I would like to ask for feedback especially for the changes to the CI and the documentation.

**Review by benjaminum — COMMENTED** [review]
I am not very familiar with the Windows CI and not sure if I can help.
Selecting 3.8 seems to be the right thing to do for cmake if there are multiple versions.
Is the problem that we mix up python versions in the build system?
Would it be enough to set Python3_ROOT to 3.6?

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3560#-:-MbpKyWY9gWyHtI0Eg0I:b-k9unar)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @ssheorey and @yxlao)

**Comment by stotko** [comment]
> I am not very familiar with the Windows CI and not sure if I can help.
> Selecting 3.8 seems to be the right thing to do for cmake if there are multiple versions.
> Is the problem that we mix up python versions in the build system?
> Would it be enough to set Python3_ROOT to 3.6?
> 
> > _[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3560#-:-MbpKyWY9gWyHtI0Eg0I:b-k9unar)_ status: 0 of 13 files reviewed, all discussions resolved (waiting on @ssheorey and @yxlao)

Yes, CMake finds Python 3.8, but the later steps in the CI seem to use version 3.6 (which comes from the Path variable?!). Perhaps, setting `Python3_FIND_REGISTRY` to `LAST` might help, but I do not know the exact motivation/implications and details behind that option and its default. The `Windows CI/Build wheel (3.6, false)` works fine presumably as it sets a virtual environment which CMake prefers by default. Therefore, I would say this is the right way to do it, but I want some feedback to back this up.

**Review by yxlao — COMMENTED** [review]
> Reviewed 10 of 13 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3560)* status: all files reviewed, 4 unresolved discussions (waiting on @ssheorey and @stotko)

___
*[CMakeLists.txt, line 230 at r2](https://reviewable.io/reviews/intel-isl/open3d/3560#-MbtKmEDAasRnKecMnfa:-MbtKmEDAasRnKecMnfb:byp51wp) ([raw file](https://github.com/intel-isl/open3d/blob/8c79ad1f939d8ac91de3921dd5625efc87a7ebd4/CMakeLists.txt#L230)):*
> ```CMake
> 
> # Set Python executable
> find_package(Python3 3.6...<3.9
> ```

Just a question: can the build system work for Python 3.9 as well?
___
*[CMakeLists.txt, line 237 at r2](https://reviewable.io/reviews/intel-isl/open3d/3560#-MbtO1vC1lFwCduRPx5J:-MbtO1vC1lFwCduRPx5K:b-6xgzpi) ([raw file](https://github.com/intel-isl/open3d/blob/8c79ad1f939d8ac91de3921dd5625efc87a7ebd4/CMakeLists.txt#L237)):*
> ```CMake
>     # which still use the deprecated find_package(PythonInterp)
>     set(PYTHON_EXECUTABLE ${Python3_EXECUTABLE} CACHE STRING
>         "Deprecated path to the Python executable (for 3rdparty only)" FORCE)
> ```

Could we also add a print here to show the python executable path and python version?
___
*[examples/test_data/download_test_data.cmake, line 36 at r2](https://reviewable.io/reviews/intel-isl/open3d/3560#-MbrAhSe7qnODLoc-ugU:-MbtP018EV5emdhoMqPT:b-6ou3p) ([raw file](https://github.com/intel-isl/open3d/blob/8c79ad1f939d8ac91de3921dd5625efc87a7ebd4/examples/test_data/download_test_data.cmake#L36)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

It would be useful to allow downloading a subset of the datasets, for example by using command line arguments to this cmake script. If no arguments are given, we can download all datasets. Some of our users have complained about slow downloads. We'll need to update the python script too.
</blockquote></details>

We could address that in a separate PR.

Our current configuration is that we download all datasets in `download_file_list.json`. For large datasets, we don't put them in `download_file_list.json`.

Some datasets are so large (e.g. several GB) that it does not make sense to download by default. They are typically needed to run certain example scripts and they are scattered in various places of the repo. We can do a separate PR to systematiclaly manage large datasets systematically. 

A list of datasets can be found in https://github.com/intel-isl/Open3D/pull/3105#issue-582887679

**Review by stotko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3560)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[CMakeLists.txt, line 230 at r2](https://reviewable.io/reviews/intel-isl/open3d/3560#-MbtKmEDAasRnKecMnfa:-MbuNRBh8ZcUhfWJl9Dx:b-x1s8qz) ([raw file](https://github.com/intel-isl/open3d/blob/8c79ad1f939d8ac91de3921dd5625efc87a7ebd4/CMakeLists.txt#L230)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Just a question: can the build system work for Python 3.9 as well?
</blockquote></details>

Yes, `3.6...<3.9` actually means "accept all Python version from `3.6.x` to `3.8.x` and ignore other installed versions like `3.9.x`". For reference, `3.6...3.8` would exclude `3.8.1` and all other known and unknown future patch releases because of `3.8 = 3.8.0 < 3.8.1`. CMake quickly updates its support for newly released Python versions, e.g. see https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5383, so we can update the statement to `3.6...<3.10` in future once we have official support for Python `3.9.x`.
___
*[CMakeLists.txt, line 237 at r2](https://reviewable.io/reviews/intel-isl/open3d/3560#-MbtO1vC1lFwCduRPx5J:-MbuP-C5BwsMxb2zkkCR:b5sop0j) ([raw file](https://github.com/intel-isl/open3d/blob/8c79ad1f939d8ac91de3921dd5625efc87a7ebd4/CMakeLists.txt#L237)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Could we also add a print here to show the python executable path and python version?
</blockquote></details>

This is not necessary as CMake's `FindPython3` module already does this nicely. For reference, I get the following output which covers the executable path, its version and the version range that has been used for lookup:
`-- Found Python3: /home/stotko/.venv/bin/python3 (found suitable version "3.8.5", required range is "3.6...<3.9") found components: Interpreter Development Development.Module Development.Embed`
___
*[CMakeLists.txt, line 241 at r2](https://reviewable.io/reviews/intel-isl/open3d/3560#-Mbr0Dw93OPuqkV8OFsD:-MbuPgXH5W15OgO1Zfxn:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/8c79ad1f939d8ac91de3921dd5625efc87a7ebd4/CMakeLists.txt#L241)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> BUILD_PYTHON_MODULE=ON requires Python 3.6-3.8. Please ensure it is in PATH.
> ```

</blockquote></details>

Done.
___
*[examples/test_data/download_test_data.cmake, line 36 at r2](https://reviewable.io/reviews/intel-isl/open3d/3560#-MbrAhSe7qnODLoc-ugU:-MbuPiqRAQBdNY5sH1o-:b-3ty3cj) ([raw file](https://github.com/intel-isl/open3d/blob/8c79ad1f939d8ac91de3921dd5625efc87a7ebd4/examples/test_data/download_test_data.cmake#L36)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We could address that in a separate PR.

Our current configuration is that we download all datasets in `download_file_list.json`. For large datasets, we don't put them in `download_file_list.json`.

Some datasets are so large (e.g. several GB) that it does not make sense to download by default. They are typically needed to run certain example scripts and they are scattered in various places of the repo. We can do a separate PR to systematiclaly manage large datasets systematically. 

A list of datasets can be found in https://github.com/intel-isl/Open3D/pull/3105#issue-582887679
</blockquote></details>

Exactly. The data this script downloads is just the some small example data and no large dataset. I would also suggest to generalize this script and its corresponding Python counterpart in a future PR. The goal here was to mimic the existing Python script to have a drop-in replacement and remove the requirement to have a Python environment installed.

**Review by yxlao — APPROVED** [review]

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3560)* status: 9 of 13 files reviewed, 4 unresolved discussions (waiting on @ssheorey, @stotko, and @yxlao)

___
*[examples/test_data/download_test_data.cmake, line 36 at r2](https://reviewable.io/reviews/intel-isl/open3d/3560#-MbrAhSe7qnODLoc-ugU:-McqMgWU7V0Y5b2Chfcw:brxp9sq) ([raw file](https://github.com/intel-isl/open3d/blob/8c79ad1f939d8ac91de3921dd5625efc87a7ebd4/examples/test_data/download_test_data.cmake#L36)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Exactly. The data this script downloads is just the some small example data and no large dataset. I would also suggest to generalize this script and its corresponding Python counterpart in a future PR. The goal here was to mimic the existing Python script to have a drop-in replacement and remove the requirement to have a Python environment installed.
</blockquote></details>

Sounds good.

**Pull request merged**
