### PR TITLE
Refactor cpu_launcher and cuda_launcher as namespaces

### PR DESCRIPTION
**Pull request by yxlao**
Changes:
- `CPULauncher` and `CUDALauncher` are now be namespaces, not classes
- Rename `LaunchGeneralKernel` to `LaunchParallel`
- Add comments

(This PR is to prepare us for the upcoming "parallel for" PR.)

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3638)

### CODE REVIEW

**Review by stotko — COMMENTED** [review]
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3638)* status: all files reviewed, 2 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[cpp/open3d/core/kernel/CPULauncher.h, line 40 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md2Tyti46wJH8b0pQSj:-Md2Tyti46wJH8b0pQSk:b6sss7t) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L40)):*
> ```objc
> namespace core {
> namespace kernel {
> namespace cpu_launcher {
> ```

Would it make sense to use a shorter, less redundant name like `cpu`? For comparison here are fully qualified calls:
```
open3d::core::kernel::cpu_launcher::LaunchParallel(...)
```
vs.
```
open3d::core::kernel::cpu::LaunchParallel(...)
```
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 49 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md2UfRwCnCQfMk_SwlN:-Md2UfRwCnCQfMk_SwlO:b-sftnm7) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L49)):*
> ```objc
> /// ```cpp
> /// #if defined(__CUDACC__)
> ///     namespace launcher = core::kernel::cuda_launcher;
> ```

If we decide to shorten the namespace, perhaps the pattern could become `namespace device = core::kernel::cpu`? The concept is actually closely related to our `Device` class, so it kind of fits. On the other hand, it might be confusing to have two nearly identical names.

**Review by ssheorey — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3638)* status: all files reviewed, 12 unresolved discussions (waiting on @stotko and @yxlao)

___
*[cpp/open3d/core/kernel/CPULauncher.h, line 40 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md2Tyti46wJH8b0pQSj:-Md3d5AdB3xBTgzyUrcT:b-8fx2u7) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L40)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Would it make sense to use a shorter, less redundant name like `cpu`? For comparison here are fully qualified calls:
```
open3d::core::kernel::cpu_launcher::LaunchParallel(...)
```
vs.
```
open3d::core::kernel::cpu::LaunchParallel(...)
```
</blockquote></details>

:+1: 
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 58 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3elsa8G4wu-1gub3c:-Md3elsa8G4wu-1gub3d:bsv93k) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L58)):*
> ```objc
> /// });
> /// ```
> ///
> ```

\note If you use a lambda function, capture only the required shared variables by reference instead of all to prevent accidental race conditions.

\note This is optimized for uniform work items, i.e. where each call to \p func takes the same time.
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 86 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3nuASBpn5U5b2cNyn:-Md3nuASBpn5U5b2cNyo:b-b5pkp3) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L86)):*
> ```objc
> 
> template <typename func_t>
> void LaunchUnaryEWKernel(const Indexer& indexer, const func_t& func) {
> ```

Add \brief docs (or more as needed).
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 94 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3nz2j-_zQKaqQKoSO:-Md3nz2j-_zQKaqQKoSP:b-b5pkp3) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L94)):*
> ```objc
> 
> template <typename func_t>
> void LaunchBinaryEWKernel(const Indexer& indexer, const func_t& func) {
> ```

Add \brief docs (or more as needed).
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 103 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3o-VV4wVF1XLBnvXT:-Md3o-VV4wVF1XLBnvXU:b-b5pkp3) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L103)):*
> ```objc
> 
> template <typename func_t>
> void LaunchAdvancedIndexerKernel(const AdvancedIndexer& indexer,
> ```

Add \brief docs (or more as needed).
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 112 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3o0M49zTySDKCmNFN:-Md3o0M49zTySDKCmNFO:b-b5pkp3) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L112)):*
> ```objc
> 
> template <typename scalar_t, typename func_t>
> void LaunchReductionKernelSerial(const Indexer& indexer, const func_t& func) {
> ```

Add \brief docs (or more as needed).
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 150 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3o7Do-mKBb55LwAOy:-Md3o7Do-mKBb55LwAOz:b-b5pkp3) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L150)):*
> ```objc
> 
> template <typename scalar_t, typename func_t>
> void LaunchReductionParallelDim(const Indexer& indexer, const func_t& func) {
> ```

Add \brief docs (or more as needed).
___
*[cpp/open3d/core/kernel/CUDALauncher.cuh, line 101 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3o9rOCFVe8AJk9dM3:-Md3o9rOCFVe8AJk9dM4:b-b5pkp3) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CUDALauncher.cuh#L101)):*
> ```Cuda
> 
> template <typename func_t>
> void LaunchUnaryEWKernel(const Indexer& indexer, const func_t& func) {
> ```

Add \brief docs (or more as needed).
___
*[cpp/open3d/core/kernel/CUDALauncher.cuh, line 121 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3oDfN2SHdvtqWAljH:-Md3oDfN2SHdvtqWAljI:b-b5pkp3) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CUDALauncher.cuh#L121)):*
> ```Cuda
> 
> template <typename func_t>
> void LaunchBinaryEWKernel(const Indexer& indexer, const func_t& func) {
> ```

Add \brief docs (or more as needed).
___
*[cpp/open3d/core/kernel/CUDALauncher.cuh, line 143 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3oGL08zmGlMRH4HSI:-Md3oGL08zmGlMRH4HSJ:b-b5pkp3) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CUDALauncher.cuh#L143)):*
> ```Cuda
> template <typename func_t>
> void LaunchAdvancedIndexerKernel(const AdvancedIndexer& indexer,
>                                  const func_t& func) {
> ```

Add \brief docs (or more as needed).
___
*[cpp/open3d/t/geometry/kernel/PointCloudCPU.cpp, line 88 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3kBdz9K4J6nfVaOKO:-Md3kBdz9K4J6nfVaOKP:bsfa513) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/t/geometry/kernel/PointCloudCPU.cpp#L88)):*
> ```cpp
>                 static_cast<int64_t>(u), static_cast<int64_t>(v));
>         float d = zc * depth_scale;
> #pragma omp critical
> ```

Name critical region so that it doesn't block an unrelated critical region running in parallel.
`#pragma omp critical(pointcloud_project)`

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3638)* status: 16 of 28 files reviewed, 12 unresolved discussions (waiting on @ssheorey and @stotko)

___
*[cpp/open3d/core/kernel/CPULauncher.h, line 40 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md2Tyti46wJH8b0pQSj:-MdMuPau8EK7jEtz1Czo:bvj8ca1) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L40)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

As we discussed in the meeting, it seems to me that `kernel::cpu::` and `kernel::cuda::` are better suited for a larger scope than just the parallel launchers. It may look less intuitive if there's only the launcher functions under the namespace `kernel::cpu::` and `kernel::cuda::`.

What about `open3d::core::kernel::cpu_launcher::ParallelFor`? This will avoid the duplicated "launch" keyword.
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 49 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md2UfRwCnCQfMk_SwlN:-MdMww6v6L7Ugm9EvgLx:b-e88mvr) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L49)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

If we decide to shorten the namespace, perhaps the pattern could become `namespace device = core::kernel::cpu`? The concept is actually closely related to our `Device` class, so it kind of fits. On the other hand, it might be confusing to have two nearly identical names.
</blockquote></details>

If we have a local variable `device`, it could be confusing if we also have a namespace alias `device`. For example in `cpp/open3d/t/pipelines/kernel/FillInLinearSystemImpl.h` we have this scenario. 

(The other idea is to actually add a `Device::LaunchParallel()` function to the `Device` class. The downside of this is that the user would have to create a `Device` instance (if it is not there) before calling the `LaunchParallel`).

For the scope of this PR, I would suggest just go with the name `launcher` name for now. In the future, we can revisit this once we have a better naming scheme.
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 58 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3elsa8G4wu-1gub3c:-MdQbH5C4hCmC4ziJz_p:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L58)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

\note If you use a lambda function, capture only the required shared variables by reference instead of all to prevent accidental race conditions.

\note This is optimized for uniform work items, i.e. where each call to \p func takes the same time.
</blockquote></details>

Done.
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 86 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3nuASBpn5U5b2cNyn:-MdQbLUP2bAACmtCa_GC:bxg0cc9) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L86)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add \brief docs (or more as needed).
</blockquote></details>

I am moving this function to the `UnaryEW.cpp` since it is only used there. Users typically don't need to use this function (they may use the `LaunchParallel`).
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 94 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3nz2j-_zQKaqQKoSO:-MdQbkmEET4vu_Z5Q-w8:b-smofot) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L94)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add \brief docs (or more as needed).
</blockquote></details>

Same as above, this is a private function and will be moved.
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 103 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3o-VV4wVF1XLBnvXT:-MdQboQGDZbOs5EhPLts:b-smofot) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L103)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add \brief docs (or more as needed).
</blockquote></details>

Same as above, this is a private function and will be moved.
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 112 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3o0M49zTySDKCmNFN:-MdQbouH2Jb5O_hoSWw6:b-smofot) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L112)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add \brief docs (or more as needed).
</blockquote></details>

Same as above, this is a private function and will be moved.
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 150 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3o7Do-mKBb55LwAOy:-MdQbpF-7efP-jI0AbgR:b-smofot) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L150)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add \brief docs (or more as needed).
</blockquote></details>

Same as above, this is a private function and will be moved.
___
*[cpp/open3d/core/kernel/CUDALauncher.cuh, line 101 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3o9rOCFVe8AJk9dM3:-MdQbpn49jp3TS4R0VzO:b-smofot) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CUDALauncher.cuh#L101)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add \brief docs (or more as needed).
</blockquote></details>

Same as above, this is a private function and will be moved.
___
*[cpp/open3d/core/kernel/CUDALauncher.cuh, line 121 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3oDfN2SHdvtqWAljH:-MdQbq5q0WUKuJnNGYgO:b-smofot) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CUDALauncher.cuh#L121)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add \brief docs (or more as needed).
</blockquote></details>

Same as above, this is a private function and will be moved.
___
*[cpp/open3d/core/kernel/CUDALauncher.cuh, line 143 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3oGL08zmGlMRH4HSI:-MdQbqNg5DS2CL1E9X53:b-smofot) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CUDALauncher.cuh#L143)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add \brief docs (or more as needed).
</blockquote></details>

Same as above, this is a private function and will be moved.
___
*[cpp/open3d/t/geometry/kernel/PointCloudCPU.cpp, line 88 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md3kBdz9K4J6nfVaOKO:-MdQu_qm3fDJ43X4H3wK:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/t/geometry/kernel/PointCloudCPU.cpp#L88)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Name critical region so that it doesn't block an unrelated critical region running in parallel.
`#pragma omp critical(pointcloud_project)`
</blockquote></details>

Done.

**Review by stotko — COMMENTED** [review]
> Reviewed 11 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3638)* status: 27 of 28 files reviewed, 12 unresolved discussions (waiting on @ssheorey, @stotko, and @yxlao)

___
*[cpp/open3d/core/kernel/CPULauncher.h, line 40 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md2Tyti46wJH8b0pQSj:-MdQyNbg6fEgCZaelR49:brxp9sq) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L40)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

As we discussed in the meeting, it seems to me that `kernel::cpu::` and `kernel::cuda::` are better suited for a larger scope than just the parallel launchers. It may look less intuitive if there's only the launcher functions under the namespace `kernel::cpu::` and `kernel::cuda::`.

What about `open3d::core::kernel::cpu_launcher::ParallelFor`? This will avoid the duplicated "launch" keyword.
</blockquote></details>

Sounds good.
___
*[cpp/open3d/core/kernel/CPULauncher.h, line 49 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md2UfRwCnCQfMk_SwlN:-MdQyX3PEWKid2D7qjx7:bv6abmv) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L49)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

If we have a local variable `device`, it could be confusing if we also have a namespace alias `device`. For example in `cpp/open3d/t/pipelines/kernel/FillInLinearSystemImpl.h` we have this scenario. 

(The other idea is to actually add a `Device::LaunchParallel()` function to the `Device` class. The downside of this is that the user would have to create a `Device` instance (if it is not there) before calling the `LaunchParallel`).

For the scope of this PR, I would suggest just go with the name `launcher` name for now. In the future, we can revisit this once we have a better naming scheme.
</blockquote></details>

Yes, that might be confusing. I'm perfectly fine with limiting the scope of this PR to `launcher`. Any larger reorganization of the naming convention needs more consideration (and is also not urgent at the moment).

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3638)* status: 12 of 28 files reviewed, 6 unresolved discussions (waiting on @ssheorey, @stotko, and @yxlao)

___
*[cpp/open3d/core/kernel/CPULauncher.h, line 40 at r1](https://reviewable.io/reviews/intel-isl/open3d/3638#-Md2Tyti46wJH8b0pQSj:-MdT2wwaCkGBGs-A_5cn:bb6mt9b) ([raw file](https://github.com/intel-isl/open3d/blob/0d29163068e01d6746f25338e973c36659a3ad81/cpp/open3d/core/kernel/CPULauncher.h#L40)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

:+1:

**Pull request merged**
