### PR TITLE
Support Float32 and Float64 neighbor search

### PR DESCRIPTION
**Pull request by junha-l**
Convert NanoFlannIndex class into template class to handle Tensor with the various data types.

### Functionality
- Handle Tensor of Dtype Float32, Float64

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2241)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  6
- cpp/tests/core/NearestNeighbor.cpp  18
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6079585&bid=19903086)

**Comment by yxlao** [comment]
hi @junha-l the first version of nns has been merged to master, with some refactoring changes, can you merge master to this branch and resolve the conflicts?

**Review by benjaminum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 7 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2241)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @benjaminum, @junha-l, and @yxlao)

___
*[cpp/open3d/core/nns/NearestNeighbor.cpp, line 51 at r3](https://reviewable.io/reviews/intel-isl/open3d/2241#-MG29BRv6mZr3rT4BKsT:-MG29BRv6mZr3rT4BKsU:b-2r1sph) ([raw file](https://github.com/intel-isl/open3d/blob/bb7b8d442dacebd99bfd24fb76b45453020bf46c/cpp/open3d/core/nns/NearestNeighbor.cpp#L51)):*
> ```cpp
>             return cast_index<float>()->SetTensorData(data_);
>         default:
>             utility::LogError("undefined data type");
> ```

Give a bit more information to the user like the other error messages.
"unsupported data type. NeighborSearch only supports float32 and float64"
___
*[cpp/open3d/core/nns/NearestNeighbor.cpp, line 75 at r3](https://reviewable.io/reviews/intel-isl/open3d/2241#-MG29WETCx1iq3BxyhrS:-MG29WETCx1iq3BxyhrT:b-2guby3) ([raw file](https://github.com/intel-isl/open3d/blob/bb7b8d442dacebd99bfd24fb76b45453020bf46c/cpp/open3d/core/nns/NearestNeighbor.cpp#L75)):*
> ```cpp
>             return cast_index<float>()->SearchKnn(query, knn);
>         default:
>             utility::LogError("undefined data type");
> ```

same here
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 141 at r3](https://reviewable.io/reviews/intel-isl/open3d/2241#-MG273bs67rD-lXd_jTM:-MG273bt8nKK7m1SEFWe:b-dlinwn) ([raw file](https://github.com/intel-isl/open3d/blob/bb7b8d442dacebd99bfd24fb76b45453020bf46c/cpp/open3d/core/nns/NanoFlannIndex.h#L141)):*
> ```objc
>     /// \param radii A list of radius. Same size with query.
>     std::tuple<core::Tensor, core::Tensor, core::Tensor> SearchRadius(
>             const core::Tensor &query, T *radii);
> ```

Let us use Tensor for radii. It allows us to check the shape and it should be safer to use.
___
*[cpp/open3d/core/nns/NearestNeighbor.h, line 74 at r3](https://reviewable.io/reviews/intel-isl/open3d/2241#-MG2937IBKc-DJA5tY1v:-MG2937IBKc-DJA5tY1w:ba4al2i) ([raw file](https://github.com/intel-isl/open3d/blob/bb7b8d442dacebd99bfd24fb76b45453020bf46c/cpp/open3d/core/nns/NearestNeighbor.h#L74)):*
> ```objc
>     template <typename T>
>     std::tuple<core::Tensor, core::Tensor, core::Tensor> RadiusSearch(
>             const core::Tensor &query, T *radii);
> ```

Same here let's use Tensor for radii.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ cpp/tests/core/NearestNeighborSearch.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6079585&bid=19903086)

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2241)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @benjaminum and @yxlao)

___
*[cpp/open3d/core/nns/NearestNeighbor.cpp, line 51 at r3](https://reviewable.io/reviews/intel-isl/open3d/2241#-MG29BRv6mZr3rT4BKsT:-MG3vgOpENpdavd_Rm47:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/bb7b8d442dacebd99bfd24fb76b45453020bf46c/cpp/open3d/core/nns/NearestNeighbor.cpp#L51)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Give a bit more information to the user like the other error messages.
"unsupported data type. NeighborSearch only supports float32 and float64"
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NearestNeighbor.cpp, line 75 at r3](https://reviewable.io/reviews/intel-isl/open3d/2241#-MG29WETCx1iq3BxyhrS:-MG3vgcs59Oe17odCFb8:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/bb7b8d442dacebd99bfd24fb76b45453020bf46c/cpp/open3d/core/nns/NearestNeighbor.cpp#L75)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 141 at r3](https://reviewable.io/reviews/intel-isl/open3d/2241#-MG273bs67rD-lXd_jTM:-MG3vf8YDgqMlMBpmeHp:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/bb7b8d442dacebd99bfd24fb76b45453020bf46c/cpp/open3d/core/nns/NanoFlannIndex.h#L141)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Let us use Tensor for radii. It allows us to check the shape and it should be safer to use.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NearestNeighbor.h, line 74 at r3](https://reviewable.io/reviews/intel-isl/open3d/2241#-MG2937IBKc-DJA5tY1v:-MG3vfs33pjWa7MGoy4Y:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/bb7b8d442dacebd99bfd24fb76b45453020bf46c/cpp/open3d/core/nns/NearestNeighbor.h#L74)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Same here let's use Tensor for radii.
</blockquote></details>

Done.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ cpp/tests/core/NearestNeighborSearch.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6079585&bid=19903086)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ cpp/tests/core/NearestNeighborSearch.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6079585&bid=19903086)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ cpp/tests/core/NearestNeighborSearch.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6079585&bid=19903086)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ cpp/tests/core/NearestNeighborSearch.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6079585&bid=19903086)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/core/nns/NanoFlannIndex.cpp  2
         

Clones removed
==============
+ cpp/tests/core/NearestNeighborSearch.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6079585&bid=19903086)

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2241)* status: 0 of 6 files reviewed, 11 unresolved discussions (waiting on @benjaminum and @yxlao)

___
*[cpp/open3d/core/CoreUtil.h, line 28 at r7](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGHKeoa9xwG40XbhUno-r7-28:-MGJe0KE3thuJY4lDC4q:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/b886ce49cb4f71c21c205e08205d05d255bfc5f2/cpp/open3d/core/CoreUtil.h#L28)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

include the header for `utility::LogError`?
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NearestNeighborSearch.h, line 100 at r6](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGGathoCjbfUM-vNW-r:-MGJeODt3WgwON-s_KUP:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fc56b8d8b060d27969a102a5015e19b3dda807c1/cpp/open3d/core/nns/NearestNeighborSearch.h#L100)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

To simplify the code, I would suggest using `double` for radius always. The dtype can then be inferred from `query_points` or `dataset_points`.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NearestNeighborSearch.cpp, line 44 at r6](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGGeqo68oMpBWtISlil:-MGJeR2TCij80tR_FNBP:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fc56b8d8b060d27969a102a5015e19b3dda807c1/cpp/open3d/core/nns/NearestNeighborSearch.cpp#L44)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Same,  use the `DISPATCH_LINALG_DTYPE_TO_TEMPLATE` mechanism.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NearestNeighborSearch.cpp, line 68 at r6](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGGb9Bz7WxHmy5oerJp:-MGJeVIJ5LaXE5HYAOHJ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fc56b8d8b060d27969a102a5015e19b3dda807c1/cpp/open3d/core/nns/NearestNeighborSearch.cpp#L68)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Can we add `NearestNeighborSearch::GetDtype()` which returns `dataset_points_.GetDtype()`?`
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NearestNeighborSearch.cpp, line 69 at r6](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGGbYD20E54A8R3pEOc:-MGJeWeXD_FVB4gxnma4:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fc56b8d8b060d27969a102a5015e19b3dda807c1/cpp/open3d/core/nns/NearestNeighborSearch.cpp#L69)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

1. If we need to switch float32 and float 64, we can use the "dispatcher" semantics here, see https://github.com/intel-isl/Open3D/blob/e3f0edb65770baeb6a08225c257b124764af4e87/cpp/open3d/core/linalg/LinalgUtils.h#L45-L56 

2. It will look like
```cpp
DISPATCH_LINALG_DTYPE_TO_TEMPLATE(dtype, [&]() {
    return cast_index<scalar_t>()->SearchKnn(query_points, knn);
});
```

3. We can move the `DISPATCH_LINALG_DTYPE_TO_TEMPLATE` to `core/CoreUtil.h` and rename it to `DISPATCH_FLOAT32_FLOAT64_DTYPE` so it is not specific to the linear algebra module.

4. However, as we discussed, I would prefer to delay the templates as much as possible. So ideally the `NanoFlannIndex` class is not templated.
</blockquote></details>

Done.
___
*[cpp/pybind/core/nns/nearest_neighbor_search.cpp, line 81 at r6](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGGdOMtCQqUgHOJJaYq:-MGJeYTKARUN-PaeABpc:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fc56b8d8b060d27969a102a5015e19b3dda807c1/cpp/pybind/core/nns/nearest_neighbor_search.cpp#L81)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

My impression is that, python will always use the `<double>` version since the only place where the template is inferred is the `radius` variable. Say in python you do `nns.fix_radius_search(q_points, 0.5)`, then pybind relies on `0.5` to determine the type, which is double. At this point, if `q_points` is `Float32`, it will be inconsistent. This is my guess, could you verify this by testing?

Taking a step back, if we always let `radius` be double and always get the dtype from `query_points` or `dataset_points`, we can avoid this problem completely.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 56 at r6](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGGfOztDJradqPk5iy4:-MGJe20dE-Dlrmjizrji:b-6elgww) ([raw file](https://github.com/intel-isl/open3d/blob/fc56b8d8b060d27969a102a5015e19b3dda807c1/cpp/open3d/core/nns/NanoFlannIndex.h#L56)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

In general, we shall delay using templates unless it becomes necessary to clean up the code. I would suggest not to use template in `NearestNeighborSearch` or `NanoFlannIndex` and only use it in `Adapter`.

That is,
- We have`class AdaptorBase`, `class Adapter<float>: public AdapterBase`, `class Adapter<double>: public AdapterBase`
- `NanoFlannIndex` is not templated, and contains `std::unique_ptr<AdaptorBase> adaptor_;`
- `NearestNeighborSearch` remains the same, only need to change the caller to `NanoFlannIndex` , since now `NanoFlannIndex` is not templated anymore.

</blockquote></details>

I created a struct (NanoFlannIndexHolder) and removed ```template <typename T>``` from NanoFlannIndex and NearestNeighbor Class

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r4, 1 of 4 files at r7, 5 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2241)* status: all files reviewed, 9 unresolved discussions (waiting on @benjaminum, @junha-l, and @yxlao)

___
*[cpp/open3d/core/nns/NearestNeighborSearch.cpp, line 101 at r8](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGN34VoEf1BXKFHCGzU:-MGN34VoEf1BXKFHCGzV:bxbykzf) ([raw file](https://github.com/intel-isl/open3d/blob/0e280f0e35e23f3e0e93b0b462dbaaa4750569b0/cpp/open3d/core/nns/NearestNeighborSearch.cpp#L101)):*
> ```cpp
>     }
>     Dtype dtype = dataset_points_.GetDtype();
>     return DISPATCH_FLOAT32_FLOAT64_DTYPE(dtype, [&]() {
> ```

Try to remove the `return` here. Since `DISPATCH_FLOAT32_FLOAT64_DTYPE` creates a scope, you can define some variable before the scope, and modify these variables in the scope, such that the variables can still be used after the scope.

Same for other `DISPATCH_FLOAT32_FLOAT64_DTYPE`. 
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 98 at r8](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGN2PdAAmtq3oOeJN1m:-MGN2PdAAmtq3oOeJN1n:b-2v3srf) ([raw file](https://github.com/intel-isl/open3d/blob/0e280f0e35e23f3e0e93b0b462dbaaa4750569b0/cpp/open3d/core/nns/NanoFlannIndex.h#L98)):*
> ```objc
> /// NanoFlann Index Holder
> template <typename T>
> struct NanoFlannIndexHolder : NanoFlannIndexHolderBase {
> ```

We can make the helper classes as nested classes, thus simplifying the templates.

```cpp
template <int METRIC, class T>
struct NanoFlannIndexHolder : NanoFlannIndexHolderBase {
    struct PointCloudAdaptor {
        PointCloudAdaptor(size_t dataset_size,
                          int dimension,
                          const T *const data_ptr)
            : dataset_size_(dataset_size),
              dimension_(dimension),
              data_ptr_(data_ptr) {}

        inline size_t kdtree_get_point_count() const { return dataset_size_; }

        inline T kdtree_get_pt(const size_t idx, const size_t dim) const {
            return data_ptr_[idx * dimension_ + dim];
        }

        template <class BBOX>
        bool kdtree_get_bbox(BBOX &) const {
            return false;
        }

        size_t dataset_size_ = 0;
        int dimension_ = 0;
        const T *const data_ptr_;
    };

    template <int M>
    struct SelectNanoflannAdaptor {};

    template <>
    struct SelectNanoflannAdaptor<L2> {
        typedef nanoflann::L2_Adaptor<T, PointCloudAdaptor, T> adaptor_t;
    };

    template <>
    struct SelectNanoflannAdaptor<L1> {
        typedef nanoflann::L1_Adaptor<T, PointCloudAdaptor, T> adaptor_t;
    };

    typedef nanoflann::KDTreeSingleIndexAdaptor<
            typename SelectNanoflannAdaptor<METRIC>::adaptor_t,
            PointCloudAdaptor,
            -1,
            size_t>
            kdtree_t;

    NanoFlannIndexHolder(size_t dataset_size,
                         int dimension,
                         const T *data_ptr) {
        adaptor_.reset(
                new PointCloudAdaptor(dataset_size, dimension, data_ptr));
        index_.reset(new kdtree_t(dimension, *adaptor_));
        index_->buildIndex();
    }

    std::unique_ptr<PointCloudAdaptor> adaptor_;
    std::unique_ptr<kdtree_t> index_;
};
```

After this, in the .cpp file, replace `NanoFlannIndexHolder<scalar_t>` with `NanoFlannIndexHolder<L2, scalar_t>`. 

For future work, we can conveniently set the L1, L2, by
```cpp
if (metric == L1) 
     holder_.reset(new NanoFlannIndexHolder<L1, scalar_t>(...));
else if (metric == L2) 
     holder_.reset(new NanoFlannIndexHolder<L2, scalar_t>(...));
```

Or even, have another dispatcher for Metrics.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 145 at r8](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGNA2na5PVGI-NYW2Zr:-MGNA2na5PVGI-NYW2Zs:b-fknur8) ([raw file](https://github.com/intel-isl/open3d/blob/0e280f0e35e23f3e0e93b0b462dbaaa4750569b0/cpp/open3d/core/nns/NanoFlannIndex.h#L145)):*
> ```objc
>     ///
>     /// \param query_points Query points. Must be 2D, with shape {n, d}, same
>     /// dtype with dataset_points. \param knn Number of nearest neighbor to
> ```

The format of these needs manual adjustments. Same for others.
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 116 at r8](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGN5fiGDcTPveXSO8Tw:-MGN5fiGDcTPveXSO8Tx:b4kjkg6) ([raw file](https://github.com/intel-isl/open3d/blob/0e280f0e35e23f3e0e93b0b462dbaaa4750569b0/cpp/open3d/core/nns/NanoFlannIndex.cpp#L116)):*
> ```cpp
>             std::vector<scalar_t> single_distances(knn);
> 
>             NanoFlannIndexHolder<scalar_t> *holder =
> ```

The RHS side type is obvious, so we can use `auto` on the LFS. Same for the other instances.

**Review by yxlao — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2241)* status: all files reviewed, 10 unresolved discussions (waiting on @benjaminum, @junha-l, and @yxlao)

___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 195 at r8](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGNVZ1B25L50n38fikR:-MGNVZ1B25L50n38fikS:b-52ootk) ([raw file](https://github.com/intel-isl/open3d/blob/0e280f0e35e23f3e0e93b0b462dbaaa4750569b0/cpp/open3d/core/nns/NanoFlannIndex.cpp#L195)):*
> ```cpp
> 
>         for (auto i = 0; i < radii.GetShape()[0]; i++) {
>             scalar_t radius = *static_cast<scalar_t *>(radii[i].GetDataPtr());
> ```

`radius = radii[i].Item<scalar_t>();`

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2241)* status: 2 of 6 files reviewed, 10 unresolved discussions (waiting on @benjaminum and @yxlao)

___
*[cpp/open3d/core/nns/NearestNeighborSearch.cpp, line 101 at r8](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGN34VoEf1BXKFHCGzU:-MGOgxGjDev3kTWrSMOB:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0e280f0e35e23f3e0e93b0b462dbaaa4750569b0/cpp/open3d/core/nns/NearestNeighborSearch.cpp#L101)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Try to remove the `return` here. Since `DISPATCH_FLOAT32_FLOAT64_DTYPE` creates a scope, you can define some variable before the scope, and modify these variables in the scope, such that the variables can still be used after the scope.

Same for other `DISPATCH_FLOAT32_FLOAT64_DTYPE`. 
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 98 at r8](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGN2PdAAmtq3oOeJN1m:-MGOfqD8BqBjeKCZtwRt:b-97ofit) ([raw file](https://github.com/intel-isl/open3d/blob/0e280f0e35e23f3e0e93b0b462dbaaa4750569b0/cpp/open3d/core/nns/NanoFlannIndex.h#L98)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We can make the helper classes as nested classes, thus simplifying the templates.

```cpp
template <int METRIC, class T>
struct NanoFlannIndexHolder : NanoFlannIndexHolderBase {
    struct PointCloudAdaptor {
        PointCloudAdaptor(size_t dataset_size,
                          int dimension,
                          const T *const data_ptr)
            : dataset_size_(dataset_size),
              dimension_(dimension),
              data_ptr_(data_ptr) {}

        inline size_t kdtree_get_point_count() const { return dataset_size_; }

        inline T kdtree_get_pt(const size_t idx, const size_t dim) const {
            return data_ptr_[idx * dimension_ + dim];
        }

        template <class BBOX>
        bool kdtree_get_bbox(BBOX &) const {
            return false;
        }

        size_t dataset_size_ = 0;
        int dimension_ = 0;
        const T *const data_ptr_;
    };

    template <int M>
    struct SelectNanoflannAdaptor {};

    template <>
    struct SelectNanoflannAdaptor<L2> {
        typedef nanoflann::L2_Adaptor<T, PointCloudAdaptor, T> adaptor_t;
    };

    template <>
    struct SelectNanoflannAdaptor<L1> {
        typedef nanoflann::L1_Adaptor<T, PointCloudAdaptor, T> adaptor_t;
    };

    typedef nanoflann::KDTreeSingleIndexAdaptor<
            typename SelectNanoflannAdaptor<METRIC>::adaptor_t,
            PointCloudAdaptor,
            -1,
            size_t>
            kdtree_t;

    NanoFlannIndexHolder(size_t dataset_size,
                         int dimension,
                         const T *data_ptr) {
        adaptor_.reset(
                new PointCloudAdaptor(dataset_size, dimension, data_ptr));
        index_.reset(new kdtree_t(dimension, *adaptor_));
        index_->buildIndex();
    }

    std::unique_ptr<PointCloudAdaptor> adaptor_;
    std::unique_ptr<kdtree_t> index_;
};
```

After this, in the .cpp file, replace `NanoFlannIndexHolder<scalar_t>` with `NanoFlannIndexHolder<L2, scalar_t>`. 

For future work, we can conveniently set the L1, L2, by
```cpp
if (metric == L1) 
     holder_.reset(new NanoFlannIndexHolder<L1, scalar_t>(...));
else if (metric == L2) 
     holder_.reset(new NanoFlannIndexHolder<L2, scalar_t>(...));
```

Or even, have another dispatcher for Metrics.
</blockquote></details>

Done. 

1. I have changed the PointCloudAdaptor as DataAdaptor since it is not limited to the point cloud.
2. I added a fake (unused) template parameter in SelectNanoflannAdaptor to resolve the ```explicit specialization in non-namespace scope``` (http://www.cplusplus.com/forum/general/193680/). 
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 145 at r8](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGNA2na5PVGI-NYW2Zr:-MGOgSKA39attHgT356e:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0e280f0e35e23f3e0e93b0b462dbaaa4750569b0/cpp/open3d/core/nns/NanoFlannIndex.h#L145)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

The format of these needs manual adjustments. Same for others.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 116 at r8](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGN5fiGDcTPveXSO8Tw:-MGOgZ8EBj6nSUyw1Cdj:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0e280f0e35e23f3e0e93b0b462dbaaa4750569b0/cpp/open3d/core/nns/NanoFlannIndex.cpp#L116)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

The RHS side type is obvious, so we can use `auto` on the LFS. Same for the other instances.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 195 at r8](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGNVZ1B25L50n38fikR:-MGOg_pX8tsy1JoDgbev:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0e280f0e35e23f3e0e93b0b462dbaaa4750569b0/cpp/open3d/core/nns/NanoFlannIndex.cpp#L195)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`radius = radii[i].Item<scalar_t>();`
</blockquote></details>

Done.

**Review by yxlao — APPROVED** [review]
> Reviewed 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2241)* status: all files reviewed, 5 unresolved discussions (waiting on @benjaminum and @yxlao)

___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 98 at r8](https://reviewable.io/reviews/intel-isl/open3d/2241#-MGN2PdAAmtq3oOeJN1m:-MGSP85B6Ux30qNlCNKS:bp11whg) ([raw file](https://github.com/intel-isl/open3d/blob/0e280f0e35e23f3e0e93b0b462dbaaa4750569b0/cpp/open3d/core/nns/NanoFlannIndex.h#L98)):*
> explicit specialization in non-namespace scope
ok, seems to be a problem from MSVC

**Comment by yxlao** [comment]
LGTM, thanks @junha-l  for the contribution!

**Pull request merged**
