### PR TITLE
Changed center parameter in Scale and Rotate

### PR DESCRIPTION
**Pull request by griegler**
Changed the `center` parameter in `Scale` and `Rotate` from `bool` to `Eigen::Vector3d`. Now the user can define an arbitrary scale/rotation center for these transformations. To get the previous behaviour one could use `geom.GetCenter()` or `Eigen::Vector3d(0,0,0)` respectively.

Updated tutorials accordingly.

Addresses #1745.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1774)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Clones removed
==============
+ src/Open3D/Geometry/Geometry3D.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5449942&bid=17869360)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Clones removed
==============
+ src/Open3D/Geometry/Geometry3D.cpp  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5449942&bid=17869360)

**Comment by pablospe** [comment]
I believe it is good to have the option of providing the center, but also it would be good to have the previous interface allowing to have old code to work without providing the center. For example, it would be possible to overload the `Rotate()` function when no center is provided (pseudo-code):

```
void Rotate(const Eigen::Matrix3d& R) {
    Rotate(R, center_);
}

void Rotate(const Eigen::Matrix3d& R, const Eigen::Vector3d &center) {
   [...] // current code
}
```

**Comment by griegler** [comment]
@pablospe Added it in PR #1920

**Pull request merged**
