### PR TITLE
Add Image IO

### PR DESCRIPTION
**Pull request by sanskar107**
Add `Image` Input/Output Operations (jpg and png).
Add new `Reset` method in Image class.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2955)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2955)* status: all files reviewed, 17 unresolved discussions (waiting on @sanskar107)

___
*[cpp/open3d/t/geometry/Image.cpp, line 44 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSDwcQ31hT89bWK_Az2:-MSDwcQ4DrFFhLwFeqt6:b-to80ou) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/geometry/Image.cpp#L44)):*
> ```cpp
>              const core::Device &device)
>     : Geometry(Geometry::GeometryType::Image, 2) {
>     if (rows < 0) {
> ```

can these checks be removed since we're also doing it in `Reset`?
___
*[cpp/open3d/t/io/ImageIO.h, line 46 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRvr_e9eyIFExFHzd9:-MSRpsMY-7g6yu0kThT3:b-atr5k3) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/ImageIO.h#L46)):*
> ```objc
> /// The function calls read functions based on the extension name of filename.
> /// \return return true if the read function is successful, false otherwise.
> bool ReadImage(const std::string &filename, geometry::Image &image);
> ```

add `\param filename`, and mention how we use the extension name
___
*[cpp/open3d/t/io/ImageIO.h, line 54 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRvkHSDzllbHygcbEz:-MSRvkHTCICvqKH5N7lw:b-atr5k3) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/ImageIO.h#L54)):*
> ```objc
> /// If the write function supports quality, the parameter will be used.
> /// Otherwise it will be ignored.
> /// \param quality: PNG: [0-9] <=2 fast write for storing intermediate data
> ```

add `\param filename`, and mention how we use the extension name
___
*[cpp/open3d/t/io/ImageIO.h, line 60 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRvOV22rBFI2KEcUeG:-MSRvOV22rBFI2KEcUeH:bqi71j3) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/ImageIO.h#L60)):*
> ```objc
> ///                 quality).
> /// \return return true if the write function is successful, false otherwise.
> bool WriteImage(const std::string &filename,
> ```

Add some comments here on:
1) supported file extension types 
2) supported dtype, channel number for both jpg and png
___
*[cpp/open3d/t/io/ImageIO.cpp, line 41 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRxykW3kmRc5ykhNWQ:-MSRxykW3kmRc5ykhNWR:b-ke3nup) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/ImageIO.cpp#L41)):*
> ```cpp
> using namespace io;
> 
> static const std::unordered_map<
> ```

looks like we can move these two `static const` to inside the `namespace io`? 
___
*[cpp/open3d/t/io/file_format/FilePNG.cpp, line 38 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRyGJ3D7rwvwqzrZCc:-MSRyGJ3D7rwvwqzrZCd:bsgisxo) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/file_format/FilePNG.cpp#L38)):*
> ```cpp
> using namespace io;
> 
> void SetPNGImageFromImage(const geometry::Image &image,
> ```

same, can we move this inside `namespace io` and add `static` before it?
___
*[cpp/open3d/t/io/file_format/FilePNG.cpp, line 77 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRyN9s9QpQi6hwA1PG:-MSRyN9s9QpQi6hwA1PH:b-t95nju) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/file_format/FilePNG.cpp#L77)):*
> ```cpp
>         pngimage.format &= ~PNG_FORMAT_FLAG_COLORMAP;
>     }
>     if (pngimage.format & PNG_FORMAT_FLAG_LINEAR)
> ```

add {}
___
*[cpp/open3d/t/io/file_format/FilePNG.cpp, line 81 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRyOgwEpIreUHWbhzq:-MSRyOgwEpIreUHWbhzr:b-t95nju) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/file_format/FilePNG.cpp#L81)):*
> ```cpp
>                     PNG_IMAGE_SAMPLE_CHANNELS(pngimage.format),
>                     core::Dtype::UInt16, image.GetDevice());
>     else
> ```

add {}
___
*[cpp/open3d/t/io/file_format/FilePNG.cpp, line 108 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRyQNiB4Y99ym1MvlF:-MSRyQNiB4Y99ym1MvlG:b-t95nju) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/file_format/FilePNG.cpp#L108)):*
> ```cpp
>         return false;
>     }
>     if (quality == kOpen3DImageIODefaultQuality)  // Set default quality
> ```

add {}
___
*[cpp/pybind/t/io/class_io.cpp, line 131 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRx9s08jsfTyylShpp:-MSRx9s08jsfTyylShpq:b-qz6sjc) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/pybind/t/io/class_io.cpp#L131)):*
> ```cpp
>                 return image;
>             },
>             "Function to read image from file", "filename"_a);
> ```

Add `.`: `from file` -> `from file.`. Could you update the rest of this file as well? Some of them are historical.
___
*[cpp/tests/t/io/ImageIO.cpp, line 46 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRqdVZ7Hc1N2m6SMm7:-MSRqdVZ7Hc1N2m6SMm8:b8bnmxn) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/tests/t/io/ImageIO.cpp#L46)):*
> ```cpp
> t::geometry::Image CreateTestImage() {
>     core::Tensor t(core::SizeVector{150, 100, 3}, core::Dtype::UInt8);
>     t.Slice(2, 0, 1).Fill(250);
> ```

i remember `t.Slice(2, 0, 1) = 250` shall work, could you give it a try?
___
*[cpp/tests/t/io/ImageIO.cpp, line 50 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRsQ3qADLiWiRo35L0:-MSRsQ3qADLiWiRo35L1:bsdyn92) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/tests/t/io/ImageIO.cpp#L50)):*
> ```cpp
>     t.Slice(2, 2, 3).Fill(200);
> 
>     auto test_img = t::geometry::Image(t);
> ```

directly return this?
___
*[cpp/tests/t/io/ImageIO.cpp, line 67 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRtg5O1gTKt_ad6xyl:-MSRtg5O1gTKt_ad6xym:b-bujm02) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/tests/t/io/ImageIO.cpp#L67)):*
> ```cpp
> TEST(ImageIO, CreateImageFromFile) {
>     auto img_png = t::io::CreateImageFromFile(std::string(TEST_DATA_DIR) +
>                                               "/test_imageio.png");
> ```

We need to create `test_imageio.png` every time. This is because people could run this test without running the `ImageIO.WriteImage` test, for example when they use the `gtest_filter`.

Also, we shall clean up the temp files after each test is done. 
___
*[cpp/tests/t/io/ImageIO.cpp, line 68 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRs_bg1NvMP4UdwWHr:-MSRs_bg1NvMP4UdwWHs:b-bwgc2b) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/tests/t/io/ImageIO.cpp#L68)):*
> ```cpp
>     auto img_png = t::io::CreateImageFromFile(std::string(TEST_DATA_DIR) +
>                                               "/test_imageio.png");
>     auto img_jpg = t::io::CreateImageFromFile(std::string(TEST_DATA_DIR) +
> ```

Let's use explicit types here for all `auto`s, it could be confusing since `CreateImageFromFile` creates a `shared_ptr<Image>` while `CreateTestImage` creates an `Image` and they need to use `->` and `.` respectively. Change this for all test cases.

Generally speaking, unless we can infer the type easily from the same line (e.g. `auto a = std::make_shared<Image>()` will be obvious), we prefer to use the explicit type. 
___
*[cpp/tests/t/io/ImageIO.cpp, line 71 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRuctm0Bms0MfRpbnS:-MSRuctm0Bms0MfRpbnT:b-zfnqrk) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/tests/t/io/ImageIO.cpp#L71)):*
> ```cpp
>                                               "/test_imageio.jpg");
> 
>     EXPECT_EQ(img_png->GetRows(), img_jpg->GetRows());
> ```

let's compare the value with either 1) hard-coded value, e.g. `150`, or, 2) with the dimension size from `CreateTestImage()` that we used as the reference
___
*[cpp/tests/t/io/ImageIO.cpp, line 177 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRv4034YInW_rUXPSm:-MSRv4034YInW_rUXPSn:bumqovj) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/tests/t/io/ImageIO.cpp#L177)):*
> ```cpp
> }
> 
> TEST(ImageIO, DifferentDtype) {
> ```

Add some comments here on what is expected to be supported, and what will fail for both jpg and png
___
*[cpp/tests/t/io/ImageIO.cpp, line 224 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRwEovCydlSoUKGlBC:-MSRwEovCydlSoUKGlBD:bf9i76s) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/tests/t/io/ImageIO.cpp#L224)):*
> ```cpp
> 
> TEST(ImageIO, CornerCases) {
>     EXPECT_ANY_THROW(t::io::WriteImage(
> ```

When do we `throw` and when do we return `false`? is there a standard for this?

One thing we can do in the future is to always `throw`, and let `ReadImage` return the `Image` instead of `bool` where the `WriteImage` returns a `void`. => could you add this to asana?

**Review by sanskar107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2955)* status: 4 of 10 files reviewed, 17 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/t/geometry/Image.cpp, line 44 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSDwcQ31hT89bWK_Az2:-MT2eeE822bDHZYm6Cyp:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/geometry/Image.cpp#L44)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

can these checks be removed since we're also doing it in `Reset`?
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/ImageIO.h, line 46 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRvr_e9eyIFExFHzd9:-MT2entM1Ttgl8kZBw5v:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/ImageIO.h#L46)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add `\param filename`, and mention how we use the extension name
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/ImageIO.h, line 54 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRvkHSDzllbHygcbEz:-MT2eoD49GzkZvIvDWI2:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/ImageIO.h#L54)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add `\param filename`, and mention how we use the extension name
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/ImageIO.h, line 60 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRvOV22rBFI2KEcUeG:-MT2evEu8FTSSEpTEsCU:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/ImageIO.h#L60)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Add some comments here on:
1) supported file extension types 
2) supported dtype, channel number for both jpg and png
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/ImageIO.cpp, line 41 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRxykW3kmRc5ykhNWQ:-MT2ezkL0QseYc1pKMdt:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/ImageIO.cpp#L41)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

looks like we can move these two `static const` to inside the `namespace io`? 
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePNG.cpp, line 38 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRyGJ3D7rwvwqzrZCc:-MT2f1rg2t8yD_cMzcfx:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/file_format/FilePNG.cpp#L38)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

same, can we move this inside `namespace io` and add `static` before it?
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePNG.cpp, line 77 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRyN9s9QpQi6hwA1PG:-MT2f3M9E0GQrUd2Dz-1:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/file_format/FilePNG.cpp#L77)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add {}
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePNG.cpp, line 81 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRyOgwEpIreUHWbhzq:-MT2f3wDCuzc6VBJgtYm:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/file_format/FilePNG.cpp#L81)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add {}
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePNG.cpp, line 108 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRyQNiB4Y99ym1MvlF:-MT2f5NjCisNAr4zoSeC:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/open3d/t/io/file_format/FilePNG.cpp#L108)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add {}
</blockquote></details>

Done.
___
*[cpp/pybind/t/io/class_io.cpp, line 131 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRx9s08jsfTyylShpp:-MT2f9iQ4nQdR2BMfGM9:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/pybind/t/io/class_io.cpp#L131)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Add `.`: `from file` -> `from file.`. Could you update the rest of this file as well? Some of them are historical.
</blockquote></details>

Done.
___
*[cpp/tests/t/io/ImageIO.cpp, line 46 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRqdVZ7Hc1N2m6SMm7:-MT2fBMN8ivemYCX2BUk:b-i74lio) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/tests/t/io/ImageIO.cpp#L46)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

i remember `t.Slice(2, 0, 1) = 250` shall work, could you give it a try?
</blockquote></details>

This doesn't work, it says `Scalar assignment can only be done on scalar Tensor with shape {}`
___
*[cpp/tests/t/io/ImageIO.cpp, line 50 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRsQ3qADLiWiRo35L0:-MT2fLbD9I0Y7zuUQY_u:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/tests/t/io/ImageIO.cpp#L50)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

directly return this?
</blockquote></details>

Done.
___
*[cpp/tests/t/io/ImageIO.cpp, line 67 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRtg5O1gTKt_ad6xyl:-MT2fO7BA-MOqgjN6Ftd:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/tests/t/io/ImageIO.cpp#L67)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We need to create `test_imageio.png` every time. This is because people could run this test without running the `ImageIO.WriteImage` test, for example when they use the `gtest_filter`.

Also, we shall clean up the temp files after each test is done. 
</blockquote></details>

Done.
___
*[cpp/tests/t/io/ImageIO.cpp, line 68 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRs_bg1NvMP4UdwWHr:-MT2fPM12CQr_epOmANc:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/tests/t/io/ImageIO.cpp#L68)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Let's use explicit types here for all `auto`s, it could be confusing since `CreateImageFromFile` creates a `shared_ptr<Image>` while `CreateTestImage` creates an `Image` and they need to use `->` and `.` respectively. Change this for all test cases.

Generally speaking, unless we can infer the type easily from the same line (e.g. `auto a = std::make_shared<Image>()` will be obvious), we prefer to use the explicit type. 
</blockquote></details>

Done.
___
*[cpp/tests/t/io/ImageIO.cpp, line 71 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRuctm0Bms0MfRpbnS:-MT2fQdz2LudQf7Ijdux:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/tests/t/io/ImageIO.cpp#L71)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

let's compare the value with either 1) hard-coded value, e.g. `150`, or, 2) with the dimension size from `CreateTestImage()` that we used as the reference
</blockquote></details>

Done.
___
*[cpp/tests/t/io/ImageIO.cpp, line 177 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRv4034YInW_rUXPSm:-MT2fV5036535FxhLmGu:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/tests/t/io/ImageIO.cpp#L177)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Add some comments here on what is expected to be supported, and what will fail for both jpg and png
</blockquote></details>

Done.
___
*[cpp/tests/t/io/ImageIO.cpp, line 224 at r1](https://reviewable.io/reviews/intel-isl/open3d/2955#-MSRwEovCydlSoUKGlBC:-MT2fXCP82zvlhC-OX-U:b-76g54x) ([raw file](https://github.com/intel-isl/open3d/blob/51637130dee3cca6757739b880c8d379a63e4e9a/cpp/tests/t/io/ImageIO.cpp#L224)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

When do we `throw` and when do we return `false`? is there a standard for this?

One thing we can do in the future is to always `throw`, and let `ReadImage` return the `Image` instead of `bool` where the `WriteImage` returns a `void`. => could you add this to asana?
</blockquote></details>

This is confusing. We `throw` when `Tensor` creating fails (eg. 0 channel size), for other failures, we return `false`. I've added this task to asana.

**Review by yxlao — APPROVED** [review]
thanks for resolving the comments, LGTM

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2955#-:-MT3ZVok4s8Ny4CinEQE:b-99j5th)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yxlao — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2955#-:-MT3ZYRD4EfXQ0j2y8Xn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
