### PR TITLE
Python binding for TensorList

### PR DESCRIPTION
**Pull request by theNded**
Supports
- Get and set with a single index (operating Tensor objects);
- Get and set with slices (operating TensorList objects);
- Get with an indexing array (wrapped with a SizeVector).

----
Update, we now remove the hassle by only supporting a single index get and set. Now the use case becomes:
```python
# tensor_list is of shape (N, shape)
tensor_list[i] = tensor_a # shape
tensor_list.tensor()[0:5:2] = tensor_b # (3, shape)
```
This assures in-place modification by reusing Tensor's functionalities and removes the inconsistent return types for `getitem`. Also, by forcing construction functions to only take contiguous tensors, we always keep the internal tensor contiguous, which is desired for the container whose major usage is push back.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1557)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Python/open3d/core.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5114562&bid=16815153)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Python/open3d/core.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5114562&bid=16815153)

**Comment by yxlao** [comment]
hi @theNded , i've merged  `master` to `gpu` and #1557 to `gpu`. Could you please update this PR to resolve the conflicts (potentially using something similar to `TensorKey`, `__getitem__` and `__setitem__` from #1557)?

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Python/open3d/core.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5114562&bid=16815153)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Python/open3d/core.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5114562&bid=16815153)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Python/open3d/core.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5114562&bid=16815153)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Python/open3d/core.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5114562&bid=16815153)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/UnitTest/Container/TensorList.cpp  -2
+ src/Open3D/Core/TensorList.cpp  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5114562&bid=16815153)

**Pull request merged**
