### PR TITLE
Jupyter Tutorials

### PR DESCRIPTION
**Pull request by griegler**
I changed most existing `Basic` and `Advanced` tutorials to Jupyter notebooks and integrated them via `nbsphinx`. This builds up on #1640.

Currently, this has three issues:
1) The references/citations are creating warnings when building the doc. I tried different formats in the notebooks, but they all did not work reliably so far.
2) ~~The stdout of the open3d `Log*` functions is not visualized in the cell outputs, but is only printed in the terminal running the jupyter instance.~~ I did improve the `Logger` such that it can redirect the output to Python's `stdout`. In addition, I added a context manager to simply change the verbosity level for a code block.
3) ~~For some visualizations the default view point is very bad. I will have to extend the `draw_geometries` function to directly pass a view point for that.~~ I added a customization to the `draw_geometries` function in the jupyter notebooks. However, those settings are not yet available in the native `draw_geometries` because I do not know yet how to handle default `None` parameters in `pybind11`. @yxlao any ideas.

I have moved/written tutorials for most existing examples in `examples/Python/Basic` and `examples/Python/Advanced`.  There exist still a few `.py` files in those folders without proper jupyter notebook tutorials. This can have a few reasons:

1) The code is outdated, e.g., half_edge_mesh.py
2) The code is referenced in some `.rst` files, e.g., `Advanced/*visualization*.py`
3) I am not sure where to put a tutorial for some files, e.g., `Advanced/trajectory_io.py`

Maybe @yxlao @qianyizh @germanros1987 can have a look at the remaining Python examples and add tutorials as needed.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/1640)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- examples/Python/Basic/open3d_tutorial.py  4
- examples/Python/Advanced/open3d_tutorial.py  4
         

Clones added
============
- examples/Python/Basic/open3d_tutorial.py  1
- examples/Python/Advanced/open3d_tutorial.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- examples/Python/Advanced/open3d_tutorial.py  4
- examples/Python/Basic/open3d_tutorial.py  2
         

Clones added
============
- examples/Python/Advanced/open3d_tutorial.py  1
- examples/Python/Basic/open3d_tutorial.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- examples/Python/Advanced/open3d_tutorial.py  4
- examples/Python/Basic/open3d_tutorial.py  2
         

Clones added
============
- examples/Python/Advanced/open3d_tutorial.py  1
- examples/Python/Basic/open3d_tutorial.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- examples/Python/Advanced/open3d_tutorial.py  4
- examples/Python/Basic/open3d_tutorial.py  2
         

Clones added
============
- examples/Python/Advanced/open3d_tutorial.py  1
- examples/Python/Basic/open3d_tutorial.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- examples/Python/Advanced/open3d_tutorial.py  4
- examples/Python/Basic/open3d_tutorial.py  2
         

Clones added
============
- examples/Python/Advanced/open3d_tutorial.py  1
- examples/Python/Basic/open3d_tutorial.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- examples/Python/Advanced/open3d_tutorial.py  4
- examples/Python/Basic/open3d_tutorial.py  2
         

Clones added
============
- examples/Python/Advanced/open3d_tutorial.py  1
- examples/Python/Basic/open3d_tutorial.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- examples/Python/Advanced/open3d_tutorial.py  8
- examples/Python/Basic/open3d_tutorial.py  6
         

Clones added
============
- examples/Python/Advanced/open3d_tutorial.py  1
- examples/Python/Basic/open3d_tutorial.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by benjaminum** [comment]
Some notebooks do not work because of missing files (fountain). Do I have to download them somewhere?

**Comment by griegler** [comment]
@benjaminum Yes, it is stated in the `color_map_optimization.ipynb` notebook that you have to download the dataset. It is hosted on a Google drive, and I would need to add another Python package to automatically download it, but it would be possible to automate it.

**Comment by benjaminum** [comment]
OK, then it is just me too lazy to read the instructions.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- examples/Python/open3d_tutorial.py  8
         

Clones added
============
- examples/Python/open3d_tutorial.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 7
           

Complexity increasing per file
==============================
- examples/Python/open3d_tutorial.py  8
         

Clones added
============
- examples/Python/Misc/meshes.py  6
- examples/Python/open3d_tutorial.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- examples/Python/open3d_tutorial.py  8
         

Clones added
============
- examples/Python/open3d_tutorial.py  8
- examples/Python/Misc/meshes.py  6
- examples/Python/jupyter_strip_output.py  1
- examples/Python/jupyter_run_all.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by griegler** [comment]
@yxlao @germanros1987 @benjaminum 
Travis fails, because it can not build the doc due to a GLFW error. This error is out of scope of this PR. Should the merge be blocking on the fix of the headless rendering, or are we good to merge?

**Comment by griegler** [comment]
@yxlao the last link looks useful. Would you mind to try it out?

**Comment by yxlao** [comment]
Sure, I can give it a try

**Comment by yxlao** [comment]
hi @griegler , you may check out my PR at https://github.com/griegler/Open3D/pull/3 and merge here to trigger the CI if appropriate.

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- examples/Python/open3d_tutorial.py  8
         

Clones added
============
- examples/Python/jupyter_strip_output.py  1
- examples/Python/Misc/meshes.py  6
- examples/Python/jupyter_run_all.py  1
- examples/Python/open3d_tutorial.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- examples/Python/open3d_tutorial.py  8
         

Clones added
============
- examples/Python/jupyter_strip_output.py  1
- examples/Python/open3d_tutorial.py  8
- examples/Python/jupyter_run_all.py  1
- examples/Python/Misc/meshes.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- examples/Python/open3d_tutorial.py  8
         

Clones added
============
- examples/Python/Misc/meshes.py  6
- examples/Python/jupyter_strip_output.py  1
- examples/Python/jupyter_run_all.py  1
- examples/Python/open3d_tutorial.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by griegler** [comment]
@yxlao Running it with `xvfb` leads to a error in the jupyter notebooks for me: `GLFW Error: X11: RandR gamma ramp support seems broken`

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- examples/Python/open3d_tutorial.py  8
         

Clones added
============
- examples/Python/jupyter_strip_output.py  1
- examples/Python/Misc/meshes.py  6
- examples/Python/open3d_tutorial.py  8
- examples/Python/jupyter_run_all.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- examples/Python/open3d_tutorial.py  8
         

Clones added
============
- examples/Python/jupyter_run_all.py  1
- examples/Python/Misc/meshes.py  6
- examples/Python/open3d_tutorial.py  8
- examples/Python/jupyter_strip_output.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- examples/Python/open3d_tutorial.py  8
         

Clones added
============
- examples/Python/jupyter_strip_output.py  1
- examples/Python/Misc/meshes.py  6
- examples/Python/jupyter_run_all.py  1
- examples/Python/open3d_tutorial.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- examples/Python/open3d_tutorial.py  8
         

Clones added
============
- examples/Python/jupyter_strip_output.py  1
- examples/Python/Misc/meshes.py  6
- examples/Python/open3d_tutorial.py  8
- examples/Python/jupyter_run_all.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- examples/Python/open3d_tutorial.py  8
         

Clones added
============
- examples/Python/jupyter_run_all.py  1
- examples/Python/Misc/meshes.py  6
- examples/Python/jupyter_strip_output.py  1
- examples/Python/open3d_tutorial.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- examples/Python/open3d_tutorial.py  8
         

Clones added
============
- examples/Python/Misc/meshes.py  6
- examples/Python/jupyter_strip_output.py  1
- examples/Python/jupyter_run_all.py  1
- examples/Python/open3d_tutorial.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- examples/Python/open3d_tutorial.py  8
         

Clones added
============
- examples/Python/open3d_tutorial.py  8
- examples/Python/jupyter_run_all.py  1
- examples/Python/jupyter_strip_output.py  1
- examples/Python/Misc/meshes.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=5217292&bid=17105988)

**Pull request merged**
