### PR TITLE
Reorg docs

### PR DESCRIPTION
**Pull request by yxlao**
Instead of `Basic` and `Advanced`, group tutorials by their functionalities, making them easier to find.

### Before 
image

### After
image

This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2381)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/python/utility/file.py  7
- examples/python/visualization/customized_visualization_key_action.py  4
- examples/python/visualization/headless_rendering.py  3
- examples/python/geometry/half_edge_mesh.py  2
- examples/python/reconstruction_system/sensors/realsense_recorder.py  3
- examples/python/utility/visualization.py  2
- examples/python/reconstruction_system/sensors/azure_kinect_mkv_reader.py  10
- examples/python/pipelines/color_map_optimization_for_reconstruction_system.py  5
- examples/python/geometry/mesh_deformation.py  3
- examples/python/reconstruction_system/integrate_scene.py  4
- examples/python/utility/downloader.py  6
- examples/python/reconstruction_system/make_fragments.py  7
- examples/python/misc/meshes.py  6
- examples/python/reconstruction_system/refine_registration.py  7
- examples/python/reconstruction_system/sensors/azure_kinect_recorder.py  4
- examples/python/benchmark/benchmark_fgr.py  1
- examples/python/misc/evaluate_geometric_feature.py  2
- examples/python/visualization/load_save_viewpoint.py  1
- examples/python/reconstruction_system/sensors/realsense_pcd_visualizer.py  1
- examples/python/utility/opencv.py  3
- examples/python/geometry/trajectory_io.py  4
- examples/python/reconstruction_system/optimize_posegraph.py  1
- examples/python/benchmark/benchmark_ransac.py  1
- examples/python/reconstruction_system/opencv_pose_estimation.py  13
- examples/python/visualization/interactive_visualization.py  3
- examples/python/benchmark/benchmark_pre.py  1
- examples/python/reconstruction_system/scripts/synchronize_frames.py  15
- examples/python/reconstruction_system/debug/visualize_alignment.py  2
- examples/python/reconstruction_system/sensors/azure_kinect_viewer.py  4
- examples/python/visualization/customized_visualization.py  3
- examples/python/benchmark/benchmark_tsdf.py  2
- examples/python/reconstruction_system/register_fragments.py  9
- examples/python/reconstruction_system/debug/pairwise_rgbd_alignment.py  1
- examples/python/reconstruction_system/initialize_config.py  2
- examples/python/visualization/remove_geometry.py  2
         

Clones added
============
- examples/python/visualization/headless_rendering.py  1
- examples/python/pipelines/rgbd_integration_uniform.py  1
- examples/python/utility/visualization.py  1
- examples/python/misc/meshes.py  6
- examples/python/reconstruction_system/refine_registration.py  1
- examples/python/reconstruction_system/sensors/azure_kinect_recorder.py  1
- examples/python/benchmark/benchmark_fgr.py  5
- examples/python/benchmark/benchmark_ransac.py  4
- examples/python/misc/feature.py  2
- examples/python/visualization/interactive_visualization.py  1
- examples/python/benchmark/benchmark_pre.py  2
- examples/python/reconstruction_system/sensors/azure_kinect_viewer.py  1
- examples/python/visualization/customized_visualization.py  1
- examples/python/benchmark/benchmark_tsdf.py  1
- examples/python/reconstruction_system/register_fragments.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6246711&bid=20344573)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/python/reconstruction_system/integrate_scene.py  4
- examples/python/reconstruction_system/sensors/realsense_pcd_visualizer.py  1
- examples/python/utility/opencv.py  3
- examples/python/reconstruction_system/optimize_posegraph.py  1
- examples/python/benchmark/benchmark_ransac.py  1
- examples/python/reconstruction_system/sensors/realsense_recorder.py  3
- examples/python/misc/evaluate_geometric_feature.py  2
- examples/python/reconstruction_system/debug/visualize_alignment.py  2
- examples/python/visualization/remove_geometry.py  2
- examples/python/utility/visualization.py  2
- examples/python/pipelines/color_map_optimization_for_reconstruction_system.py  5
- examples/python/visualization/interactive_visualization.py  3
- examples/python/visualization/customized_visualization.py  3
- examples/python/benchmark/benchmark_fgr.py  1
- examples/python/reconstruction_system/debug/pairwise_rgbd_alignment.py  1
- examples/python/visualization/customized_visualization_key_action.py  4
- examples/python/geometry/half_edge_mesh.py  2
- examples/python/geometry/mesh_deformation.py  3
- examples/python/misc/meshes.py  6
- examples/python/reconstruction_system/make_fragments.py  7
- examples/python/visualization/load_save_viewpoint.py  1
- examples/python/utility/downloader.py  6
- examples/python/reconstruction_system/sensors/azure_kinect_viewer.py  4
- examples/python/reconstruction_system/initialize_config.py  2
- examples/python/geometry/trajectory_io.py  4
- examples/python/utility/file.py  7
- examples/python/reconstruction_system/refine_registration.py  7
- examples/python/visualization/headless_rendering.py  3
- examples/python/reconstruction_system/register_fragments.py  9
- examples/python/reconstruction_system/opencv_pose_estimation.py  13
- examples/python/reconstruction_system/sensors/azure_kinect_recorder.py  4
- examples/python/benchmark/benchmark_tsdf.py  2
- examples/python/reconstruction_system/scripts/synchronize_frames.py  15
- examples/python/benchmark/benchmark_pre.py  1
- examples/python/reconstruction_system/sensors/azure_kinect_mkv_reader.py  10
         

Clones added
============
- examples/python/benchmark/benchmark_ransac.py  4
- examples/python/utility/visualization.py  1
- examples/python/visualization/interactive_visualization.py  1
- examples/python/visualization/customized_visualization.py  1
- examples/python/benchmark/benchmark_fgr.py  5
- examples/python/misc/feature.py  2
- examples/python/misc/meshes.py  6
- examples/python/pipelines/rgbd_integration_uniform.py  1
- examples/python/reconstruction_system/sensors/azure_kinect_viewer.py  1
- examples/python/reconstruction_system/refine_registration.py  1
- examples/python/visualization/headless_rendering.py  1
- examples/python/reconstruction_system/register_fragments.py  1
- examples/python/reconstruction_system/sensors/azure_kinect_recorder.py  1
- examples/python/benchmark/benchmark_tsdf.py  1
- examples/python/benchmark/benchmark_pre.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6246711&bid=20344573)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- examples/python/visualization/headless_rendering.py  3
- examples/python/reconstruction_system/register_fragments.py  9
- examples/python/geometry/half_edge_mesh.py  2
- examples/python/benchmark/benchmark_fgr.py  1
- examples/python/geometry/mesh_deformation.py  3
- examples/python/reconstruction_system/sensors/azure_kinect_viewer.py  4
- examples/python/reconstruction_system/make_fragments.py  7
- examples/python/reconstruction_system/sensors/realsense_pcd_visualizer.py  1
- examples/python/benchmark/benchmark_ransac.py  1
- examples/python/reconstruction_system/debug/pairwise_rgbd_alignment.py  1
- examples/python/reconstruction_system/sensors/azure_kinect_mkv_reader.py  10
- examples/python/reconstruction_system/sensors/azure_kinect_recorder.py  4
- examples/python/visualization/interactive_visualization.py  3
- examples/python/reconstruction_system/debug/visualize_alignment.py  2
- examples/python/reconstruction_system/scripts/synchronize_frames.py  15
- examples/python/reconstruction_system/optimize_posegraph.py  1
- examples/python/misc/meshes.py  6
- examples/python/visualization/customized_visualization.py  3
- examples/python/visualization/load_save_viewpoint.py  1
- examples/python/visualization/remove_geometry.py  2
- examples/python/misc/evaluate_geometric_feature.py  2
- examples/python/visualization/customized_visualization_key_action.py  4
- examples/python/pipelines/color_map_optimization_for_reconstruction_system.py  5
- examples/python/reconstruction_system/sensors/realsense_recorder.py  3
- examples/python/utility/visualization.py  2
- examples/python/reconstruction_system/refine_registration.py  7
- examples/python/utility/opencv.py  3
- examples/python/utility/file.py  7
- examples/python/utility/downloader.py  6
- examples/python/reconstruction_system/initialize_config.py  2
- examples/python/benchmark/benchmark_pre.py  1
- examples/python/reconstruction_system/integrate_scene.py  4
- examples/python/benchmark/benchmark_tsdf.py  2
- examples/python/geometry/trajectory_io.py  4
- examples/python/reconstruction_system/opencv_pose_estimation.py  13
         

Clones added
============
- examples/python/visualization/headless_rendering.py  1
- examples/python/reconstruction_system/register_fragments.py  1
- examples/python/benchmark/benchmark_fgr.py  5
- examples/python/reconstruction_system/sensors/azure_kinect_viewer.py  1
- examples/python/benchmark/benchmark_ransac.py  4
- examples/python/pipelines/rgbd_integration_uniform.py  1
- examples/python/reconstruction_system/sensors/azure_kinect_recorder.py  1
- examples/python/visualization/interactive_visualization.py  1
- examples/python/misc/meshes.py  6
- examples/python/visualization/customized_visualization.py  1
- examples/python/utility/visualization.py  1
- examples/python/reconstruction_system/refine_registration.py  1
- examples/python/misc/feature.py  2
- examples/python/benchmark/benchmark_pre.py  2
- examples/python/benchmark/benchmark_tsdf.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6246711&bid=20344573)

**Comment by griegler** [comment]
Will have a closer look later but two things I already noticed:
1) Basic vs Core? Should we rename core to Tensor or something similar?
2) `make_docs.py` fails if I build without PyTorch ops 

```
Traceback (most recent call last):
  File "make_docs.py", line 537, in <module>
    sdb.run()
  File "make_docs.py", line 283, in run
    self._gen_python_api_docs()
  File "make_docs.py", line 296, in _gen_python_api_docs
    pd.generate_rst()
  File "make_docs.py", line 79, in generate_rst
    module = self._get_open3d_module(module_name)
  File "make_docs.py", line 87, in _get_open3d_module
    if open3d._build_config['BUILD_PYTORCH_OPS']:
KeyError: 'BUILD_PYTORCH_OPS'
```

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           

Complexity increasing per file
==============================
- examples/python/pipelines/color_map_optimization_for_reconstruction_system.py  5
- examples/python/visualization/interactive_visualization.py  3
- examples/python/utility/downloader.py  6
- examples/python/reconstruction_system/sensors/azure_kinect_mkv_reader.py  10
- examples/python/visualization/headless_rendering.py  3
- examples/python/reconstruction_system/sensors/realsense_recorder.py  3
- examples/python/utility/opencv.py  3
- examples/python/geometry/half_edge_mesh.py  2
- examples/python/benchmark/benchmark_pre.py  1
- examples/python/reconstruction_system/optimize_posegraph.py  1
- examples/python/utility/file.py  7
- examples/python/reconstruction_system/integrate_scene.py  4
- examples/python/reconstruction_system/scripts/synchronize_frames.py  15
- examples/python/reconstruction_system/debug/visualize_alignment.py  2
- examples/python/reconstruction_system/register_fragments.py  9
- examples/python/reconstruction_system/opencv_pose_estimation.py  13
- examples/python/geometry/trajectory_io.py  4
- examples/python/benchmark/benchmark_tsdf.py  2
- examples/python/visualization/customized_visualization_key_action.py  4
- examples/python/visualization/load_save_viewpoint.py  1
- examples/python/utility/visualization.py  2
- examples/python/benchmark/benchmark_ransac.py  1
- examples/python/benchmark/benchmark_fgr.py  1
- examples/python/reconstruction_system/make_fragments.py  7
- examples/python/reconstruction_system/sensors/azure_kinect_viewer.py  4
- examples/python/reconstruction_system/sensors/realsense_pcd_visualizer.py  1
- examples/python/reconstruction_system/sensors/azure_kinect_recorder.py  4
- examples/python/misc/evaluate_geometric_feature.py  2
- examples/python/visualization/remove_geometry.py  2
- examples/python/visualization/customized_visualization.py  3
- examples/python/geometry/mesh_deformation.py  3
- examples/python/misc/meshes.py  6
- examples/python/reconstruction_system/debug/pairwise_rgbd_alignment.py  1
- examples/python/reconstruction_system/initialize_config.py  2
- examples/python/reconstruction_system/refine_registration.py  7
         

Clones added
============
- examples/python/visualization/interactive_visualization.py  1
- examples/python/visualization/headless_rendering.py  1
- examples/python/benchmark/benchmark_pre.py  2
- examples/python/pipelines/rgbd_integration_uniform.py  1
- examples/python/misc/feature.py  2
- examples/python/reconstruction_system/register_fragments.py  1
- examples/python/benchmark/benchmark_tsdf.py  1
- examples/python/utility/visualization.py  1
- examples/python/benchmark/benchmark_ransac.py  4
- examples/python/benchmark/benchmark_fgr.py  5
- examples/python/reconstruction_system/sensors/azure_kinect_viewer.py  1
- examples/python/reconstruction_system/sensors/azure_kinect_recorder.py  1
- examples/python/visualization/customized_visualization.py  1
- examples/python/misc/meshes.py  6
- examples/python/reconstruction_system/refine_registration.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6246711&bid=20344573)

**Comment by yxlao** [comment]
> Basic vs Core? Should we rename core to Tensor or something similar?

Renamed the display name `Core` -> `Tensor`. The internal logic is that we put things roughly according to the namespace. But I do agree that `Tensor` is a better name to put in the sidebar menu.

> make_docs.py fails if I build without PyTorch ops

The error I got is when `make_docs.py` tries to actually import `open3d.ml.tf` or `open3d.ml.torch`. I've made changes to address that. 

`open3d._build_config['BUILD_PYTORCH_OPS']` seems strange, probably the installed open3d is not the latest one? Since no matter whether open3d is built with/wihout pytorch or TF, the key `BUILD_PYTORCH_OPS` should always exist.

**Review by griegler — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2381#-:-MIYWiLb2T_VpGVlMeg5:bnfp4nl)* status: 0 of 244 files reviewed, all discussions resolved (waiting on @griegler)

**Comment by yxlao** [comment]
thanks @griegler

**Pull request merged**
