### PR TITLE
fix contrib-subsample unit test order

### PR DESCRIPTION
**Pull request by yxlao**
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2321)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ python/test/ml/test_contrib_subsample.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6163791&bid=20132112)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ python/test/ml/test_contrib_subsample.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6163791&bid=20132112)

**Review by ssheorey — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2321)* status: all files reviewed, 1 unresolved discussion (waiting on @yxlao)

___
*[python/test/ml/test_contrib_subsample.py, line 21 at r2](https://reviewable.io/reviews/intel-isl/open3d/2321#-MH9y_mM3Cw9I3H5sY5G:-MH9y_mM3Cw9I3H5sY5H:b-l6eeew) ([raw file](https://github.com/intel-isl/open3d/blob/80b355fa4e6dacf2a8b10bc3b54b11a7a605e414/python/test/ml/test_contrib_subsample.py#L21)):*
> ```Python
>     if actual_labels is not None and expect_labels is not None:
>         np.testing.assert_equal(actual_labels[actual_argsort],
>                                 expect_labels[expect_argsort])
> ```

Good idea to sort the points before comparing. 
Does this solve the issue for labels, if the subsampled label may be from any equally nearby neighbor? Or is that only a degenerate case for specific inputs?

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2321)* status: all files reviewed, 1 unresolved discussion (waiting on @ssheorey)

___
*[python/test/ml/test_contrib_subsample.py, line 21 at r2](https://reviewable.io/reviews/intel-isl/open3d/2321#-MH9y_mM3Cw9I3H5sY5G:-MHA4MUF0Z9a7i08uIar:b-xcm62i) ([raw file](https://github.com/intel-isl/open3d/blob/80b355fa4e6dacf2a8b10bc3b54b11a7a605e414/python/test/ml/test_contrib_subsample.py#L21)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Good idea to sort the points before comparing. 
Does this solve the issue for labels, if the subsampled label may be from any equally nearby neighbor? Or is that only a degenerate case for specific inputs? 
</blockquote></details>

You're right. This does not solve the where the subsampled label may be from any equally nearby neighbor. Since we're mainly testing that the pybind interface is working (as the implementation is done by 3rd party), this test should be sufficient.

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2321)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
