### PR TITLE
Integrate Faiss to NearestNeighborSearch

### PR DESCRIPTION
**Pull request by kookhh0827**
I've moved Faiss api made at few months ago into the '/core/nns' folder.
All other methods have been removed but SearchKnn and SearchHybrid remain on 'knnFaiss.h/cpp'
Python binding for Knnfaiss has been removed.
Cpp test code for Knnfaiss has been modified and moved into '/core' folder.

* Faiss support only Float32 type, so we will have to check data's type in NNS class before toss it to faiss api.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2400)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/KnnFaiss.cpp  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_faiss.py  1
         

Clones added
============
- cpp/tests/core/KnnFaiss.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/KnnFaiss.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/KnnFaiss.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/KnnFaiss.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/KnnFaiss.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by yxlao** [comment]
@junha-l can we try: Install with pip (run inside a Python virtual environment): `pip install cmake`?

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/KnnFaiss.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/KnnFaiss.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones added
============
- cpp/tests/core/KnnFaiss.cpp  10
- cpp/tests/core/FaissIndex.cpp  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones added
============
- cpp/tests/core/FaissIndex.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones added
============
- cpp/tests/core/FaissIndex.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones added
============
- cpp/tests/core/FaissIndex.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/FaissIndex.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/FaissIndex.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/FaissIndex.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/FaissIndex.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/FaissIndex.cpp  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6259795&bid=20382749)

**Review by yxlao — COMMENTED** [review]
> Reviewed 6 of 15 files at r1, 5 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2400)* status: 9 of 15 files reviewed, 3 unresolved discussions (waiting on @kookhh0827 and @yxlao)

___
*[cpp/open3d/core/nns/FaissIndex.h, line 48 at r3](https://reviewable.io/reviews/intel-isl/open3d/2400#-MLQtyv3-1cnBitBPSid:-MLQtyv48jx1yAuUF9U6:b-btv80n) ([raw file](https://github.com/intel-isl/open3d/blob/90525c870f77d5b286c0a7c0018493201e4e82a7/cpp/open3d/core/nns/FaissIndex.h#L48)):*
> ```objc
> ///
> /// \brief Faiss for nearest neighbor search.
> class FaissIndex {
> ```

Looks like there is some duplicated code comparing `NanoFlannIndex` and `FaissIndex`. Is it possible to create a parent class e.g. `NNSIndex` to merge some common code?
___
*[cpp/open3d/core/nns/FaissIndex.cpp, line 80 at r3](https://reviewable.io/reviews/intel-isl/open3d/2400#-MLQugBFCphyi3qOcA-8:-MLQugBFCphyi3qOcA-9:bwk7t1c) ([raw file](https://github.com/intel-isl/open3d/blob/90525c870f77d5b286c0a7c0018493201e4e82a7/cpp/open3d/core/nns/FaissIndex.cpp#L80)):*
> ```cpp
>     Dtype dtype = GetDtype();
> 
>     if (dtype != Dtype::Float32) {
> ```

let's add a failed unit test for `Dtype::Float64` to remind us that only `Float32` is supported.
___
*[cpp/open3d/core/nns/FaissIndex.cpp, line 83 at r3](https://reviewable.io/reviews/intel-isl/open3d/2400#-MLQusvwAbIUj1kDT8OH:-MLQusvwAbIUj1kDT8OI:b-rw52az) ([raw file](https://github.com/intel-isl/open3d/blob/90525c870f77d5b286c0a7c0018493201e4e82a7/cpp/open3d/core/nns/FaissIndex.cpp#L83)):*
> ```cpp
>         utility::LogError(
>                 "[FaissIndex::SetTensorData] Data type must be Float32.");
>         return false;
> ```

We don't need to `return false` since `LogError` throws an exception. Same for other locations.

This is not discovered in `NanaoFlannIndex.cpp`. So let's update that as well.

**Review by yxlao — COMMENTED** [review]
> Reviewed 4 of 15 files at r1, 2 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2400)* status: all files reviewed, 6 unresolved discussions (waiting on @kookhh0827)

___
*[cpp/open3d/core/nns/FaissIndex.cpp, line 152 at r3](https://reviewable.io/reviews/intel-isl/open3d/2400#-MLRf1dxDVSLI6XihI7q:-MLRf1dxDVSLI6XihI7r:b-o2s5g2) ([raw file](https://github.com/intel-isl/open3d/blob/90525c870f77d5b286c0a7c0018493201e4e82a7/cpp/open3d/core/nns/FaissIndex.cpp#L152)):*
> ```cpp
>                              query_points.GetBlob()->GetDevice());
>     std::pair<Tensor, Tensor> result_pair_(result_indices_, result_distance2_);
>     return result_pair_;
> ```

return `std::make_pair(xxx, xxx)`
___
*[cpp/open3d/core/nns/FaissIndex.cpp, line 194 at r3](https://reviewable.io/reviews/intel-isl/open3d/2400#-MLS4NbB3bafrdZgVnZc:-MLS4NbB3bafrdZgVnZd:b-ib4klb) ([raw file](https://github.com/intel-isl/open3d/blob/90525c870f77d5b286c0a7c0018493201e4e82a7/cpp/open3d/core/nns/FaissIndex.cpp#L194)):*
> ```cpp
>                   indices.data());
> 
>     unsigned int upper_ = max_knn * query_size;
> ```

let's use `int64_t` since `max_knn` is `int` and `query_size` is `int64_t`
___
*[cpp/open3d/core/nns/FaissIndex.cpp, line 207 at r3](https://reviewable.io/reviews/intel-isl/open3d/2400#-MLS49eh8YW9hnHR3SCm:-MLS49eh8YW9hnHR3SCn:bidk7ct) ([raw file](https://github.com/intel-isl/open3d/blob/90525c870f77d5b286c0a7c0018493201e4e82a7/cpp/open3d/core/nns/FaissIndex.cpp#L207)):*
> ```cpp
>                              query_points.GetBlob()->GetDevice());
>     std::pair<Tensor, Tensor> result_pair_(result_indices_, result_distance2_);
>     return result_pair_;
> ```

return std::make_pair(result_indices_, result_distance2_);

**Review by junha-l — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2400)* status: all files reviewed, 6 unresolved discussions (waiting on @kookhh0827)

**Review by yxlao — APPROVED** [review]
> Reviewed 4 of 9 files at r4, 4 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2400)* status: 18 of 19 files reviewed, 3 unresolved discussions (waiting on @kookhh0827)

**Comment by junha-l** [comment]
@yxlao I think we can merge this PR now

**Comment by yxlao** [comment]
yes, merged

**Pull request merged**
