### PR TITLE
Init voxeldownsample

### PR DESCRIPTION
**Pull request by theNded**
This PR uses hashmap's unique operation for voxel downsampling. 

It randomly selects one point falling in the selected voxels per grid, with its properties.

We may support average property per grid later, but that includes non-trivial scatter-reduction (https://github.com/rusty1s/pytorch_scatter) that might be available in the Open3D-ML module?

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3144)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3144)* status: all files reviewed, 3 unresolved discussions (waiting on @benjaminum and @theNded)

___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 153 at r1](https://reviewable.io/reviews/intel-isl/open3d/3144#-MVJc90fErM2cWtMKWv9:-MVJc90gBaCzYjfQFGqb:b-obgrhq) ([raw file](https://github.com/intel-isl/open3d/blob/bf617ffa6c534d83a28cfb497b192b26d7adf87f/cpp/open3d/t/geometry/PointCloud.cpp#L153)):*
> ```cpp
> }
> 
> PointCloud PointCloud::VoxelDownSample(double voxel_size) const {
> ```

check `voxel_size` is positive
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 164 at r1](https://reviewable.io/reviews/intel-isl/open3d/3144#-MVJequ240vEj_AiIBBq:-MVJequ240vEj_AiIBBr:b572efl) ([raw file](https://github.com/intel-isl/open3d/blob/bf617ffa6c534d83a28cfb497b192b26d7adf87f/cpp/open3d/t/geometry/PointCloud.cpp#L164)):*
> ```cpp
>     points_voxeli_hashmap.Activate(points_voxeli, addrs, masks);
> 
>     std::unordered_map<std::string, core::Tensor> pcd_down_map;
> ```

instead of creating the map first, it would be simpler to create the new point cloud first and directly set lts attributes, something like this:


```cpp
PointCloud PointCloud::VoxelDownSample(double voxel_size) const {
    core::Tensor points_voxeld = GetPoints() / voxel_size;
    core::Tensor points_voxeli = points_voxeld.Floor().To(core::Dtype::Int64);

    core::Hashmap points_voxeli_hashmap(points_voxeli.GetLength(),
                                        core::Dtype::Int64, core::Dtype::Int32,
                                        {3}, {1}, device_);
    core::Tensor addrs, masks;
    points_voxeli_hashmap.Activate(points_voxeli, addrs, masks);

    PointCloud pcd_down(GetPoints().GetDevice());
    for (auto &kv : point_attr_) {
        if (kv.first == "points") {
            pcd_down.SetPointAttr(kv.first, points_voxeli.IndexGet({masks}).To(
                                                    GetPoints().GetDtype()) *
                                                    voxel_size);
        } else {
            pcd_down.SetPointAttr(kv.first, kv.second.IndexGet({masks}));
        }
    }
    return pcd_down;
}
```
___
*[cpp/tests/t/geometry/PointCloud.cpp, line 404 at r1](https://reviewable.io/reviews/intel-isl/open3d/3144#-MVJf5A60oNXG9rwGvpI:-MVJf5A60oNXG9rwGvpJ:bgqm196) ([raw file](https://github.com/intel-isl/open3d/blob/bf617ffa6c534d83a28cfb497b192b26d7adf87f/cpp/tests/t/geometry/PointCloud.cpp#L404)):*
> ```cpp
>     auto pcd_down = pcd.VoxelDownSample(0.1);
>     io::WritePointCloud(fmt::format("down_{}.pcd", device.ToString()),
>                         pcd_down.ToLegacyPointCloud());
> ```

besides this can we add a really simple unit test? e.g. a voxel grid with 8 cubs and several points inside.

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3144)* status: all files reviewed, 3 unresolved discussions (waiting on @benjaminum and @yxlao)

___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 153 at r1](https://reviewable.io/reviews/intel-isl/open3d/3144#-MVJc90fErM2cWtMKWv9:-MVxnrXgDIqyH8EyUJLq:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/bf617ffa6c534d83a28cfb497b192b26d7adf87f/cpp/open3d/t/geometry/PointCloud.cpp#L153)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

check `voxel_size` is positive
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 164 at r1](https://reviewable.io/reviews/intel-isl/open3d/3144#-MVJequ240vEj_AiIBBq:-MVxqyXK8sdaaSRALNyO:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/bf617ffa6c534d83a28cfb497b192b26d7adf87f/cpp/open3d/t/geometry/PointCloud.cpp#L164)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

instead of creating the map first, it would be simpler to create the new point cloud first and directly set lts attributes, something like this:


```cpp
PointCloud PointCloud::VoxelDownSample(double voxel_size) const {
    core::Tensor points_voxeld = GetPoints() / voxel_size;
    core::Tensor points_voxeli = points_voxeld.Floor().To(core::Dtype::Int64);

    core::Hashmap points_voxeli_hashmap(points_voxeli.GetLength(),
                                        core::Dtype::Int64, core::Dtype::Int32,
                                        {3}, {1}, device_);
    core::Tensor addrs, masks;
    points_voxeli_hashmap.Activate(points_voxeli, addrs, masks);

    PointCloud pcd_down(GetPoints().GetDevice());
    for (auto &kv : point_attr_) {
        if (kv.first == "points") {
            pcd_down.SetPointAttr(kv.first, points_voxeli.IndexGet({masks}).To(
                                                    GetPoints().GetDtype()) *
                                                    voxel_size);
        } else {
            pcd_down.SetPointAttr(kv.first, kv.second.IndexGet({masks}));
        }
    }
    return pcd_down;
}
```

</blockquote></details>

Done.
___
*[cpp/tests/t/geometry/PointCloud.cpp, line 404 at r1](https://reviewable.io/reviews/intel-isl/open3d/3144#-MVJf5A60oNXG9rwGvpI:-MVxqgAX2lYP-XE1PsDA:b56cirq) ([raw file](https://github.com/intel-isl/open3d/blob/bf617ffa6c534d83a28cfb497b192b26d7adf87f/cpp/tests/t/geometry/PointCloud.cpp#L404)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

besides this can we add a really simple unit test? e.g. a voxel grid with 8 cubs and several points inside.
</blockquote></details>

Added a test with only one point after downsample, since the downsampling returns coordinates with a random order, and we don't have sort for now.

**Comment by reyanshsolis** [comment]
Here is the performance benchmark:

```
----------------------------------------------------------------------------------
Benchmark                                        Time             CPU   Iterations
----------------------------------------------------------------------------------
[Open3D INFO]  PointCloud: 198835, Downsampled PointCloud: 95354
BenchmarkVoxelDownsample/[0.01] Legacy        38.2 ms         38.2 ms           18
[Open3D INFO]  PointCloud: 198835, Downsampled PointCloud: 4760
BenchmarkVoxelDownsample/[0.05] Legacy        7.62 ms         7.61 ms           88
[Open3D INFO]  PointCloud: 198835, Downsampled PointCloud: 2154
BenchmarkVoxelDownsample/[0.075] Legacy       7.21 ms         7.21 ms           91
[Open3D INFO]  PointCloud: 198835, Downsampled PointCloud: 1301
BenchmarkVoxelDownsample/[0.1] Legacy         7.15 ms         7.15 ms           94
[Open3D INFO]  PointCloud: 198835, Downsampled PointCloud: 95682
BenchmarkTVoxelDownsample/[0.01] CPU          74.1 ms         74.0 ms           10
[Open3D INFO]  PointCloud: 198835, Downsampled PointCloud: 4801
BenchmarkTVoxelDownsample/[0.05] CPU          41.0 ms         41.0 ms           13
[Open3D INFO]  PointCloud: 198835, Downsampled PointCloud: 2173
BenchmarkTVoxelDownsample/[0.075] CPU         42.9 ms         42.7 ms           17
[Open3D INFO]  PointCloud: 198835, Downsampled PointCloud: 1334
BenchmarkTVoxelDownsample/[0.1] CPU           39.7 ms         39.6 ms           18
[Open3D INFO]  PointCloud: 198835, Downsampled PointCloud: 95682
BenchmarkTVoxelDownsample/[0.01] CUDA         6.56 ms         6.47 ms           93
[Open3D INFO]  PointCloud: 198835, Downsampled PointCloud: 4801
BenchmarkTVoxelDownsample/[0.05] CUDA         4.49 ms         4.48 ms          155
[Open3D INFO]  PointCloud: 198835, Downsampled PointCloud: 2173
BenchmarkTVoxelDownsample/[0.075] CUDA        4.49 ms         4.49 ms          155
[Open3D INFO]  PointCloud: 198835, Downsampled PointCloud: 1334
BenchmarkTVoxelDownsample/[0.1] CUDA          4.46 ms         4.46 ms          156
```

**Comment by reyanshsolis** [comment]
Also, VoxelDownSample legacy returns `std::shared_ptr<open3d::geometry::PointCloud>` while VoxelDownSample tensor returns `t::geometry::PointCloud`.

**Comment by reyanshsolis** [comment]
> Thanks for the benchmarking! Do you think we need to optimize the CPU/CUDA implementation before merging, or merge it as a placeholder first?

I think it's better to merge first and optimize later since this will be very useful in other PRs.

**Comment by yxlao** [comment]
> Added a test with only one point after downsample, since the downsampling returns coordinates with a random order, and we don't have sort for now.
@theNded did you forgot to push some commits?

**Comment by theNded** [comment]
> > Added a test with only one point after downsample, since the downsampling returns coordinates with a random order, and we don't have sort for now.
> 
> @theNded did you forgot to push some commits?

I pushed (see the commit https://github.com/intel-isl/Open3D/commit/262c1f46206cf4b936591db1616565c465a3a06d on Mar 16), but some how it is now synced here, strange...

**Review by yxlao — APPROVED** [review]

**Pull request merged**
