### PR TITLE
Downsample point clouds with by using a different index array

### PR DESCRIPTION
**Pull request by prewettg**
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2318)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/visualization/rendering/Open3DScene.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6160814&bid=20124877)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/visualization/rendering/Open3DScene.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6160814&bid=20124877)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/visualization/rendering/Open3DScene.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6160814&bid=20124877)

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/visualization/rendering/Open3DScene.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6160814&bid=20124877)

**Review by errissa — APPROVED** [review]
> Reviewed 4 of 12 files at r1, 7 of 8 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2318)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
