### PR TITLE
TensorToEigenMatrix Ops.

### PR DESCRIPTION
**Pull request by reyanshsolis**
Adding Tensor to Eigen Matrix ops, in support of Issue #3087. 

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3163)

### CODE REVIEW

**Comment by reyanshsolis** [comment]
@yxlao Do we want to give an option for `copy = false` in TensorToEigenMatrix Ops making Tensor and EigenMatrix share the same memory if it is `Contiguous,  same underlying data type, and on CPU` ?

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3163)* status: all files reviewed, 6 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/core/EigenConverter.h, line 60 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaDbpJ3I8iUgK5VvR1:-MVaDbpJ3I8iUgK5VvR2:bpml2f0) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/open3d/core/EigenConverter.h#L60)):*
> ```objc
> template <typename T>
> Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>
> TensorToEigenMatrix(const core::Tensor &tensor);
> ```

Is the following API possible?

- `Eigen::MatrixXd TensorToEigenMatrixXd(const core::Tensor& tensor)`
- `Eigen::MatrixXf TensorToEigenMatrixXf(const core::Tensor& tensor)`
- `Eigen::MatrixXi TensorToEigenMatrixXi(const core::Tensor& tensor)`
- Move `TensorToEigenMatrix` to `.cpp` so that it's hidden
___
*[cpp/open3d/core/EigenConverter.cpp, line 51 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaF-yA7TzJgLqNPl9C:-MVaF-yA7TzJgLqNPl9D:bes58w0) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/open3d/core/EigenConverter.cpp#L51)):*
> ```cpp
>         utility::LogError(
>                 " [TensorToEigenMatrix]: Number of dimensions supported = 2, "
>                 "but got {}",
> ```

add `.`.
___
*[cpp/open3d/core/EigenConverter.cpp, line 55 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaFLeM6MDY1UXkmxUC:-MVaFLeM6MDY1UXkmxUD:bxfqsth) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/open3d/core/EigenConverter.cpp#L55)):*
> ```cpp
>     }
> 
>     core::Tensor tensor_copy =
> ```

maybe `tensor_cpu_contiguous` is more informative
___
*[cpp/open3d/core/EigenConverter.cpp, line 57 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaFSS6E9geZtyzMd3J:-MVaFSS6E9geZtyzMd3K:bgl3x3y) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/open3d/core/EigenConverter.cpp#L57)):*
> ```cpp
>     core::Tensor tensor_copy =
>             tensor.Contiguous().To(core::Device("CPU:0"), dtype);
>     T *tensor_ptr = tensor_copy.GetDataPtr<T>();
> ```

`data_ptr`, since this is a ptr to data, not tensor
___
*[cpp/open3d/core/EigenConverter.cpp, line 62 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaG9mHDIOFjCyAb6Ai:-MVaG9mHDIOFjCyAb6Aj:b-3v95kr) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/open3d/core/EigenConverter.cpp#L62)):*
> ```cpp
>             Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>>
>             EigenMatrixX(tensor_ptr, dim[0], dim[1]);
>     return EigenMatrixX;
> ```

Copy the Eigen matrix again, and return a copy of that.

The original tensor may go out-of-scope while the user is still using the Eigen matrix. Memory sharing shall only be done in a controlled environment since it has unknown implications.
___
*[cpp/tests/core/EigenConverter.cpp, line 50 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaGHD06hrfdKGrckyx:-MVaGHD06hrfdKGrckyy:b-67h4p) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/tests/core/EigenConverter.cpp#L50)):*
> ```cpp
>     // Device transfer and dtype conversions are handled.
>     for (core::Dtype dtype : {core::Dtype::Float32, core::Dtype::Float64,
>                               core::Dtype::Int32, core::Dtype::Int64}) {
> ```

How is `Int64` possible if we were doing memory mapping to `Eigen::MatrixXi`?

We shall add tests for special shapes:
`{0, 0}, {0, 1}, {1, 0}, {1, 1}`

**Comment by yxlao** [comment]
@reyanshsolis 
> Do we want to give an option for copy = false in TensorToEigenMatrix Ops making Tensor and EigenMatrix share the same memory if it is Contiguous, same underlying data type, and on CPU ?

Not at the moment. We might add it in the future when we actually need it.

Memory sharing across different representations shall be done in a more careful way. The original tensor can go out-of-scope while the user is still using the memory-mapped Eigen variable, causing unexpected errors.

In Tensor to `DLPack` converter, the `DLPack` structure:
1) holds Tensor reference and make sure that the Tensor will not go out-of-scope and; 
2) has a deleter that reduces the Tensor reference count by 1 when the `DLPack` structure destructs

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3163)* status: all files reviewed, 6 unresolved discussions (waiting on @reyanshsolis and @yxlao)

___
*[cpp/open3d/core/EigenConverter.h, line 60 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaDbpJ3I8iUgK5VvR1:-MVaI1CNBQwuxk-bYlSw:b-619wbz) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/open3d/core/EigenConverter.h#L60)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Is the following API possible?

- `Eigen::MatrixXd TensorToEigenMatrixXd(const core::Tensor& tensor)`
- `Eigen::MatrixXf TensorToEigenMatrixXf(const core::Tensor& tensor)`
- `Eigen::MatrixXi TensorToEigenMatrixXi(const core::Tensor& tensor)`
- Move `TensorToEigenMatrix` to `.cpp` so that it's hidden


</blockquote></details>

Yes, that will be better. Should we keep special cases like TensorToEigenMatrix 4d, 4f, 4i, 6d, 6f, 6i, along with this, or remove them and just keep TensorToEigenMatrix Xd, Xf, Xi ?

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3163)* status: all files reviewed, 6 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/core/EigenConverter.h, line 60 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaDbpJ3I8iUgK5VvR1:-MVaIYQp0VAPWvN5ojmC:b-hy5o77) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/open3d/core/EigenConverter.h#L60)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Yes, that will be better. Should we keep special cases like TensorToEigenMatrix 4d, 4f, 4i, 6d, 6f, 6i, along with this, or remove them and just keep TensorToEigenMatrix Xd, Xf, Xi ? 
</blockquote></details>

remove them if the general version works
___
*[cpp/open3d/core/EigenConverter.cpp, line 62 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaG9mHDIOFjCyAb6Ai:-MVaIfwCBgkn0PktACIT:b-kv4uok) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/open3d/core/EigenConverter.cpp#L62)):*
> Copy the Eigen matrix again, and return a copy of that.
To be more clear: return a copy of that Eigen matrix

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3163)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/EigenConverter.h, line 60 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaDbpJ3I8iUgK5VvR1:-MVb4J-z4iWvJP2OoGpB:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/open3d/core/EigenConverter.h#L60)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove them if the general version works
</blockquote></details>

Done.
___
*[cpp/open3d/core/EigenConverter.cpp, line 51 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaF-yA7TzJgLqNPl9C:-MVb4K6U3ALKaeuZ5Te4:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/open3d/core/EigenConverter.cpp#L51)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add `.`.
</blockquote></details>

Done.
___
*[cpp/open3d/core/EigenConverter.cpp, line 55 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaFLeM6MDY1UXkmxUC:-MVb4KUiCDCyWrdZ29LT:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/open3d/core/EigenConverter.cpp#L55)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

maybe `tensor_cpu_contiguous` is more informative
</blockquote></details>

Done.
___
*[cpp/open3d/core/EigenConverter.cpp, line 57 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaFSS6E9geZtyzMd3J:-MVb4Kue1EgUUUuefDtL:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/open3d/core/EigenConverter.cpp#L57)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`data_ptr`, since this is a ptr to data, not tensor
</blockquote></details>

Done.
___
*[cpp/open3d/core/EigenConverter.cpp, line 62 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaG9mHDIOFjCyAb6Ai:-MVb6rotCcvb0vdXgFLk:bs7wumx) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/open3d/core/EigenConverter.cpp#L62)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

> Copy the Eigen matrix again, and return a copy of that.
To be more clear: return a copy of that Eigen matrix


</blockquote></details>

Done. 
___
*[cpp/tests/core/EigenConverter.cpp, line 50 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaGHD06hrfdKGrckyx:-MVb4WWHC7v_90XLRcka:b-p9pt1k) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/tests/core/EigenConverter.cpp#L50)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

How is `Int64` possible if we were doing memory mapping to `Eigen::MatrixXi`?

We shall add tests for special shapes:
`{0, 0}, {0, 1}, {1, 0}, {1, 1}`
</blockquote></details>

`Int64` is there just to test type conversion. Even if the tensor is in Float32, Float64, Int32, Int64, on CPU or CUDA, the device transfer, and type conversions are handled.

**Review by yxlao — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3163)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @reyanshsolis and @yxlao)

___
*[cpp/open3d/core/EigenConverter.cpp, line 61 at r3](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVbE1HZ1rHwJFQMgKEg:-MVbE1HZ1rHwJFQMgKEh:bjfbmzp) ([raw file](https://github.com/intel-isl/open3d/blob/62b4c05f97886753e6755d59971a200066480a61/cpp/open3d/core/EigenConverter.cpp#L61)):*
> ```cpp
>     Eigen::Map<
>             Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>>
>             EigenMatrixX(data_ptr, dim[0], dim[1]);
> ```

`EigenMatrixX` shall be `snake_case` in the name.
___
*[cpp/tests/core/EigenConverter.cpp, line 50 at r2](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVaGHD06hrfdKGrckyx:-MVbHPw24T3KIkQPO5vU:b-61karq) ([raw file](https://github.com/intel-isl/open3d/blob/c8be22f072169e6def0404b3ef3030a87027a86f/cpp/tests/core/EigenConverter.cpp#L50)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

`Int64` is there just to test type conversion. Even if the tensor is in Float32, Float64, Int32, Int64, on CPU or CUDA, the device transfer, and type conversions are handled.
</blockquote></details>

If we are testing type conversion, we shall test with more representative conversions, e.g. 

```cpp
// less representative: converting 1 to 1.f, since we cannot check for value difference
int64 i = 1;
float f = static_cast<float>(i);

// more representative: converting 3.14f to 3
float f = 3.14f;
int i = static_cast<int>(f);
```
___
*[cpp/tests/core/EigenConverter.cpp, line 52 at r3](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVbHsp_EqTsmbumT-2p:-MVbHsp_EqTsmbumT-2q:bw9dnv8) ([raw file](https://github.com/intel-isl/open3d/blob/62b4c05f97886753e6755d59971a200066480a61/cpp/tests/core/EigenConverter.cpp#L52)):*
> ```cpp
>                               core::Dtype::Int32, core::Dtype::Int64}) {
>         // Testing on shapes {i, j} : {0, 0}, {0, 1}, {1, 0}, {1, 1}.
>         for (int row = 0; row < 2; row++) {
> ```

`for (const SizeVector& shape: {{0, 0}, {0, 1}, ...})` might be more clear

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3163)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/EigenConverter.cpp, line 61 at r3](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVbE1HZ1rHwJFQMgKEg:-MVkGIeF42qxyWRydsQ9:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/62b4c05f97886753e6755d59971a200066480a61/cpp/open3d/core/EigenConverter.cpp#L61)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`EigenMatrixX` shall be `snake_case` in the name.
</blockquote></details>

Done.
___
*[cpp/tests/core/EigenConverter.cpp, line 52 at r3](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVbHsp_EqTsmbumT-2p:-MVkIVO0Dw-TwnA_5WS7:b-wk46fj) ([raw file](https://github.com/intel-isl/open3d/blob/62b4c05f97886753e6755d59971a200066480a61/cpp/tests/core/EigenConverter.cpp#L52)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`for (const SizeVector& shape: {{0, 0}, {0, 1}, ...})` might be more clear
</blockquote></details>

I tried that initially, but due to nested {{}}, for loop fails to `deduce the range for range-based for loop`.

**Review by yxlao — APPROVED** [review]
LGTM after resolving two more minor issues

> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3163#-:-MVukDs6EmoCLKQuTpR1:b-2i2kna)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @reyanshsolis and @yxlao)

___
*[cpp/open3d/core/EigenConverter.cpp, line 64 at r4](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVui6kO7z0TDQW0z2vm:-MVui6kO7z0TDQW0z2vn:b-an3wu8) ([raw file](https://github.com/intel-isl/open3d/blob/65165b4dd1c4b12f06584dad85f4b750ed10af15/cpp/open3d/core/EigenConverter.cpp#L64)):*
> ```cpp
> 
>     Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>
>             eigen_matrix_copy = eigen_matrix;
> ```

Could we try the copy constructor `Eigen::Matrix<xxx> dst_matrix(src_matrx);`. This is more explicit.

The copy assignment operator could be tricky, since if someone accidentally used an `auto` it may not be a copy, depending on the implementation.

```cpp
auto a = b; // may not be a copy, see https://stackoverflow.com/a/59623634/1255535
Eigen::Matrix<XXX> a = b; // ok
Eigen::Matrix<xxx> a(b);  // better
```
___
*[cpp/tests/core/EigenConverter.cpp, line 52 at r3](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVbHsp_EqTsmbumT-2p:-MVuhlZD8fn2fUJBZgwB:b-xbserp) ([raw file](https://github.com/intel-isl/open3d/blob/62b4c05f97886753e6755d59971a200066480a61/cpp/tests/core/EigenConverter.cpp#L52)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

I tried that initially, but due to nested {{}}, for loop fails to `deduce the range for range-based for loop`.
</blockquote></details>

then we can try:
```cpp
for (const auto& shape : std::vector<core::SizeVector>({{0, 0}, {0, 1}, {1, 0}, {1, 1}})) 
```

The nested row, col loop doesn't make too much sense since we care about the shapes

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3163)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/EigenConverter.cpp, line 64 at r4](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVui6kO7z0TDQW0z2vm:-MVw27QdAqgt1olUVAYb:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/65165b4dd1c4b12f06584dad85f4b750ed10af15/cpp/open3d/core/EigenConverter.cpp#L64)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Could we try the copy constructor `Eigen::Matrix<xxx> dst_matrix(src_matrx);`. This is more explicit.

The copy assignment operator could be tricky, since if someone accidentally used an `auto` it may not be a copy, depending on the implementation.

```cpp
auto a = b; // may not be a copy, see https://stackoverflow.com/a/59623634/1255535
Eigen::Matrix<XXX> a = b; // ok
Eigen::Matrix<xxx> a(b);  // better
```
</blockquote></details>

Done.
___
*[cpp/tests/core/EigenConverter.cpp, line 52 at r3](https://reviewable.io/reviews/intel-isl/open3d/3163#-MVbHsp_EqTsmbumT-2p:-MVw254X2lusE2tqXY2D:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/62b4c05f97886753e6755d59971a200066480a61/cpp/tests/core/EigenConverter.cpp#L52)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

then we can try:
```cpp
for (const auto& shape : std::vector<core::SizeVector>({{0, 0}, {0, 1}, {1, 0}, {1, 1}})) 
```

The nested row, col loop doesn't make too much sense since we care about the shapes
</blockquote></details>

Done.

**Pull request merged**
